
PATHDIR = ../..
PATHINC = $(PATHDIR)/include
PATHLIB = $(PATHDIR)/lib/linux64/static

CC    = gcc
CFLAGS = -static -m32 -I. -I.. -I$(PATHINC) -O3

all: 
	$(CC) $(CFLAGS) -o main main.c SimpleLCP_Path.c -L$(PATHLIB) -lpath46 -lm

