ROSS.Net: bgp-mrai.c File Reference
bgp-mrai.c File Reference
#include <bgp.h>
Functions
void bgp_mrai_tmr (bgp_state *state, tw_lp *lp)
void bgp_mrai_timer (bgp_state *state, tw_bf *bf, bgp_message *msg, tw_lp *lp)
Function Documentation
void bgp_mrai_timer (bgp_state * state, tw_bf * bf, bgp_message * msg, tw_lp * lp)
Definition at line 20 of file bgp-mrai.c.
References bgp_update_all(), and g_rn_nas.
Referenced by bgp_event_handler().
{
        tw_memory       *b;
        bgp_route       *r;
        int              i;
        state->tmr_mrai = NULL;
        msg->b.update = 1;
        msg->b.cause_bgp = 1;
        msg->b.cause_ospf = 0;
        // Foreach route in the RIB with dirty bit set, send updates to nbrs
        for(i = 0; i < g_rn_nas; i++)
        {
                b = state->rib[i];
                // Route has not been updated since previous MRAI timer fired
                if(!b || b->bit == TW_FALSE)
                        continue;
                r = tw_memory_data(b);
                b->bit = TW_FALSE;
                bgp_update_all(state, msg, lp->id, r, lp);
        }
}
void bgp_mrai_tmr (bgp_state * state, tw_lp * lp)
Definition at line 7 of file bgp-mrai.c.
References bgp_timer_start().
Referenced by bgp_keepalive(), and bgp_route_add().
{
        if(state->tmr_mrai && state->tmr_mrai->recv_ts >= tw_now(lp))
                return;
        // keep the keepalive timer going
        state->tmr_mrai = bgp_timer_start(lp,
                                          state->tmr_mrai,
                                          state->as->mrai_interval,
                                          MRAITIMER);
}