ROSS.Net: bgp-nbr.c File Reference
bgp-nbr.c File Reference
#include <bgp.h>
Functions
bgp_nbr * bgp_getnbr (bgp_state *state, int id)
Function Documentation
bgp_nbr* bgp_getnbr (bgp_state * state, int id)
This function returns the PEER associated with id
Definition at line 7 of file bgp-nbr.c.
Referenced by bgp_decision(), bgp_keepalive(), bgp_notify(), bgp_open(), bgp_r_event_handler(), bgp_update(), and r_msg_notification().
{
        bgp_nbr         *n;
        int              i;
        for(i = 0; i < state->n_interfaces; i++)
        {
                n = &state->nbr[i];
                if (n->id == id)
                        return n;
        }
        //tw_error(TW_LOC, "Unable to find nbr: %d \n", id);
        return NULL;
}