ROSS.Net: bgp-utils.c File Reference
bgp-utils.c File Reference
#include <bgp.h>
Functions
tw_event * bgp_timer_start (tw_lp *lp, tw_event *tmr, tw_stime ts, bgp_message_type type)
void bgp_r_timer_start ()
Function Documentation
void bgp_r_timer_start ()
Definition at line 19 of file bgp-utils.c.
{
}
tw_event* bgp_timer_start (tw_lp * lp, tw_event * tmr, tw_stime ts, bgp_message_type type)
Definition at line 4 of file bgp-utils.c.
References g_bgp_fd, and rn_timer_simple().
Referenced by bgp_init(), bgp_keepalive_tmr(), and bgp_mrai_tmr().
{
        tw_memory       *b = tw_memory_alloc(lp, g_bgp_fd);
        bgp_message     *m = tw_memory_data(b);
        tmr = rn_timer_simple(lp, ts);
        m->b.type = type;
        tw_event_memory_set(tmr, b, g_bgp_fd);
        return tmr;
}