ROSS.Net: bgp-extern.h File Reference
bgp-extern.h File Reference
Functions
void bgp_open_send (bgp_state *, bgp_nbr *n, tw_lp *lp)
void bgp_open (bgp_state *, tw_bf *, bgp_message *, int, tw_lp *)
int bgp_decision (bgp_state *, bgp_route *r1, bgp_route *r2, tw_lp *)
int bgp_route_inpath (bgp_state *state, bgp_route *r_in, tw_lp *lp)
void bgp_route_aspath_print (bgp_state *state, bgp_route *r)
int bgp_route_free (bgp_state *state, tw_memory *route, tw_lp *lp)
tw_memory * bgp_getroute (bgp_state *state, bgp_route *find)
void bgp_route_add (bgp_state *state, tw_memory *b)
void bgp_route_withdraw (bgp_state *state, bgp_route *r)
tw_memory * bgp_route_new (bgp_state *, tw_lp *, tw_lp *, tw_lp *)
int bgp_route_equals (bgp_route *, bgp_route *)
tw_memory * bgp_route_copy (bgp_state *, bgp_route *, bgp_nbr *, bgp_update_type, tw_lp *)
void bgp_rib_print (bgp_state *state, tw_lp *lp)
void bgp_route_print (bgp_state *state, bgp_route *r)
void bgp_rt_file (int *read)
void bgp_main (int argc, char **argv, char **env)
void bgp_md_final ()
tw_event * bgp_timer_start (tw_lp *, tw_event *, tw_stime, bgp_message_type)
void bgp_init (bgp_state *, tw_lp *)
void bgp_event_handler (bgp_state *, tw_bf *, rn_message *, tw_lp *)
void bgp_r_event_handler (bgp_state *, tw_bf *, rn_message *, tw_lp *)
void bgp_final (bgp_state *, tw_lp *)
void bgp_xml (bgp_state *state, const xmlNodePtr node, tw_lp *)
void bgp_notify_send (bgp_state *, bgp_nbr *n, tw_lp *lp)
void bgp_notify (bgp_state *state, tw_bf *bf, int src, tw_lp *lp)
bgp_nbr * bgp_getnbr (bgp_state *state, int id)
void bgp_connect (bgp_state *state, bgp_nbr *n, tw_lp *lp)
void bgp_ospf_init (bgp_state *bs, bgp_route *r, tw_lp *lp)
void bgp_ospf_flush (bgp_state *, rn_as *, bgp_route *, int, tw_lp *)
void bgp_ospf_update (bgp_state *, rn_as *, bgp_route *, int, tw_lp *)
void bgp_mrai_tmr (bgp_state *state, tw_lp *lp)
void bgp_mrai_timer (bgp_state *, tw_bf *, bgp_message *, tw_lp *)
void bgp_update_all (bgp_state *, bgp_message *, int, bgp_route *, tw_lp *)
void bgp_update_send (bgp_state *, bgp_nbr *, bgp_route *, bgp_message *, int, tw_lp *)
void bgp_update (bgp_state *, tw_bf *, bgp_message *, int, tw_lp *)
void bgp_keepalive_tmr (bgp_state *state, tw_lp *lp)
void bgp_keepalive_send (bgp_nbr *n, tw_lp *lp)
void bgp_keepalive (bgp_state *state, int, int, tw_lp *)
void bgp_keepalive_timer (bgp_state *, tw_bf *, bgp_message *, tw_lp *)
void deal_with_timed_out_routers (bgp_state *state, tw_bf *bf, bgp_message *msg, tw_lp *lp)
Variables
tw_fd g_bgp_fd
tw_fd g_bgp_fd_rtes
tw_fd g_bgp_fd_asp
FILE * g_bgp_rt_fd
bgp_stats g_bgp_stats
bgp_state * g_bgp_state
bgp_as * g_bgp_as
char * g_bgp_init_file
xmlXPathObjectPtr * g_bgp_ases
Function Documentation
void bgp_connect (bgp_state * state, bgp_nbr * n, tw_lp * lp)
Send a BGP CONNECT message to complete the connection established process.
BGP needs CONNECT message from transport layer.. upon receiving ANY msg from another BGP router, the OPEN msg is created and sent to that neighbor. Do not use these for anything other than during the init phase. I have changed the process somewhat so that each peer on either side of a connection do not need to send the CONNECT.
Definition at line 13 of file bgp-connect.c.
References BGP_CONNECT, DOWNSTREAM, g_bgp_fd, rn_event_new(), rn_event_send(), rn_getlink(), and rn_route().
Referenced by bgp_init().
{
        tw_event        *e;
        tw_memory       *hdr;
        tw_stime         ts = 0.0;
        bgp_message     *m;
#if 1
        if(lp->id < n->id)
                ts = 0.0;
        else
                return;
#endif
#if VERIFY_BGP
        printf("%ld: BGP router coming online, connecting to %d: %lf \n",
                lp->id, n->id, ts);
#endif
        state->stats->s_nconnects++;
        e = rn_event_new(n->id, ts, lp, DOWNSTREAM, BGP_CONNECT);
        // Create the BGP message header
        hdr = tw_memory_alloc(lp, g_bgp_fd);
        m = tw_memory_data(hdr);
        m->b.type = CONNECT;
        m->b.cause_bgp = 1;
        m->b.cause_ospf = 0;
        tw_event_memory_set(e, hdr, g_bgp_fd);
        rn_event_send(e);
        if(e == lp->pe->abort_event)
        {
                state->stats->s_nconnects_dropped++;
        } else
        {
                if(NULL == rn_getlink(state->m, n->id))
                        if(-1 == rn_route(state->m, n->id))
                                state->stats->s_nconnects_dropped++;
        }
}
int bgp_decision (bgp_state * state, bgp_route * new, bgp_route * exist, tw_lp * lp)
This function models the BGP decision process.
Resolve ties in the following order:
lowest local_pref (not implemented outside of XML)
shortest AS PATH
lowest origin, one of:
iBGP (1)
eBGP (2)
Incomplete (3)
lowest MED (if next_hops equal)
Hot Potato Routing (lowest hop count)
lowest next hop
DEFAULT: Keep existing route
Definition at line 35 of file bgp-decision.c.
References bgp_getnbr(), g_bgp_as, g_bgp_state, g_bgp_stats, rn_getas(), and rn_getmachine().
Referenced by update_add().
{
        rn_as           *new_as = rn_getas(rn_getmachine(new->src));
        rn_as           *exist_as = rn_getas(rn_getmachine(exist->src));
        // LOCAL PREF : lower is higher priority (better)
        // was next_hop .. next_hop is AS id, not node id
        if(g_bgp_state->b.local_pref &&
                g_bgp_as[new_as->id].local_pref < g_bgp_as[exist_as->id].local_pref)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: local_pref (%d > %d) \n",
                        g_bgp_as[new_as->id].local_pref,
                        g_bgp_as[exist_as->id].local_pref);
#endif
                g_bgp_stats.s_ndec_local_pref++;
                return TW_TRUE;
        } else if(g_bgp_state->b.local_pref &&
                  g_bgp_as[exist_as->id].local_pref < g_bgp_as[new_as->id].local_pref)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: local_pref (%d < %d) \n",
                        g_bgp_as[new_as->id].local_pref,
                        g_bgp_as[exist_as->id].local_pref);
#endif
                g_bgp_stats.s_ndec_local_pref++;
                return TW_FALSE;
        }
        // shortest AS path
        if(g_bgp_state->b.as_path && new->as_path.size < exist->as_path.size)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: as path (%d < %d)\n",
                        new->as_path.size, exist->as_path.size);
#endif
                g_bgp_stats.s_ndec_aspath++;
                return TW_TRUE;
        } else if(g_bgp_state->b.as_path && new->as_path.size > exist->as_path.size)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: as path (%d > %d)\n",
                        new->as_path.size, exist->as_path.size);
#endif
                g_bgp_stats.s_ndec_aspath++;
                return TW_FALSE;
        }
        // ORIGIN code pref: 1 IGP 2 EGP 3 Incomplete
        if(g_bgp_state->b.origin && new->origin > exist->origin)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: origin (%d > %d)\n",
                        new->origin, exist->origin);
#endif
                g_bgp_stats.s_ndec_origin++;
                return TW_TRUE;
        } else if(g_bgp_state->b.origin && new->origin < exist->origin)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: origin (%d < %d)\n",
                        new->origin, exist->origin);
#endif
                g_bgp_stats.s_ndec_origin++;
                return TW_FALSE;
        }
        //bgp_route_print(state, new);
        //bgp_route_print(state, exist);
        // lowest med preferred, next_hop must be equal
        if(g_bgp_state->b.med && new->next_hop == exist->next_hop)
        {
                if(new->med < exist->med)
                {
#if VERIFY_BGP_DECISION
                        fprintf(state->log, "\tdecision: MED (%d < %d)\n",
                                new->med, exist->med);
#endif
                        g_bgp_stats.s_ndec_med++;
                        return TW_TRUE;
                } else if(new->med > exist->med)
                {
#if VERIFY_BGP_DECISION
                        fprintf(state->log, "\tdecision: MED (%d > %d)\n",
                                new->med, exist->med);
#endif
                        g_bgp_stats.s_ndec_med++;
                        return TW_FALSE;
                }
        }
        if(g_bgp_state->b.hot_potato)
        {
                bgp_nbr *exist_n = bgp_getnbr(state, exist->src);
                bgp_nbr *new_n = bgp_getnbr(state, new->src);
                if(exist_n->hop_count < new_n->hop_count)
                {
                        g_bgp_stats.s_ndec_hot_potato++;
                        return TW_FALSE;
                } else if(new_n->hop_count < exist_n->hop_count)
                {
/*
                        fprintf(state->log, "\tdecision: hot-potato (%d < %d) \n",
                                new_n->hop_count, exist_n->hop_count);
*/
                        g_bgp_stats.s_ndec_hot_potato++;
                        return TW_TRUE;
                }
        }
        // Always take lowest next_hop
        if(g_bgp_state->b.next_hop && new->next_hop < exist->next_hop)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: next hop (%d < %d)\n",
                        new->next_hop, exist->next_hop);
#endif
                g_bgp_stats.s_ndec_next_hop++;
                return TW_TRUE;
        }
        if(g_bgp_state->b.existing)
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: default, keep existing route! \n");
#endif
                g_bgp_stats.s_ndec_existing++;
                return TW_FALSE;
        } else
        {
#if VERIFY_BGP_DECISION
                fprintf(state->log, "\tdecision: default, install new route! \n");
#endif
                g_bgp_stats.s_ndec_existing++;
                return TW_TRUE;
        }
        g_bgp_stats.s_ndec_default++;
        return TW_FALSE;
}
void bgp_event_handler (bgp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 4 of file bgp-router.c.
References bgp_keepalive(), bgp_keepalive_timer(), bgp_mrai_timer(), bgp_notify(), bgp_open(), bgp_update(), deal_with_timed_out_routers(), g_bgp_fd, and g_rn_converge_ospf.
{
        tw_memory      *hdr;
        bgp_message    *msg;
        *(int *) bf = 0;
        // reset that neighbors timer
        hdr = tw_event_memory_get(lp);
        msg = tw_memory_data(hdr);
        if(g_rn_converge_ospf)
                tw_error(TW_LOC, "Should not be in BGP!");
        if(rn_msg->port != 169)
                tw_error(TW_LOC, "recv non-bgp message!");
        // 'cause it would be a timer..
        if (rn_msg->src != lp->id)
                bgp_keepalive(state, rn_msg->src, (int) rn_msg->ttl, lp);
        switch (msg->b.type)
        {
                case CONNECT:
#if VERIFY_BGP
                        fprintf(state->log, "\n%ld BGP: CONNECT from %ld at %lf\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                        break;
                case OPEN:
#if VERIFY_BGP
                        fprintf(state->log, "\n%ld BGP: OPEN from %ld at %lf\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                        bgp_open(state, bf, msg, rn_msg->src, lp);
                        state->stats->s_cause_ospf += msg->b.cause_ospf;
                        state->stats->s_cause_bgp += msg->b.cause_bgp;
                        break;
                case UPDATE:
#if VERIFY_BGP
                        fprintf(state->log, "\n%ld BGP: UPDATE from %ld at %lf\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                        bgp_update(state, bf, msg, rn_msg->src, lp);
                        state->stats->s_nupdates_recv++;
                        break;
                case NOTIFICATION:
#if VERIFY_BGP
                        fprintf(state->log, "\n%ld BGP: NOTIFY from %ld at %lf\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                        bgp_notify(state, bf, rn_msg->src, lp);
                        state->stats->s_nnotify_recv++;
                        break;
                case KEEPALIVE:
#if VERIFY_BGP_KEEPALIVE
                        fprintf(state->log, "\n%ld BGP: KEEPALIVE from %ld at %lf\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                        state->stats->s_nkeepalives++;
                        break;
                case KEEPALIVETIMER:
#if VERIFY_BGP_KEEPALIVE
                        fprintf(state->log, "\n%ld BGP: KEEPALIVE_TIMER at %lf\n",
                                lp->id, tw_now(lp));
#endif
                        bgp_keepalive_timer(state, bf, msg, lp);
                        deal_with_timed_out_routers(state, bf, msg, lp);
                        break;
                case MRAITIMER:
#if VERIFY_BGP
                        fprintf(state->log, "\n%ld: BGP: MRAI_TIMER at %lf \n",
                                lp->id, tw_now(lp));
#endif
                        state->stats->s_nmrai_timers++;
                        bgp_mrai_timer(state, bf, msg, lp);
                        break;
                default:
                        tw_error(TW_LOC, "Unhandled BGP event type!");
        }
        tw_memory_free(lp, hdr, g_bgp_fd);
        if(NULL != lp->pe->cur_event->memory)
                tw_error(TW_LOC, "memory buffers remain on event! \n");
}
void bgp_final (bgp_state * , tw_lp *)
Definition at line 4 of file bgp-stats.c.
References bgp_rib_print(), bgp_route_print(), g_bgp_rt_fd, g_bgp_stats, g_rn_converge_ospf, g_rn_logs_dir, g_rn_nas, rn_getas(), and rn_getmachine().
{
#ifndef BGP_CONVERGED
        bgp_route       *r;
#endif
        int              i;
        bgp_rib_print(state, lp);
        g_bgp_stats.s_nroute_adds += state->stats->s_nroute_adds;
        g_bgp_stats.s_nroute_removes += state->stats->s_nroute_removes;
        g_bgp_stats.s_nupdates_sent += state->stats->s_nupdates_sent;
        g_bgp_stats.s_nupdates_recv+= state->stats->s_nupdates_recv;
        g_bgp_stats.s_nnotify_sent += state->stats->s_nnotify_sent;
        g_bgp_stats.s_nnotify_recv += state->stats->s_nnotify_recv;
        g_bgp_stats.s_nopens += state->stats->s_nopens;
        g_bgp_stats.d_opens += state->stats->d_opens;
        g_bgp_stats.s_nunreachable += state->stats->s_nunreachable;
        g_bgp_stats.s_nkeepalives += state->stats->s_nkeepalives;
        g_bgp_stats.s_nkeepalivetimers += state->stats->s_nkeepalivetimers;
        g_bgp_stats.s_nmrai_timers += state->stats->s_nmrai_timers;
        g_bgp_stats.s_nconnects += state->stats->s_nconnects;
        g_bgp_stats.s_nconnects_dropped += state->stats->s_nconnects_dropped;
        g_bgp_stats.s_nconnects_dropped += state->stats->s_nconnects_dropped;
        g_bgp_stats.s_cause_bgp += state->stats->s_cause_bgp;
        g_bgp_stats.s_cause_ospf += state->stats->s_cause_ospf;
        for(i = 0; i < state->n_interfaces; i++)
        {
                if(state->nbr[i].up == TW_FALSE)
                {
                        if(rn_getas(rn_getmachine(state->nbr[i].id)) == state->as)
                                g_bgp_stats.s_nibgp_nbrs++;
                        else
                                g_bgp_stats.s_nebgp_nbrs++;
                } else
                {
                        if(rn_getas(rn_getmachine(state->nbr[i].id)) == state->as)
                                g_bgp_stats.s_nibgp_nbrs_up++;
                        else
                                g_bgp_stats.s_nebgp_nbrs_up++;
                }
        }
#if VERIFY_BGP
        if(stdout != state->log)
                fclose(state->log);
#endif
#ifndef BGP_CONVERGED
        if(g_rn_converge_ospf)
                return;
        if(!g_bgp_rt_fd)
        {
                char file[255];
                sprintf(file, "%s/bgp-route.file", g_rn_logs_dir);
                g_bgp_rt_fd = fopen(file, "w");
                if(!g_bgp_rt_fd)
                        tw_error(TW_LOC, "Unable to open: %s", file);
                else
                        printf("%lld: opening %s\n", lp->id, file);
        }
        state->log = g_bgp_rt_fd;
        for(i = 0; i < g_rn_nas; i++)
        {
                if(state->rib[i] == NULL)
                {
                        fprintf(state->log, "-1 \n");
                } else
                {
                        r = tw_memory_data(state->rib[i]);
                        bgp_route_print(state, r);
                }
        }
#endif
}
bgp_nbr* bgp_getnbr (bgp_state * state, int id)
This function returns the PEER associated with id
Definition at line 7 of file bgp-nbr.c.
Referenced by bgp_decision(), bgp_keepalive(), bgp_notify(), bgp_open(), bgp_r_event_handler(), bgp_update(), and r_msg_notification().
{
        bgp_nbr         *n;
        int              i;
        for(i = 0; i < state->n_interfaces; i++)
        {
                n = &state->nbr[i];
                if (n->id == id)
                        return n;
        }
        //tw_error(TW_LOC, "Unable to find nbr: %d \n", id);
        return NULL;
}
tw_memory* bgp_getroute (bgp_state * state, bgp_route * find)
Definition at line 43 of file bgp-route.c.
Referenced by update_add(), and update_withdraw().
{
        if(NULL != state->rib[find->dst])
                return state->rib[find->dst];
        return NULL;
}
void bgp_init (bgp_state * , tw_lp *)
Definition at line 70 of file bgp-init.c.
References bgp_connect(), bgp_keepalive_timer(), bgp_route_add(), bgp_route_new(), bgp_timer_start(), g_rn_areas, g_rn_converge_ospf, g_rn_logs_dir, g_rn_nas, init_rib(), rn_getarea(), rn_getas(), rn_getlink(), rn_getmachine(), and rn_route().
{
        tw_stime         keepalive_interval;
        bgp_nbr         *n;
        int              i;
#if BGP_CONVERGED
        rn_area         *ar;
        rn_area         *d_ar;
        int              x_id;
#endif
#if VERIFY_BGP
        char             name[255];
        sprintf(name, "%s/router-%ld.log", g_rn_logs_dir, lp->id);
        if(lp->log)
                state->log = lp->log;
        else
                state->log = stdout;
                //lp->log = state->log = fopen(name, "w");
#else
        state->log = stdout;
#endif
        state->m = rn_getmachine(lp->id);
        state->as = rn_getas(state->m);
        state->stats = (bgp_stats *) calloc(sizeof(bgp_stats), 1);
        if(!state->stats)
                tw_error(TW_LOC, "Out of memory!");
        state->rib = (tw_memory **) calloc(sizeof(tw_memory *), g_rn_nas);
        if(!state->rib)
                tw_error(TW_LOC, "Out of memory!");
#if 0
        // connect all area tree roots
        if(0 && state->m->subnet->area->root == lp->id)
        {
#if VERIFY_BGP && 0
                printf("%ld: I am root for area: %d, lvl %d \n",
                        lp->id, state->m->subnet->area->id, state->m->level);
#endif
                for(i = 0; i < state->as->nareas; i++)
                {
                        if(g_rn_areas[i+state->as->low].root == INT_MAX ||
                           g_rn_areas[i+state->as->low].root == lp->id)
                                continue;
                        n = &state->nbr[state->n_interfaces++];
                        n->id = g_rn_areas[i+state->as->low].root;
                        n->up = TW_FALSE;
                }
        }
#endif
        if(g_rn_converge_ospf)
                return;
        // start the keepalive timer
        if(0 && state->as->hold_interval != 0.0)
        {
                keepalive_interval = tw_rand_exponential(lp->rng,
                                        state->as->keepalive_interval);
                state->tmr_keep_alive = bgp_timer_start(lp,
                                                state->tmr_keep_alive,
                                                keepalive_interval,
                                                KEEPALIVETIMER);
        }
#if BGP_CONVERGED
        for(i = 0; i < state->n_interfaces; i++)
        {
                n = &state->nbr[i];
                n->last_update = 0;
                if(-1 != rn_route(state->m, n->id) || rn_getlink(state->m, n->id))
                        n->up = TW_TRUE;
                else
                        n->up = TW_FALSE;
                ar = rn_getarea(state->m);
                d_ar = rn_getarea(rn_getmachine(n->id));
                // x_id is 0 for nbr ASes!
                if(ar == d_ar)
                        x_id = n->id - ar->low;
                else if(state->as == d_ar->as)
                        x_id = ar->nmachines + d_ar->id - state->as->low;
                else
                        x_id = -1;
                if(-1 == x_id)
                        n->hop_count = 0;
                else
                        n->hop_count = state->m->nhop[x_id];
        }
        init_rib(state, lp);
        bgp_keepalive_timer(state, NULL, NULL, lp);
#else
        // Create and install the route in our table
        bgp_route_add(state, bgp_route_new(state, lp, lp, lp));
        for(i = 0; i < state->n_interfaces; i++)
        {
                n = &state->nbr[i];
                n->last_update = 0;
                if(n->up == TW_FALSE)
                        bgp_connect(state, n, lp);
        }
#endif
}
void bgp_keepalive (bgp_state * state, int , int , tw_lp *)
Definition at line 42 of file bgp-keepalive.c.
References bgp_getnbr(), bgp_mrai_tmr(), bgp_open_send(), g_bgp_state, g_rn_nas, rn_getarea(), and rn_getmachine().
Referenced by bgp_event_handler().
{
        rn_area         *d_ar;
        rn_area         *ar;
        bgp_route       *r;
        bgp_nbr         *n;
        int              x_id;
        int              i;
        n = bgp_getnbr(state, src);
        if(NULL == n)
        {
                printf("%lld: adding neighbor: %d \n", lp->id, src);
                n = &state->nbr[state->n_interfaces++];
                n->id = src;
                n->up = TW_FALSE;
        }
        ar = rn_getarea(state->m);
        d_ar = rn_getarea(rn_getmachine(n->id));
        if(ar == d_ar)
                x_id = n->id - ar->low;
        else if(state->as == d_ar->as)
                x_id = ar->nmachines + d_ar->id - state->as->low;
        else
                x_id = -1;
        if(-1 != x_id && x_id > ar->g_ospf_nlsa)
                tw_error(TW_LOC, "x_id out of range!");
        // Get the latest hop count to the neighbor off this message
        if(g_bgp_state->b.hot_potato &&
                state->as == d_ar->as && x_id != -1 &&
                n->hop_count != state->m->nhop[x_id])
        {
                n->hop_count = state->m->nhop[x_id];
                for(i = 0; i < g_rn_nas; i++)
                {
                        if(!state->rib[i])
                                continue;
                        r = tw_memory_data(state->rib[i]);
                        if(r->src == n->id)
{
                                state->rib[i]->bit = TW_TRUE;
                                bgp_mrai_tmr(state, lp);
                        }
                }
        }
        // If we receive a message from a down host, start the OPEN process
        if(n->up == TW_FALSE)
        {
                bgp_open_send(state, n, lp);
                n->up = TW_TRUE;
#if VERIFY_BGP
                fprintf(state->log, "\tbringing up nbr %d at %lf\n",
                        src, tw_now(lp));
#endif
        }
        n->last_update = floor(tw_now(lp));
}
void bgp_keepalive_send (bgp_nbr * n, tw_lp * lp)
Definition at line 20 of file bgp-keepalive.c.
References BGP_KEEPALIVE, DOWNSTREAM, g_bgp_fd, rn_event_new(), and rn_event_send().
{
        tw_event       *e;
        tw_memory      *hdr;
        bgp_message    *m;
        e = rn_event_new(n->id, 0.0, lp, DOWNSTREAM, BGP_KEEPALIVE);
                return;
        // create the BGP header
        hdr = tw_memory_alloc(lp, g_bgp_fd);
        m = tw_memory_data(hdr);
        m->b.type = KEEPALIVE;
        tw_event_memory_set(e, hdr, g_bgp_fd);
        rn_event_send(e);
}
void bgp_keepalive_timer (bgp_state * , tw_bf * , bgp_message * , tw_lp *)
Definition at line 113 of file bgp-keepalive.c.
References BGP_KEEPALIVE, bgp_keepalive_tmr(), bgp_open_send(), DOWNSTREAM, g_bgp_fd, rn_event_new(), and rn_event_send().
Referenced by bgp_event_handler(), and bgp_init().
{
        tw_event       *e;
        tw_memory      *hdr;
        bgp_message    *m;
        bgp_nbr        *n;
        unsigned int    i;
        state->stats->s_nkeepalivetimers++;
        // send a keepalive to each neighbor
        for (i = 0, n = state->nbr; i < state->n_interfaces; n = &state->nbr[++i])
        {
                // If the neighbor is down, attempt to send OPEN instead..
                // idea is to simulate transport connection layer attempt
                if (n->up == TW_FALSE)
                {
                        bgp_open_send(state, n, lp);
                        continue;
                }
                e = rn_event_new(n->id, 0.0, lp, DOWNSTREAM, BGP_KEEPALIVE);
                hdr = tw_memory_alloc(lp, g_bgp_fd);
                m = tw_memory_data(hdr);
                m->b.type = KEEPALIVE;
                tw_event_memory_set(e, hdr, g_bgp_fd);
                rn_event_send(e);
#if VERIFY_BGP
                fprintf(state->log, "\tsent KEEPALIVE msg to %d at %lf \n",
                        n->id, e->recv_ts);
#endif
        }
        bgp_keepalive_tmr(state, lp);
}
void bgp_keepalive_tmr (bgp_state * state, tw_lp * lp)
Definition at line 7 of file bgp-keepalive.c.
References bgp_timer_start().
Referenced by bgp_keepalive_timer().
{
        if(0 == state->as->hold_interval)
                return;
        // keep the keepalive timer going
        state->tmr_keep_alive = bgp_timer_start(lp,
                                                state->tmr_keep_alive,
                                                state->as->keepalive_interval,
                                                KEEPALIVETIMER);
}
void bgp_main (int argc, char ** argv, char ** env)
Definition at line 147 of file bgp-main.c.
References bgp_setup_ases(), bgp_setup_options(), g_bgp_fd, g_bgp_fd_asp, g_bgp_fd_rtes, g_bgp_rt_fd, and g_rn_tools_dir.
{
        /*
         * Init the memory buffers for this model
         */
#if BGP_CONVERGED
        char            file[1024];
#endif
        tw_kp          *kp;
        int             i;
        printf("\nInitializing BGP memory buffers... ");
        for (i = 0; i < g_tw_nkp; i++)
        {
                kp = tw_getkp(i);
/*
                // Commented out for NCS
                g_bgp_fd_rtes = tw_kp_memory_init(kp, 1000 * g_tw_nlp, sizeof(bgp_route), 1);
                g_bgp_fd_asp = tw_kp_memory_init(kp, 1000 * g_tw_nlp, sizeof(int), 1);
                g_bgp_fd = tw_kp_memory_init(kp, 2000 * g_tw_nlp, sizeof(bgp_message), 1);
*/
                g_bgp_fd_rtes = tw_kp_memory_init(kp, g_tw_nlp, sizeof(bgp_route), 1);
                g_bgp_fd_asp = tw_kp_memory_init(kp, g_tw_nlp, sizeof(int), 1);
                g_bgp_fd = tw_kp_memory_init(kp, g_tw_nlp, sizeof(bgp_message), 1);
        }
        printf("done!\n");
/*
        printf("\tRoute   q: %10ld bufs %10ld fd\n", 1000 * g_tw_nlp, g_bgp_fd_rtes);
        printf("\tAS Path q: %10ld bufs %10ld fd\n", 1000 * g_tw_nlp, g_bgp_fd_asp);
        printf("\tMessage q: %10ld bufs %10ld fd\n", 1000 * g_tw_nlp, g_bgp_fd);
*/
        printf("\tRoute   q: %10lld bufs %10ld fd\n", g_tw_nlp, g_bgp_fd_rtes);
        printf("\tAS Path q: %10lld bufs %10ld fd\n", g_tw_nlp, g_bgp_fd_asp);
        printf("\tMessage q: %10lld bufs %10ld fd\n", g_tw_nlp, g_bgp_fd);
        printf("\n");
        bgp_setup_options(argc, argv);
        bgp_setup_ases();
#if BGP_CONVERGED
        sprintf(file, "tools/%s/bgp-route.file", g_rn_tools_dir);
        g_bgp_rt_fd = fopen(file, "r");
        if(!g_bgp_rt_fd)
                tw_error(TW_LOC, "Unable to open BGP routing file: %s", file);
#else
/*
        sprintf(file, "%s/bgp-route.file", g_rn_logs_dir);
        g_bgp_rt_fd = fopen(file, "w");
        if(!g_bgp_rt_fd)
                tw_error(TW_LOC, "Unable to open file: %s!", file);
*/
#endif
}
void bgp_md_final ()
Definition at line 208 of file bgp-main.c.
References g_bgp_as, g_bgp_rt_fd, g_bgp_stats, and g_rn_nas.
{
        int      i;
        int      j;
        printf("\nBGP4 Model Statistics: \n\n");
        printf("\t%-50s %11d\n", "Connects", g_bgp_stats.s_nconnects);
        printf("\t%-50s %11d\n", "Connects Dropped", g_bgp_stats.s_nconnects_dropped);
        printf("\n");
        printf("\t%-50s %11d\n", "Opens", g_bgp_stats.s_nopens);
        printf("\t%-50s %11d\n", "D Opens", g_bgp_stats.d_opens);
        printf("\n");
        printf("\t%-50s %11d\n", "Routes Added", g_bgp_stats.s_nroute_adds);
        printf("\t%-50s %11d\n", "Routes Removed", g_bgp_stats.s_nroute_removes);
        printf("\n");
        printf("\t%-50s %11d\n", "Updates Sent", g_bgp_stats.s_nupdates_sent);
        printf("\t%-50s %11d\n", "Updates Recv", g_bgp_stats.s_nupdates_recv);
        printf("\t%-50s %11d\n", "Update Unreachable", g_bgp_stats.s_nunreachable);
        printf("\n");
        printf("\t%-50s %11d\n", "Notify Sent", g_bgp_stats.s_nnotify_sent);
        printf("\t%-50s %11d\n", "Notify Recv", g_bgp_stats.s_nnotify_recv);
        printf("\n");
        printf("\t%-50s %11d\n", "Keepalives", g_bgp_stats.s_nkeepalives);
        printf("\t%-50s %11d\n", "Keepalive Timers", g_bgp_stats.s_nkeepalivetimers);
        printf("\n");
        printf("\t%-50s %11d\n", "MRAI Timers", g_bgp_stats.s_nmrai_timers);
        printf("\n");
        printf("\t%-50s %11d\n", "iBGP Neighbors Down", g_bgp_stats.s_nibgp_nbrs);
        printf("\t%-50s %11d\n", "eBGP Neighbors Down", g_bgp_stats.s_nebgp_nbrs);
        printf("\n");
        printf("\t%-50s %11d\n", "iBGP Neighbors Up", g_bgp_stats.s_nibgp_nbrs_up);
        printf("\t%-50s %11d\n", "eBGP Neighbors Up", g_bgp_stats.s_nebgp_nbrs_up);
        printf("\n");
        printf("\t%-50s %11d\n", "Decision: Local Pref", g_bgp_stats.s_ndec_local_pref);
        printf("\t%-50s %11d\n", "Decision: AS Path", g_bgp_stats.s_ndec_aspath);
        printf("\t%-50s %11d\n", "Decision: Origin", g_bgp_stats.s_ndec_origin);
        printf("\t%-50s %11d\n", "Decision: MED", g_bgp_stats.s_ndec_med);
        printf("\t%-50s %11d\n", "Decision: Hot Potato", g_bgp_stats.s_ndec_hot_potato);
        printf("\t%-50s %11d\n", "Decision: Next Hop", g_bgp_stats.s_ndec_next_hop);
        printf("\t%-50s %11d\n", "Decision: Existing", g_bgp_stats.s_ndec_existing);
        printf("\t%-50s %11d\n", "Decision: Default", g_bgp_stats.s_ndec_default);
        printf("\n");
        printf("BGP Caused Updates: %d\n", g_bgp_stats.s_cause_bgp);
        printf("OSPF Caused BGP Updates: %d", g_bgp_stats.s_cause_ospf);
        printf("\n");
        printf("BGP4 Topology: \n\n");
        for(i = 0; i < g_rn_nas; i++)
        {
                for(j = 0; j < g_rn_nas; j++)
                        printf("%10d ", g_bgp_as[i].degree[j]);
                printf("\n");
        }
        if(0 && g_bgp_rt_fd)
                fclose(g_bgp_rt_fd);
}
void bgp_mrai_timer (bgp_state * , tw_bf * , bgp_message * , tw_lp *)
Definition at line 20 of file bgp-mrai.c.
References bgp_update_all(), and g_rn_nas.
Referenced by bgp_event_handler().
{
        tw_memory       *b;
        bgp_route       *r;
        int              i;
        state->tmr_mrai = NULL;
        msg->b.update = 1;
        msg->b.cause_bgp = 1;
        msg->b.cause_ospf = 0;
        // Foreach route in the RIB with dirty bit set, send updates to nbrs
        for(i = 0; i < g_rn_nas; i++)
        {
                b = state->rib[i];
                // Route has not been updated since previous MRAI timer fired
                if(!b || b->bit == TW_FALSE)
                        continue;
                r = tw_memory_data(b);
                b->bit = TW_FALSE;
                bgp_update_all(state, msg, lp->id, r, lp);
        }
}
void bgp_mrai_tmr (bgp_state * state, tw_lp * lp)
Definition at line 7 of file bgp-mrai.c.
References bgp_timer_start().
Referenced by bgp_keepalive(), and bgp_route_add().
{
        if(state->tmr_mrai && state->tmr_mrai->recv_ts >= tw_now(lp))
                return;
        // keep the keepalive timer going
        state->tmr_mrai = bgp_timer_start(lp,
                                          state->tmr_mrai,
                                          state->as->mrai_interval,
                                          MRAITIMER);
}
void bgp_notify (bgp_state * state, tw_bf * bf, int src, tw_lp * lp)
Definition at line 29 of file bgp-notify.c.
References bgp_getnbr().
Referenced by bgp_event_handler().
{
        bgp_nbr         *n;
        n = bgp_getnbr(state, src);
#if VERIFY_BGP
        printf("%ld BGP: lost contact with %d \n", lp->id, n->id);
#endif
        //msg->old_last_update = n->last_update;
        n->last_update = floor(tw_now(lp)) - state->as->hold_interval; // - state->mrai;
        bf->c1 = 1;
}
void bgp_notify_send (bgp_state * , bgp_nbr * n, tw_lp * lp)
Definition at line 4 of file bgp-notify.c.
References BGP_NOTIFY, DOWNSTREAM, g_bgp_fd, rn_event_new(), and rn_event_send().
{
        tw_event        *e;
        tw_memory       *hdr;
        bgp_message     *m;
        state->stats->s_nnotify_sent++;
        e = rn_event_new(n->id, 0.0, lp, DOWNSTREAM, BGP_NOTIFY);
        hdr = tw_memory_alloc(lp, g_bgp_fd);
        m = tw_memory_data(hdr);
        m->b.type = NOTIFICATION;
        tw_event_memory_set(e, hdr, g_bgp_fd);
        rn_event_send(e);
#if VERIFY_BGP
        fprintf(state->log, "\tsent notify to nbr %d at %f\n", n->id, tw_now(lp));
#endif
}
void bgp_open (bgp_state * , tw_bf * , bgp_message * , int , tw_lp *)
Definition at line 48 of file bgp-open.c.
References bgp_getnbr(), bgp_update_send(), g_rn_nas, rn_getas(), and rn_getmachine().
Referenced by bgp_event_handler().
{
        tw_memory      *b;
        bgp_route       *r;
        bgp_nbr         *n;
        int              i;
        state->stats->d_opens = 1;
        state->stats->s_nopens++;
        // set the nbr to up
        n = bgp_getnbr(state, src);
        //n->up = TW_TRUE;
        // send a keepalive in response to the open
        //bgp_keepalive_send(n, lp);
        // now we will send this neighbor our full routing table
        // reflection: only send down in the BGP hierarchy
#if VERIFY_BGP
        fprintf(state->log, "\tsending routing table to %d\n", n->id);
#endif
        /*
         * If route source is down (timed out) and iBGP node,
         * then some internal OSPF route must have changed.
         *
         * If an eBGP node has timed out, it is not due to OSPF.
         *
         * Send an update for each route in our routing table.
         */
        for(i = 0; i < g_rn_nas; i++)
        {
                if(NULL == (b = state->rib[i]))
                        continue;
                r = tw_memory_data(b);
                msg->b.update = 1;
                // If OPEN from iBGP node, do not append to AS_PATH
                if(rn_getas(rn_getmachine(n->id)) == state->as)
                {
                        if(r->dst == state->as->id)
                                continue;
                        bgp_update_send(state, n, r, msg, 1, lp);
                } else
                {
                        if(r->dst == rn_getas(rn_getmachine(n->id))->id)
                                continue;
                        bgp_update_send(state, n, r, msg, 0, lp);
                }
        }
}
void bgp_open_send (bgp_state * , bgp_nbr * n, tw_lp * lp)
Definition at line 4 of file bgp-open.c.
References BGP_OPEN, DOWNSTREAM, g_bgp_fd, rn_event_new(), rn_event_send(), rn_getas(), and rn_getmachine().
Referenced by bgp_keepalive(), and bgp_keepalive_timer().
{
        tw_event        *e;
        tw_memory       *b;
        bgp_message     *m;
        e = rn_event_new(n->id, 0.0, lp, DOWNSTREAM, BGP_OPEN);
        // Create the BGP message header
        b = tw_memory_alloc(lp, g_bgp_fd);
        m = tw_memory_data(b);
        m->b.type = OPEN;
        // Must be caused by OSPF route newly available to iBGP neighbor
        // Also, to avoid counting on initial OPEN messages, tw_now > 0.0
        if(tw_now(lp) > 0.0 && state->as == rn_getas(rn_getmachine(n->id)))
        {
                m->b.cause_ospf = 1;
                m->b.cause_bgp = 0;
        } else if(tw_now(lp) > 0.0)
        {
                m->b.cause_ospf = 0;
                m->b.cause_bgp = 1;
        } else
        {
                m->b.cause_ospf = 0;
                m->b.cause_bgp = 0;
        }
        tw_event_memory_set(e, b, g_bgp_fd);
        rn_event_send(e);
#if VERIFY_BGP
        fprintf(state->log, "%ld BGP: Send OPEN to %d\n", lp->id, n->id);
#endif
}
void bgp_ospf_flush (bgp_state * , rn_as * , bgp_route * , int , tw_lp *)
Definition at line 330 of file bgp-ospf.c.
{
        tw_error(TW_LOC, "argh");
}
void bgp_ospf_init (bgp_state * bs, bgp_route * r, tw_lp * lp)
Definition at line 8 of file bgp-ospf.c.
References bgp_lsa_find(), ospf_db_remove(), ospf_db_route(), OSPF_MIN_LSA_SEQNUM, rn_getarea(), rn_getmachine(), rn_getstream_byport(), and s.
{
        rn_lp_state     *rn_state;
        rn_stream       *s;
        rn_area         *ar;
        ospf_state      *state;
        ospf_db_entry   *dbe;
        int              entry;
        ar = rn_getarea(rn_getmachine(lp->id));
        entry = ar->nmachines + ar->as->nareas + r->dst;
        rn_state = lp->cur_state;
        s = rn_getstream_byport(rn_state, 23);
        if(!s || s->port != 23)
                return;
        state = s->layers[0].lp.cur_state;
        dbe = &state->db[entry];
        /*** CANNOT RE-BUILD ROUTING TABLES !!! ***/
        if(NULL == r)
        {
                // remove from database
                ospf_db_remove(state, entry, lp);
        } else if(1 == dbe->b.free)
        {
                // insert into DB
                dbe->b.age = 0;
                dbe->b.free = 0;
                dbe->b.entry = entry;
                dbe->seqnum = OSPF_MIN_LSA_SEQNUM;
                dbe->lsa = bgp_lsa_find(bs, state, r, entry, lp);
                ospf_db_route(state, dbe, lp);
        } else
        {
                // update database
                dbe = &state->db[entry];
                dbe->b.age = 0;
                dbe->b.free = 0;
                dbe->b.entry = entry;
                dbe->seqnum = OSPF_MIN_LSA_SEQNUM;
                dbe->lsa = bgp_lsa_find(bs, state, r, entry, lp);
                ospf_db_route(state, dbe, lp);
        }
#if VERIFY_BGP
        fprintf(bs->log, "\tinitialized OSPF lsa: AS %d, LSA %d \n",
                r->dst, entry);
#endif
}
void bgp_ospf_update (bgp_state * , rn_as * , bgp_route * , int , tw_lp *)
Definition at line 70 of file bgp-ospf.c.
References bgp_lsa_find(), getlsa(), ospf_lsa_create(), OSPF_LSA_MAX_AGE, rn_getarea(), rn_getmachine(), rn_getstream_byport(), and s.
Referenced by deal_with_timed_out_routers(), update_add(), and update_withdraw().
{
#ifdef HAVE_OSPF_H
        tw_lp           *cur_lp;
        rn_lp_state     *rn_state;
        rn_area         *ar;
        rn_stream       *s;
        ospf_state      *state;
        ospf_db_entry   *dbe;
        ospf_lsa        *old_lsa;
        ospf_nbr         nbr;
        int              entry;
        int              cur_stream;
        ar = rn_getarea(rn_getmachine(lp->id));
        entry = ar->nmachines + ar->as->nareas + dest_as->id;
        // Get the OSPF router state
        rn_state = lp->cur_state;
        cur_stream = rn_state->cur_stream;
        cur_lp = rn_state->cur_lp;
        s = rn_getstream_byport(rn_state, 23);
        if(!s || s->port != 23)
        {
                printf("%ld: Did not send update (%d) to OSPF! \n", lp->id, add);
                rn_state->cur_stream = cur_stream;
                return;
        }
        state = s->layers[0].lp.cur_state;
        rn_state->cur_lp = &s->layers[0].lp;
        // Get and fill in the new LSA
        dbe = &state->db[entry];
/*
        You *MUST* restore the cur_stream and cur_lp pointers
        BEFORE return-ing from this function!!!!!!!!!!!!!!!!!
        If you don't, future BGP pkts will go to OSPF on the
        other side of the connection!
*/
        if(add && dbe->b.free == 0)
        {
                // If multiple possible originators,
                // rtr w/ > id is originator.
                // Eliminates oscillation / duplicate effort
                old_lsa = getlsa(state->m, dbe->lsa, entry);
                if(old_lsa && lp->id < old_lsa->adv_r)
                {
                        rn_state->cur_lp = cur_lp;
                        rn_state->cur_stream = cur_stream;
                        return;
                }
                // No need to change LSA is route src has not changed!
                if(old_lsa)
                {
                        ospf_lsa_link *l = tw_memory_data(old_lsa->links.head);
                        if(l->dst == r->src && old_lsa->adv_r == lp->id)
{
                                rn_state->cur_lp = cur_lp;
                                rn_state->cur_stream = cur_stream;
                                return;
                        }
                }
        }
        /*
         * Construct the DB entry we need, and have OSPF process it.
         * If we wanted to connect BGP to OSPF on different routers,
         * we would simply need to send the OSPF node an UPDATE message
         */
        //dbe->b.entry = entry;
        dbe->cause_bgp = 1;
        dbe->lsa = bgp_lsa_find(bs, state, r, entry, lp);
        nbr.id = r->src;
        nbr.state = ospf_nbr_full_st;
        if(add)
        {
                dbe->b.age = 0;
                dbe->b.free = 0;
                dbe->seqnum = state->lsa_seqnum;
                ospf_lsa_create(state, &nbr, entry, lp);
        } else
        {
                if(dbe->b.free)
                {
                        rn_state->cur_stream = cur_stream;
                        rn_state->cur_lp = cur_lp;
                        return;
                }
                dbe->b.age = OSPF_LSA_MAX_AGE;
                ospf_lsa_create(state, &nbr, entry, lp);
                dbe->b.free = 1;
        }
        state->stats->s_cause_bgp++;
#if VERIFY_BGP
        if(add)
                fprintf(bs->log, "\tinstalled lsa into OSPF! AS %d, LSA %d \n",
                        dest_as->id, entry);
        else
                fprintf(bs->log, "removed lsa from OSPF! \n");
#endif
        rn_state->cur_stream = cur_stream;
        rn_state->cur_lp = cur_lp;
#endif
}
void bgp_r_event_handler (bgp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 179 of file bgp-rc-router.c.
References bgp_getnbr(), r_msg_keepalive(), r_msg_keepalivetimer(), r_msg_open(), r_msg_update(), and rn_message_data().
{
        bgp_message    *msg;
        bgp_nbr         *n;
        msg = rn_message_data(rn_msg);
        switch (msg->type)
        {
        case OPEN:
                {
                        // open bgp_message
                        r_msg_open(state, bf, msg, lp);
                        break;
                }
        case KEEPALIVE:
                {
                        // keepalive bgp_message
                        r_msg_keepalive(state, bf, msg, lp);
                        break;
                }
        case UPDATE:
                {
                        // update bgp_message
                        r_msg_update(state, bf, msg, lp);
                        break;
                }
        case NOTIFICATION:
                {
                        // notification (error) bgp_message
                        // r_msg_notification(state, bf, msg, lp);
                        break;
                }
        case KEEPALIVETIMER:
                {
                        // keepalive timer event
                        // r_deal_with_timed_out_routers(state, bf, msg, lp);
                        r_msg_keepalivetimer(state, bf, msg, lp);
                        break;
                }
        default:
                printf("Unhandled message type: %d \n", msg->type);
        }
        n = bgp_getnbr(state, msg->src);
        n->last_update = msg->old_last_update;
        n->up = msg->was_up;
}
void bgp_rib_print (bgp_state * state, tw_lp * lp)
Definition at line 360 of file bgp-route.c.
References bgp_route_print(), g_rn_nas, rn_getas(), and rn_getmachine().
Referenced by bgp_final().
{
#if VERIFY_BGP
        tw_memory       *b;
        rn_as           *as;
        rn_machine      *m;
        bgp_route       *r;
        int              offset;
        int              i;
        m = rn_getmachine(lp->id);
        as = rn_getas(m);
        fprintf(state->log, "\nRouting Information Base (RIB): Node %ld, AS %d\n",
                lp->id, as->id);
        fprintf(state->log, "%-10s%-10s%-10s%-10s%-10s%-10s\n",
                "Dest", "NHI", "NHI Node", "MED", "ORIGIN", " #  AS Path");
        offset = m->subnet->area->nmachines + as->nareas;
        for(i = 0; i < g_rn_nas; i++)
        {
                if(NULL == (b = state->rib[i]))
                        continue;
                r = tw_memory_data(b);
                if(r->dst == as->id)
                {
                        bgp_route_print(state, r);
                        fprintf(state->log, "\n");
                } else
                {
                        bgp_route_print(state, r);
                        fprintf(state->log, "\n");
                }
        }
#endif
}
void bgp_route_add (bgp_state * state, tw_memory * b)
Definition at line 73 of file bgp-route.c.
References bgp_mrai_tmr(), bgp_route_print(), rn_getarea(), rn_getas(), rn_getlink(), rn_getmachine(), rn_route(), and rn_route_change().
Referenced by bgp_init(), and update_add().
{
        rn_link         *l;
        rn_area         *ar;
        bgp_route       *r;
        int              offset;
        int              nhi;
        int              dst;
        int              i;
        ar = rn_getarea(state->m);
        r = tw_memory_data(b);
        nhi = -1;
        offset = ar->nmachines + ar->as->nareas;
        if(state->rib[r->dst] != NULL)
                tw_error(TW_LOC, "Over-writing route for AS %d!", r->dst);
        state->rib[r->dst] = b;
        // reset the MRAI timer as needed
        b->bit = TW_TRUE;
        bgp_mrai_tmr(state, tw_getlp(state->m->id));
        state->stats->s_nroute_adds++;
        // Self-originated route
        if(r->src == state->m->id)
                return;
        l = rn_getlink(state->m, r->src);
        // eBGP route being added, so must have interface to node
        // (could be iBGP w/o OSPF network in-between also)
        if(l)
        {
                for(i = 0; i < state->m->nlinks; i++)
                        if(state->m->link[i].addr == r->src)
{
                                nhi = i;
                                break;
                        }
                dst = r->src;
                offset += rn_getas(rn_getmachine(r->src))->id;
        } else // must be iBGP route being added, so must get route to node
        {
                dst = r->src;
                nhi = rn_route(state->m, r->src);
                offset += r->dst;
        }
        rn_route_change(state->m, offset, nhi);
#if VERIFY_BGP
        fprintf(state->log, "\tadding route: ft[%d]=%d \n\t",
                offset, rn_route(state->m, dst));
        bgp_route_print(state, r);
#endif
}
void bgp_route_aspath_print (bgp_state * state, bgp_route * r)
Definition at line 30 of file bgp-route.c.
Referenced by bgp_route_print(), and update_add().
{
#if VERIFY_BGP || !BGP_CONVERGED
        tw_memory       *b;
        fprintf(state->log, " %d  ", r->as_path.size);
        for (b = r->as_path.head; b != NULL; b = b->next)
                fprintf(state->log, "%d ", * (int *) tw_memory_data(b));
        fprintf(state->log, "\n");
#endif
}
tw_memory* bgp_route_copy (bgp_state * , bgp_route * , bgp_nbr * , bgp_update_type , tw_lp *)
Definition at line 221 of file bgp-route.c.
References bgp_route_free(), g_bgp_as, g_bgp_fd_asp, g_bgp_fd_rtes, rn_getas(), rn_getlink(), rn_getmachine(), and rn_route().
Referenced by bgp_update_send().
{
        rn_as           *as;
        rn_as           *d_as;
        tw_memory       *new_route;
        tw_memory       *b;
        tw_memory       *b1;
        bgp_nbr         *nbr;
        bgp_route       *r;
        int             *hop;
        int              last;
        int              size;
        int              i;
        as = rn_getas(rn_getmachine(lp->id));
        d_as = rn_getas(rn_getmachine(n->id));
        new_route = tw_memory_alloc(lp, g_bgp_fd_rtes);
        new_route->bit = 0;
        r = tw_memory_data(new_route);
        // If IP drops pkt, it does not know to free these bufs
        if(r->as_path.head || r->as_path.tail)
        {
                bgp_route_free(state, new_route, lp);
                new_route = tw_memory_alloc(lp, g_bgp_fd_rtes);
                if(r->as_path.head || r->as_path.tail)
                        tw_error(TW_LOC, "STILL!");
        }
        /*
         5.1.4   MULTI_EXIT_DISC
                The MULTI_EXIT_DISC attribute may be used on external (inter-AS)
                links to discriminate among multiple exit or entry points to the same
                neighboring AS.  The value of the MULTI_EXIT_DISC attribute is a four
                octet unsigned number which is called a metric.  All other factors
                being equal, the exit or entry point with lower metric should be
                preferred.  If received over external links, the MULTI_EXIT_DISC
                attribute may be propagated over internal links to other BGP speakers
                within the same AS.  The MULTI_EXIT_DISC attribute is never
                propagated to other BGP speakers in neighboring AS's.
                Cisco MED example: http://www.cisco.com/warp/public/459/37.html
         */
        if(d_as == as)
        {
                r->med = to_be_copied->med;
        } else if(to_be_copied->src == lp->id)
        {
                // Should only be executed when we are creating route for
                // the first time, which should only be once per connection
                for(size = 0, i = 0; i < state->n_interfaces; i++)
                {
                        nbr = &state->nbr[i];
                        if(rn_getas(rn_getmachine(nbr->id))->id == d_as->id)
                                size++;
                }
                if(size > 1)
                        r->med = g_bgp_as[as->id].med;
                else
                        r->med = 0xffff;
        } else
                r->med = 0xffff;
        r->src = lp->id;
        r->dst = to_be_copied->dst;
        if(d_as != state->as)
                r->origin = 2;
        else
                r->origin = 1;
        // Copy the AS path
        // have to preserve the AS path order, so go backwards through list!
        size = to_be_copied->as_path.size;
        last = -1;
        for(i = 0, b = to_be_copied->as_path.tail; i < size; i++, b = b->prev)
        {
                b1 = tw_memory_alloc(lp, g_bgp_fd_asp);
                hop = tw_memory_data(b1);
                *hop = *(int *) tw_memory_data(b);
                last = *hop;
                tw_memoryq_push(&r->as_path, b1);
        }
        if(d_as == as)
        {
                r->next_hop = to_be_copied->next_hop;
                if(rn_getlink(state->m, n->id))
                        r->next_hop = n->id;
                else
                        r->next_hop = state->m->link[rn_route(state->m, n->id)].addr;
        } else
        {
                r->next_hop = as->id;
                // Add myself to the AS path only on UPDATE adds
                if(t == ADD)
                {
/*
                        printf("Padding by %d for AS %d \n",
                                g_bgp_as[as->id].path_padding, as->id);
*/
                        for(i = 0; i < g_bgp_as[as->id].path_padding; i++)
{
                                b1 = tw_memory_alloc(lp, g_bgp_fd_asp);
                                hop = tw_memory_data(b1);
                                *hop = lp->id;
                                tw_memoryq_push(&r->as_path, b1);
                        }
                }
        }
        return new_route;
}
int bgp_route_equals (bgp_route * , bgp_route *)
Definition at line 176 of file bgp-route.c.
Referenced by bgp_update_send(), and update_withdraw().
{
        tw_memory       *b1;
        tw_memory       *b2;
        int             *hop1;
        int             *hop2;
        if (r1->dst != r2->dst)
                return TW_FALSE;
        if (r1->next_hop != r2->next_hop)
                return TW_FALSE;
        if (r1->as_path.size != r2->as_path.size)
                return TW_FALSE;
        if (r1->med != r2->med)
                return TW_FALSE;
        // Since AS path order is preserved, we should have
        // a one to one mapping between route AS paths
        b1 = r1->as_path.head;
        b2 = r2->as_path.head;
        for(; b1 && b2; b1 = b1->next, b2 = b2->next)
        {
                hop1 = tw_memory_data(b1);
                hop2 = tw_memory_data(b2);
                if(*hop1 != *hop2)
                        return TW_FALSE;
        }
        return TW_TRUE;
}
int bgp_route_free (bgp_state * state, tw_memory * route, tw_lp * lp)
Definition at line 52 of file bgp-route.c.
References g_bgp_fd_asp, and g_bgp_fd_rtes.
Referenced by bgp_route_copy(), bgp_update(), deal_with_timed_out_routers(), update_add(), and update_withdraw().
{
        tw_memory       *b;
        bgp_route       *r;
        int              rv;
        r = tw_memory_data(route);
        rv = r->as_path.size;
        while((b = tw_memoryq_pop(&r->as_path)))
                tw_memory_free(lp, b, g_bgp_fd_asp);
        if(r->as_path.head || r->as_path.tail)
                tw_error(TW_LOC, "AS Path not empty!");
        tw_memory_free(lp, route, g_bgp_fd_rtes);
        return rv;
}
int bgp_route_inpath (bgp_state * state, bgp_route * r_in, tw_lp * lp)
Definition at line 5 of file bgp-route.c.
Referenced by update_add().
{
        tw_memory       *b;
        int             *hop;
        int              i;
        //for (b = r_in->as_path.head; b; b = b->next)
        for(i = 0, b = r_in->as_path.head; i < r_in->as_path.size; i++, b = b->next)
        {
                hop = tw_memory_data(b);
                if(*hop == lp->id)
                {
#if VERIFY_BGP
                        fprintf(state->log, "\tfound myself in AS path: %ld\n",
                                lp->id);
#endif
                        return TW_TRUE;
                }
        }
        return TW_FALSE;
}
tw_memory* bgp_route_new (bgp_state * , tw_lp * , tw_lp * , tw_lp *)
Definition at line 157 of file bgp-route.c.
References g_bgp_fd_rtes, rn_getas(), and rn_getmachine().
Referenced by bgp_init().
{
        tw_memory       *b;
        bgp_route       *r;
        b = tw_memory_alloc(lp, g_bgp_fd_rtes);
        r = tw_memory_data(b);
        r->src = src->id;
        r->dst = rn_getas(rn_getmachine(dst->id))->id;
        r->next_hop = state->as->id;
        r->origin = 3;
        r->med = 0xffff;
        return b;
}
void bgp_route_print (bgp_state * state, bgp_route * r)
Definition at line 350 of file bgp-route.c.
References bgp_route_aspath_print().
Referenced by bgp_final(), bgp_rib_print(), bgp_route_add(), bgp_route_withdraw(), bgp_update_send(), and update_withdraw().
{
#if VERIFY_BGP || !BGP_CONVERGED
        fprintf(state->log, "%-10hd%-10hd%-10d%-10hd%-10hd",
                r->dst, r->next_hop, r->src, r->med, r->origin);
        bgp_route_aspath_print(state, r);
#endif
}
void bgp_route_withdraw (bgp_state * state, bgp_route * r)
Definition at line 138 of file bgp-route.c.
References bgp_route_print(), rn_getarea(), rn_route(), and rn_route_change().
Referenced by deal_with_timed_out_routers(), update_add(), and update_withdraw().
{
        rn_area         *ar;
        ar = rn_getarea(state->m);
        state->rib[r->dst] = NULL;
        rn_route_change(state->m, ar->nmachines + ar->as->nareas + r->dst, -1);
        state->stats->s_nroute_removes++;
#if VERIFY_BGP
        fprintf(state->log, "\twithdrawing route: ft[%d]=%d \n\t",
                ar->nmachines + ar->as->nareas + r->dst,
                rn_route(state->m, ar->nmachines + ar->as->nareas + r->dst));
        bgp_route_print(state, r);
#endif
}
void bgp_rt_file (int * read)
tw_event* bgp_timer_start (tw_lp * , tw_event * , tw_stime , bgp_message_type)
Definition at line 4 of file bgp-utils.c.
References g_bgp_fd, and rn_timer_simple().
Referenced by bgp_init(), bgp_keepalive_tmr(), and bgp_mrai_tmr().
{
        tw_memory       *b = tw_memory_alloc(lp, g_bgp_fd);
        bgp_message     *m = tw_memory_data(b);
        tmr = rn_timer_simple(lp, ts);
        m->b.type = type;
        tw_event_memory_set(tmr, b, g_bgp_fd);
        return tmr;
}
void bgp_update (bgp_state * , tw_bf * , bgp_message * , int , tw_lp *)
Definition at line 81 of file bgp-update.c.
References bgp_getnbr(), bgp_route_free(), bgp_update_send(), update_add(), and update_withdraw().
Referenced by bgp_event_handler().
{
        tw_memory       *b_in;
        bgp_route       *r;
        int              cause;
        char             temp[2048];
        if(NULL == (b_in = tw_event_memory_get(lp)))
                tw_error(TW_LOC, "No UPDATE on event!");
        r = tw_memory_data(b_in);
        if(!r)
                tw_error(TW_LOC, "Invalid route on UDPATE!");
        sprintf(temp, "%d %d %d", r->src, r->dst, r->next_hop);
        // we're adding a route
        if(msg->b.update)
        {
                update_add(state, bf, b_in, msg, src, lp);
        } else
        {
                update_withdraw(state, bf, r, msg, src, lp);
                if(msg->b.unreachable == 0)
                        return;
#if VERIFY_BGP
                fprintf(state->log, "\tgot UNREACHABLE UPDATE from %d, for AS %d\n",
                        src, r->dst);
#endif
                if(state->rib[r->dst] != NULL)
                {
                        msg->b.update = 1;
                        if(msg->b.cause_ospf)
                                cause = 1;
                        else
                                cause = 0;
                        bgp_update_send(state, bgp_getnbr(state, src),
                                        tw_memory_data(state->rib[r->dst]),
                                        msg, cause, lp);
                        state->stats->s_nunreachable++;
                }
                bgp_route_free(state, b_in, lp);
        }
}
void bgp_update_all (bgp_state * , bgp_message * , int , bgp_route * , tw_lp *)
Definition at line 264 of file bgp-update.c.
References bgp_update_send(), rn_getas(), and rn_getmachine().
Referenced by bgp_mrai_timer(), update_add(), and update_withdraw().
{
        bgp_nbr         *n;
        int              i;
        for(i = 0, n = state->nbr; i < state->n_interfaces; n = &state->nbr[++i])
        {
                if (n->up == TW_FALSE || (src == n->id))
                        continue;
                if(r->dst == rn_getas(rn_getmachine(n->id))->id)
                        continue;
                // If from iBGP peer, do not send to other iBGP peers
                if(state->as == rn_getas(rn_getmachine(r->src)) &&
                   state->as == rn_getas(rn_getmachine(n->id)))
                        continue;
                if(msg->b.cause_bgp == msg->b.cause_ospf)
                        tw_error(TW_LOC, "Unmarked UPDATE!");
                if(msg->b.cause_bgp)
                        bgp_update_send(state, n, r, msg, 0, lp);
                else
                        bgp_update_send(state, n, r, msg, 1, lp);
                //msg->b.rev_num_neighbors++;
        }
}
void bgp_update_send (bgp_state * , bgp_nbr * , bgp_route * , bgp_message * , int , tw_lp *)
Definition at line 7 of file bgp-update.c.
References bgp_route_copy(), bgp_route_equals(), bgp_route_print(), BGP_UPDATE, DOWNSTREAM, g_bgp_fd, g_bgp_fd_rtes, g_bgp_stats, rn_event_new(), rn_event_send(), rn_getas(), and rn_getmachine().
Referenced by bgp_open(), bgp_update(), bgp_update_all(), and deal_with_timed_out_routers().
{
        tw_event        *e;
        tw_memory       *hdr;
        tw_memory       *b;
        //bgp_route     *test;
        bgp_message     *m;
        state->stats->s_nupdates_sent++;
        e = rn_event_new(n->id, 0.0, lp, DOWNSTREAM, BGP_UPDATE);
        hdr = tw_memory_alloc(lp, g_bgp_fd);
        m = tw_memory_data(hdr);
        m->b.type = UPDATE;
        m->b.update = msg->b.update;
        m->b.cause_bgp = m->b.cause_ospf = 0;
        if(cause)
                m->b.cause_ospf = 1;
        else
        {
                m->b.cause_bgp = 1;
                g_bgp_stats.s_cause_bgp++;
        }
        // Having problems with membufs being attached to membufs.. impossible
        // to free them if the pkt is dropped outside the BGP model.
        tw_event_memory_set(e, hdr, g_bgp_fd);
        rn_event_send(e);
        if(e->state.owner == TW_pe_free_q || e == lp->pe->abort_event)
                return;
        // if can be sent, get the hdr back off the event now so the route
        // can be put on first.
        e->memory = NULL;
        // Add the route to the UPDATE message
        if(msg->b.update == 0 || rn_getas(rn_getmachine(n->id)) == state->as)
                b = bgp_route_copy(state, r_send, n, 0, lp);
        else
                b = bgp_route_copy(state, r_send, n, 1, lp);
#if 0
        test = tw_memory_data(b);
        if(TW_FALSE == bgp_route_equals(test, r_send))
                tw_error(TW_LOC, "Invalid ROUTE copy!");
#endif
        if(m->b.update == REMOVE && state->rib[r_send->dst] == NULL)
                m->b.unreachable = 1;
        else
                m->b.unreachable = 0;
        tw_event_memory_set(e, b, g_bgp_fd_rtes);
        tw_event_memory_set(e, hdr, g_bgp_fd);
        // Had to be moved up to before membufs placed onto event.. because
        // event may be aborted, and then we do not want to copy the route
        //rn_event_send(e);
#if VERIFY_BGP
        fprintf(state->log, "\t\tsent UPDATE (%d) to %d at %f: \n\t\t",
                m->b.update, n->id, tw_now(lp));
        bgp_route_print(state, tw_memory_data(b));
#endif
}
void bgp_xml (bgp_state * state, const xmlNodePtr node, tw_lp *)
Definition at line 6 of file bgp-xml.c.
References g_bgp_as, g_bgp_ases, g_bgp_state, rn_getarea(), rn_getas(), rn_getmachine(), and xml_getprop().
{
#if IBGP
        xmlXPathObjectPtr        obj;
        xmlNodePtr               node2;
        int                      id;
        int                      j;
#endif
        xmlNodePtr               interface;
        rn_machine              *m;
        rn_area                 *ar;
        bgp_nbr                 *n;
        //char                  *local_pref;
        int                      i;
        int                      lvl;
#if IBGP_TREE
        int                      diff;
        int                      has_ibgp;
#endif
        state->m = m = rn_getmachine(lp->id);
        state->as = rn_getas(m);
        ar = rn_getarea(m);
        // Check for local parameter settings
        // then check for global parameter settings
        // then set to defaults
        if(0 != strcmp("", xml_getprop(node, "keep_alive")))
        {
                //state->keepalive_interval = atof(xml_getprop(node, "keep_alive"));
                //state->hold_interval = atof(xml_getprop(node, "hold"));
                //state->mrai = atof(xml_getprop(node, "mrai"));
        } else if(NULL != g_bgp_state)
        {
                state->keepalive_interval = g_bgp_state->keepalive_interval;
                state->hold_interval = g_bgp_state->hold_interval;
                state->mrai_interval = g_bgp_state->mrai_interval;
        } else
        {
                //state->keepalive_interval = 30.0;
                //state->hold_interval = 45.0;
                //state->mrai = 90.0;
        }
        /*
         * Now we need to set up the interfaces for the BGP neighbors
         */
        for(interface = node->children; interface; interface = interface->next)
        {
                if(0 != strcmp((char *) interface->name, "neighbor"))
                        continue;
                state->n_interfaces++;
        }
        // Add in the iBGP neighbors
#if IBGP
        state->n_interfaces += g_bgp_ases[state->as->id]->nodesetval->nodeNr - 1;
        state->n_interfaces += state->as->nareas;
#endif
        if(state->n_interfaces <= 0)
                return; //tw_error(TW_LOC, "BGP router has no neighbors!");
        state->nbr = (bgp_nbr *) calloc(sizeof(bgp_nbr), state->n_interfaces);
        if(!state->nbr)
                tw_error(TW_LOC, "Out of memory!");
        for(i = 0, interface = node->children; interface; interface = interface->next)
        {
                if(0 != strcmp((char *) interface->name, "neighbor"))
                        continue;
                if(rn_getmachine(atoi(xml_getprop(interface, "addr")))->subnet->area->as == state->as)
                {
                        if(lp->id % 100000 == 0)
                                printf("%lld: removing iBGP node from nbrs: %d \n",
                                        lp->id, atoi(xml_getprop(interface, "addr")));
                        state->n_interfaces--;
                        continue;
                }
                n = &state->nbr[i++];
                n->up = TW_FALSE;
                n->id = atoi(xml_getprop(interface, "addr"));
                g_bgp_as[state->as->id].degree[rn_getas(rn_getmachine(n->id))->id]++;
                g_bgp_as[state->as->id].degree[state->as->id]++;
#if 0
                local_pref = xml_getprop(interface, "local_pref");
                if(0 != strcmp("", local_pref))
                {
                        n->local_pref = atoi(local_pref);
#if VERIFY_BGP
                        printf("%ld BGP: nbr %d local_pref: %d \n",
                                lp->id, n->id, n->local_pref);
#endif
                } else
                {
                        n->local_pref = 100;
                }
#endif
        }
#if IBGP
        // AS level
#if 0
        // Determine Area root node
        if(ar->root_lvl > m->level)
        {
                ar->root = m->id;
                ar->root_lvl = m->level;
        }
#endif
        state->n_interfaces -= state->as->nareas;
        obj = g_bgp_ases[state->as->id];
        node2 = obj->nodesetval->nodeTab[0];
        for(j = 0; j < obj->nodesetval->nodeNr; node2 = obj->nodesetval->nodeTab[++j])
        {
                id = atoi(xml_getprop(node2->parent, "id"));
                lvl = atoi(xml_getprop(node2->parent, "lvl"));
                if(id == lp->id)
                        continue;
#if IBGP_TREE
                diff = state->m->level - lvl;
                if(state->m->subnet->area == rn_getarea(rn_getmachine(id)) &&
                    (diff == -1 || diff == 1))
                {
                        has_ibgp = 1;
                        n = &state->nbr[i++];
                        n->id = id;
                        n->up = TW_TRUE;
                } else
                        state->n_interfaces--;
#else
                n = &state->nbr[i++];
                n->id = id;
                n->up = TW_TRUE;
#endif
        }
#if 0
        // Make sure we're at least connected once to our BGP network
        if(state->m->root == 0 && has_ibgp == 0)
        {
                state->n_interfaces++;
                n = &state->nbr[i++];
                n->id = state->m->subnet->area->root;
                n->up = TW_FALSE;
        }
#endif
#endif
}
void deal_with_timed_out_routers (bgp_state * state, tw_bf * bf, bgp_message * msg, tw_lp * lp)
Definition at line 156 of file bgp-keepalive.c.
References bgp_ospf_update(), bgp_route_free(), bgp_route_withdraw(), bgp_update_send(), g_rn_nas, rn_getas(), and rn_getmachine().
Referenced by bgp_event_handler().
{
        tw_stime        now;
        tw_memory      *b;
        tw_memory      *r_next;
        bgp_route      *r;
        bgp_nbr        *n;
        bgp_nbr        *n1;
        int             cause;
        int             found;
        int             i;
        int             j;
        now = floor(tw_now(lp));
        //msg->rev_num_neighbors = 0;
        //msg->rc_asp = 0;
        for (i = 0, n = state->nbr; i < state->n_interfaces; n = &state->nbr[++i])
        {
                if (!n->up || ((now - n->last_update) <= state->as->hold_interval))
                        continue;
#if VERIFY_BGP
                fprintf(state->log, "\tnbr %d timed out: %lf > %lf hold interval\n",
                        n->id, (now - n->last_update), state->as->hold_interval);
#endif
                n->up = TW_FALSE;
                found = TW_FALSE;
                // If nbr timed out due to failed eBGP link, then the
                // cause of the UPDATES is BGP.
                //
                // If the nbr timed out due to a failed iBGP path to the
                // nbr, then the cause of the UPDATES is the OSPF network.
                if(rn_getas(rn_getmachine(n->id)) != state->as)
                        cause = 0;
                else
                        cause = 1;
                //bgp_notify_send(state, n, lp);
                // Delete any routes originated by this timed out router
                for(i = 0; i < g_rn_nas; i++)
                {
                        if(NULL == (b = state->rib[i]))
                                continue;
                        r = tw_memory_data(b);
                        r_next = b->next;
                        if (n->id != r->src)
                                continue;
                        for (j = 0; j < state->n_interfaces; j++)
{
                                n1 = &state->nbr[j];
                                if (n1->up != TW_TRUE)
                                        continue;
                                //msg->rev_num_neighbors++;
                                msg->b.update = 0;
                                bgp_update_send(state, n1, r, msg, 1, lp);
                        }
                        bgp_route_withdraw(state, r);
                        bgp_route_free(state, b, lp);
                        // Don't do for iBGP connections
                        if (rn_getas(rn_getmachine(r->src)) != state->as)
                                bgp_ospf_update(state,
                                                rn_getas(rn_getmachine(r->dst)),
                                                r, TW_FALSE, lp);
                }
        }
}
Variable Documentation
bgp_as* g_bgp_as
Definition at line 24 of file bgp-global.c.
Referenced by bgp_decision(), bgp_md_final(), bgp_route_copy(), bgp_setup_ases(), bgp_setup_options(), and bgp_xml().
xmlXPathObjectPtr* g_bgp_ases
Definition at line 31 of file bgp-global.c.
Referenced by bgp_setup_ases(), and bgp_xml().
tw_fd g_bgp_fd
Definition at line 10 of file bgp-global.c.
Referenced by bgp_connect(), bgp_event_handler(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_main(), bgp_notify_send(), bgp_open_send(), bgp_timer_start(), and bgp_update_send().
tw_fd g_bgp_fd_asp
Definition at line 12 of file bgp-global.c.
Referenced by bgp_main(), bgp_route_copy(), bgp_route_free(), init_rib(), r_deal_with_timed_out_bgp_routers(), and r_msg_update().
tw_fd g_bgp_fd_rtes
Definition at line 11 of file bgp-global.c.
Referenced by bgp_main(), bgp_route_copy(), bgp_route_free(), bgp_route_new(), bgp_update_send(), init_rib(), r_deal_with_timed_out_bgp_routers(), and r_msg_update().
char* g_bgp_init_file
Definition at line 26 of file bgp-global.c.
Referenced by bgp_setup_options().
FILE* g_bgp_rt_fd
Definition at line 32 of file bgp-global.c.
Referenced by bgp_final(), bgp_main(), bgp_md_final(), and init_rib().
bgp_state* g_bgp_state
Definition at line 25 of file bgp-global.c.
Referenced by bgp_decision(), bgp_keepalive(), bgp_setup_ases(), bgp_setup_options(), and bgp_xml().
bgp_stats g_bgp_stats
Definition at line 23 of file bgp-global.c.
Referenced by bgp_decision(), bgp_final(), bgp_md_final(), and bgp_update_send().