ROSS.Net: epi-extern.h File Reference
epi-extern.h File Reference
Functions
void epi_report_census_tract ()
void epi_num_check_report (epi_state *state, tw_lp *lp)
void epi_num_add (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_num_remove (epi_state *state, tw_bf *bf, epi_agent *a, tw_lp *lp)
void epi_location_timer (epi_state *, tw_lp *lp)
void * pq_create (void)
void pq_enqueue (void *pq, epi_agent *)
void * pq_dequeue (void *pq)
void * pq_top (void *pq)
void * pq_next (void *pq, int next)
tw_stime pq_minimum (void *pq)
void pq_delete_any (void *pq, epi_agent **)
unsigned int pq_get_size (void *q)
unsigned int pq_max_size (void *q)
void epi_seir_compute (epi_state *state, tw_bf *bf, tw_lp *lp)
epi_agent * epi_getagent (int id)
void epi_agent_add (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_agent_remove (epi_state *, tw_bf *bf, tw_lp *lp)
void epi_agent_stage_tran (epi_state *, tw_bf *bf, epi_agent *, tw_lp *lp)
void epi_report_census_track ()
void epi_setup_options (int argc, char **argv)
void epi_init_scenario ()
void epi_main (int argc, char **argv, char **env)
void epi_xml (epi_state *state, const xmlNodePtr node, tw_lp *lp)
void epi_md_final ()
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_rc_event_handler (epi_state *, tw_bf *cv, rn_message *message, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
void epi_stats_print ()
Variables
unsigned int g_epi_complete
unsigned int g_epi_hospital
double g_epi_psick
double g_epi_work_while_sick_p
unsigned int g_epi_nagents
unsigned int g_epi_nsick
unsigned int g_epi_nstages
epi_ic_stage * g_epi_stages
char * g_epi_ic_fn
char * g_epi_position_fn
FILE * g_epi_position_f
FILE * g_epi_log_f
FILE * g_epi_hospital_f
epi_statistics * g_epi_stats
unsigned int ** g_epi_ct
unsigned int g_epi_nct
unsigned int g_epi_day
double g_epi_worried_well_rate
double g_epi_worried_well_threshold
unsigned int g_epi_worried_well_duration
int g_epi_mod
int g_epi_stay_home
int g_epi_nreport_days
int * g_epi_report_days
int g_epi_next_report_day
tw_fd g_epi_fd
double EPSILON
Function Documentation
void epi_agent_add (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 112 of file epi-agent.c.
{
        // Test to make sure this location is this lp
        if (lp->id != a->loc[a->curr])
                tw_error(TW_LOC, "epi_agent_add adding agent to lp %d but loc[%d] is %d",
                         lp->id, a->curr, a->loc[a->curr]);
        // if agent is contagious, increment number of contagious agents here
        if(g_epi_stages[a->stage].ln_multiplier != 0.0)
                state->ncontagious++;
        a->ts_remove = tw_now(lp) + a->dur[a->curr];
        /* need to check stage time */
        if (a->ts_stage_tran <= a->ts_remove)
                a->ts_next = a->ts_stage_tran;
        else
                a->ts_next = a->ts_remove;
        pq_enqueue(state->pq, a);
        if(pq_get_size(state->pq) > state->max_queue_size)
                state->max_queue_size = pq_get_size(state->pq);
// If not at home, if agent is a worried well, if there are already enough symtomatic
// people here then starting tomorrow, this agent will stay home for the number
// of days remaining.  days_remaining is checked in agent_remove().
        if(!a->days_remaining && a->nloc > 1 && a->loc[a->curr] != a->loc[0] &&
                (a->behavior_flags & EPI_AGENT_WORRIED_WELL))
        {
                if ((float) state->ncontagious / (float) state->max_queue_size >
                                g_epi_worried_well_threshold)
                {
                        a->days_remaining = g_epi_worried_well_duration;
                        a->behavior_flags = 0;
                }
        }
}
void epi_agent_remove (epi_state * , tw_bf * bf, tw_lp * lp)
Definition at line 195 of file epi-agent.c.
References epi_agent_add_back(), epi_agent_stage_tran(), epi_num_remove(), g_epi_stages, g_epi_stay_home, pq_dequeue(), pq_top(), rn_event_direct(), rn_event_send(), and TWENTY_FOUR_HOURS.
Referenced by epi_event_handler().
{
        tw_event        *e;
        epi_agent       *a;
        while(NULL != (a = pq_top(state->pq)) && a->ts_next == tw_now(lp))
        {
                if(a->ts_stage_tran == tw_now(lp))
                {
                        epi_agent_stage_tran(state, bf, a, lp);
                        continue;
                }
                a = pq_dequeue(state->pq);
                // if stay-at-home flag is set, then set days_remaining > 0.  This
                // causes everyone to stay at home
                if (g_epi_stay_home > 0)
                        a->days_remaining = 180;
        // if days_remaining > 0, then go through motions by moving curr, but
        // do not move agent.  Thus, a->loc[a->curr] may not be home.  Need
        // to do this in order to send network traffic.
        // only change days_remaining at midnight, so when days_remaining goes
        // to zero, curr will go to zero and agent will be at home.
        // Make sure agent is at home.  If agent becomes worried well at
        // work, must continue to move until he is at home.
                if(a->days_remaining && lp->id == a->loc[0])
                {
                        if ((int) tw_now(lp) % TWENTY_FOUR_HOURS == 0)
{
                                if(--a->days_remaining)
{
                                        epi_agent_add_back(state, lp, a);
                                        continue;
                                }
                        } else
{
                                epi_agent_add_back(state, lp, a);
                                continue;
                        }
                }
                epi_num_remove(state, bf, a, lp);
                // if agent is contagious, decrement number of
                // contagious agents in this location
                if(g_epi_stages[a->stage].ln_multiplier != 0.0)
                        state->ncontagious--;
                if (state->ncontagious < 0)
                        tw_error(TW_LOC,
                                "Less than zero contagious agents in %d", lp->id);
                // increment location
                if(++a->curr >= a->nloc)
                        a->curr = 0;
                e = rn_event_direct(a->loc[a->curr], 0.0, lp);
                e->memory = (tw_memory *) a;
                rn_event_send(e);
        }
}
void epi_agent_stage_tran (epi_state * , tw_bf * bf, epi_agent * , tw_lp * lp)
Definition at line 20 of file epi-agent.c.
{
        epi_ic_stage    *s;
        // this agent is at head of pq
        a = pq_dequeue(state->pq);
        // simple error checking
        if(NULL == a)
                tw_error(TW_LOC, "Empty PQ!");
        // if this agent is contagious in the old stage, then reduce the location number of
        // contagious agents by one.
        s = &g_epi_stages[a->stage];
        if(s->ln_multiplier != 0.0)
                state->ncontagious--;
        if(state->ncontagious < 0)
                tw_error(TW_LOC, "Less than zero ncontagious!");
        g_epi_ct[a->ct][a->stage]--;
        a->stage++;
        g_epi_ct[a->ct][a->stage]++;
        if (a->stage >= g_epi_nstages)
                tw_error(TW_LOC, "Invalid stage: %d", a->stage);
        s = &g_epi_stages[a->stage];
        //a->ts_last_tran = tw_now(lp);
        a->ts_stage_tran = tw_now(lp);
        if (fabs(s->max_duration - s->min_duration) < EPSILON)
                a->ts_stage_tran += s->min_duration;
        else
                a->ts_stage_tran += s->min_duration +
                                tw_rand_unif(lp->rng) * (s->max_duration - s->min_duration);
        if(a->ts_stage_tran > tw_now(lp) + s->max_duration)
                tw_error(TW_LOC, "Too long!");
        // Perform mortality check
        if(s->mortality_rate > 0 && tw_rand_unif(lp->rng) < s->mortality_rate )
        {
                g_epi_ct[a->ct][a->stage]--;
                a->stage = g_epi_nstages;
                a->days_remaining = 0;
                g_epi_ct[a->ct][a->stage]++;
                // collect statistics
                state->stats->s_ndead++;
        } else
        {
                // if new stage has infectivity,
                // then increment location number of contagious agents.
                if(s->ln_multiplier != 0.0)
                {
                        state->ncontagious++;
                        state->stats->s_ninfected++;
                        if(a->behavior_flags == EPI_AGENT_WORRIED_WELL)
                                a->behavior_flags = 0;
                        // then must set number of days to stay home
                        if(!(a->behavior_flags & EPI_AGENT_WORK_WHILE_SICK))
{
                                a->days_remaining = ((int) (a->ts_stage_tran - tw_now(lp)) / TWENTY_FOUR_HOURS);
                                if (a->days_remaining < 1)
                                        a->days_remaining = 1;
                                g_epi_hospital++;
                        }
                }
                if (a->ts_stage_tran <= a->ts_remove)
                        a->ts_next = a->ts_stage_tran;
                else
                        a->ts_next = a->ts_remove;
                // re-enqueue with new ts_next
                pq_enqueue(state->pq, a);
        }
}
void epi_event_handler (epi_state * state, tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 44 of file epi.c.
{
        tw_stime         delta_time;
        int              today;
        // TO DO: need to check for last day to get last day of statistics
        today = (int) (tw_now(lp) / TWENTY_FOUR_HOURS);
        if(today > g_epi_day)
        {
                // report yesterday's statistics
                epi_report_census_tract();
                g_epi_day++;
                // send message to do repport check in num
                //epi_num_check_report(state, lp);
                // check for report day
                if (g_epi_nreport_days > 0)
                        if (today > g_epi_report_days[g_epi_next_report_day])
                                if (g_epi_nreport_days > g_epi_next_report_day+1)
                                        g_epi_next_report_day++;
        }
        delta_time = tw_now(lp) - state->last_event;
        if(g_epi_complete)
                return;
        if(lp->pe->cur_event->memory)
        {
                epi_agent       *a = (epi_agent *) tw_event_memory_get(lp);
                // compute SEIR for existing, then add agent to LP
                // skip seir if no time has passed
                if ( (state->ncontagious > 0) && (EPSILON < delta_time) )
                        epi_seir_compute(state, bf, lp);
                epi_agent_add(state, bf, a, lp);
                epi_num_add(state, bf, a, lp);
                epi_location_timer(state, lp);
        } else
        {
                // compute SEIR for all, then remove agent from LP
                // skip seir if no time has passed
                if((state->ncontagious > 0) && (EPSILON < delta_time))
                        epi_seir_compute(state, bf, lp);
                epi_agent_remove(state, bf, lp);
                epi_location_timer(state, lp);
        }
        state->last_event = tw_now(lp);
}
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 121 of file epi.c.
{
        if(g_epi_day)
        {
                epi_report_census_tract();
                g_epi_day = 0;
        }
        //g_epi_stats->s_move_ev += state->stats->s_move_ev;
        //g_epi_stats->s_nchecked += state->stats->s_nchecked;
        //g_epi_stats->s_ndraws += state->stats->s_ndraws;
        g_epi_stats->s_ninfected += state->stats->s_ninfected;
        g_epi_stats->s_ndead += state->stats->s_ndead;
}
epi_agent* epi_getagent (int id)
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file epi.c.
{
        epi_agent       *a = pq_top(state->pq);
        if(!a)
                return;
        // agents will not have a remove time of zero.
        // set timer for minimum of ts_remove and ts_stage_tran with
        // appropriate event type.  EPI_STAGE_TRANSITION has priority.
        if (a->ts_stage_tran <= a->ts_remove)
                a->ts_next = a->ts_stage_tran;
        epi_location_timer(state, lp);
}
void epi_init_scenario ()
Definition at line 225 of file epi-init.c.
Referenced by epi_main().
{
        if (0 == strcmp(g_epi_ic_fn, "default"))
                init_default_ic_stages();
        else
                init_ic_stages_from_file();
}
void epi_location_timer (epi_state * , tw_lp * lp)
Definition at line 4 of file epi-timer.c.
References pq_top(), rn_timer_init(), and rn_timer_reset().
Referenced by epi_event_handler(), and epi_init().
{
        epi_agent        *a;
        // state->tmr_remove fired, so reset time to next lowest agent
        // Note that queue may be empty because the only agent in this location died.
        if(NULL != (a = pq_top(state->pq)))
        {
                if(state->tmr_remove && state->tmr_remove->memory)
                        tw_error(TW_LOC, "Membuf on state->tmr_remove!");
                if(!state->tmr_remove || state->tmr_remove == lp->pe->cur_event)
                        state->tmr_remove = rn_timer_init(lp, a->ts_next);
                else
                        state->tmr_remove =
                                rn_timer_reset(lp, &state->tmr_remove, a->ts_next);
        } else
                state->tmr_remove = NULL;
}
void epi_main (int argc, char ** argv, char ** env)
Definition at line 8 of file epi-main.c.
{
        g_epi_stats = tw_calloc(TW_LOC, "", 1, sizeof(epi_statistics));
        // parse command line args
        epi_setup_options(argc, argv);
        // read input files, create global data structures, etc
        epi_init_scenario();
}
void epi_md_final ()
Definition at line 20 of file epi-main.c.
{
        if (g_epi_log_f)
                fclose(g_epi_log_f);
        printf("\nPandemic Flu Initial State Variables: \n");
        printf("\n");
        printf("\t%-50s %11d\n", "Total Agents", g_epi_nagents);
        printf("\t%-50s %11d\n", "Total Sick", g_epi_nsick);
        printf("\n");
        epi_stats_print();
}
void epi_num_add (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 21 of file epi-num.c.
Referenced by epi_agent_add_back(), and epi_event_handler().
{
        tw_event        *e;
        rn_message      *m;
        long int         i_time;
        int              today;
        //long int       next_move_time;
        today = (int) tw_now(lp) / 86400;
        i_time = (int) tw_now(lp) % TWENTY_FOUR_HOURS;
        // if the time is before 9:00 AM and the next move is at or before
        // 9:00 AM, then send type 2 event so num will not set a timer
        // for nine oclock that will be cancelled by next move.
        // Cannot just ignore event, because num needs midnight event
        // to calculate daily statistics.
        if(i_time < NINE_OCLOCK || i_time >= 6120000)
                return;
        // only send if home
        if(a->loc[0] != lp->id)
                return;
        // only invoke network user model every Nth day
        if(g_epi_mod > 1 && (today % g_epi_mod) + 1 != g_epi_mod)
                return;
        if(g_epi_nreport_days > 0)
        {
                if ( today+1 != g_epi_report_days[g_epi_next_report_day])
                        return;
        }
        e = rn_event_direct(a->num, 0.0, lp);
        m = tw_event_data(e);
        m->ttl = 1;
        rn_event_send(e);
}
void epi_num_check_report (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-num.c.
References pq_top(), rn_event_direct(), and rn_event_send().
{
        tw_event        *e;
        rn_message      *m;
        epi_agent       *a;
        // get first agent (does not matter which one)
        if (NULL == (a = pq_top(state->pq)))
                tw_error(TW_LOC, "Agent queue is empty\n");
        e = rn_event_direct(a->num, 0.0, lp);
        m = tw_event_data(e);
        m->ttl = 2;
        rn_event_send(e);
}
void epi_num_remove (epi_state * state, tw_bf * bf, epi_agent * a, tw_lp * lp)
Definition at line 63 of file epi-num.c.
Referenced by epi_agent_remove(), and epi_event_handler().
{
#if 0
        tw_event        *e;
        rn_message      *m;
        // only send if home
        if(a->loc[0] != lp->id)
                return;
        if(!a->started)
                return;
        a->started = 0;
        e = rn_event_direct(a->num, 0.0, lp);
        if (e->state.b.abort)
                tw_error(TW_LOC, "ABORT event!");
        m = tw_event_data(e);
        m->ttl = 0;
        rn_event_send(e);
#endif
}
void epi_rc_event_handler (epi_state * , tw_bf * cv, rn_message * message, tw_lp * lp)
Definition at line 110 of file epi.c.
{
}
void epi_report_census_track ()
void epi_report_census_tract ()
Definition at line 29 of file epi-report.c.
Referenced by epi_event_handler(), and epi_final().
{
        int i,j;
        int total;
        g_epi_complete = 1;
        for(i = 0; i < g_epi_nct; i++)
        {
                total = 0;
                for (j = 0; j <= g_epi_nstages; j++)
                {
                        total += g_epi_ct[i][j];
                }
                if(0 == total)
                        continue;
                fprintf(g_epi_log_f, "%d %d", g_epi_day, i);
                for(j = 0; j <= g_epi_nstages; j++)
                {
                        fprintf(g_epi_log_f, " %d", (100*g_epi_ct[i][j])/total);
                }
                fprintf(g_epi_log_f," %d", total);
                for(j = 0; j <= g_epi_nstages; j++)
                {
                        fprintf(g_epi_log_f, " %d", g_epi_ct[i][j]);
                }
                fprintf(g_epi_log_f, "\n");
                if(g_epi_ct[i][1] || g_epi_ct[i][2])
                        g_epi_complete = 0;
        }
        fprintf(g_epi_hospital_f, "%d %u\n", g_epi_day, g_epi_hospital);
        g_epi_hospital = 0;
        fflush(NULL);
        fsync(fileno(g_epi_log_f));
        fsync(fileno(g_epi_hospital_f));
}
void epi_seir_compute (epi_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 18 of file epi-seir.c.
References g_epi_ct, g_epi_stages, pq_get_size(), pq_next(), and s.
Referenced by epi_event_handler().
{
        tw_stime         draw;
        tw_stime         delta_t;
        epi_agent       *a;
        epi_agent       *b;
        epi_ic_stage    *s;
        unsigned int     q_sz;
        unsigned int     i;
        unsigned int     j;
        void            *pq = state->pq;
        delta_t = tw_now(lp) - state->last_event;
#if VERIFY_SEIR
        printf("%ld: SEIR_COMP delta_t %lf at %lf\n", lp->id, delta_t, tw_now(lp));
#endif
        for(i = 0, q_sz = pq_get_size(pq); i < q_sz; i++)
        {
                a = pq_next(pq, i);
                if(a->stage != EPI_SUSCEPTIBLE)
                        continue;
                // do not go through total location population, define
                // contact pop as subset of overall, and walk through
                // iteratively, or randomly
                for (j = 0; j < q_sz; j++)
                {
                        if(j == i)
                                continue;
                        b = pq_next(pq, j);
                        s = &g_epi_stages[b->stage];
                        if(s->ln_multiplier != 0.0)
{
#if 0
                                // tw_geometric draws from uniform until the draw
                                // is greater than P.
                                // tw_geometric then returns the number of draws.
                                // For large P (which is 1.0 - multiplier) this could
                                // be very large.  Also note that tw_geometric
                                // always returns an integer of 1 or greater.
                                draw = tw_rand_geometric(lp->id,
                                        (s->start_multiplier + s->stop_multiplier)/2);
                                state->stats->s_ndraws += draw;
                                state->stats->s_nchecked++;
#endif
                                // Or, we can compute it directly as:
                                // draw = log(random draw) / log(1 - prob of contagiousness)
                                draw = tw_rand_unif(lp->rng);
                                draw = log(draw);
                                draw /= s->ln_multiplier;
                                // multiply draw to factor in contact population
                                draw *= q_sz;
                                // Make agent sick
                                if(draw <= delta_t)
{
#if VERIFY_SEIR
                                        printf("%ld: pop %d, draw %lf, delta_t %lf \n",
                                                lp->id, q_sz, draw, delta_t);
#endif
                                        g_epi_ct[a->ct][a->stage]--;
                                        a->stage++; // = EPI_INCUBATING;
                                        g_epi_ct[a->ct][a->stage]++;
                                        //g_epi_exposed_today++;
                                        s = &g_epi_stages[a->stage];
                                        a->ts_stage_tran = tw_rand_unif(lp->rng) *
                                                        (s->max_duration - s->min_duration) +
                                                        s->min_duration + tw_now(lp);
                                        break;
                                }
                        }
                }
        }
}
void epi_setup_options (int argc, char ** argv)
Definition at line 30 of file epi-setup.c.
Referenced by epi_main().
{
        int              c;
        char             hospital_fn[1024];
        char             log_fn[1024];
        g_epi_nsick = 0;
        g_epi_ic_fn = tw_calloc(TW_LOC, "", sizeof(char), 255);
        g_epi_position_fn = tw_calloc(TW_LOC, "", sizeof(char), 255);
        sprintf(hospital_fn, "%s/hospital.log", g_rn_logs_dir),
        sprintf(log_fn, "%s/epi.log", g_rn_logs_dir);
        printf("\nEpi User Specified Input Parameters: \n\n");
        opterr = 0;
        optind = 0;
        while(-1 != (c = getopt(argc, argv, "-W:U:h:T:D:S:I:B:M:2:")))
        {
                switch(c)
                {
                        case 'I':
                                strcpy(g_epi_ic_fn, optarg);
                                printf("\t%-50s %11s\n", "IC File", g_epi_ic_fn);
                                break;
                        case 'S':
                                g_epi_psick = atof(optarg);
                                printf("\t%-50s %11f\n", "Probability Agents are Sick", g_epi_psick);
                                break;
                        case 'M':
                                g_epi_position_fn = tw_calloc(TW_LOC, "", sizeof(char), 255);
                                strcpy(g_epi_position_fn, optarg);
                                printf("\t%-50s %11s\n", "Position (Agent Moves) File", g_epi_position_fn);
                                g_epi_position_f = fopen(g_epi_position_fn, "w");
                                if (!g_epi_position_f)
                                        tw_printf(TW_LOC, "Unable to create output file: %s \n",
                                                g_epi_position_fn);
                                break;
                        case 'W':
                                g_epi_worried_well_rate = atof(optarg);
                                printf("\t%-50s %11f\n", "Probability of being Worried Well", g_epi_worried_well_rate);
                                break;
                        case 'T':
                                g_epi_worried_well_threshold = atof(optarg);
                                printf("\t%-50s %11f\n", "Worried Well threshold", g_epi_worried_well_threshold);
                                break;
                        case 'U':
                                g_epi_mod = atoi(optarg);
                                printf("\t%-50s %11d\n",
                                        "Reporting Interval",
                                        g_epi_mod);
                                break;
                        case 'D':
                                g_epi_worried_well_duration = atoi(optarg);
                                printf("\t%-50s %11d\n", "Worried Well duration", g_epi_worried_well_duration);
                                break;
                        case '2':
                                g_epi_work_while_sick_p = atof(optarg);
                                printf("\t%-50s %11f\n", "Probability agent will go to work while sick",
                                        g_epi_work_while_sick_p);
                                break;
                        case 'B':
                                if ( strcmp(optarg, "HOME") == 0 )
{
                                        g_epi_stay_home = 1;
                                        printf("\tAll agents stay home and use the network\n");
                                }
                                break;
                        case 'h':
                                sprintf(hospital_fn, "%s", optarg);
                                break;
                }
        }
        if(0 == strcmp(g_epi_ic_fn, ""))
                sprintf(g_epi_ic_fn, "tools/%s/ic.txt", g_rn_tools_dir);
        /*
         * Fix-up vars, open output files, etc
         */
        if(NULL == (g_epi_log_f = fopen(log_fn, "w")))
                tw_error(TW_LOC, "Unable to open: %s \n", log_fn);
        if(NULL == (g_epi_hospital_f = fopen(hospital_fn, "w")))
                tw_error(TW_LOC, "Unable to open: %s \n", hospital_fn);
        printf("\n");
}
void epi_stats_print ()
Definition at line 4 of file epi-stats.c.
Referenced by epi_md_final().
{
        printf("\nEPI Statistics: \n");
        printf("\n");
        printf("\t%-50s %11.2lf\n", "Sim End Time (secs)", g_tw_ts_end);
        printf("\n");
        //printf("\t%-50s %11ld\n", "Ttl Move Events", g_epi_stats->s_move_ev);
        //printf("\t%-50s %11ld\n", "Ttl Agents Checked for Infection", g_epi_stats->s_nchecked);
        //printf("\t%-50s %11ld\n", "Ttl Draws from Uniform Random Distribution", g_epi_stats->s_ndraws);
        printf("\t%-50s %11ld\n", "Ttl Number of Infected Agents", g_epi_stats->s_ninfected);
        printf("\t%-50s %11ld\n", "Ttl Number of Dead Agents", g_epi_stats->s_ndead);
        printf("\n");
}
void epi_xml (epi_state * state, const xmlNodePtr node, tw_lp * lp)
Definition at line 8 of file epi-xml.c.
{
        xmlNodePtr       agent;
        xmlNodePtr       move;
        rn_machine      *m = rn_getmachine(lp->id);
        epi_agent       *a;
        epi_ic_stage    *s;
        double           x;
        int              ct;
        int              i;
        char            *sick;
        // create census tract table if it does not exist
        // need 1 more than number of stages to save dead agents
        // dead is not a stage.
        if (!g_epi_ct)
        {
                g_epi_nct = 2200; //rn_getarea(m)->nsubnets;
                g_epi_ct = tw_calloc(TW_LOC, "", sizeof(unsigned int *), g_epi_nct);
                for (i = 0; i < g_epi_nct; i++)
                        g_epi_ct[i] = tw_calloc(TW_LOC, "", sizeof(unsigned int), g_epi_nstages);
        }
        state->stats = tw_calloc(TW_LOC, "", sizeof(epi_statistics), 1);
        state->pq = pq_create();
        ct = rn_getsubnet(m)->id - rn_getarea(m)->subnets[0].id;
        // spin through agents 'homed' at this location and allocate + init them
        //
        // NOTE: May not have *any* agents homed at a given location
        for(agent = node->children; agent; agent = agent->next)
        {
                if(0 != strcmp((char *) agent->name, "agent"))
                        continue;
                a = tw_calloc(TW_LOC, "", sizeof(epi_agent), 1);
                a->ct = m->uid; //ct;
                a->num = atoi(xml_getprop(agent, "num"));
                //a->a_type = atoi(xml_getprop(agent,"type"));
                sick = xml_getprop(agent, "sick");
                if(g_epi_psick > EPSILON)
                {
                        if ( tw_rand_unif(lp->rng) < g_epi_psick )
                                sick = "1";
                }
                if(0 != strcmp(sick, "0"))
                {
                        //a->ts_infected = atof(sick);
                        a->stage = EPI_INCUBATING;
                        s = &g_epi_stages[a->stage];
                        x = ((double) tw_rand_integer(lp->rng, 0, INT_MAX) / (double) INT_MAX);
                        a->ts_stage_tran = (s->min_duration +
                                                (x * (s->max_duration - s->min_duration)));
#if EPI_XML_VERIFY
                        printf("\tstage: %d, time %5f \n",
                                s->stage_index, a->ts_stage_tran);
#endif
                        g_epi_nsick++;
                } else
                {
                        a->stage = EPI_SUSCEPTIBLE;
                        a->ts_stage_tran = DBL_MAX;
                        //a->ts_infected = DBL_MAX;
                }
                g_epi_ct[a->ct][a->stage]++;
                //a->id = g_epi_nagents++;
                g_epi_nagents++;
                a->curr = 0;
                //a->ts_last_tran = 0.0;
                a->ts_next = a->ts_remove = (double) 86400.0;
                //a->n_infected = 0;
                for(move = agent->children; move; move = move->next)
                {
                        if(0 != strcmp((char *) move->name, "move"))
                                continue;
                        a->nloc++;
                }
                if(!a->nloc)
                        tw_error(TW_LOC, "Agent has no locations!");
                a->nloc++; // add a location to return home at end of day
                a->loc = tw_calloc(TW_LOC, "", sizeof(int) * a->nloc, 1);
                a->dur = tw_calloc(TW_LOC, "", sizeof(tw_stime) * a->nloc, 1);
                int seconds_used = 0; // totals duration to check for 24 hours
                for(i = 0, move = agent->children; move; move = move->next)
                {
                        if(0 != strcmp((char *) move->name, "move"))
                                continue;
                        a->loc[i] = atoi(xml_getprop(move, "loc"));
                        a->dur[i] = atoi(xml_getprop(move, "dur")) * 3600;
                        seconds_used += a->dur[i];
                        i++;
                }
                if (seconds_used > 86400)
                        tw_error(TW_LOC, "Agent has duration more than 24 hours\n");
                else if (seconds_used == 86400)
                        a->nloc--; // do not need last location
                else {
                        a->loc[a->nloc-1] = a->loc[0]; // return home
                        a->dur[a->nloc-1] = 86400 - seconds_used;
                }
                a->behavior_flags = 0;
                if (g_epi_worried_well_rate > 0)
                {
                        if (tw_rand_unif(lp->rng) < g_epi_worried_well_rate)
                                a->behavior_flags = 1;
                } else if (g_epi_work_while_sick_p > EPSILON)
                        if (tw_rand_unif(lp->rng) < g_epi_work_while_sick_p)
                                a->behavior_flags = 2;
                // Set ts_next and enqueue
                a->ts_remove = a->dur[a->curr];
                if(a->ts_remove < a->ts_stage_tran)
                        a->ts_next = a->ts_remove;
                else
                        a->ts_next = a->ts_stage_tran;
                pq_enqueue(state->pq, a);
        }
}
void* pq_create (void)
Definition at line 207 of file queue-heap.c.
Referenced by epi_xml().
{
  CHeap *h = (CHeap *)malloc(sizeof(CHeap));
  h->nelems = 0;
  h->curr_max = (10);
  h->elems = (epi_agent **)malloc(sizeof(epi_agent *)*h->curr_max);
  if( !h->elems ) { fprintf( stderr, "Failed to create heap\n" ); exit(1); }
/*  printf("Initialized Heap. Allocated %ld bytes\n", sizeof(epi_agent *)*h->curr_max); */
  fflush(stdout);
  return (void *)h;
}
void pq_delete_any (void * pq, epi_agent **)
Definition at line 181 of file queue-heap.c.
{
  CHeap *h = (CHeap *)(pq);
  epi_agent * victim = *q;
  int i = victim->heap_index;
  if( !(0 <= i && i < h->nelems) || (h->elems[i]->heap_index != i) )
    {
      fprintf( stderr, "Fatal: Bad node in FEL!\n" ); exit(2);
    }
  else
    {
      h->nelems--;
      if( h->nelems > 0 )
        {
          epi_agent * successor = h->elems[h->nelems];
          h->elems[i] = successor;
          successor->heap_index = i;
          if( KEY(successor) <= KEY(victim) ) percolate_up( h, i );
          else sift_down( h, i );
        }
    }
}
void* pq_dequeue (void * pq)
Definition at line 149 of file queue-heap.c.
Referenced by epi_agent_remove(), and epi_agent_stage_tran().
{
  CHeap *h = (CHeap *)pq;
  if( h->nelems <= 0 )
    return 0;
  else
    {
      epi_agent * e = h->elems[0];
      h->elems[0] = h->elems[--h->nelems];
      h->elems[0]->heap_index = 0;
      sift_down( h, 0 );
      return e;
    }
}
void pq_enqueue (void * pq, epi_agent *)
Definition at line 126 of file queue-heap.c.
Referenced by epi_agent_add(), epi_agent_add_back(), epi_agent_stage_tran(), and epi_xml().
{
  CHeap *h = (CHeap *)pq;
  if( h->nelems >= h->curr_max )
    {
      h->elems = (epi_agent **)
        realloc(h->elems, sizeof(epi_agent *)*(h->curr_max + 50));
      if( !h->elems ) {fprintf(stderr,"Can't expand heap!\n"); exit(1);}
      //else {fprintf(stderr,"Expanded heap to %d!\n", h->curr_max + 50);}
      h->curr_max += 50;
    }
  e->heap_index = h->nelems;
  h->elems[h->nelems++] = e;
  percolate_up( h, h->nelems-1 );
  e->next = NULL;
  e->prev = NULL;
}
unsigned int pq_get_size (void * q)
Definition at line 245 of file queue-heap.c.
Referenced by epi_agent_add(), and epi_seir_compute().
{
  return ( ((CHeap *)pq)->nelems );
}
unsigned int pq_max_size (void * q)
tw_stime pq_minimum (void * pq)
Definition at line 222 of file queue-heap.c.
{
  epi_agent * e = HeapPeekTop( (CHeap*)(pq) );
  double retval = e ? KEY(e) : HUGE_VAL;
  return retval;
}
void* pq_next (void * pq, int next)
Definition at line 240 of file queue-heap.c.
Referenced by epi_seir_compute().
{
        return ((CHeap *) h)->elems[next];
}
void* pq_top (void * pq)
Definition at line 231 of file queue-heap.c.
Referenced by epi_agent_remove(), epi_init(), epi_location_timer(), epi_num_check_report(), and timer_helper().
{
  return HeapPeekTop( (CHeap*)(pq) );
}
Variable Documentation
double EPSILON
Definition at line 40 of file epi-global.c.
Referenced by epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_event_handler(), epi_seir_compute(), epi_xml(), and init_ic_stages_from_file().
unsigned int g_epi_complete
Definition at line 25 of file epi-global.c.
Referenced by epi_event_handler(), and epi_report_census_tract().
unsigned int** g_epi_ct
Definition at line 20 of file epi-global.c.
Referenced by epi_agent_stage_tran(), epi_report_census_tract(), epi_seir_compute(), and epi_xml().
unsigned int g_epi_day
Definition at line 22 of file epi-global.c.
Referenced by epi_event_handler(), epi_final(), and epi_report_census_tract().
tw_fd g_epi_fd
Definition at line 37 of file epi-global.c.
Referenced by epi_timer_cancel().
unsigned int g_epi_hospital
Definition at line 6 of file epi-global.c.
Referenced by epi_agent_stage_tran(), and epi_report_census_tract().
FILE* g_epi_hospital_f
Definition at line 14 of file epi-global.c.
Referenced by epi_report_census_tract(), and epi_setup_options().
char* g_epi_ic_fn
Definition at line 10 of file epi-global.c.
Referenced by epi_init_scenario(), epi_setup_options(), and init_ic_stages_from_file().
FILE* g_epi_log_f
Definition at line 13 of file epi-global.c.
Referenced by epi_main(), epi_md_final(), epi_report_census_tract(), and epi_setup_options().
int g_epi_mod
Definition at line 23 of file epi-global.c.
Referenced by epi_num_add(), and epi_setup_options().
unsigned int g_epi_nagents
Definition at line 18 of file epi-global.c.
Referenced by epi_md_final(), and epi_xml().
unsigned int g_epi_nct
Definition at line 21 of file epi-global.c.
Referenced by epi_report_census_tract(), and epi_xml().
int g_epi_next_report_day
Definition at line 35 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
int g_epi_nreport_days
Definition at line 33 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
unsigned int g_epi_nsick
Definition at line 19 of file epi-global.c.
Referenced by epi_md_final(), epi_setup_options(), and epi_xml().
unsigned int g_epi_nstages
Definition at line 24 of file epi-global.c.
Referenced by epi_agent_stage_tran(), epi_report_census_tract(), epi_xml(), and init_ic_stages_from_file().
FILE* g_epi_position_f
Definition at line 12 of file epi-global.c.
Referenced by epi_seir_compute(), and epi_setup_options().
char* g_epi_position_fn
Definition at line 11 of file epi-global.c.
Referenced by epi_setup_options().
double g_epi_psick
Definition at line 16 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
int* g_epi_report_days
Definition at line 34 of file epi-global.c.
Referenced by epi_event_handler(), and epi_num_add().
epi_ic_stage* g_epi_stages
Definition at line 31 of file epi-global.c.
Referenced by epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_seir_compute(), epi_xml(), init_default_ic_stages(), and init_ic_stages_from_file().
epi_statistics* g_epi_stats
Definition at line 8 of file epi-global.c.
Referenced by epi_final(), epi_main(), and epi_stats_print().
int g_epi_stay_home
Definition at line 27 of file epi-global.c.
Referenced by epi_agent_remove(), and epi_setup_options().
double g_epi_work_while_sick_p
Definition at line 17 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
unsigned int g_epi_worried_well_duration
Definition at line 30 of file epi-global.c.
Referenced by epi_agent_add(), and epi_setup_options().
double g_epi_worried_well_rate
Definition at line 28 of file epi-global.c.
Referenced by epi_setup_options(), and epi_xml().
double g_epi_worried_well_threshold
Definition at line 29 of file epi-global.c.
Referenced by epi_agent_add(), and epi_setup_options().