ROSS.Net: epi-timer.c File Reference
epi-timer.c File Reference
#include <epi.h>
Functions
void epi_location_timer (epi_state *state, tw_lp *lp)
Function Documentation
void epi_location_timer (epi_state * state, tw_lp * lp)
Definition at line 4 of file epi-timer.c.
References pq_top(), rn_timer_init(), and rn_timer_reset().
Referenced by epi_event_handler(), and epi_init().
{
        epi_agent        *a;
        // state->tmr_remove fired, so reset time to next lowest agent
        // Note that queue may be empty because the only agent in this location died.
        if(NULL != (a = pq_top(state->pq)))
        {
                if(state->tmr_remove && state->tmr_remove->memory)
                        tw_error(TW_LOC, "Membuf on state->tmr_remove!");
                if(!state->tmr_remove || state->tmr_remove == lp->pe->cur_event)
                        state->tmr_remove = rn_timer_init(lp, a->ts_next);
                else
                        state->tmr_remove =
                                rn_timer_reset(lp, &state->tmr_remove, a->ts_next);
        } else
                state->tmr_remove = NULL;
}