ROSS.Net: ip-extern.h File Reference
ip-extern.h File Reference
Functions
void ip_init (ip_state *, tw_lp *)
void ip_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_event_handler (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_final (ip_state *state, tw_lp *lp)
void ip_upstream (ip_state *, rn_message *, tw_lp *lp)
void ip_rc_upstream (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_downstream_source (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_downstream_forward (ip_state *, tw_bf *, rn_message *, tw_lp *)
void ip_rc_downstream (ip_state *, rn_message *, tw_lp *)
void ip_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_routing_init ()
void ip_rt_print (ip_state *state, tw_lp *lp, FILE *log)
rn_link * ip_route (rn_machine *me, rn_message *msg)
tw_lpid ip_getroute (ip_state *state, tw_lpid dst)
void ip_xml (tw_lp *lp, xmlNodePtr node)
void ip_md_init (int argc, char **argv, char **env)
void ip_md_final ()
Variables
tw_stime g_ip_major_interval
tw_stime g_ip_minor_interval
ip_stats * g_ip_stats
int g_ip_header
tw_fd g_ip_fd
int g_ip_routing_simple
FILE * g_ip_log
FILE * g_ip_routing_file
int ** g_ip_rt
unsigned int g_ip_log_on
short int * g_ip_front
short int * g_ip_p
short int * g_ip_f
short int * g_ip_s
short int * g_ip_d
Function Documentation
void ip_downstream_forward (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 95 of file ip-downstream.c.
References forward(), ip_packet_drop(), and rn_event_send().
Referenced by ip_event_handler().
{
        tw_event        *e;
        rn_message      *m;
        if(--msg->ttl == 0)
        {
                state->stats->s_ndropped_ttl++;
                ip_packet_drop(state, msg, lp);
                return;
        }
        if(NULL == (e = forward(state, bf, msg, lp)))
                return;
        // TODO: Move this logic into rn_event_send
        if(e == lp->pe->abort_event)
        {
                printf("got abort event in IP\n");
                rn_event_send(e);
                return;
        }
        // If I was not the destination, then must be forwarding this pkt
        if(!lp->pe->cur_event->memory)
                tw_error(TW_LOC, "No membuf on forward event!");
        //if(lp->cur_event->memory && e->memory->next && !e->state.b.abort)
        if(lp->pe->cur_event->memory && e->memory && e != lp->pe->abort_event)
                tw_error(TW_LOC, "Unable to forward membufs!");
        e->memory = lp->pe->cur_event->memory;
        lp->pe->cur_event->memory = NULL;
        // fixup the message source
        m = tw_event_data(e);
        m->src = msg->src;
        m->dst = msg->dst;
        m->port = msg->port;
        m->ttl = msg->ttl;
        rn_event_send(e);
}
void ip_downstream_source (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 84 of file ip-downstream.c.
References forward(), g_ip_header, and rn_event_send().
Referenced by ip_event_handler().
{
        tw_event        *e;
        msg->size += g_ip_header;
        if(NULL != (e = forward(state, bf, msg, lp)))
                rn_event_send(e);
}
void ip_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 25 of file ip.c.
References c_ha_router, c_router, DOWNSTREAM, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, ip_downstream_forward(), ip_downstream_source(), ip_upstream(), and rn_getmachine().
{
        //tw_memory     *b = NULL;
        tw_stime         now = tw_now(lp);
        tw_stime         avg = 0.0;
        rn_machine      *me = rn_getmachine(lp->id);
        rn_link         *l;
        int              i;
        if(msg->type == DOWNSTREAM)
        {
                if(msg->src == lp->id)
                        ip_downstream_source(state, bf, msg, lp);
                else
                        tw_error(TW_LOC, "Downstream pkt not from self?");
        } else
        {
                if(msg->dst == lp->id)
                        ip_upstream(state, msg, lp);
                else
                        ip_downstream_forward(state, bf, msg, lp);
        }
        // if next minor reporting interval.. report after adding in delay
        if(g_ip_log_on && now >= state->minor &&
                (me->type > c_router && me->type < c_ha_router))
        {
                for(i = 0; i < me->nlinks; i++)
                {
                        l = &me->link[i];
                        avg += l->avg_delay;
                        l->avg_delay = 0.0;
                }
                state->max_delay = max(state->max_delay,
                                        avg / (tw_stime) g_ip_minor_interval);
                state->minor = now + g_ip_minor_interval;
        }
        // && me->uid
        if(g_ip_log_on && now >= state->major &&
                (me->type > c_router && me->type < c_ha_router))
        {
                // divide router capacity by max_delay and output float in range: 0..1)
                fprintf(g_ip_log, "%d %d %d %2.8lf\n",
                        me->type, (int) now / 86400, me->uid,
                        (float) state->max_delay / (float) state->capacity);
                fflush(NULL);
                fsync(fileno(g_ip_log));
                state->major = now + g_ip_major_interval;
        }
}
void ip_final (ip_state * state, tw_lp * lp)
Definition at line 138 of file ip.c.
References g_ip_stats.
{
        g_ip_stats->s_ncomplete += state->stats->s_ncomplete;
        g_ip_stats->s_nforward += state->stats->s_nforward;
        g_ip_stats->s_ndropped += state->stats->s_ndropped;
        g_ip_stats->s_ndropped_ttl += state->stats->s_ndropped_ttl;
        g_ip_stats->s_ndropped_source += state->stats->s_ndropped_source;
        g_ip_stats->s_nnet_failures += state->stats->s_nnet_failures;
        g_ip_stats->s_avg_ttl += state->stats->s_avg_ttl;
        g_ip_stats->s_max_ttl = max(g_ip_stats->s_max_ttl, state->stats->s_max_ttl);
}
tw_lpid ip_getroute (ip_state * state, tw_lpid dst)
void ip_init (ip_state * , tw_lp *)
Definition at line 7 of file ip.c.
References g_ip_major_interval, g_ip_minor_interval, and rn_getmachine().
{
        rn_machine      *me;
        int              i;
        me = rn_getmachine(lp->id);
        state->stats = tw_calloc(TW_LOC, "", sizeof(ip_stats), 1);
        // in seconds..
        state->minor = 32400 + g_ip_minor_interval;
        state->major = 32400 + g_ip_major_interval;
        for(i = 0; i < me->nlinks; i++)
                state->capacity += me->link[i].bandwidth;
}
void ip_md_final ()
Definition at line 52 of file ip-model.c.
References g_ip_stats.
{
        printf("\nIP Model Statistics:\n\n");
        printf("\t%-50s %11ld \n", "Total Packets Completed", g_ip_stats->s_ncomplete);
        printf("\t%-50s %11ld \n", "Total Packets Dropped", g_ip_stats->s_ndropped);
        printf("\t%-50s %11ld \n", "Packets Dropped at Source",
                g_ip_stats->s_ndropped_source);
        printf("\t%-50s %11ld \n", "Packets Dropped (TTL)", g_ip_stats->s_ndropped_ttl);
        printf("\t%-50s %11ld \n", "Packets Dropped by Network Failure",
                g_ip_stats->s_nnet_failures);
        printf("\t%-50s %11ld \n", "Packets Forwarded", g_ip_stats->s_nforward);
        printf("\n");
        printf("\t%-50s %11d \n", "Packet Avg TTL",
                g_ip_stats->s_avg_ttl ?
                        (int) (g_ip_stats->s_avg_ttl / g_ip_stats->s_ncomplete) :
                        (int) g_ip_stats->s_avg_ttl);
        printf("\t%-50s %11ld \n", "Packet Max TTL", g_ip_stats->s_max_ttl);
}
void ip_md_init (int argc, char ** argv, char ** env)
Definition at line 11 of file ip-model.c.
References g_ip_fd, g_ip_log, g_ip_log_on, g_ip_major_interval, g_ip_minor_interval, g_ip_stats, g_rn_logs_dir, ip_opts, and ip_routing_init().
{
        //int    i;
        char     log[1024];
        g_ip_stats = tw_calloc(TW_LOC, "", sizeof(ip_stats), 1);
        // in secs..
        g_ip_minor_interval = 60;
        g_ip_major_interval = 86400;
        tw_opt_add(ip_opts);
        if(g_ip_log_on)
        {
                sprintf(log, "%s/ip.log", g_rn_logs_dir);
                g_ip_log = fopen(log, "w");
                if(!g_ip_log)
                        tw_error(TW_LOC, "Unable to open: %s \n", log);
        }
#if 0
        for(i = 0; i < g_tw_nkp; i++)
                g_ip_fd = tw_kp_memory_init(tw_getkp(i), 1000000, sizeof(ip_message), 1);
#endif
        ip_routing_init();
        if(tw_ismaster())
        {
                printf("\nInitializing Model: IPv4\n");
#if 0
                printf("\t%-50s %11d (%ld)\n",
                        "IP Membufs", 1000000, g_ip_fd);
#endif
        }
}
void ip_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-packet.c.
References DOWNSTREAM, and rn_event_new().
Referenced by getroute(), and ip_downstream_forward().
{
        tw_event        *e;
        state->stats->s_ndropped++;
        if(msg->src == lp->id)
                state->stats->s_ndropped_source++;
#if VERIFY_IP
        printf("%lld: dropped src %lld, dst %lld on port %d \n",
                lp->id, msg->src, msg->dst, msg->port);
#endif
        // Need to free the event otherwise it will simply be lost!
        e = rn_event_new(msg->dst, 0.0, lp, DOWNSTREAM, msg->size);
        if(e == lp->pe->abort_event)
                tw_event_free(lp->pe, e);
}
void ip_rc_downstream (ip_state * , rn_message * , tw_lp *)
Definition at line 38 of file ip-rc-downstream.c.
References g_ip_fd, ip_rc_packet_drop(), and rc_getroute().
Referenced by ip_rc_event_handler().
{
        tw_memory       *b;
        //tw_event      *e;
        tw_stime         ts;
        rn_link         *l;
        ip_message      *ip;
        ts = 0.0;
        state->stats->s_nforward--;
        if(NULL == (l = rc_getroute(state, msg, lp)))
        {
                ip_rc_packet_drop(state, msg, lp);
                return;
        }
        b = tw_event_memory_get(lp);
        ip = tw_memory_data(b);
        //l->last_sent = ip->rc_lastsent;
        tw_memory_alloc_rc(lp, b, g_ip_fd);
#if 0
        if(bf->c31)
        {
                state->stats->s_nnet_failures--;
                msg->ttl--;
        }
#endif
#if VERIFY_IP
        printf("%ld IP: RC sent DOWN src %ld, link %d, dst %ld, ts %lf \n",
                lp->id, msg->src, l->addr, msg->dst, e->recv_ts);
#endif
}
void ip_rc_event_handler (ip_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 85 of file ip.c.
References DOWNSTREAM, g_ip_fd, g_ip_header, ip_rc_downstream(), ip_rc_packet_drop(), and ip_rc_upstream().
{
#if 0
        tw_memory       *b;
        ip_message      *ip;
        // put IP membuf back onto event
        if(msg->src != lp->id && NULL == (b = tw_memory_free_rc(lp, g_ip_fd)))
                tw_error(TW_LOC, "No IP header!");
        if(b)
        {
                ip = tw_memory_data(b);
                //ip->rc_link->last_sent = ip->rc_lastsent;
                tw_event_memory_get_rc(lp, b, g_ip_fd);
        }
        if(msg->type == DOWNSTREAM)
        {
                if(msg->src == lp->id)
                {
                        ip_rc_downstream(state, msg, lp);
                        msg->size -= g_ip_header;
                } else
                {
                        tw_error(TW_LOC, "RC donwstream pkt not from self?");
                }
        } else
        {
                if(msg->dst == lp->id)
                {
                        ip_rc_upstream(state, msg, lp);
                } else
                {
                        if(++msg->ttl == 1)
{
                                state->stats->s_ndropped_ttl--;
                                ip_rc_packet_drop(state, msg, lp);
                        } else
{
                                ip_rc_downstream(state, msg, lp);
                        }
                }
        }
        if(b)
                tw_event_memory_get_rc(lp, b, g_ip_fd);
#endif
}
void ip_rc_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 26 of file ip-packet.c.
Referenced by ip_rc_downstream(), and ip_rc_event_handler().
{
        state->stats->s_ndropped--;
        if(msg->src == lp->id)
                state->stats->s_ndropped_source--;
}
void ip_rc_upstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 23 of file ip-upstream.c.
References g_ip_header, and g_rn_ttl.
Referenced by ip_rc_event_handler().
{
        msg->size += g_ip_header;
        state->stats->s_ncomplete--;
        // not correct, must be state-saved
        state->stats->s_max_ttl = max(state->stats->s_max_ttl, g_rn_ttl - msg->ttl);
        state->stats->s_avg_ttl -= (g_rn_ttl - msg->ttl);
}
rn_link* ip_route (rn_machine * me, rn_message * msg)
Definition at line 9 of file ip-routing.c.
References g_ip_rt, and rn_getlink().
Referenced by getroute(), and rc_getroute().
{
        int      i;
        int      sz;
        sz = g_ip_rt[msg->src][0];
        for(i = 1; i < sz; i++)
                if(g_ip_rt[msg->src][i] == me->id)
                        return rn_getlink(me, g_ip_rt[msg->src][++i]);
        return NULL;
}
void ip_routing_init ()
Definition at line 124 of file ip-routing.c.
References routing_read(), and routing_write().
Referenced by ip_md_init().
{
        if(!routing_read())
                routing_write();
}
void ip_rt_print (ip_state * state, tw_lp * lp, FILE * log)
void ip_upstream (ip_state * , rn_message * , tw_lp * lp)
Definition at line 4 of file ip-upstream.c.
References g_ip_header, g_rn_ttl, rn_event_new(), rn_event_send(), and UPSTREAM.
Referenced by ip_event_handler().
{
        tw_event        *e;
        state->stats->s_avg_ttl += (g_rn_ttl - msg->ttl);
        state->stats->s_max_ttl = max(state->stats->s_max_ttl, g_rn_ttl - msg->ttl);
        state->stats->s_ncomplete++;
        msg->size -= g_ip_header;
        e = rn_event_new(lp->gid, 0.0, lp, UPSTREAM, msg->size);
        rn_event_send(e);
#if VERIFY_IP
                printf("%lld IP: sent UP src %lld, dst %lld, ts %lf \n",
                        lp->id, msg->src, msg->dst, tw_now(lp));
#endif
}
void ip_xml (tw_lp * lp, xmlNodePtr node)
Definition at line 4 of file ip-xml.c.
{
}
Variable Documentation
short int* g_ip_d
Definition at line 34 of file ip-global.c.
short int* g_ip_f
Definition at line 32 of file ip-global.c.
tw_fd g_ip_fd
Definition at line 14 of file ip-global.c.
Referenced by ip_md_init(), ip_rc_downstream(), and ip_rc_event_handler().
short int* g_ip_front
Definition at line 30 of file ip-global.c.
int g_ip_header
Definition at line 12 of file ip-global.c.
Referenced by ip_downstream_source(), ip_rc_event_handler(), ip_rc_upstream(), and ip_upstream().
FILE* g_ip_log
Definition at line 20 of file ip-global.c.
Referenced by ip_event_handler(), and ip_md_init().
unsigned int g_ip_log_on
Definition at line 25 of file ip-global.c.
Referenced by ip_event_handler(), and ip_md_init().
tw_stime g_ip_major_interval
Definition at line 23 of file ip-global.c.
Referenced by ip_event_handler(), ip_init(), and ip_md_init().
tw_stime g_ip_minor_interval
Definition at line 24 of file ip-global.c.
Referenced by ip_event_handler(), ip_init(), and ip_md_init().
short int* g_ip_p
Definition at line 31 of file ip-global.c.
FILE* g_ip_routing_file
Definition at line 17 of file ip-global.c.
Referenced by routing_init_ft_read(), routing_init_ft_write(), routing_read(), and routing_write().
int g_ip_routing_simple
Definition at line 15 of file ip-global.c.
int** g_ip_rt
Definition at line 18 of file ip-global.c.
Referenced by ip_route(), and routing_read().
short int* g_ip_s
Definition at line 33 of file ip-global.c.
ip_stats* g_ip_stats
Definition at line 11 of file ip-global.c.
Referenced by ip_final(), ip_md_final(), and ip_md_init().