ROSS.Net: ip-packet.c File Reference
ip-packet.c File Reference
#include <ip.h>
Functions
void ip_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_packet_drop (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-packet.c.
References DOWNSTREAM, and rn_event_new().
Referenced by getroute(), and ip_downstream_forward().
{
        tw_event        *e;
        state->stats->s_ndropped++;
        if(msg->src == lp->id)
                state->stats->s_ndropped_source++;
#if VERIFY_IP
        printf("%lld: dropped src %lld, dst %lld on port %d \n",
                lp->id, msg->src, msg->dst, msg->port);
#endif
        // Need to free the event otherwise it will simply be lost!
        e = rn_event_new(msg->dst, 0.0, lp, DOWNSTREAM, msg->size);
        if(e == lp->pe->abort_event)
                tw_event_free(lp->pe, e);
}
void ip_rc_packet_drop (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 26 of file ip-packet.c.
Referenced by ip_rc_downstream(), and ip_rc_event_handler().
{
        state->stats->s_ndropped--;
        if(msg->src == lp->id)
                state->stats->s_ndropped_source--;
}