ROSS.Net: ip-rc-downstream.c File Reference
ip-rc-downstream.c File Reference
#include <ip.h>
Functions
rn_link * rc_getroute (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_downstream (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_rc_downstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 38 of file ip-rc-downstream.c.
References g_ip_fd, ip_rc_packet_drop(), and rc_getroute().
Referenced by ip_rc_event_handler().
{
        tw_memory       *b;
        //tw_event      *e;
        tw_stime         ts;
        rn_link         *l;
        ip_message      *ip;
        ts = 0.0;
        state->stats->s_nforward--;
        if(NULL == (l = rc_getroute(state, msg, lp)))
        {
                ip_rc_packet_drop(state, msg, lp);
                return;
        }
        b = tw_event_memory_get(lp);
        ip = tw_memory_data(b);
        //l->last_sent = ip->rc_lastsent;
        tw_memory_alloc_rc(lp, b, g_ip_fd);
#if 0
        if(bf->c31)
        {
                state->stats->s_nnet_failures--;
                msg->ttl--;
        }
#endif
#if VERIFY_IP
        printf("%ld IP: RC sent DOWN src %ld, link %d, dst %ld, ts %lf \n",
                lp->id, msg->src, l->addr, msg->dst, e->recv_ts);
#endif
}
rn_link* rc_getroute (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 20 of file ip-rc-downstream.c.
References ip_route(), rn_getlink(), and rn_getmachine().
Referenced by ip_rc_downstream().
{
        rn_machine      *me = rn_getmachine(lp->id);
        rn_link         *link = NULL;
        /*
         * Get the next_hop destination from the forwarding table
         * for this IP packet.
         */
        if(msg->src == lp->id && me->nlinks == 1)
                link = me->link;
        else if(NULL == (link = rn_getlink(me, msg->dst)))
                link = ip_route(me, msg);
        return link;
}