ROSS.Net: ip-upstream.c File Reference
ip-upstream.c File Reference
#include <ip.h>
Functions
void ip_upstream (ip_state *state, rn_message *msg, tw_lp *lp)
void ip_rc_upstream (ip_state *state, rn_message *msg, tw_lp *lp)
Function Documentation
void ip_rc_upstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 23 of file ip-upstream.c.
References g_ip_header, and g_rn_ttl.
Referenced by ip_rc_event_handler().
{
        msg->size += g_ip_header;
        state->stats->s_ncomplete--;
        // not correct, must be state-saved
        state->stats->s_max_ttl = max(state->stats->s_max_ttl, g_rn_ttl - msg->ttl);
        state->stats->s_avg_ttl -= (g_rn_ttl - msg->ttl);
}
void ip_upstream (ip_state * state, rn_message * msg, tw_lp * lp)
Definition at line 4 of file ip-upstream.c.
References g_ip_header, g_rn_ttl, rn_event_new(), rn_event_send(), and UPSTREAM.
Referenced by ip_event_handler().
{
        tw_event        *e;
        state->stats->s_avg_ttl += (g_rn_ttl - msg->ttl);
        state->stats->s_max_ttl = max(state->stats->s_max_ttl, g_rn_ttl - msg->ttl);
        state->stats->s_ncomplete++;
        msg->size -= g_ip_header;
        e = rn_event_new(lp->gid, 0.0, lp, UPSTREAM, msg->size);
        rn_event_send(e);
#if VERIFY_IP
                printf("%lld IP: sent UP src %lld, dst %lld, ts %lf \n",
                        lp->id, msg->src, msg->dst, tw_now(lp));
#endif
}