ROSS.Net: num.c File Reference
num.c File Reference
#include <num.h>
Defines
#define DEBUG_LP 504065
Functions
void num_init (num_state *state, tw_lp *lp)
void num_update (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_start (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_event_handler (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_rc_event_handler (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void num_final (num_state *state, tw_lp *lp)
Define Documentation
#define DEBUG_LP 504065
Definition at line 7 of file num.c.
Function Documentation
void num_event_handler (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 185 of file num.c.
{
        if(msg->type == UPSTREAM)
                num_file_complete(state, bf, msg, lp);
        else if(msg->ttl == 2)
                num_update(state, bf, msg, lp);
        else if(msg->type == TIMER)
                num_file_start(state, bf, state->file_size, lp);
        else if(msg->ttl == 1)
                num_start(state, bf, msg, lp);
        else
                num_file_stop(state, bf, lp);
}
void num_final (num_state * state, tw_lp * lp)
Definition at line 212 of file num.c.
{
        int today = (int) tw_now(lp) / TWENTY_FOUR_HOURS;;
        // print out final days worth of statistics
        if(g_num_mod != INT_MIN)
        {
                if(g_num_mod != 0)
                {
                        // don't mess with Texas
                        num_report_levels(today-(today%g_num_mod)-1+g_num_mod);
                        g_num_mod = INT_MIN;
                } else
                        num_report_levels(today);
        }
        g_num_stats->s_nstop += state->stats->s_nstop;
        g_num_stats->s_nstart += state->stats->s_nstart;
        g_num_stats->s_nfiles += state->stats->s_nfiles;
}
void num_init (num_state * state, tw_lp * lp)
Definition at line 14 of file num.c.
{
        state->stats = tw_calloc(TW_LOC, "", sizeof(num_statistics), 1);
        state->file_size = MIN_FILE_SIZE;
}
void num_rc_event_handler (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 203 of file num.c.
{
        tw_error(TW_LOC, "NUM Model cannot be run with more than 1 CPU!");
}
void num_start (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 81 of file num.c.
References DEBUG_LP, g_num_level, g_num_mod, g_num_net_pop, g_num_next_report_day, g_num_nreport_days, g_num_report_days, MIN_FILE_SIZE, NINE_OCLOCK, num_file_start(), ONE_MINUTE, QUIT_TIME, rn_timer_init(), and TWENTY_FOUR_HOURS.
Referenced by num_event_handler().
{
        tw_event        *e;
        tw_stime         ts;
        rn_message      *m;
        int              today;
        int              timeofday;
        today = (int) tw_now(lp) / TWENTY_FOUR_HOURS;;
        timeofday = (int) tw_now(lp) % TWENTY_FOUR_HOURS;
        // set file size to zero for beginning
        state->file_size = MIN_FILE_SIZE;
        // num_starts recv'd after midnight, so report previous days results
        // moved to update
        // num_report_levels(tw_now(lp) / TWENTY_FOUR_HOURS);
        // only send to QUIT_TIME each day (e.g., 10:00 am)
        if(timeofday >= QUIT_TIME)
                return;
        // update network population here
        g_num_net_pop[state->type]++;
        // if NETWORK is off, then done
        if(g_num_mod == 0 && g_num_nreport_days == 0)
        {
                if(timeofday >= NINE_OCLOCK)
                {
                        state->stats->s_nstart++;
                        // update report log
                        g_num_level[state->type][NUM_LEVEL_0]++;
                }
                // create the stats update timer, and override the TTL value
                // in the rn_message data to indicate the event type
                e = rn_timer_init(lp, ((today + 1) * 86400) - 1);
                m = tw_event_data(e);
                m->ttl = 2;
                return;
        }
#if ONE
        if(lp->id != DEBUG_LP)
                return;
#endif
        // if not mod day, then do not need to start anything
        if(g_num_mod > 1 && (today % g_num_mod)+1 != g_num_mod)
                return;
        if(g_num_nreport_days > 0 && today != g_num_report_days[g_num_next_report_day])
                        return;
        // first file of the day
        state->file_size = MIN_FILE_SIZE;
        // If before 9:00 AM set a timer to start at 9:00
        if(timeofday < NINE_OCLOCK)
        {
                ts = tw_now(lp) + NINE_OCLOCK - timeofday
                                + tw_rand_unif(lp->rng) * ONE_MINUTE;
                if((int) ts % TWENTY_FOUR_HOURS >= QUIT_TIME)
                        tw_error(TW_LOC, "Next file request past quit time!");
                rn_timer_init(lp, ts);
        } else if (timeofday == NINE_OCLOCK)
        {
                // jitter time a liitle bit and start with small file
                ts = tw_now(lp) + tw_rand_unif(lp->rng) * ONE_MINUTE;
                if((int) ts % TWENTY_FOUR_HOURS >= QUIT_TIME)
                        tw_error(TW_LOC, "Next file request past quit time!");
                rn_timer_init(lp, ts);
        } else
        {
                num_file_start(state, bf, MIN_FILE_SIZE, lp);
        }
        // create the stats update timer, and override the TTL value
        // in the rn_message data to indicate the event type
        e = rn_timer_init(lp, ((today + 1) * 86400) - 1);
        m = tw_event_data(e);
        m->ttl = 2;
}
void num_update (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 29 of file num.c.
References g_num_level, g_num_log_f, g_num_mod, g_num_nreport_days, g_num_profiles, num_report_levels(), and TWENTY_FOUR_HOURS.
Referenced by num_event_handler().
{
        num_profile     *np;
        float            tput;
        int              today;
        if(!g_num_log_f)
                return;
        today = (int) tw_now(lp) / TWENTY_FOUR_HOURS;;
        num_report_levels(today);
        np = &g_num_profiles[state->type];
        tput = (state->stats->s_total_time > 0) ?
                        state->stats->s_total_kb / state->stats->s_total_time : 0.0;
        // is network on?
        if((g_num_mod > 0) || (g_num_nreport_days > 0))
        {
                if(state->stats->s_nfailures)
                {
                        g_num_level[state->type][state->stats->s_nfailures]++;
                } else if(state->stats->s_total_kb > 0)
                {
                        if (tput > np->bitrate)
                                g_num_level[state->type][NUM_LEVEL_0]++;
                        else if (tput > ((float) np->bitrate) / 2.0)
                                g_num_level[state->type][NUM_LEVEL_1]++;
                        else
                                tw_error(TW_LOC, "Should not be here!");
                                //g_num_level[state->type][NUM_LEVEL_2]++;
                }
        }
        // reset state variables
        state->stats->s_total_kb = 0;
        state->stats->s_total_time = 0;
        state->stats->s_nfailures = 0;
}