ROSS.Net: ospf-extern.h File Reference
ospf-extern.h File Reference
Functions
void ospf_random_weights (ospf_state *state, tw_lp *lp)
void ospf_experiment_weights (ospf_state *state, long int i, tw_lp *lp)
void ospf_ip_route (ospf_state *state, tw_bf *bf, rn_message *rn_msg, tw_lp *lp)
void ospf_router_debug_routing (ospf_state *state, int d, tw_lp *lp)
void ospf_router_debug_rate (tw_lp *lp, int *next)
void ospf_xml (ospf_state *state, const xmlNodePtr my_node, tw_lp *lp)
ospf_lsa * getlsa (rn_machine *, int index, int id)
int shouldRecalculateTable (ospf_lsa *newLsa, ospf_lsa *oldLsa)
tw_event * ospf_timer_cancel (tw_event *tmr, tw_lp *lp)
tw_event * ospf_timer_start (ospf_nbr *nbr, tw_event *tmr, tw_stime ts, int type, tw_lp *lp)
void ospf_interface_event_handler (ospf_nbr *nbr, ospf_int_event event, tw_lp *lp)
void ospf_list_free (char *list, unsigned int *size)
int ospf_list_contains (char *list, int index)
void ospf_list_link (char *list, int index, unsigned int *size)
void ospf_list_unlink (char *list, int index, unsigned int *size)
void ospf_aging_timer_set (ospf_state *state, ospf_db_entry *, int, tw_lp *)
void ospf_aging_timer (ospf_state *state, tw_bf *bf, tw_lp *lp)
void ospf_hello_send (ospf_state *state, ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_hello_packet (ospf_state *, ospf_nbr *, ospf_hello *, tw_bf *, tw_lp *)
void ospf_nbr_event_handler (ospf_state *state, ospf_nbr *nbr, ospf_nbr_event event, tw_lp *lp)
tw_memory * ospf_dd_copy (tw_memory *b2, tw_lp *lp)
void ospf_dd_fill_hdrs (ospf_nbr *nbr)
void ospf_dd_exchange (ospf_state *state, tw_lp *lp, ospf_message *m, int)
void ospf_dd_fill_header (ospf_nbr *nbr, int index)
int ospf_dd_compare (ospf_dd_pkt *h1, ospf_dd_pkt *h2)
void ospf_dd_event_handler (ospf_state *, ospf_nbr *, tw_bf *, tw_lp *lp)
void ospf_dd_retransmit (ospf_state *state, ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_lsa_flush (ospf_state *, ospf_nbr *, ospf_db_entry *, tw_lp *)
int ospf_lsa_find (ospf_state *state, ospf_nbr *, int id, tw_lp *lp)
void ospf_lsa_print (FILE *log, ospf_lsa *lsa)
char lsa_create (ospf_state *state, int lsa_index, tw_lp *lp)
void ospf_lsa_link_allocate (ospf_state *state, ospf_lsa *lsa, tw_lp *lp)
tw_memory * ospf_lsa_allocate (tw_lp *lp)
void ospf_lsa_premature_age (ospf_state *state, ospf_db_entry *, tw_lp *lp)
unsigned int ospf_lsa_age (ospf_state *, ospf_db_entry *dbe, tw_lp *lp)
void ospf_lsa_refresh (ospf_state *state, ospf_db_entry *dbe, tw_lp *lp)
void ospf_lsa_create (ospf_state *state, ospf_nbr *, int lsa_index, tw_lp *lp)
void ospf_lsa_start_flood (ospf_nbr *nbr, ospf_db_entry *dbe, tw_lp *lp)
void ospf_lsa_flood (ospf_state *s, ospf_db_entry *d, int f, tw_lp *lp)
int ospf_lsa_isnewer (ospf_state *, ospf_db_entry *, ospf_db_entry *, tw_lp *)
void ospf_lsa_process (ospf_state *state, ospf_message *m, int interface)
ospf_lsa * ospf_lsa_compare (ospf_nbr *n, ospf_lsa *lsa)
void ospf_ls_update_recv (ospf_state *, tw_bf *, ospf_nbr *, tw_lp *)
void ospf_ls_request (ospf_state *state, ospf_nbr *nbr, tw_lp *lp)
void ospf_ls_request_recv (ospf_state *, tw_bf *, ospf_nbr *, tw_lp *)
void ospf_ack_delayed (ospf_nbr *nbr, tw_memory *buf, int, tw_lp *lp)
void ospf_ack_timed_out (ospf_nbr *, tw_bf *, tw_lp *lp)
void ospf_ack_direct (ospf_nbr *, tw_memory *, int size, tw_lp *lp)
void ospf_ack_process (ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_db_read (ospf_state *state, tw_lp *lp)
void ospf_db_print_raw (ospf_state *state, FILE *log, tw_lp *lp)
void ospf_db_print (ospf_state *state, FILE *log, tw_lp *lp)
void ospf_db_route (ospf_state *, ospf_db_entry *curr, tw_lp *lp)
void ospf_db_remove (ospf_state *state, int, tw_lp *lp)
unsigned int ospf_db_init (ospf_state *state, tw_lp *lp)
ospf_db_entry * ospf_db_insert (ospf_state *s, int index, ospf_db_entry *, tw_lp *lp)
void ospf_db_update (ospf_state *, ospf_nbr *nbr, ospf_db_entry *, tw_lp *)
tw_event * ospf_event_new (ospf_state *, tw_lp *, tw_stime, tw_lp *)
tw_event * ospf_event_send (ospf_state *state, tw_event *event, int type, tw_lp *, int size, tw_memory *mem, int area)
void ospf_statistics_collection (ospf_state *state, tw_lp *lp)
ospf_nbr * ospf_getnbr (ospf_state *state, int id)
void ospf_neighbor_init (ospf_state *state, tw_lp *lp)
ospf_nbr * ospf_get_neighbor (ospf_state *state, int id)
void ospf_routing_init (ospf_state *state, tw_lp *lp)
void ospf_rt_build (ospf_state *state, int start_vertex)
void ospf_rt_timer (ospf_state *state, int start_vertex)
void ospf_rt_print (ospf_state *state, tw_lp *lp, FILE *)
ospf_nbr * ospf_int_getinterface (ospf_state *state, int id)
void ospf_startup (ospf_state *state, tw_lp *lp)
void ospf_event_handler (ospf_state *, tw_bf *bf, rn_message *m, tw_lp *lp)
void ospf_rc_event_handler (ospf_state *, tw_bf *bf, rn_message *m, tw_lp *lp)
void ospf_main (int argc, char **argv, char **env)
void ospf_md_final ()
Variables
int g_ospf_link_weight
int g_route []
int g_route1 []
int gr1
int gr2
int g_ospf_rt_write
int db_sz
tw_fd g_ospf_fd
tw_fd g_ospf_lsa_fd
tw_fd g_ospf_dd_fd
tw_fd g_ospf_ll_fd
ospf_global_state * g_ospf_state
char * g_ospf_init_file
FILE * g_ospf_routing_file
FILE * g_ospf_lsa_file
FILE * g_ospf_lsa_input
int * p
int * front
int * f
int * s
int * d
ospf_statistics * g_ospf_stats
tw_memory ** g_ospf_lsa
int g_routers
int g_max_updates
unsigned int g_memory
unsigned int OSPF_LSA_MAX_AGE
unsigned int OSPF_LSA_REFRESH_AGE
Function Documentation
ospf_lsa* getlsa (rn_machine * , int index, int id)
Definition at line 247 of file ospf-lsa.c.
References g_ospf_lsa, and rn_getarea().
Referenced by bgp_ospf_update(), dd_process(), flood_summary(), ls_update_process(), ospf_aging_timer(), ospf_db_init(), ospf_db_print(), ospf_db_route(), ospf_db_update(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_create(), ospf_lsa_flood(), ospf_lsa_flush(), ospf_lsa_refresh(), ospf_lsa_start_flood(), ospf_nbr_reset(), ospf_rt_print(), ospf_rt_timer(), and process_lsa_recv().
{
        tw_memory       *b;
        ospf_lsa        *lsa;
        int i;
        if(NULL == (b = rn_getarea(m)->g_ospf_lsa[id]))
                return NULL;
        lsa = tw_memory_data(b);
        for(i = 0; i < index; i++)
        {
                b = lsa->next;
                if(!b)
                        return NULL;
                lsa = tw_memory_data(b);
        }
        if(lsa == NULL)
                tw_error(TW_LOC, "Could not locate the request lsa!!");
        return lsa;
}
char lsa_create (ospf_state * state, int lsa_index, tw_lp * lp)
Definition at line 278 of file ospf-lsa.c.
References ospf_getnbr(), ospf_lsa_allocate(), ospf_lsa_link_allocate(), and rn_getarea().
{
        tw_memory       *b;
        ospf_lsa        *lsa;
        ospf_lsa_link   *l;
        ospf_nbr        *nbr;
        int              nlinks;
        int              i;
        int              x_id;
        char             index;
        nlinks = 0;
        if(entry < state->ar->nmachines)
                x_id = state->ar->id;
        else if(entry >= state->ar->nmachines + state->ar->as->nareas)
                x_id = entry - state->ar->nmachines - state->ar->as->nareas;
        else
                x_id = entry - state->ar->nmachines + state->ar->as->low;
        // Need to get nlinks FIRST, since # LSA links can be < # current
        // go by neighbor states, not topology, unless AS external LSA
        for(i = 0; i < state->n_interfaces; i++)
        {
                nbr = &state->nbr[i];
                if(nbr->state != ospf_nbr_full_st ||
                   nbr->istate != ospf_int_point_to_point_st)
                        continue;
                // If router_lsa, only count links within my area
                if(entry < state->ar->nmachines)
                {
                        if(nbr->ar != state->ar)
                                nlinks++;
                } else if(entry > state->ar->nmachines + state->ar->as->nareas)
                {
                        // AS ext LSA, count link if to nbr AS == id's AS
                        if(nbr->ar->as->id == x_id)
                                nlinks++;
                } else
                {
                        // Summary LSA, count link if to nbr Area == id's Area
                        if(state->ar->id == x_id)
                                nlinks++;
                }
        }
        // Get the head of the LSA array for this index
        b = rn_getarea(state->m)->g_ospf_lsa[entry];
        lsa = tw_memory_data(b);
        for(index = 0; NULL != lsa; index++)
        {
                if(lsa->links.size == nlinks)
                {
                        b = lsa->links.head;
                        for(i = 0; i < lsa->links.size; i++)
{
                                l = tw_memory_data(b);
                                nbr = ospf_getnbr(state, l->dst);
                                if(!nbr || (nbr->state != ospf_nbr_full_st))
                                        break;
                                b = b->next;
                        }
                        if(nlinks == i && lsa->adv_r == lp->id)
{
#if VERIFY_LS
                                printf("%ld OSPF: Found LSA for %d in graph! \n",
                                        lp->id, lsa->id);
#endif
                                return index;
                        }
                }
                if(lsa->next == NULL)
                {
                        index++;
                        break;
                }
                b = lsa->next;
                lsa = tw_memory_data(b);
        }
        lsa->next = ospf_lsa_allocate(lp);
        lsa = tw_memory_data(lsa->next);
        lsa->id = entry;
        lsa->adv_r = lp->id;
        if(x_id < state->ar->nmachines)
                lsa->type = ospf_lsa_router;
        else if(x_id < state->ar->nmachines + state->ar->as->nareas)
                lsa->type = ospf_lsa_summary3;
        else
                lsa->type = ospf_lsa_as_ext;
        ospf_lsa_link_allocate(state, lsa, lp);
        return index;
}
void ospf_ack_delayed (ospf_nbr * nbr, tw_memory * buf, int , tw_lp * lp)
Definition at line 4 of file ospf-ack.c.
References ospf_timer_start().
{
        if (NULL != nbr->delay_ack_timer)
        {
                // This means that this is the first delayed ack to be added to the
                // queue..
                nbr->delay_ack_timer = ospf_timer_start(nbr, nbr->delay_ack_timer,
                                                        1, OSPF_ACK_TIMEOUT, lp);
        }
        buf->next = nbr->delay;
        nbr->delay = buf;
        nbr->delay_ack_size += size;
}
void ospf_ack_direct (ospf_nbr * , tw_memory * , int size, tw_lp * lp)
Definition at line 49 of file ospf-ack.c.
References OSPF_ACK_HEADER, ospf_event_new(), and ospf_event_send().
Referenced by ospf_lsa_flush(), and process_lsa_recv().
{
        tw_event       *e;
        ospf_db_entry  *dbe;
        dbe = tw_memory_data(buf);
        e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_LS_ACK, lp, size + OSPF_ACK_HEADER,
                                                buf, nbr->router->ar->id);
/*
        e = ospf_event_send(nbr->router, tw_getlp(nbr->id), OSPF_LS_ACK,
                                                lp, size + OSPF_ACK_HEADER,
                                                buf, nbr->router->area);
*/
#if VERIFY_OSPF_ACK
        printf("%ld: sending direct ACK for LSA %d to %d at %f, now %f\n",
                   lp->id, dbe->b.entry, nbr->id, e->recv_ts, tw_now(lp));
#endif
}
void ospf_ack_process (ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 75 of file ospf-ack.c.
References g_ospf_fd.
Referenced by ospf_event_handler().
{
        tw_memory      *buf;
        ospf_db_entry  *dbe;
        int             cnt;
        cnt = 0;
        for (buf = tw_event_memory_get(lp); buf; buf = tw_event_memory_get(lp))
        {
                dbe = tw_memory_data(buf);
                tw_memory_free(lp, buf, g_ospf_fd);
        }
#if VERIFY_OSPF_ACK
        if (nbr->state < ospf_nbr_exchange_st)
        {
                printf("%ld: nbr state is %d: LS ACK is ignored\n",
                                lp->id, nbr->state);
                return;
        }
#endif
}
void ospf_ack_timed_out (ospf_nbr * , tw_bf * , tw_lp * lp)
Definition at line 25 of file ospf-ack.c.
References OSPF_ACK_HEADER, ospf_event_new(), ospf_event_send(), and ospf_timer_cancel().
Referenced by ospf_event_handler().
{
        tw_event        *e;
        e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_LS_ACK, lp,
                                        nbr->delay_ack_size,
                                        nbr->delay, nbr->router->ar->id);
/*
        ospf_event_send(nbr->router, tw_getlp(nbr->id), OSPF_LS_ACK, lp,
                                        nbr->delay_ack_size,
                                        nbr->delay, nbr->router->ar->id);
*/
        nbr->delay = NULL;
        nbr->delay_ack_size = OSPF_ACK_HEADER;
        nbr->delay_ack_timer = ospf_timer_cancel(nbr->delay_ack_timer, lp);
}
void ospf_aging_timer (ospf_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 147 of file ospf-timer-aging.c.
References can_be_removed(), getlsa(), OSPF_AGING_INTERVAL, ospf_lsa_flood(), OSPF_LSA_MAX_AGE, ospf_lsa_refresh(), OSPF_LSA_REFRESH_AGE, OSPF_MIN_LSA_SEQNUM, ospf_rt_build(), and ospf_timer_start().
Referenced by ospf_event_handler().
{
        tw_stime        ts;
        ospf_db_entry  *dbe;
        ospf_lsa       *lsa;
        int             i;
        int             next_timer;
        char            rebuild_rt;
        int             aging_increment;
        ts = -1.0;
        rebuild_rt = 0;
        //aging_increment = aging_timer_increment(state, lp);
        aging_increment = (floor(tw_now(lp) - state->db_last_ts) / 4) * 4;
        state->db_last_ts = tw_now(lp);
#if VERIFY_AGING
        printf("%ld: Aging DB: new last ts: %f \n", lp->id, tw_now(lp));
#endif
        next_timer = OSPF_LSA_MAX_AGE;
        for (i = 0; i < state->ar->g_ospf_nlsa; i++)
        {
                dbe = &state->db[i];
                if (dbe->b.free)
                        continue;
                lsa = getlsa(state->m, dbe->lsa, i);
#if VERIFY_AGING
                printf("%ld: Age before aging lsa %d: %d (incr = %d), after %d\n",
                           lp->id, lsa->id, dbe->b.age, aging_increment,
                           dbe->b.age + aging_increment);
#endif
                dbe->b.age += aging_increment;
                if (TW_TRUE == can_be_removed(state, dbe, lp))
                {
#if VERIFY_AGING
                        printf("\tchecking db entry for LSA %d REMOVED (age = %d)\n",
                                i, dbe->b.age);
#endif
                        if (lsa->adv_r == lp->id)
{
                                //printf("%d: my LSA reached MAX AGE! \n", lp->id);
                                state->lsa_wrapping = 0;
                                state->lsa_seqnum = OSPF_MIN_LSA_SEQNUM + 1;
                                dbe->b.age = 0;
                                ospf_lsa_refresh(state, dbe, lp);
                        } else
{
                                dbe->b.free = 1;
                                //ospf_rt_build(state, lp->id);
                                rebuild_rt = 1;
                        }
                } else
                {
                        if (lsa->adv_r == lp->id)
{
                                if (dbe->b.age >= OSPF_LSA_REFRESH_AGE)
{
                                        dbe->b.age = 0;
                                        printf("\n%lld: refresh LSA %d: now %lf \n",
                                                lp->id, dbe->b.entry, tw_now(lp));
                                        ospf_lsa_refresh(state, dbe, lp);
                                        ts = OSPF_LSA_REFRESH_AGE;
                                        continue;
#if VERIFY_AGING
                                        printf("set ts: %lf, now %lf > REFRESH \n",
                                                   ts, tw_now(lp));
#endif
                                } else
{
                                        next_timer = min(OSPF_LSA_REFRESH_AGE -
                                                         dbe->b.age, next_timer);
#if VERIFY_AGING
                                        printf("\tset next_timer: %d, < REFRESH \n",
                                                next_timer);
#endif
                                }
                                if (dbe->b.age >= OSPF_LSA_REFRESH_AGE)
{
                                        printf("%lld: FLOODING LSA %d for refresh!\n",
                                                lp->id, dbe->b.entry);
                                        ospf_lsa_flood(state, dbe, -1, lp);
                                        //ospf_rt_build(state, lp->id);
                                        //rebuild_rt = 1;
                                }
                        } else
{
                                /*
                                 * Do not overwrite TS, if set already by either
                                 * a self-originated LSA, or otherwise.
                                 */
                                if (dbe->b.age >= OSPF_LSA_MAX_AGE && ts < 0.0)
{
                                        dbe->b.age = OSPF_LSA_MAX_AGE;
                                        ts = floor(tw_now(lp) / OSPF_AGING_INTERVAL) *
                                                OSPF_AGING_INTERVAL;
                                        //printf("%d: setting (ns) ts: %f, > MAX AGE\n", lp->id, ts);
                                } else if (ts < 0.0)
{
                                        next_timer = min(OSPF_LSA_MAX_AGE -
                                                        dbe->b.age, next_timer);
/*
                                        printf("%d: setting (ns)next_timer: %d, < REFRESH \n",
                                                   lp->id, next_timer);
*/
                                }
                                if (dbe->b.age >= OSPF_LSA_MAX_AGE)
{
/*
                                        printf("%d: FLOODING %d LSA\n",
                                                                lp->id, lsa->adv_r);
*/
                                        ospf_lsa_flood(state, dbe, -1, lp);
                                        //ospf_rt_build(state, lp->id);
                                        rebuild_rt = 1;
                                }
                        }
                }
        }
        if(rebuild_rt)
                ospf_rt_build(state, lp->id);
        if(ts < 0.0)
        {
                state->aging_timer = ospf_timer_start(NULL, state->aging_timer,
                                                        next_timer,
                                                        OSPF_AGING_TIMER, lp);
        }
        else
        {
                state->aging_timer = ospf_timer_start(NULL, state->aging_timer,
                                                        ts,
                                                        OSPF_AGING_TIMER, lp);
        }
#if VERIFY_AGING
        if(state->aging_timer)
                printf("\tnext aging timer to fire at %lf\n",
                        state->aging_timer->recv_ts);
#endif
}
void ospf_aging_timer_set (ospf_state * state, ospf_db_entry * , int , tw_lp *)
Definition at line 24 of file ospf-timer-aging.c.
References OSPF_AGING_INTERVAL, ospf_lsa_age(), OSPF_LSA_MAX_AGE, OSPF_LSA_REFRESH_AGE, and ospf_timer_start().
Referenced by ospf_db_update(), ospf_lsa_create(), ospf_lsa_refresh(), and ospf_lsa_start_flood().
{
        tw_stime        ts;
        int     i;
        int     incr;
#if VERIFY_AGING
        printf("%ld: Aging DB for new LSA: new last ts: %f \n", lp->id, tw_now(lp));
#endif
        /*
         * Have to subtract the over-aging that will occur on this lsa
         * in the next aging timer interval.
         */
        //dbe->b.age = age - aging_timer_increment(state, lp);
        // age them all immediately, they cannot be past the timer!
        ts = DBL_MAX;
        if(state->aging_timer)
                ts = state->aging_timer->recv_ts - tw_now(lp);
        incr = (floor(tw_now(lp) - state->db_last_ts) / 4) * 4;
        state->db_last_ts = tw_now(lp);
        // Age our LSAs, and increment the other LSA ages to the current time
        if(incr > 0)
        {
                for(i = 0; i < state->ar->g_ospf_nlsa; i++)
                {
                        if(dbe->b.free)
                                continue;
                        if(dbe->b.entry == i)
                                state->db[i].b.age = age;
                        else
                                state->db[i].b.age += incr;
#if VERIFY_AGING
                        printf("\tLSA %d new age: %d\n", i, state->db[i].b.age);
#endif
                }
        } else
        {
                state->db[dbe->b.entry].b.age = age;
        }
        // now move the timer up, if the new LSA is going to cause the next
        // timer firing
        if(dbe->b.entry == lp->id)
        {
                if(ts > OSPF_LSA_REFRESH_AGE - dbe->b.age)
                        ts = OSPF_LSA_REFRESH_AGE - dbe->b.age;
        } else
        {
                if(ts > OSPF_LSA_MAX_AGE - dbe->b.age)
                        ts = OSPF_LSA_MAX_AGE - dbe->b.age;
        }
#if VERIFY_AGING
        printf("\tdbe age now : %d \n", dbe->b.age);
        printf("\tospf_lsa_age: %d \n", ospf_lsa_age(state, dbe, lp));
        printf("\tage increment: %d \n", incr);
        printf("\tnew age: %d \n", age);
#endif
        /*
         * Set the timer for the next aging timer interval so we can compute the
         * new ages and reset the timer appropriately for REFRESH_AGE and MAX_AGE
         */
        ts = (floor(tw_now(lp) / OSPF_AGING_INTERVAL) + 1) * OSPF_AGING_INTERVAL;
        ts -= tw_now(lp);
        state->aging_timer = ospf_timer_start(NULL, state->aging_timer,
                                  ts, OSPF_AGING_TIMER, lp);
#if VERIFY_AGING
        if(state->aging_timer)
                printf("\tnext aging timer will fire at %lf, now %lf \n",
                                state->aging_timer->recv_ts, tw_now(lp));
        else
                printf("\tnext aging timer past end time (%f)!! \n",
                                        tw_now(lp) + ts);
#endif
}
unsigned int ospf_db_init (ospf_state * state, tw_lp * lp)
Definition at line 393 of file ospf-database.c.
References flood_summary(), g_ospf_rt_write, g_rn_nas, getlsa(), ospf_lsa_find(), OSPF_LSA_MAX_AGE, OSPF_LSA_REFRESH_AGE, OSPF_MIN_LSA_SEQNUM, and rn_getarea().
Referenced by ospf_startup().
{
        rn_area         *ar;
        ospf_db_entry   *dbe;
        ospf_lsa        *lsa;
        unsigned int    next_timer;
        unsigned int    j;
        unsigned int    i;
        ar = rn_getarea(state->m);
        state->db = (ospf_db_entry *)
                        calloc(sizeof(ospf_db_entry), state->ar->g_ospf_nlsa);
        if(!state->db)
                tw_error(TW_LOC, "Out of memory for local LSA database!");
#if VERIFY_DATABASE
        printf("%ld: INIT DB: nentries %d \n", lp->id, state->ar->g_ospf_nlsa);
#endif
        /*
         * Starting converged, setup LSA database
         */
        state->db_last_ts = 0;
        next_timer = OSPF_LSA_MAX_AGE;
        j = 0;
        for(i = 0; i < state->ar->g_ospf_nlsa - g_rn_nas; i++)
        {
                dbe = &state->db[i];
                dbe->b.age = 0;
                dbe->b.free = 1;
                dbe->b.entry = i;
                dbe->seqnum = OSPF_MIN_LSA_SEQNUM + 1;
                // get the FIRST entry for the LSA
                if((NULL == (lsa = getlsa(state->m, dbe->lsa, i))) ||
                   lsa->adv_r == 0xffffffff)
                {
                        if(i < state->ar->nmachines)
                                continue;
                        // May need to create the LSA from a prior run
                        if(0 == g_ospf_rt_write && state->m->ft[i] != -1)
{
                                dbe->lsa = ospf_lsa_find(state,
                                                        &state->nbr[state->m->ft[i]],
                                                         i, lp);
                                lsa = getlsa(state->m, dbe->lsa, i);
                        }
                }
                // I think this is ok, since an LSA with no links is not
                // part of the database.. at that point it is simply removed
                if(lsa->links.size == 0)
                        continue;
                dbe->b.free = 0;
#if VERIFY_DATABASE
                printf("\t%ld: lsa %d: age %d, adv_r %d\n",
                        lp->id, i, dbe->b.age, lsa->adv_r);
#endif
                if(lsa->adv_r == lp->id)
                {
                        // If mine, variable so not all flood simulataneously.
                        //dbe->b.age = tw_rand_integer(lp->id, 0, OSPF_LSA_REFRESH_AGE - 1);
                        if(i >= state->ar->nmachines &&
                                i < state->ar->g_ospf_nlsa - g_rn_nas)
{
                                flood_summary(state, dbe, i, lp);
                        }
                        if(dbe->b.age >= OSPF_LSA_REFRESH_AGE)
                                tw_error(TW_LOC, "LSA %d too old to start off with, "
                                         "should be less than %d "
                                         "(OSPF_LSA_REFRESH_AGE) \n",
                                         dbe->b.age,
                                         OSPF_LSA_REFRESH_AGE);
                        next_timer = min(OSPF_LSA_REFRESH_AGE - dbe->b.age, next_timer);
#if VERIFY_DATABASE
                        printf("\tLSA %d, next timer: %d (mine)\n", i, next_timer);
#endif
                } else
                {
                        if(i >= state->ar->nmachines &&
                                i < state->ar->g_ospf_nlsa - g_rn_nas)
{
                                flood_summary(state, dbe, i, lp);
                        }
                        if(dbe->b.age >= OSPF_LSA_MAX_AGE)
                                tw_error(TW_LOC, "LSA %d too old to start off with, "
                                         "should be less than %d "
                                         "(OSPF_LSA_MAX_AGE) \n",
                                         dbe->b.age,
                                         OSPF_LSA_MAX_AGE);
                        next_timer = min(OSPF_LSA_MAX_AGE - dbe->b.age, next_timer);
#if VERIFY_DATABASE
                        printf("\tLSA %d, next timer: %d \n", i, next_timer);
#endif
                }
        }
        for(; i < state->ar->g_ospf_nlsa; i++)
        {
                state->db[i].b.entry = i;
                state->db[i].b.free = 1;
        }
        //ospf_db_print(state, stdout, lp);
        return next_timer;
}
ospf_db_entry* ospf_db_insert (ospf_state * s, int index, ospf_db_entry * , tw_lp * lp)
Definition at line 366 of file ospf-database.c.
References ospf_db_route(), and ospf_rt_build().
Referenced by ospf_lsa_create().
{
        ospf_db_route(state, curr, lp);
        curr->lsa = index;
        curr->b.age = 0;
        curr->b.free = 0;
        ospf_rt_build(state, lp->id);
        return curr;
}
void ospf_db_print (ospf_state * state, FILE * log, tw_lp * lp)
Definition at line 193 of file ospf-database.c.
References getlsa(), and ospf_lsa_print().
Referenced by ospf_statistics_collection().
{
        ospf_db_entry   *dbe;
        ospf_lsa        *lsa;
        int              i;
        int              x_id;
        fprintf(log, "LSA Database contains %d LSAs: db_last_ts %lf \n\n",
                state->ar->g_ospf_nlsa, state->db_last_ts);
        fprintf(log, "\n\t%-15s %-10s %-10s # \n",
                "Router Id", "index", "adv_r");
        for(i = 0; i < state->ar->nmachines; i++)
        {
                dbe = &state->db[i];
                x_id = i + state->ar->low;
                if(x_id == state->m->id)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "self");
                } else if(state->db[i].b.free)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "no entry");
                } else if(NULL != (lsa = getlsa(state->m, dbe->lsa, i)))
                {
                        fprintf(log, "\t%-15d ", x_id);
                        ospf_lsa_print(log, lsa);
                } else
                {
                        fprintf(log, "\t%-15d %-15s",
                                x_id, "Fatal Error: NO LSA");
                }
        }
        fprintf(log, "\n\t%-15s %-10s %-10s # \n",
                "Area Id", "index", "adv_r");
        for(; i < state->ar->nmachines + state->ar->as->nareas; i++)
        {
                dbe = &state->db[i];
                x_id = i - state->ar->nmachines + state->ar->as->low;
                if(x_id == state->ar->id)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "self");
                } else if(state->db[i].b.free)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "no entry");
                } else if(NULL != (lsa = getlsa(state->m, dbe->lsa, i)))
                {
                        fprintf(log, "\t%-15d ", x_id);
                        ospf_lsa_print(log, lsa);
                } else
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "Fatal Error: NO LSA");
                }
        }
        fprintf(log, "\n\t%-15s %-10s %-10s # \n",
                "AS Id", "index", "adv_r");
        for(; i < state->ar->g_ospf_nlsa; i++)
        {
                dbe = &state->db[i];
                x_id = i - state->ar->nmachines - state->ar->as->nareas;
                if(x_id == state->ar->as->id)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "self");
                } else if(state->db[i].b.free)
                {
                        fprintf(log, "\t%-15d %-15s \n",
                                x_id, "no entry");
                } else if(NULL != (lsa = getlsa(state->m, dbe->lsa, i)))
                {
                        fprintf(log, "\t%-15d ", x_id);
                        ospf_lsa_print(log, lsa);
                } else
                {
                        fprintf(log, "\t%-15d %-15s\n",
                                x_id, "Fatal Error: NO LSA");
                }
        }
}
void ospf_db_print_raw (ospf_state * state, FILE * log, tw_lp * lp)
Definition at line 65 of file ospf-database.c.
Referenced by ospf_statistics_collection().
{
        ospf_db_entry   *dbe;
        int              i;
        fprintf(log, "%lf\n", state->db_last_ts);
        for(i = 0; i < state->ar->g_ospf_nlsa; i++)
        {
                dbe = &state->db[i];
                fprintf(log, "%d %d %d %d %d %d %d\n",
                        dbe->b.free, dbe->b.age, dbe->b.entry,
                        dbe->lsa, dbe->seqnum, dbe->cause_bgp, dbe->cause_ospf);
        }
}
void ospf_db_read (ospf_state * state, tw_lp * lp)
Definition at line 83 of file ospf-database.c.
References g_ospf_ll_fd, g_ospf_lsa_fd, g_ospf_lsa_input, and ospf_lsa_print().
Referenced by ospf_startup().
{
        tw_memory       *b;
        //tw_stime       db_last_ts;
        ospf_db_entry   *dbe;
        ospf_lsa        *lsa;
        ospf_lsa_link   *l;
        FILE            *fp;
        int              age;
        int              free;
        int              entry;
        int              id;
        int              size;
        int              i;
        int              j;
        fp = g_ospf_lsa_input;
        state->db = (ospf_db_entry *)
                        calloc(sizeof(ospf_db_entry), state->ar->g_ospf_nlsa);
        if(!state->db)
                tw_error(TW_LOC, "Out of memory for local LSA database!");
        fscanf(fp, "%lf", &state->db_last_ts);
        if(!state->db_last_ts)
                state->db_last_ts = 1;
        if(state->ar->low == lp->id)
        {
                //printf("%ld: Reading in LSAs for area: %d \n", lp->id, state->ar->id);
                state->ar->g_ospf_lsa = (tw_memory **) calloc(sizeof(tw_memory *) *
                                                state->ar->g_ospf_nlsa, 1);
                if(!state->ar->g_ospf_lsa)
                        tw_error(TW_LOC, "Unable to allocate global LSA table!");
                fscanf(fp, "%d", &id);
                for(i = 0; i < state->ar->g_ospf_nlsa; i++)
                {
                        state->ar->g_ospf_lsa[i] = tw_memory_alloc(lp, g_ospf_lsa_fd);
                        lsa = tw_memory_data(state->ar->g_ospf_lsa[i]);
                        while(id == i)
{
                                lsa->type = ospf_lsa_router;
                                lsa->id = id;
                                fscanf(fp, "%d %d", &lsa->adv_r, &size);
                                for(j = 0; j < size; j++)
{
                                        b = tw_memory_alloc(lp, g_ospf_ll_fd);
                                        l = tw_memory_data(b);
                                        fscanf(fp, "%d %d", &l->dst, &l->metric);
                                        tw_memoryq_push(&lsa->links, b);
                                }
                                fscanf(fp, "%d", &id);
                                if(id == i)
{
#if VERIFY_OSPF_READ
                                        printf("\t");
                                        ospf_lsa_print(stdout, lsa);
#endif
                                        lsa->next = tw_memory_alloc(lp, g_ospf_lsa_fd);
                                        lsa = tw_memory_data(lsa->next);
                                } else
{
#if VERIFY_OSPF_READ
                                        printf("\t");
                                        ospf_lsa_print(stdout, lsa);
#endif
                                }
                        }
                }
        }
#if VERIFY_OSPF_READ || 1
        printf("%lld: Database: %lf \n", lp->gid, state->db_last_ts);
#endif
        for(i = 0; i < state->ar->g_ospf_nlsa; i++)
        {
                dbe = &state->db[i];
                fscanf(fp, "%d %d %d %d %d %c %c",
                        &free, &age, &entry, &dbe->lsa, &dbe->seqnum,
                        &dbe->cause_bgp, &dbe->cause_ospf);
                dbe->b.free = free;
                //dbe->b.age = age;
                dbe->b.age = 0;
                dbe->b.entry = entry;
                dbe->cause_bgp = dbe->cause_ospf = 0;
#if VERIFY_OSPF_READ
                printf("\t%d %d %d %d %d %c %c \n",
                        dbe->b.free, dbe->b.age, dbe->b.entry,
                        dbe->lsa, dbe->seqnum, dbe->cause_bgp, dbe->cause_ospf);
#endif
        }
}
void ospf_db_remove (ospf_state * state, int , tw_lp * lp)
Definition at line 380 of file ospf-database.c.
References ospf_db_route(), and OSPF_LSA_MAX_AGE.
Referenced by bgp_ospf_init(), ospf_lsa_create(), ospf_lsa_flush(), and ospf_nbr_reset().
{
        ospf_db_entry   *curr;
        curr = &state->db[index];
        curr->b.free = 1;
        curr->b.age = OSPF_LSA_MAX_AGE;
        ospf_db_route(state, curr, lp);
}
void ospf_db_route (ospf_state * , ospf_db_entry * curr, tw_lp * lp)
Definition at line 6 of file ospf-database.c.
References d, getlsa(), rn_route(), and rn_route_change().
Referenced by bgp_ospf_init(), ospf_db_insert(), ospf_db_remove(), ospf_db_update(), and ospf_rt_timer().
{
        tw_memory       *b;
        ospf_lsa_link   *l;
        ospf_lsa        *lsa;
        int              d = -1;
        if(curr->b.free)
        {
#if VERIFY_DATABASE
                printf("\t%ld: removing rn_route to %d! \n", lp->id, curr->b.entry);
#endif
                rn_route_change(state->m, curr->b.entry, -1);
                state->m->nhop[curr->b.entry] = -1;
                return;
        }
        lsa = getlsa(state->m, curr->lsa, curr->b.entry);
        if(lsa->adv_r == lp->id)
        {
                for(b = lsa->links.head; b; b = b->next)
                {
                        l = tw_memory_data(b);
                        d = rn_route(state->m, l->dst);
                        if(-1 == d)
                                continue;
                        rn_route_change(state->m, curr->b.entry, d);
                        state->m->nhop[curr->b.entry] =
                                        state->m->nhop[lp->id - state->ar->low];
                        break;
                }
                // Could not find route..
                if(-1 == d)
                {
                        rn_route_change(state->m, curr->b.entry, -1);
                        state->m->nhop[curr->b.entry] = -1;
                }
        } else
        {
                d = rn_route(state->m, lsa->adv_r);
                rn_route_change(state->m, curr->b.entry, d);
                state->m->nhop[curr->b.entry] =
                                state->m->nhop[lsa->adv_r - state->ar->low];
        }
#if VERIFY_DATABASE
        printf("\t%ld: adding rn_route for DB entry %d: adv_r %d, nhi %d \n",
                lp->id, curr->b.entry, lsa->adv_r, d);
#endif
}
void ospf_db_update (ospf_state * , ospf_nbr * nbr, ospf_db_entry * , tw_lp *)
Definition at line 288 of file ospf-database.c.
References g_route, g_route1, getlsa(), gr1, gr2, ospf_aging_timer_set(), ospf_db_route(), ospf_lsa_age(), OSPF_LSA_MAX_AGE, and ospf_rt_build().
Referenced by process_lsa_recv().
{
#if VERIFY_OSPF_CONVERGENCE
        ospf_lsa        *lsa;
#endif
        ospf_db_entry   *curr;
        int              last_lsa;
        int              curr_age;
        curr = &state->db[new_dbe->b.entry];
        //curr_age = new_dbe->b.age;
        if(curr->b.free != 1)
                curr_age = ospf_lsa_age(state, curr, lp);
        else
                curr_age = OSPF_LSA_MAX_AGE;
        last_lsa = curr->lsa;
        curr->lsa = new_dbe->lsa;
        curr->b.free = 0;
        curr->seqnum = new_dbe->seqnum;
        ospf_db_route(state, curr, lp);
        ospf_aging_timer_set(state, curr, new_dbe->b.age, lp);
        if((new_dbe->b.age == OSPF_LSA_MAX_AGE &&
            curr_age != OSPF_LSA_MAX_AGE) ||
           (new_dbe->b.age != OSPF_LSA_MAX_AGE &&
            curr_age == OSPF_LSA_MAX_AGE) ||
           (new_dbe->lsa != last_lsa))
        {
                ospf_rt_build(state, lp->id);
#if VERIFY_OSPF_CONVERGENCE
                lsa = getlsa(state->m, new_dbe->lsa, new_dbe->b.entry);
                lsa->count--;
                if(lsa->count == 0)
                {
                        if(lsa->adv_r == 0)
{
                                g_route[0] = lp->id;
                                g_route[1] = nbr->id;
                                gr1 = 1;
                        } else
{
                                g_route1[0] = lp->id;
                                g_route1[1] = nbr->id;
                                gr2 = 1;
                        }
                        printf("%ld: Convergence time for lsa %d: %f - %f = %f seconds\n",
                                lp->id, lsa->adv_r,
                                tw_now(lp), lsa->start,
                                tw_now(lp) - lsa->start);
/*
                        printf("%ld: link down at %f, time now %f \n",
                                lp->id, lsa->start, tw_now(lp));
*/
                        state->c_time = tw_now(lp) -
                                        lsa->start +
                                        state->gstate->rt_interval;
                }
/*
                else
                        printf("%d: lsa %d remaining: %d \n",
                                lp->id, lsa->adv_r, lsa->count);
*/
#endif
        }
}
int ospf_dd_compare (ospf_dd_pkt * h1, ospf_dd_pkt * h2)
Definition at line 417 of file ospf-dd.c.
Referenced by ospf_dd_event_handler().
{
        if (h1->b.init == h2->b.init &&
            h1->b.more == h2->b.more &&
            h1->b.master == h2->b.master &&
            h1->seqnum == h2->seqnum+1)
        {
                return 1;
        }
        return 0;
}
tw_memory* ospf_dd_copy (tw_memory * b2, tw_lp * lp)
Definition at line 200 of file ospf-dd.c.
References g_ospf_dd_fd, and g_ospf_fd.
Referenced by ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_nbr_neg_done(), and ospf_nbr_two_way_recv().
{
        tw_memory       *b;
        tw_memory       *head;
        tw_memory       *last;
        tw_memory       *next_b;
        ospf_dd_pkt     *h1;
        ospf_dd_pkt     *h2;
        ospf_db_entry   *dbe;
        ospf_db_entry   *h2_dbe;
        int     i;
        b = tw_memory_alloc(lp, g_ospf_dd_fd);
        h1 = tw_memory_data(b);
        h2 = tw_memory_data(b2);
        h1->b.init = h2->b.init;
        h1->b.more = h2->b.more;
        h1->b.master = h2->b.master;
        h1->seqnum = h2->seqnum;
        h1->nlsas = h2->nlsas;
        head = last = b;
        next_b = b2->next;
        for(i = 0; i < h2->nlsas; i++, next_b = next_b->next)
        {
                b = tw_memory_alloc(lp, g_ospf_fd);
                dbe = tw_memory_data(b);
                h2_dbe = tw_memory_data(next_b);
                dbe->b = h2_dbe->b;
                dbe->lsa = h2_dbe->lsa;
                dbe->seqnum = h2_dbe->seqnum;
                last->next = b;
                last = b;
        }
        return head;
}
void ospf_dd_event_handler (ospf_state * , ospf_nbr * , tw_bf * , tw_lp * lp)
if master
Definition at line 280 of file ospf-dd.c.
References dd_exchange(), dd_process(), g_ospf_dd_fd, ospf_dd_compare(), ospf_dd_copy(), OSPF_DD_HEADER, ospf_dd_retransmit(), ospf_event_new(), ospf_event_send(), OSPF_LSA_UPDATE_HEADER, and ospf_nbr_event_handler().
Referenced by ospf_event_handler().
{
        tw_event        *e;
        tw_memory       *b;
        tw_memory       *send;
        ospf_dd_pkt     *in_dd;
        ospf_dd_pkt     *out_dd;
        b = lp->pe->cur_event->memory; //tw_event_memory_get(lp);
        lp->pe->cur_event->memory = NULL;
        in_dd = tw_memory_data(b);
        printf("%lld OSPF: DD from %d, ts %lf, state %d, I %d, M %d, Master %d \n",
                lp->id, nbr->id, tw_now(lp), nbr->state, in_dd->b.init, in_dd->b.more,
                in_dd->b.master);
        switch(nbr->state)
        {
                case ospf_nbr_down_st:
                        state->stats->s_drop_dd++;
                        break;
                case ospf_nbr_attempt_st:
                        state->stats->s_drop_dd++;
                        break;
                case ospf_nbr_init_st:
                        printf("%lld OSPF: DD sending nbr %d 2-way recv event \n",
                                                lp->id, nbr->id);
                        ospf_nbr_event_handler(state, nbr, ospf_nbr_two_way_recv_ev, lp);
                        if(nbr->state != ospf_nbr_exstart_st)
                                break;
                case ospf_nbr_exstart_st:
                        if(in_dd->b.init && in_dd->b.more && in_dd->b.master &&
                           in_dd->nlsas == 0 && nbr->id > lp->id)
{
                                nbr->master = 1;
                                nbr->dd_seqnum = in_dd->seqnum;
                        } else
                                nbr->master = 0;
                        state->stats->s_proc_dd++;
                        nbr->last_recv_dd = ospf_dd_copy(b, lp);
                        ospf_nbr_event_handler(state, nbr, ospf_nbr_neg_done_ev, lp);
                        break;
                case ospf_nbr_two_way_st:
                        state->stats->s_drop_dd++;
                        break;
                case ospf_nbr_exchange_st:
                        state->stats->s_proc_dd++;
                        /*
                         * Verify DD packet received is in proper format
                         */
                        if(in_dd->b.init)
{
                                ospf_nbr_event_handler(state,nbr,
                                                ospf_nbr_seqnum_mismatch_ev, lp);
                                break;
                        } else if(in_dd->b.master != nbr->master)
{
                                ospf_nbr_event_handler(state,nbr,
                                                ospf_nbr_seqnum_mismatch_ev, lp);
                                break;
                        } else if((nbr->master && in_dd->seqnum != nbr->dd_seqnum+1) ||
                                  (!nbr->master && in_dd->seqnum != nbr->dd_seqnum))
{
                                ospf_nbr_event_handler(state,nbr,
                                                ospf_nbr_seqnum_mismatch_ev, lp);
                                break;
                        }
                        /*
                         * If the slave recvs a duplicate, it resends it
                         */
                        if(nbr->master &&
                           ospf_dd_compare(in_dd, tw_memory_data(nbr->last_recv_dd)))
{
                                ospf_dd_retransmit(state, nbr, bf, lp);
                                break;
                        }
printf("%lld: got valid DD in exchange from %d, more = %d \n", lp->id, nbr->id, in_dd->b.more);
                        nbr->last_recv_dd = ospf_dd_copy(b, lp);
                        dd_process(state, nbr, b, lp);
                        dd_exchange(state, nbr, lp);
                        if(in_dd->b.more == 0)
                                ospf_nbr_event_handler(state, nbr,
                                        ospf_nbr_exchange_done_ev, lp);
                        break;
                case ospf_nbr_loading_st:
                case ospf_nbr_full_st:
                        if(ospf_dd_compare(in_dd, tw_memory_data(nbr->last_recv_dd)))
{
                                if(!nbr->master)
{
                                        send = ospf_dd_copy(nbr->retrans_dd, lp);
                                        out_dd = tw_memory_data(send);
                                        out_dd->b.master = 0;
                                        out_dd->b.init = 0;
                                        out_dd->b.more = 0;
                                        e = ospf_event_new(state, tw_getlp(nbr->id),
                                                           0.0, lp);
                                        ospf_event_send(state, e,
                                                OSPF_DD_MSG, lp,
                                                OSPF_DD_HEADER +
                                                        (out_dd->nlsas *
                                                         OSPF_LSA_UPDATE_HEADER),
                                                send, state->ar->id);
                                        state->stats->s_sent_dds++;
                                }
                        } else
                                ospf_nbr_event_handler(state,nbr,
                                        ospf_nbr_seqnum_mismatch_ev, lp);
                        break;
                default:
                        printf("%lld: Received DD with unknown type\n", lp->id);
        }
        tw_memory_free(lp, b, g_ospf_dd_fd);
}
void ospf_dd_exchange (ospf_state * state, tw_lp * lp, ospf_message * m, int)
void ospf_dd_fill_hdrs (ospf_nbr * nbr)
void ospf_dd_fill_header (ospf_nbr * nbr, int index)
void ospf_dd_retransmit (ospf_state * state, ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 255 of file ospf-dd.c.
References ospf_dd_copy(), OSPF_DD_HEADER, ospf_event_new(), ospf_event_send(), OSPF_LSA_UPDATE_HEADER, OSPF_RETRANS_INTERVAL, and ospf_timer_start().
Referenced by ospf_dd_event_handler(), and ospf_event_handler().
{
        tw_event        *e;
        tw_memory       *b;
        ospf_dd_pkt     *dd;
        b = ospf_dd_copy(nbr->retrans_dd, lp);
        dd = tw_memory_data(b);
        printf("%lld OSPF: retransmit DD to %d, ts %lf \n",
                lp->id, nbr->id, tw_now(lp) + OSPF_RETRANS_INTERVAL);
        e = ospf_event_new(state, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_DD_MSG, lp,
                        OSPF_DD_HEADER + (dd->nlsas * OSPF_LSA_UPDATE_HEADER),
                        b, nbr->router->ar->id);
        nbr->retrans_timer =
                ospf_timer_start(nbr, nbr->retrans_timer,
                                        OSPF_RETRANS_INTERVAL,
                                        OSPF_RETRANS_TIMEOUT,
                                        lp);
}
void ospf_event_handler (ospf_state * state, tw_bf * bf, rn_message * rn_msg, tw_lp * lp)
OSPF model event handler function.
This is the OSPF model event handler function. This function is a simple switch statement which determine what kind of event was recieved and passes control to the appropriate function.
Definition at line 37 of file ospf-router.c.
References g_ospf_fd, ospf_ack_process(), ospf_ack_timed_out(), ospf_aging_timer(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_experiment_weights(), ospf_hello_packet(), ospf_hello_send(), ospf_int_getinterface(), ospf_ls_request_recv(), ospf_ls_update_recv(), ospf_nbr_event_handler(), ospf_rt_timer(), rn_getas(), and TIMER.
{
        tw_memory       *b;
        ospf_nbr        *nbr;
        ospf_message    *msg;
        // get the OSPF message header
        b = tw_event_memory_get(lp);
        if(!b)
                tw_error(TW_LOC, "No membuf on event!");
        msg = tw_memory_data(b);
        nbr = ospf_int_getinterface(state, rn_msg->src);
        if(!nbr)
                nbr = msg->data;
        if(rn_msg->type != TIMER && rn_getas(state->m) != rn_getas(nbr->m))
                printf("Got event from nbr outside my AS! \n");
/*
        //printf("%d: got message  %d at %g\n", lp->id, rn_msg->src, tw_now(lp));
        if(g_route[gr1] == lp->id)
        {
                gr1++;
                g_route[gr1] = state->from;
        }
        if(g_route1[gr2] == lp->id)
        {
                gr2++;
                g_route1[gr2] = state->from1;
        }
*/
        if(rn_msg->port != 23)
                tw_error(TW_LOC, "%ld: recv non-ospf message from %d!", lp->id, nbr->id);
        switch (msg->type)
        {
        case OSPF_HELLO_MSG:
#if VERIFY_HELLO || 1
        if(1 == lp->id)
                printf("%lld OSPF: recv HELLO_MSG (%ld) from %lld, ts %f\n",
                        lp->id, (long int) lp->pe->cur_event, rn_msg->src, tw_now(lp));
#endif
                ospf_hello_packet(state, nbr, msg->data, bf, lp);
                state->stats->s_e_hello_in++;
                break;
        case OSPF_HELLO_SEND:
#if VERIFY_HELLO || 1
        if(1 == lp->id)
                printf("%lld OSPF: recv HELLO_SEND timer from %lld, ts %lf \n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                ospf_hello_send(state, nbr, bf, lp);
                break;
        case OSPF_DD_MSG:
#if VERIFY_DD || 1
        if(1 == lp->id)
                printf("\n%lld OSPF: got DD packet from %lld\n", lp->id, rn_msg->src);
#endif
                ospf_dd_event_handler(state, nbr, bf, lp);
                state->stats->s_e_dd_msgs++;
                break;
        case OSPF_LS_REQUEST:
#if VERIFY_LS || 1
        if(1 == lp->id)
                printf("\n%lld: got LS_Request from %lld at %f\n",
                        lp->id, rn_msg->src, tw_now(lp));
#endif
                ospf_ls_request_recv(state, bf, nbr, lp);
                state->stats->s_e_ls_requests++;
                break;
        case OSPF_LS_UPDATE:
#if VERIFY_LS || 1
        if(1 == lp->id)
                printf("\n%lld: got LS Update from %lld at %f\n",
                        lp->id, rn_msg->src, tw_now(lp));
#endif
                ospf_ls_update_recv(state, bf, nbr, lp);
                state->stats->s_e_ls_updates++;
                break;
        case OSPF_FLOOD_TIMEOUT:
                tw_error(TW_LOC, "Should not be here!!");
                //ospf_flood_recv(state, nbr, bf, lp);
                break;
        case OSPF_LS_ACK:
#if VERIFY_LS || 1
        if(1 == lp->id)
                printf("\n%lld: got LS_ACK from %lld %f\n",
                                lp->id, rn_msg->src, tw_now(lp));
#endif
                ospf_ack_process(nbr, bf, lp);
                state->stats->s_e_ls_acks++;
                break;
        case OSPF_AGING_TIMER:
#if VERIFY_AGING || 1
        if(1 == lp->id)
                printf("%lld: got AGING_TIMER at %f\n", lp->id, tw_now(lp));
#endif
                ospf_aging_timer(state, bf, lp);
                state->stats->s_e_aging_timeouts++;
                break;
        case OSPF_RT_TIMER:
#if 1
                printf("\n%lld: rt timer fired! \n", lp->id);
#endif
                tw_event_memory_get(lp);
                ospf_rt_timer(state, lp->id);
                break;
        case OSPF_RETRANS_TIMEOUT:
#if VERIFY_DD || 1
        if(1 == lp->id)
                printf("%lld: got RETRANS_TIMEOUT\n", lp->id);
#endif
                tw_error(TW_LOC, "should not be here!");
                ospf_dd_retransmit(state, nbr, bf, lp);
                break;
        case OSPF_ACK_TIMEOUT:
#if VERIFY_LS || 1
        if(1 == lp->id)
                printf("%lld: got Ack Timer \n", lp->id);
#endif
                ospf_ack_timed_out(nbr, bf, lp);
                state->stats->s_e_ack_timeouts++;
                break;
        case OSPF_HELLO_TIMEOUT:
#if VERIFY_HELLO || 1
        if(1 == lp->id)
                printf("%lld: recv HELLO_TIMEOUT for nbr %d, ts %lf \n",
                                                lp->id, nbr->id, tw_now(lp));
#endif
                state->stats->s_e_hello_timeouts++;
                ospf_nbr_event_handler(state, nbr,
                                        ospf_nbr_inactivity_timer_ev, lp);
                break;
        case OSPF_WEIGHT_CHANGE:
#if VERIFY_OSPF_EXPERIMENT
                printf("%lld: recv WEIGHT CHANGE for link %ld, ts %lf \n",
                        lp->id, (long int) msg->data, tw_now(lp));
#endif
                ospf_experiment_weights(state, (long int) msg->data, lp);
                break;
        default:
                tw_error(TW_LOC, "%lld: Invalid packet type: %d at %f",
                                 lp->id, msg->type, tw_now(lp));
        }
        // Free the OSPF message header membuf
        tw_memory_free(lp, b, g_ospf_fd);
        if(lp->pe->cur_event->memory)
                tw_error(TW_LOC, "Left memory buffer on event!");
}
tw_event* ospf_event_new (ospf_state * , tw_lp * , tw_stime , tw_lp *)
Definition at line 4 of file ospf-util.c.
References DOWNSTREAM, and rn_event_new().
Referenced by dd_exchange(), ospf_ack_direct(), ospf_ack_timed_out(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_h_send(), ospf_ip_route(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_start_flood(), ospf_nbr_neg_done(), ospf_nbr_two_way_recv(), and process_lsa_recv().
{
        tw_event       *event = NULL;
        event = rn_event_new(dest->gid, ts, src, DOWNSTREAM, 0);
        if(src->pe->abort_event)
        {
                state->stats->s_sent_lost++;
#if VERIFY_HELLO
                printf("%ld OSPF: Dropped event to dst %lld \n",
                           src->id, dest->gid);
#endif
        }
        return event;
}
tw_event* ospf_event_send (ospf_state * state, tw_event * event, int type, tw_lp * , int size, tw_memory * mem, int area)
Definition at line 24 of file ospf-util.c.
References g_ospf_fd, OSPF_HEADER, rn_event_send(), and rn_message_setsize().
Referenced by dd_exchange(), ospf_ack_direct(), ospf_ack_timed_out(), ospf_dd_event_handler(), ospf_dd_retransmit(), ospf_h_send(), ospf_ip_route(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_start_flood(), ospf_nbr_neg_done(), ospf_nbr_two_way_recv(), and process_lsa_recv().
{
        tw_memory       *b;
        ospf_message   *msg;
        // packet data
        if(mem)
                tw_event_memory_set(event, mem, g_ospf_fd);
        // packet header
        b = tw_memory_alloc(src, g_ospf_fd);
        msg = tw_memory_data(b);
        msg->type = type;
        msg->area = 0;
        tw_event_memory_set(event, b, g_ospf_fd);
        rn_message_setsize(tw_event_data(event), size + OSPF_HEADER);
        rn_event_send(event);
#if VERIFY_HELLO
        printf("%ld OSPF: sent type %d, dst %ld, ts = %lf \n",
                   src->id, type, event->dest_lp->id, event->recv_ts);
#endif
        switch (type)
        {
                case OSPF_HELLO_MSG:
                        state->stats->s_sent_hellos++;
                        break;
                case OSPF_DD_MSG:
                        state->stats->s_sent_dds++;
                        break;
                case OSPF_LS_REQUEST:
                        state->stats->s_sent_ls_requests++;
                        break;
                case OSPF_LS_UPDATE:
                        state->stats->s_sent_ls_updates++;
                        break;
                case OSPF_LS_ACK:
                        state->stats->s_sent_ls_acks++;
                        break;
                default:
                        state->stats->s_sent_unknown++;
        }
        return event;
}
void ospf_experiment_weights (ospf_state * state, long int i, tw_lp * lp)
Definition at line 41 of file ospf-experiments.c.
References g_ospf_link_weight, ospf_lsa_find(), ospf_lsa_refresh(), and ospf_rt_build().
Referenced by ospf_event_handler().
{
        ospf_db_entry   *dbe;
        int              metric;
        int              low;
        int              high;
        low = 50 - g_ospf_link_weight;
        high = 50 + g_ospf_link_weight;
        if(low <= 0)
                low = 1;
        metric = tw_rand_integer(lp->rng, low, high);
        if(metric == state->m->link[i].cost)
                return;
#if VERIFY_OSPF_EXPERIMENT
        printf("%ld: updating link %ld-%d metric: %d -> %d \n",
                lp->id, state->m->id, state->m->link[i].addr,
                state->m->link[i].cost, metric);
#endif
        state->m->link[i].cost = metric;
        dbe = &state->db[lp->id - state->ar->low];
        dbe->lsa = ospf_lsa_find(state, NULL, lp->id - state->ar->low, lp);
        dbe->cause_ospf = 1;
        dbe->cause_bgp = 0;
        ospf_rt_build(state, lp->id);
        ospf_lsa_refresh(state, dbe, lp);
        dbe->cause_ospf = 0;
}
ospf_nbr* ospf_get_neighbor (ospf_state * state, int id)
Definition at line 94 of file ospf-neighbor.c.
{
        int i;
        for(i = 0; i < state->n_interfaces; i++)
                if(id == state->nbr[i].id)
                        return &state->nbr[i];
        tw_error(TW_LOC, "Unable to find neighbor %d!!", id);
        return NULL;
}
ospf_nbr* ospf_getnbr (ospf_state * state, int id)
Definition at line 4 of file ospf-neighbor.c.
Referenced by lsa_create(), and ospf_lsa_find().
{
        int      i;
        for(i = 0; i < state->n_interfaces; i++)
                if(state->nbr[i].id == id)
                        return &state->nbr[i];
        //tw_error(TW_LOC, "Unable to find neighbor!");
        return NULL;
}
void ospf_hello_packet (ospf_state * , ospf_nbr * , ospf_hello * , tw_bf * , tw_lp *)
Definition at line 115 of file ospf-hello.c.
References g_ospf_fd, ospf_interface_event_handler(), and ospf_nbr_event_handler().
Referenced by ospf_event_handler().
{
        tw_memory       *b;
        ospf_message    *m;
        int              i;
        int              priority;
        if(NULL == nbr)
        {
                tw_error(TW_LOC, "Do not have nbr!");
                state->stats->s_drop_hello_int++;
                bf->c1 = 1;
#if VERIFY_HELLO
                printf("%ld: Dropping nbr HELLO since I have no state for it! "
                        "(%f)\n", lp->id, tw_now(lp));
#endif
                return;
        }
        b = tw_event_memory_get(lp);
        m = tw_memory_data(b);
        r = m->data;
        if(!r)
                tw_error(TW_LOC, "Unable to read HELLO message!");
        /*
         * Check the packet integrity
         */
        if (r->hello_interval != state->gstate->hello_sendnext)
        {
                state->stats->s_drop_hello_int++;
                bf->c1 = 1;
#if VERIFY_HELLO
                printf("%ld: dropped hello due to hello interval! %g != %g \n",
                                lp->id, r->hello_interval,
                                state->gstate->hello_sendnext);
#endif
                return;
        }
        if (r->poll_interval != state->gstate->poll_interval)
        {
                state->stats->s_drop_poll_int++;
                bf->c2 = 1;
                tw_memory_free(lp, b, g_ospf_fd);
#if VERIFY_HELLO
                printf("%ld: dropped hello due to poll interval! %g != %g \n",
                                lp->id, r->poll_interval, state->gstate->poll_interval);
#endif
                return;
        }
        nbr->priority = r->priority;
        nbr->designated_r = r->designated_r;
        nbr->b_designated_r = r->b_designated_r;
        ospf_nbr_event_handler(state, nbr, ospf_nbr_hello_recv_ev, lp);
        /*
         * If I am in the list of neighbors of the sending router,
         * then send a two_way_recv event
         */
        for (i = r->offset; i < r->end; i++)
        {
                if(r->neighbors[i] == lp->id)
                {
#if VERIFY_HELLO && 0
                        printf("%d: found myself in HELLO message! \n", lp->id);
#endif
                        priority = nbr->priority;
                        ospf_nbr_event_handler(state, nbr, ospf_nbr_two_way_recv_ev, lp);
                        if (priority != nbr->priority)
                                ospf_interface_event_handler(nbr, ospf_int_nbrchange_ev, lp);
                        if (r->designated_r == nbr->id &&
                                r->b_designated_r == 0xffffffff &&
                                nbr->istate == ospf_int_waiting_st)
{
                                ospf_interface_event_handler(nbr, ospf_int_backupseen_ev, lp);
                        } else
{
/*
            Otherwise, if the
            neighbor is declaring itself to be Designated Router and it
            had not previously, or the neighbor is not declaring itself
            Designated Router where it had previously, the receiving
            interface's state machine is scheduled with the event
            NeighborChange.
*/
                                if((r->designated_r == nbr->id &&
                                        r->designated_r != state->designated_r) ||
                                   (r->designated_r != nbr->id &&
                                        r->designated_r == state->designated_r))
{
                                        ospf_interface_event_handler(nbr,
                                                        ospf_int_nbrchange_ev, lp);
                                }
                        }
                        if (r->b_designated_r == nbr->id &&
                                nbr->istate == ospf_int_waiting_st)
{
                                ospf_interface_event_handler(nbr, ospf_int_backupseen_ev, lp);
                        } else
{
/*
            Otherwise, if the
            neighbor is declaring itself to be Backup Designated Router and it
            had not previously, or the neighbor is not declaring itself Backup
            Designated Router where it had previously, the receiving
            interface's state machine is scheduled with the event
            NeighborChange.
*/
                                if((r->b_designated_r == nbr->id &&
                                        r->b_designated_r != state->b_designated_r) ||
                                   (r->b_designated_r != nbr->id &&
                                        r->b_designated_r == state->b_designated_r))
{
                                        ospf_interface_event_handler(nbr,
                                                        ospf_int_nbrchange_ev, lp);
                                }
                        }
                        tw_memory_free(lp, b, g_ospf_fd);
                        return;
                }
        }
        /*
         * Start one-way event with neighbor which sent this message
         */
        ospf_nbr_event_handler(state, nbr, ospf_nbr_one_way_ev, lp);
        tw_memory_free(lp, b, g_ospf_fd);
}
void ospf_hello_send (ospf_state * state, ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 101 of file ospf-hello.c.
References ospf_h_send(), and ospf_timer_start().
Referenced by ospf_event_handler().
{
        nbr->hello_timer = ospf_timer_start(nbr, nbr->hello_timer,
                                            nbr->hello_interval,
                                            OSPF_HELLO_SEND, lp);
        if(nbr->istate >= ospf_int_loopback_st)
                ospf_h_send(state, nbr, lp, tw_getlp(nbr->id));
}
ospf_nbr* ospf_int_getinterface (ospf_state * state, int id)
Definition at line 16 of file ospf-router.c.
Referenced by ospf_event_handler(), and ospf_rc_event_handler().
{
        int     i;
        for (i=0; i < state->n_interfaces; i++)
        {
                if (state->nbr[i].id == id)
                        return &state->nbr[i];
        }
        return NULL;
}
void ospf_interface_event_handler (ospf_nbr * nbr, ospf_int_event event, tw_lp * lp)
Definition at line 348 of file ospf-interface.c.
References ospf_interface_backupseen(), ospf_interface_down(), ospf_interface_nbrchange(), ospf_interface_unloopind(), ospf_interface_up(), and ospf_interface_waittimer().
Referenced by ospf_hello_packet().
{
        switch(event)
        {
                case ospf_int_up_ev:
                        if(nbr->istate == ospf_int_down_st)
                                ospf_interface_up(nbr, lp);
                        break;
                case ospf_int_waittimer_ev:
                        if(nbr->istate == ospf_int_waiting_st)
                                ospf_interface_waittimer(nbr, lp);
                        break;
                case ospf_int_backupseen_ev:
                        if(nbr->istate == ospf_int_waiting_st)
                                ospf_interface_backupseen(nbr, lp);
                        break;
                case ospf_int_nbrchange_ev:
                        if(nbr->istate == ospf_int_dr_other_st ||
                           nbr->istate == ospf_int_backup_st ||
                           nbr->istate == ospf_int_dr_st)
                                ospf_interface_nbrchange(nbr, lp);
                        break;
                case ospf_int_loopind_ev:
                        ospf_interface_down(nbr, lp);
                        nbr->istate = ospf_int_loopback_st;
                        break;
                case ospf_int_unloopind_ev:
                        if(nbr->istate == ospf_int_loopback_st)
                                ospf_interface_unloopind(nbr, lp);
                        break;
                case ospf_int_down_ev:
                        ospf_interface_down(nbr, lp);
                        break;
                default:
                        tw_error(TW_LOC, "Unknown interface event: %d", event);
        }
}
void ospf_ip_route (ospf_state * state, tw_bf * bf, rn_message * rn_msg, tw_lp * lp)
Definition at line 5 of file ospf-ip.c.
References c_host, d, g_rn_nrouters, ospf_event_new(), ospf_event_send(), rn_event_data(), rn_getmachine(), rn_message_data(), rn_message_getsize(), and rn_route().
{
        tw_event        *e;
/*
        rn_message      *m;
        ospf_message    *ospf;
        ospf_message    *msg;
        tcp_message     *tcp_in;
        tcp_message     *tcp_out;
*/
        unsigned int     dest;
        unsigned int     d;
        tw_error(TW_LOC, "Should not be getting IP packets.. ");
        //msg = rn_message_data(rn_msg);
#if PLEASE_FIX_ME
        d = (rn_msg->final_dest / 1) - (g_rn_nrouters / 1) + (g_rn_nrouters - g_rn_npops);
#endif
        dest = rn_route(state->m, d);
        if(0 && dest == 0xff || dest == -1)
        {
#if PLEASE_FIX_ME
                dest = rn_msg->final_dest;
#endif
                e = ospf_event_new(state, tw_getlp(dest), lp);
                // I think this size is correct, probably not though
                tw_printf(TW_LOC, "Check OSPF ip pkt size! \n");
                ospf_event_send(state, e, OSPF_IP, lp,
                                rn_message_getsize(tw_event_data(lp->cur_event)),
                                NULL, state->area);
/*
                e = ospf_event_send(state, tw_getlp(dest),
                                OSPF_IP, lp, LINK_TIME, NULL, state->area);
*/
#if 0
                tcp_in = ospf_util_data(msg);
                tcp = rn_event_data(e);
                tcp->MethodName = tcp_in->MethodName;
                tcp->ack = tcp_in->ack;
                tcp->source = tcp_in->source;
                tcp->dest = tcp_in->dest;
                tcp->seq_num = tcp_in->seq_num;
#endif
#if 0
                if(rn_msg->final_dest == 1010)
                {
                        printf("%d: tcp_in src = %d, tcp_in dst = %f\n",
                                lp->id,
                                tcp_in->source,
                                tcp_in->dest);
                        printf("%d: tcp src = %d, tcp dst = %f\n",
                                lp->id,
                                tcp->source,
                                tcp->dest);
                        printf("%d: %d \n", lp->id, rn_msg->final_dest);
                }
#endif
                return;
        } else
        {
                dest = state->nbr[dest].id;
        }
        // transfer all membufs from inbound IP to outbound
        e->memory = lp->cur_event->memory;
        lp->cur_event->memory = NULL;
        e = ospf_event_new(state, tw_getlp(dest), lp);
        tw_printf(TW_LOC, "Check my OSPF ip pkt size 2! \n");
        e = ospf_event_send(state, e, OSPF_IP, lp,
                                rn_message_getsize(tw_event_data(lp->cur_event)),
                                NULL, state->area);
#if 0
        m = tw_event_data(e);
        if(rn_getmachine(rn_msg->src)->type == c_host)
                tcp_in = rn_message_data(rn_msg);
        else
                tcp_in = ospf_util_data(msg);
        tcp = ospf_util_data(rn_message_data(m));
        tcp->MethodName = tcp_in->MethodName;
        tcp->ack = tcp_in->ack;
        tcp->source = tcp_in->source;
        tcp->dest = tcp_in->dest;
        tcp->seq_num = tcp_in->seq_num;
#endif
#if 0
        if(rn_msg->final_dest == 1010)
        {
                printf("%d: tcp_in src = %d, tcp_in dst = %f\n",
                                lp->id, tcp_in->source, tcp_in->dest);
                printf("%d: tcp src = %d, tcp dst = %f\n",
                                lp->id, tcp->source, tcp->dest);
        }
#endif
        return;
}
int ospf_list_contains (char * list, int index)
Definition at line 22 of file ospf-neighbor-list.c.
Referenced by ls_update_process(), and process_lsa_recv().
{
        if(list[index] == 1)
                return TW_TRUE;
        return TW_FALSE;
}
void ospf_list_free (char * list, unsigned int * size)
Definition at line 4 of file ospf-neighbor-list.c.
{
        int     i;
        for(i = 0; i < *size; i++)
                list[i] = 0;
        *size = 0;
}
void ospf_list_link (char * list, int index, unsigned int * size)
Definition at line 31 of file ospf-neighbor-list.c.
{
        list[index] = 1;
        (*size)++;
}
void ospf_list_unlink (char * list, int index, unsigned int * size)
Definition at line 15 of file ospf-neighbor-list.c.
Referenced by ls_update_process().
{
        list[index] = 0;
        (*size)--;
}
void ospf_ls_request (ospf_state * state, ospf_nbr * nbr, tw_lp * lp)
Definition at line 335 of file ospf-ls.c.
References g_ospf_fd, getlsa(), ospf_event_new(), ospf_event_send(), OSPF_HEADER, ospf_lsa_age(), OSPF_LSA_UPDATE_HEADER, OSPF_RETRANS_INTERVAL, and ospf_timer_start().
Referenced by ospf_nbr_exchange_done().
{
        tw_event        *e;
        tw_memory       *b;
        ospf_db_entry   *dbe;
        ospf_db_entry   *out_dbe;
        ospf_lsa        *lsa;
        int      accum;
        int      i;
        if(0 == nbr->nrequests)
                return;
        e = ospf_event_new(state, tw_getlp(nbr->id), 0.0, lp);
        accum = state->gstate->mtu - OSPF_HEADER;
        for(i = 0; accum >= OSPF_LSA_UPDATE_HEADER && i < state->ar->nmachines; i++)
        {
                if(!nbr->requests[i])
                        continue;
                printf("%lld: Adding LSA %d to LS_REQUEST \n", lp->id, i);
                accum -= OSPF_LSA_UPDATE_HEADER;
                dbe = &nbr->router->db[i];
                lsa = getlsa(state->m, dbe->lsa, i);
                b = tw_memory_alloc(lp, g_ospf_fd);
                out_dbe = tw_memory_data(b);
                out_dbe->lsa = dbe->lsa;
                out_dbe->b.age = ospf_lsa_age(nbr->router, dbe, lp);
                out_dbe->b.entry = dbe->b.entry;
                tw_event_memory_setfifo(e, b, g_ospf_fd);
        }
        ospf_event_send(nbr->router, e, OSPF_LS_REQUEST, lp,
                        state->gstate->mtu - accum - OSPF_HEADER,
                        NULL, nbr->router->ar->id);
        printf("%lld: sent LS_REQUEST to %d, ts %lf \n",
                lp->id, nbr->id, e->recv_ts);
        // cannot remember how I was going to eliminate this timer.
        //nbr->next_retransmit = tw_now(lp) + OSPF_RETRANS_TIMEOUT;
        nbr->retrans_timer = ospf_timer_start(nbr,
                                nbr->retrans_timer, OSPF_RETRANS_INTERVAL,
                                OSPF_RETRANS_TIMEOUT, lp);
        if(nbr->retrans_timer)
                printf("%lld: Setting retransmit timer for %d at %lf \n",
                        lp->id, nbr->id, nbr->retrans_timer->recv_ts);
}
void ospf_ls_request_recv (ospf_state * , tw_bf * , ospf_nbr * , tw_lp *)
Definition at line 4 of file ospf-ls-request.c.
References g_ospf_fd, getlsa(), ospf_event_new(), ospf_event_send(), OSPF_HEADER, and ospf_lsa_age().
Referenced by ospf_event_handler().
{
        tw_stime         ts;
        ospf_db_entry   *dbe;
        ospf_db_entry   *in_dbe;
        ospf_db_entry   *out_dbe;
        ospf_lsa        *lsa;
        tw_memory               *buf;
        tw_memory               *recv;
        tw_memory               *send;
        int              accum;
        if(nbr->state < ospf_nbr_exchange_st)
                return;
        send = buf = NULL;
        accum = OSPF_HEADER;
        recv = tw_event_memory_get(lp);
        dbe = NULL;
        ts = 0;
        while(recv)
        {
                in_dbe = tw_memory_data(recv);
                lsa = getlsa(in_dbe->lsa, nbr->id);
                dbe = &state->db[lsa->adv_r];
                //dbe = &state->db[request->lsa[i].lsa->adv_r];
                accum +=  lsa->length;
                if(accum > state->gstate->mtu || recv->next == NULL)
                {
                        ts += LINK_TIME;
                        ospf_event_send(state,
                                        tw_getlp(nbr->id),
                                        OSPF_LS_UPDATE,
                                        lp,
                                        ts,
                                        send,
                                        nbr->router->area);
                        accum = OSPF_HEADER;
                        send = NULL;
                }
                if(NULL == send)
                        send = buf = tw_memory_alloc(lp, g_ospf_fd);
                else
                        buf->next = tw_memory_alloc(lp, g_ospf_fd);
                out_dbe = buf->data;
                out_dbe->lsa = dbe->lsa;
                out_dbe->b.age = ospf_lsa_age(state, dbe, lp);
                printf("Sending LSA ages: old %d, new %d \n", dbe->b.age,
                                        out_dbe->b.age);
                buf = buf->next;
                tw_memory_free(lp, recv, g_ospf_fd);
                recv = tw_event_memory_get(lp);
        }
}
void ospf_ls_update_recv (ospf_state * , tw_bf * , ospf_nbr * , tw_lp *)
Definition at line 274 of file ospf-ls.c.
References g_ospf_fd, ls_update_process(), ospf_lsa_find(), and process_lsa_recv().
Referenced by ospf_event_handler().
{
        tw_memory       *b;
        ospf_db_entry   *dbe;
        if(nbr->state == ospf_nbr_exchange_st || nbr->state == ospf_nbr_loading_st)
        {
                ls_update_process(state, nbr, lp);
                return;
        }
        if (nbr->state != ospf_nbr_full_st)
        {
                printf("%lld: dropping LS update, nbr is %d (down=%d) \n",
                        lp->id, nbr->state, ospf_nbr_down_st);
                while(NULL != (b = tw_event_memory_get(lp)))
                        tw_memory_free(lp, b, g_ospf_fd);
                return;
                //tw_error(TW_LOC, "Unhandled neigbor state!");
        }
        while(NULL != (b = tw_event_memory_get(lp)))
        {
                dbe = tw_memory_data(b);
                // normal flood, LSA correctly set already
                if(state->ar == nbr->ar)
                {
                        //lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                } else
                {
                        // re-point dbe for my AREA
                        dbe->b.entry = dbe->b.entry - nbr->ar->nmachines +
                                                        state->ar->nmachines;
                        dbe->lsa = ospf_lsa_find(state, nbr, dbe->b.entry, lp);
                }
#if VERIFY_LS
                printf("\tprocess LSA %d from nbr %d \n",
                        dbe->b.entry - state->ar->nmachines, nbr->id);
#endif
                process_lsa_recv(state, nbr, dbe, lp);
                tw_memory_free(lp, b, g_ospf_fd);
        }
}
unsigned int ospf_lsa_age (ospf_state * , ospf_db_entry * dbe, tw_lp * lp)
Definition at line 231 of file ospf-lsa.c.
References OSPF_LSA_MAX_AGE, and x.
Referenced by dd_exchange(), ospf_aging_timer_set(), ospf_db_update(), ospf_ls_request(), ospf_ls_request_recv(), ospf_lsa_isnewer(), ospf_lsa_start_flood(), and process_lsa_recv().
{
        int     x;
        if(dbe->b.free || dbe->b.age == OSPF_LSA_MAX_AGE)
                return OSPF_LSA_MAX_AGE;
        if((tw_now(lp) - state->db_last_ts) < 4)
                return dbe->b.age;
        x = (floor((tw_now(lp) - state->db_last_ts) / 4) * 4) + dbe->b.age;
        return (unsigned int) x;
}
tw_memory* ospf_lsa_allocate (tw_lp * lp)
Definition at line 387 of file ospf-lsa.c.
References g_ospf_lsa_fd.
Referenced by bgp_lsa_find(), lsa_create(), and ospf_lsa_find().
{
        tw_memory       *b;
        ospf_lsa        *lsa;
        //tw_printf(TW_LOC, "%d: Allocating a new LSA! \n", lp->id);
        b = tw_memory_alloc(lp, g_ospf_lsa_fd);
        if(!b)
                tw_error(TW_LOC, "Could not dynamically allocate any new LSAs! \n");
        lsa = tw_memory_data(b);
        return  b;
}
ospf_lsa* ospf_lsa_compare (ospf_nbr * n, ospf_lsa * lsa)
void ospf_lsa_create (ospf_state * state, ospf_nbr * , int lsa_index, tw_lp * lp)
Definition at line 527 of file ospf-lsa.c.
References getlsa(), ospf_aging_timer_set(), ospf_db_insert(), ospf_db_remove(), ospf_lsa_equals(), ospf_lsa_find(), ospf_lsa_flood(), OSPF_LSA_MAX_AGE, OSPF_MAX_LSA_SEQNUM, rn_getarea(), rn_getlink(), rn_getmachine(), and rn_route().
Referenced by bgp_ospf_update(), ospf_lsa_flush(), ospf_nbr_exchange_done(), ospf_nbr_inactivity_timer(), and process_lsa_recv().
{
        rn_link *l = NULL;
        ospf_lsa        *old_lsa;
        ospf_lsa        *lsa;
        ospf_db_entry   *dbe;
        int              wrapping = 0;
        int              index;
#if VERIFY_OSPF_CONVERGENCE
        int              i;
#endif
        index = ospf_lsa_find(state, nbr, entry, lp);
        dbe = &state->db[entry];
        lsa = getlsa(state->m, index, entry);
        old_lsa = getlsa(state->m, dbe->lsa, entry);
        // If LSA links drops to zero, flush LSA from network
        if(lsa->links.size == 0)
        {
                if(dbe->b.free || ospf_lsa_equals(old_lsa, lsa) == TW_TRUE)
                        return;
#if VERIFY_LS
                printf("%ld: flushing LSA %d: no links \n",
                        lp->id, lsa->id);
#endif
                dbe->lsa = index;
                ospf_db_remove(state, entry, lp);
                ospf_lsa_flood(state, dbe, nbr->id, lp);
                return;
        }
        // Highest adv_r creates LSAs
        if(old_lsa->adv_r != 0xffffffff &&
           old_lsa->adv_r > lsa->adv_r &&
           rn_getarea(rn_getmachine(old_lsa->adv_r)) != rn_getarea(rn_getmachine(lsa->adv_r)))
                return;
        if(state->lsa_seqnum == OSPF_MAX_LSA_SEQNUM)
        {
                if(state->lsa_wrapping)
                {
                        tw_error(TW_LOC, "Not sure what to do here now!");
                        return;
                } else
                {
                        dbe->seqnum = OSPF_MAX_LSA_SEQNUM;
                        wrapping = 1;
                }
        } else
        {
                if(dbe->b.entry < state->ar->nmachines)
                        dbe->seqnum = ++state->lsa_seqnum;
        }
        dbe->cause_bgp = 0;
        //dbe->cause_ospf = 1;
        //state->stats->s_cause_bgp++;
        if(dbe->b.free || TW_FALSE == ospf_lsa_equals(old_lsa,lsa) ||
           state->lsa_seqnum > OSPF_MAX_LSA_SEQNUM)
        {
                if(!lsa->links.size)
                        tw_error(TW_LOC, "Insert LSA with no links into DB!");
                dbe = ospf_db_insert(state, index, dbe, lp);
                l = rn_getlink(rn_getmachine(lp->id), nbr->id);
#if VERIFY_OSPF_CONVERGENCE
                lsa->count = 0;
                for(i = 0; i < state->ar->nmachines; i++)
                {
                        if(rn_route(state->m, i) == -1)
                                continue;
                        int int_id = state->nbr[rn_route(state->m, i)].id;
                        if(int_id != -1 &&
                                int_id != l->wire->id &&
                                i != lp->id)
{
                                lsa->count++;
                        }
                }
                lsa->start = l->last_status;
                printf("%ld: lsa start time: %f hop count %d \n",
                        lp->id, lsa->start, lsa->count);
#endif
        }
        if (wrapping)
        {
                tw_error(TW_LOC, "I did not expect to be here!");
                /*
                 * Prematurely age the LSA -- have to reset the aging timer
                 * so that this LSA can be handled at the next LSA timer
                 * interval
                 */
                ospf_aging_timer_set(state, &state->db[lsa->id],
                                                        OSPF_LSA_MAX_AGE, lp);
                ospf_lsa_flood(state, dbe, lp->id, lp);
                state->lsa_wrapping = 1;
        } else
        {
                ospf_lsa_flood(state, dbe, nbr->id, lp);
        }
}
int ospf_lsa_find (ospf_state * state, ospf_nbr * , int id, tw_lp * lp)
Definition at line 76 of file ospf-lsa.c.
References g_ospf_ll_fd, ospf_getnbr(), ospf_lsa_allocate(), ospf_lsa_link_allocate(), and rn_getlink().
Referenced by ospf_db_init(), ospf_experiment_weights(), ospf_ls_update_recv(), and ospf_lsa_create().
{
        tw_memory       *b;
        tw_memory       *b1;
        ospf_lsa_link   *ll;
        ospf_lsa        *lsa;
        ospf_nbr        *nbr;
        int              index;
        int              nlinks;
        int              x_id;
        int              i;
        nlinks = 0;
        nbr = NULL;
        if(id < state->ar->nmachines)
                x_id = state->ar->id;
        else if(id < state->ar->nmachines + state->ar->as->nareas)
        {
                x_id = id - state->ar->nmachines + state->ar->as->low;
                if(n->ar->id != x_id)
                        nlinks = 1;
        } else
                x_id = id - state->ar->nmachines - state->ar->as->nareas;
        // Need to get nlinks FIRST, since # LSA links can be < # current
        // go by neighbor states, not topology, unless AS external LSA
        for(i = 0; i < state->n_interfaces; i++)
        {
                nbr = &state->nbr[i];
                if(nbr->state != ospf_nbr_full_st ||
                   nbr->istate != ospf_int_point_to_point_st)
                        continue;
                // If router_lsa, only count links within my area
                if(id < state->ar->nmachines)
                {
                        if(nbr->ar != state->ar)
                                nlinks++;
                } else if(id >= state->ar->nmachines + state->ar->as->nareas)
                {
                        // AS ext LSA, count link if to nbr AS == id's AS
                        // If AS ext LSA, only thing I can do is count the
                        // nbr which sent me the LSA
                        nlinks = 1;
                        break;
                        if(nbr->ar->as->id == x_id)
                                nlinks++;
                } else
                {
/*
                        if(nbr->ar->id == x_id)
{
                                nlinks = 1;
                                break;
                        }
*/
                        // Summary LSA, count link if to nbr Area == id's Area
                        if(nbr->ar->id == x_id)
                                nlinks++;
                }
        }
        b = state->ar->g_ospf_lsa[id];
        lsa = tw_memory_data(b);
        for(index = 0; NULL != lsa; index++)
        {
                if(lsa->links.size == nlinks && lsa->adv_r == lp->id)
                {
                        if(nlinks == 0)
{
                                i = nlinks;
                        } else if(id >= state->ar->nmachines + state->ar->as->nareas)
{
                                ll = tw_memory_data(lsa->links.head);
                                if(n->id == ll->dst)
                                        i = nlinks;
                        } else
{
                                // foreach LSA link: if is up, good, otherwise, not the LSA!
                                b1 = lsa->links.head;
                                for(i = 0; i < lsa->links.size; i++, b1 = b1->next)
{
                                        ll = tw_memory_data(b1);
                                        nbr = ospf_getnbr(state, ll->dst);
                                        if(nbr->state != ospf_nbr_full_st)
                                                break;
                                }
                        }
                        if(i == nlinks)
                                return index;
                }
                if(lsa->next == NULL)
                        break;
                b = lsa->next;
                lsa = tw_memory_data(b);
        }
        if(lsa->next != NULL)
                tw_error(TW_LOC, "Not at end of LSA list!");
        index++;
        lsa->next = ospf_lsa_allocate(lp);
        lsa = tw_memory_data(lsa->next);
        lsa->id = id;
        lsa->adv_r = lp->id;
        if(id < state->ar->nmachines)
        {
                lsa->type = ospf_lsa_router;
                ospf_lsa_link_allocate(state, lsa, lp);
                return index;
        } else if(id < state->ar->nmachines + state->ar->as->nareas)
        {
                lsa->type = ospf_lsa_summary3;
                ospf_lsa_link_allocate(state, lsa, lp);
                // Only add nbr to LSA if it does NOT match x_id, because
                // that is the case where we are originating an LSA for
                // an AS/area more than 1 hop away
                if(n->ar->id == x_id)
                        return index;
        } else
                lsa->type = ospf_lsa_as_ext;
        b = tw_memory_alloc(lp, g_ospf_ll_fd);
        tw_memoryq_push(&lsa->links, b);
        ll = tw_memory_data(b);
        ll->dst = n->id;
        ll->metric = rn_getlink(state->m, n->id)->cost;
/*
        printf("%ld: Creating LSA: %d, advr %d, %lf \n",
                lp->id, lsa->id, lsa->adv_r, lp->cur_event->recv_ts);
*/
        return index;
}
void ospf_lsa_flood (ospf_state * s, ospf_db_entry * d, int f, tw_lp * lp)
Definition at line 731 of file ospf-lsa.c.
References getlsa(), ospf_lsa_print(), and ospf_lsa_start_flood().
Referenced by ospf_aging_timer(), ospf_lsa_create(), ospf_lsa_flush(), ospf_lsa_refresh(), and process_lsa_recv().
{
        ospf_nbr *nbr;
        int       i;
        for (i = 0; i < state->n_interfaces; i++)
        {
                nbr = &state->nbr[i];
                if (nbr->state < ospf_nbr_exchange_st)
                        continue;
                /* Don't send it to myself, or the neighbor who sent it to me */
                if ((from != -1 || from != lp->id) && nbr->id == from)
                        continue;
                /* Don't send router LSAs to neighbors in other areas */
                if(state->ar != nbr->ar && dbe->b.entry < state->ar->nmachines)
                        continue;
                /* Don't send LSAs to neighbors in other ASes, ever */
                if(state->ar->as != nbr->ar->as)
                        continue;
                // Don't send LSA for nbr's area to nbr
                if(nbr->ar->id == dbe->b.entry - state->ar->nmachines)
                        continue;
                // Don't send my area LSA to nbr, should already have it!
                if(state->ar->id == dbe->b.entry - state->ar->nmachines)
                        continue;
                if(nbr->state == ospf_nbr_exchange_st ||
                   nbr->state == ospf_nbr_loading_st)
                {
/*
Here we are not supposed to start flooding if the LSA in the request list
is newer than this one..
 This case shouldn't really come up, where the outstanding LSA is newer
 than the one we want to flood..
                        if(dbe->state.b.updated =
                                continue;
*/
                        tw_error(TW_LOC, "Unhandled ospf flooding case!");
                }
#if VERIFY_LS
                printf("\t\tstarting flood LSA %d to %d: \n", dbe->b.entry, nbr->id);
                printf("\t\t\tsn: %d ", dbe->seqnum);
                ospf_lsa_print(state->log, getlsa(state->m, dbe->lsa, dbe->b.entry));
#endif
                ospf_lsa_start_flood(nbr, dbe, lp);
        }
}
void ospf_lsa_flush (ospf_state * , ospf_nbr * , ospf_db_entry * , tw_lp *)
Definition at line 850 of file ospf-lsa.c.
References g_ospf_fd, getlsa(), ospf_ack_direct(), ospf_db_remove(), ospf_lsa_create(), ospf_lsa_flood(), and OSPF_LSA_MAX_AGE.
Referenced by ospf_nbr_reset(), and process_lsa_recv().
{
        tw_memory       *send;
        ospf_lsa        *r_lsa;
        ospf_db_entry   *dbe;
        ospf_db_entry   *out_dbe;
        int              originator;
        int              x_id = -1;
        int              i = -1;
        dbe = &state->db[r_dbe->b.entry];
        r_lsa = getlsa(state->m, r_dbe->lsa, r_dbe->b.entry);
        originator = 0;
        if(r_lsa->adv_r == lp->id)
        {
                if(r_lsa->type == ospf_lsa_router)
                {
                        originator = 1;
                } else if(r_lsa->type == ospf_lsa_summary3)
                {
                        x_id = r_dbe->b.entry - state->ar->nmachines;
                        for(i = 0; i < state->n_interfaces; i++)
{
                                if(state->nbr[i].ar->id == x_id &&
                                   state->nbr[i].state == ospf_nbr_full_st)
{
                                        originator = i;
                                        break;
                                }
                        }
                }
                // if AS ext, do nothing, we do not originate them ever,
                // the BGP layer/model does
        }
        if(-1 == originator)
        {
                if(dbe->b.free)
                        return;
#if VERIFY_LS
                printf("\tflushing LSA %d \n", r_dbe->b.entry);
#endif
                r_dbe->b.age--;
                ospf_db_remove(state, dbe->b.entry, lp);
                ospf_lsa_flood(state, r_dbe, nbr->id, lp);
                send = tw_memory_alloc(lp, g_ospf_fd);
                out_dbe = tw_memory_data(send);
                out_dbe->lsa = r_dbe->lsa;
                out_dbe->b.age = OSPF_LSA_MAX_AGE;
                out_dbe->b.entry = r_dbe->b.entry;
                ospf_ack_direct(nbr, send, r_lsa->length, lp);
        } else
                ospf_lsa_create(state, &state->nbr[originator], r_dbe->b.entry, lp);
}
int ospf_lsa_isnewer (ospf_state * , ospf_db_entry * , ospf_db_entry * , tw_lp *)
Definition at line 793 of file ospf-lsa.c.
References ospf_lsa_age(), OSPF_LSA_MAX_AGE, and OSPF_LSA_MAX_AGE_DIFF.
Referenced by dd_process(), and process_lsa_recv().
{
        unsigned int old_age;
        old_age = ospf_lsa_age(state, old, lp);
        if(old->b.free || old_age == OSPF_LSA_MAX_AGE)
        {
#if VERIFY_LS
        printf("\tis_newer: old NONE new (%d %d)\n", new->b.age, new->seqnum);
#endif
                return 1;
        }
#if VERIFY_LS
        printf("\tis_newer: old (%d %d) new (%d %d)\n",
                        old_age, old->seqnum, new->b.age, new->seqnum);
#endif
        /*
         * Make sure we are in the right packet sequence
         */
        if(new->seqnum > old->seqnum)
        {
                return 1;
        } else if (old->seqnum > new->seqnum)
        {
                return -1;
        } else
        {
                // I am going into my old age writing this function..
                if(new->b.age == OSPF_LSA_MAX_AGE && old_age != OSPF_LSA_MAX_AGE)
                {
                        return 1;
                } else if(old_age == OSPF_LSA_MAX_AGE &&
                        new->b.age != OSPF_LSA_MAX_AGE)
                {
                        return -1;
                } else
                {
                        if(abs(old_age - new->b.age) > OSPF_LSA_MAX_AGE_DIFF)
{
                                if (new->b.age < old_age)
                                        return 1;
                                else
                                        return -1;
                        }
                }
        }
        return 0;
}
void ospf_lsa_link_allocate (ospf_state * state, ospf_lsa * lsa, tw_lp * lp)
Definition at line 406 of file ospf-lsa.c.
References g_ospf_ll_fd, OSPF_LSA_LINK_LENGTH, and OSPF_LSA_UPDATE_HEADER.
Referenced by lsa_create(), and ospf_lsa_find().
{
        tw_memory       *b;
        ospf_lsa_link   *l;
        ospf_nbr        *nbr;
        int              add;
        int              x_id;
        int              i;
#if VERIFY_OSPF_CONVERGENCE
        lsa->count = state->ar->nmachines;
#endif
        if(lsa->id < state->ar->nmachines)
                x_id = lsa->id;
        else if(lsa->id > state->ar->nmachines + state->ar->as->nareas)
                x_id = lsa->id - state->ar->nmachines - state->ar->as->nareas;
        else
                x_id = lsa->id - state->ar->nmachines + state->ar->as->low;
        // go by neighbor states, not topology, unless AS external LSA
        for(i = 0; i < state->n_interfaces; i++)
        {
                nbr = &state->nbr[i];
                if(nbr->state != ospf_nbr_full_st ||
                   nbr->istate != ospf_int_point_to_point_st)
                        continue;
                add = 0;
                // If router_lsa, only count links within my area
                if(lsa->id < state->ar->nmachines)
                {
                        // router LSA, count if nbr area == my area
                        if(nbr->ar == state->ar)
{
                                b = tw_memory_alloc(lp, g_ospf_ll_fd);
                                tw_memoryq_push(&lsa->links, b);
                                l = tw_memory_data(b);
                                l->dst = nbr->id;
                                l->metric = state->m->link[i].cost;
                        }
                } else
                {
                        // summary LSA, count if nbr area == LSA area
                        if(nbr->ar->id == x_id)
{
                                b = tw_memory_alloc(lp, g_ospf_ll_fd);
                                tw_memoryq_push(&lsa->links, b);
                                l = tw_memory_data(b);
                                l->dst = nbr->id;
                                l->metric = state->m->link[i].cost;
                        }
                }
        }
        lsa->length = OSPF_LSA_UPDATE_HEADER +
                        (lsa->links.size * OSPF_LSA_LINK_LENGTH);
}
void ospf_lsa_premature_age (ospf_state * state, ospf_db_entry * , tw_lp * lp)
void ospf_lsa_print (FILE * log, ospf_lsa * lsa)
Definition at line 4 of file ospf-lsa.c.
Referenced by flood_summary(), main_setup_areas(), ospf_db_print(), ospf_db_read(), ospf_lsa_flood(), and ospf_statistics_collection().
{
#if OSPF_LOG && 0
        tw_memory       *b;
        ospf_lsa_link   *l;
/*
        fprintf(log,
                "adv: %d id: %d nlinks: %d ",
                lsa->adv_r, lsa->id, lsa->links.size);
*/
        fprintf(log, "%-10d %-10d %-5d ",
                lsa->id, lsa->adv_r, lsa->links.size);
        for(b = lsa->links.head; b; b = b->next)
        {
                l = tw_memory_data(b);
                fprintf(log, "%d %d ", l->dst, l->metric);
        }
        fprintf(log, "\n");
#endif
}
void ospf_lsa_process (ospf_state * state, ospf_message * m, int interface)
void ospf_lsa_refresh (ospf_state * state, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 481 of file ospf-lsa.c.
References getlsa(), ospf_aging_timer_set(), ospf_lsa_flood(), OSPF_LSA_MAX_AGE, and OSPF_MAX_LSA_SEQNUM.
Referenced by ospf_aging_timer(), and ospf_experiment_weights().
{
        int             wrapping = 0;
        ospf_db_entry    temp_dbe;
        ospf_lsa        *lsa;
        lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
        if (state->lsa_seqnum == OSPF_MAX_LSA_SEQNUM)
        {
                if(state->lsa_wrapping)
                {
                        dbe->b.free = 1;
                } else
                {
                        dbe->seqnum = OSPF_MAX_LSA_SEQNUM;
                        wrapping = 1;
                        // Prematurely age the LSA
                        ospf_aging_timer_set(state, &state->db[lsa->id],
                                                        OSPF_LSA_MAX_AGE, lp);
                        /* Make a copy for flooding with the correct AGE */
                        temp_dbe.b = dbe->b;
                        temp_dbe.lsa = dbe->lsa;
                        ospf_lsa_flood(state, &temp_dbe, lp->id, lp);
                        state->lsa_wrapping = 1;
                }
                return;
        }
        //printf("%d: old LSA %d seqnum: %d \n", lp->id, lp->id, dbe->seqnum);
        dbe->seqnum++;
        //printf("%d: new LSA %d seqnum: %d \n", lp->id, lp->id, dbe->seqnum);
        ospf_lsa_flood(state, dbe, lp->id, lp);
}
void ospf_lsa_start_flood (ospf_nbr * nbr, ospf_db_entry * dbe, tw_lp * lp)
Definition at line 646 of file ospf-lsa.c.
References g_ospf_fd, getlsa(), ospf_aging_timer_set(), ospf_event_new(), ospf_event_send(), ospf_lsa_age(), and OSPF_LSA_MAX_AGE.
Referenced by flood_summary(), and ospf_lsa_flood().
{
        tw_event        *e;
        tw_memory       *send;
        ospf_db_entry   *out_dbe;
        ospf_lsa        *lsa;
        if(ospf_lsa_age(nbr->router, dbe, lp) + 1 > OSPF_LSA_MAX_AGE)
                ospf_aging_timer_set(nbr->router, dbe, OSPF_LSA_MAX_AGE, lp);
        /*
         * If the flood timer has already gone off, just send the LSA in a
         * single pkt.
         */
        if(nbr->next_flood > tw_now(lp))
        {
                send = tw_memory_alloc(lp, g_ospf_fd);
                out_dbe = tw_memory_data(send);
                out_dbe->lsa = dbe->lsa;
                out_dbe->b.entry = dbe->b.entry;
                out_dbe->seqnum = dbe->seqnum;
                out_dbe->b.age = ospf_lsa_age(nbr->router, dbe, lp) + 1;
                out_dbe->b.free = 0;
                out_dbe->cause_bgp = dbe->cause_bgp;
                out_dbe->cause_ospf = dbe->cause_ospf;
                lsa = getlsa(nbr->router->m, out_dbe->lsa, out_dbe->b.entry);
                e = ospf_event_new(nbr->router,
                                tw_getlp(nbr->id), nbr->next_flood - tw_now(lp), lp);
                ospf_event_send(nbr->router, e, OSPF_LS_UPDATE, lp,
                                lsa->length, send, nbr->router->ar->id);
#if VERIFY_LS
                printf("\tflood adding LSA %d to %d: mine (%d %d) send (%d %d) at %lf\n",
                                dbe->b.entry, nbr->id,
                                dbe->b.age, dbe->seqnum,
                                out_dbe->b.age, out_dbe->seqnum, e->recv_ts);
#endif
        } else
        {
                /*
                 * To start flood, and no flood has already started, set the flood
                 * timer and place all requests onto the retranmit list.  When
                 * the flood timer goes off, that is when you will send the pkts.
                 */
                nbr->next_flood = nbr->router->gstate->flood_timer + tw_now(lp);
                lsa = getlsa(nbr->router->m, dbe->lsa, dbe->b.entry);
                if(!lsa)
                {
                        printf("%lld: aborting flood of LSA: %d \n",
                                lp->id, dbe->b.entry);
                        return;
                }
                send = tw_memory_alloc(lp, g_ospf_fd);
                out_dbe = tw_memory_data(send);
                out_dbe->b.age = dbe->b.age + 1;
                out_dbe->b.entry = dbe->b.entry;
                out_dbe->b.free = 0;
                out_dbe->lsa = dbe->lsa;
                out_dbe->seqnum = dbe->seqnum;
                out_dbe->cause_bgp = dbe->cause_bgp;
                out_dbe->cause_ospf = dbe->cause_ospf;
                e = ospf_event_new(nbr->router, tw_getlp(nbr->id),
                                        nbr->router->gstate->flood_timer, lp);
                nbr->flood = ospf_event_send(nbr->router, e, OSPF_LS_UPDATE, lp,
                                        lsa->length, send, nbr->router->ar->id);
#if VERIFY_LS
                printf("\t\t\tflood LSA %d to %d: send (%d %d) at %lf\n",
                                dbe->b.entry, nbr->id,
                                out_dbe->b.age, out_dbe->seqnum, e->recv_ts);
#endif
        }
}
void ospf_main (int argc, char ** argv, char ** env)
Definition at line 281 of file ospf-main.c.
References ctxt, g_ospf_dd_fd, g_ospf_fd, g_ospf_ll_fd, g_ospf_lsa_fd, g_ospf_lsa_file, g_ospf_lsa_input, g_ospf_stats, g_rn_converge_ospf, g_rn_logs_dir, g_rn_tools_dir, main_setup_areas(), ospf_setup_options(), and xpath().
{
        char             file[255];
        int              i;
        xmlXPathObjectPtr       l_obj;
        g_ospf_stats = tw_calloc(TW_LOC, "", sizeof(ospf_statistics), 1);
        /*
         * Determine the number of LSAs to create in the global LSA array
         */
        // Need a better xpath expr to find only OSPF routers in my area!
        l_obj = xpath("//layer[@name=\'ospf\']", ctxt);
        if(l_obj->nodesetval->nodeNr < 1)
                return; //tw_error(TW_LOC, "Could not find any OSPF nodes!");
        if(sizeof(ospf_dd_pkt) < sizeof(ospf_lsa_link))
                tw_error(TW_LOC, "Cannot use DD membufs for LSA links!");
        /*
         * Init the memory queues needed by this model
         */
        for(i = 0; i < g_tw_nkp; i++)
        {
                printf("\nInitializing OSPF memory buffers... ");
                tw_kp_memory_init(tw_getkp(i), 20000, sizeof(ospf_db_entry), 1);
/*
                // Commented out for NCS
                g_ospf_fd = tw_kp_memory_init(tw_getkp(i),
                                        400 * l_obj->nodesetval->nodeNr,
                                        sizeof(ospf_db_entry), 1);
                g_ospf_lsa_fd = tw_kp_memory_init(tw_getkp(i),
                                        100 * l_obj->nodesetval->nodeNr,
                                        sizeof(ospf_lsa), 1);
                g_ospf_dd_fd = tw_kp_memory_init(tw_getkp(i),
                                        1 * l_obj->nodesetval->nodeNr,
                                        sizeof(ospf_dd_pkt), 1);
                g_ospf_ll_fd = tw_kp_memory_init(tw_getkp(i),
                                        100 * l_obj->nodesetval->nodeNr,
                                        sizeof(ospf_lsa_link), 1);
*/
                g_ospf_fd = tw_kp_memory_init(tw_getkp(i),
                                        2000000,
                                        sizeof(ospf_db_entry), 1);
                g_ospf_lsa_fd = tw_kp_memory_init(tw_getkp(i),
                                        2000000,
                                        sizeof(ospf_lsa), 1);
                g_ospf_dd_fd = tw_kp_memory_init(tw_getkp(i),
                                        100000,
                                        sizeof(ospf_dd_pkt), 1);
                g_ospf_ll_fd = tw_kp_memory_init(tw_getkp(i),
                                        1000000,
                                        sizeof(ospf_lsa_link), 1);
                printf("done!\n");
                //g_tw_kp[0].queues[g_ospf_fd].debug = 1;
                //g_tw_kp[0].queues[g_ospf_lsa_fd].debug = 1;
                //g_tw_kp[0].queues[g_ospf_dd_fd].debug = 1;
                //g_tw_kp[0].queues[g_ospf_ll_fd].debug = 1;
/*
                printf("\tDB  q: %10.0f bufs %10ld fd\n",
                        (float) (100 * l_obj->nodesetval->nodeNr), g_ospf_fd);
                printf("\tLSA q: %10.0f bufs %10ld fd\n",
                        (float) (100 * l_obj->nodesetval->nodeNr), g_ospf_lsa_fd);
                printf("\tDD  q: %10.0f bufs %10ld fd\n",
                        (float) (1 * l_obj->nodesetval->nodeNr), g_ospf_dd_fd);
                printf("\tLL  q: %10.0f bufs %10ld fd\n",
                        (float) (100 * l_obj->nodesetval->nodeNr), g_ospf_ll_fd);
*/
                printf("\tDB  q: %10.0f bufs %10ld fd\n",
                        (float) 2000000.0, g_ospf_fd);
                printf("\tLSA q: %10.0f bufs %10ld fd\n",
                        (float) 2000000, g_ospf_lsa_fd);
                printf("\tDD  q: %10.0f bufs %10ld fd\n",
                        (float) 100000, g_ospf_dd_fd);
                printf("\tLL  q: %10.0f bufs %10ld fd\n",
                        (float) 1000000, g_ospf_ll_fd);
        }
        ospf_setup_options(argc, argv);
        if(g_rn_converge_ospf)
        {
                main_setup_areas(l_obj);
        } else
        {
                sprintf(file, "tools/%s/ospf-lsa.file", g_rn_tools_dir);
                g_ospf_lsa_input = fopen(file, "r");
        }
        xmlXPathFreeObject(l_obj);
        sprintf(file, "%s/ospf-lsa.file", g_rn_logs_dir);
        g_ospf_lsa_file = fopen(file, "w");
        if(!g_ospf_lsa_file)
                tw_error(TW_LOC, "Unable to open: %s", file);
}
void ospf_md_final ()
Definition at line 386 of file ospf-main.c.
References c_router, g_ospf_lsa_file, g_ospf_routing_file, g_ospf_stats, g_rn_machines, and g_rn_nmachines.
{
        rn_machine      *m;
        rn_area         *ar;
        int              i;
        int              j;
        printf("\nOSPFv2 Model Statistics: \n\n");
        printf("\t%-50s %11ld\n", "Hello Packets", g_ospf_stats->s_sent_hellos);
        printf("\t%-50s %11ld\n", "Hello: sent", g_ospf_stats->s_e_hello_out);
        printf("\t%-50s %11ld\n", "Hello: recv", g_ospf_stats->s_e_hello_in);
        printf("\n");
        printf("\t%-50s %11ld\n", "DD Packets", g_ospf_stats->s_sent_dds);
        printf("\t%-50s %11ld\n", "Dropped Packets", g_ospf_stats->dropped_packets);
        printf("\t%-50s %11ld\n", "Dropped DD Packets", g_ospf_stats->s_drop_dd);
        printf("\t%-50s %11ld\n", "LS Requests", g_ospf_stats->s_sent_ls_requests);
        printf("\t%-50s %11ld\n", "LS Updates", g_ospf_stats->s_sent_ls_updates);
        printf("\t%-50s %11ld\n", "LS Acks", g_ospf_stats->s_sent_ls_acks);
        printf("\t%-50s %11ld\n", "Unknown Packets", g_ospf_stats->s_sent_unknown);
        printf("\t%-50s %11ld\n", "Lost Packets", g_ospf_stats->s_sent_lost);
        printf("\n");
        printf("BGP Caused OSPF Updates: %ld\n", g_ospf_stats->s_cause_bgp);
        printf("OSPF Caused OSPF Updates: %ld\n", g_ospf_stats->s_cause_ospf);
        printf("\n");
        if(!g_ospf_routing_file)
        {
                printf("Unable to create routing file! \n");
                return;
        }
        for(i = 0; i < g_rn_nmachines; i++)
        {
                m = &g_rn_machines[i];
                ar = m->subnet->area;
                if(m->type != c_router)
                        continue;
                //write(g_ospf_routing_file, m->ft, ar->g_ospf_nlsa * sizeof(unsigned int));
                for(j = 0; j < ar->g_ospf_nlsa; j++)
                        fprintf(g_ospf_routing_file, "%d ", m->ft[j]);
                fprintf(g_ospf_routing_file, "\n");
        }
        //fclose(g_ospf_routing_file);
        if(g_ospf_lsa_file)
                ; // fclose(g_ospf_lsa_file);
}
void ospf_nbr_event_handler (ospf_state * state, ospf_nbr * nbr, ospf_nbr_event event, tw_lp * lp)
Definition at line 544 of file ospf-neighbor-state.c.
References ospf_nbr_adj_ok(), ospf_nbr_exchange_done(), ospf_nbr_hello_recv(), ospf_nbr_inactivity_timer(), ospf_nbr_kill_nbr(), ospf_nbr_ll_down(), ospf_nbr_neg_done(), ospf_nbr_one_way_recv(), ospf_nbr_seqnum_mismatch(), ospf_nbr_start(), and ospf_nbr_two_way_recv().
Referenced by dd_process(), ls_update_process(), ospf_dd_event_handler(), ospf_event_handler(), ospf_hello_packet(), ospf_interface_calc_dr(), ospf_interface_down(), ospf_rc_event_handler(), and ospf_routing_init().
{
        switch (event)
        {
        case ospf_nbr_hello_recv_ev:
                ospf_nbr_hello_recv(nbr, lp);
                break;
        case ospf_nbr_start_ev:
                ospf_nbr_start(nbr, lp);
                break;
        case ospf_nbr_one_way_ev:
                ospf_nbr_one_way_recv(nbr, lp);
                break;
        case ospf_nbr_two_way_recv_ev:
                ospf_nbr_two_way_recv(nbr, lp);
                break;
        case ospf_nbr_neg_done_ev:
                ospf_nbr_neg_done(state, nbr, lp);
                break;
        case ospf_nbr_exchange_done_ev:
                ospf_nbr_exchange_done(state, nbr, lp);
                break;
        case ospf_nbr_bad_ls_request_ev:
                if (nbr->state >= ospf_nbr_exchange_st)
                        ospf_nbr_seqnum_mismatch(nbr, lp);
                break;
        case ospf_nbr_load_done_ev:
                if (nbr->state == ospf_nbr_loading_st)
                        nbr->state = ospf_nbr_full_st;
                printf("%lld: new neighbor at full_st: %d \n", lp->id, nbr->id);
                break;
        case ospf_nbr_adj_ok_ev:
                ospf_nbr_adj_ok(nbr, lp);
                break;
        case ospf_nbr_seqnum_mismatch_ev:
                ospf_nbr_seqnum_mismatch(nbr, lp);
                break;
        case ospf_nbr_kill_nbr_ev:
                ospf_nbr_kill_nbr(nbr, lp);
                break;
        case ospf_nbr_inactivity_timer_ev:
                ospf_nbr_inactivity_timer(nbr, lp);
                break;
        case rc_ospf_nbr_inactivity_timer_ev:
                ospf_nbr_inactivity_timer(nbr, lp);
                break;
        case ospf_nbr_ll_down_ev:
                ospf_nbr_ll_down(nbr, lp);
                break;
        default:
                tw_error(TW_LOC, "Unknown nbr event: %d", event);
        }
}
void ospf_neighbor_init (ospf_state * state, tw_lp * lp)
Definition at line 82 of file ospf-neighbor.c.
References neighbor_init().
Referenced by ospf_startup().
{
        int              i;
        for(i = 0; i < state->n_interfaces; i++)
                neighbor_init(state, &state->nbr[i], lp);
}
void ospf_random_weights (ospf_state * state, tw_lp * lp)
Definition at line 4 of file ospf-experiments.c.
References g_ospf_fd, and rn_timer_simple().
Referenced by ospf_startup().
{
        tw_memory       *b;
        tw_event        *e;
        tw_stime         next_status;
        ospf_message    *m;
        int              percent;
        long int         i;
        for(i = 0; i < state->m->nlinks; i++)
        {
                percent = tw_rand_integer(lp->rng, 0, 100);
                if(percent > 10 + 1)
                        return;
                next_status = tw_rand_integer(lp->rng, 1, g_tw_ts_end);
                if(next_status >= g_tw_ts_end)
                        continue;
                e = NULL;
                e = rn_timer_simple(lp, next_status);
                b = tw_memory_alloc(lp, g_ospf_fd);
                m = tw_memory_data(b);
                m->type = OSPF_WEIGHT_CHANGE;
                m->data = (void *) i;
                tw_event_memory_set(e, b, g_ospf_fd);
        }
}
void ospf_rc_event_handler (ospf_state * , tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 4 of file ospf-router-rc.c.
References ospf_hello_packet_rc(), ospf_int_getinterface(), ospf_nbr_event_handler(), ospf_timer_start(), and rn_message_data().
{
#if 0
        ospf_message    *msg;
        ospf_nbr        *nbr;
        msg = rn_message_data(rn_msg);
        nbr = ospf_int_getinterface(state, rn_msg->src);
        if(!nbr)
                nbr = ospf_util_data(msg);
        if(msg->type == OSPF_IP)
                tw_error(TW_LOC, "IP packet forwarding not reversible yet!");
        switch(msg->type)
        {
                case OSPF_HELLO_MSG:
                        ospf_hello_packet_rc(state, nbr, bf, msg, lp);
                        state->stats->s_e_hello_in--;
                        break;
                case OSPF_HELLO_SEND:
                        // need to restart timer
                        nbr->hello_timer =
                                ospf_timer_start(nbr, nbr->hello_timer,
                                         nbr->hello_interval,
                                         OSPF_HELLO_SEND, lp);
                        break;
                case OSPF_HELLO_TIMEOUT:
                        state->stats->s_e_hello_timeouts--;
                        ospf_nbr_event_handler(state, nbr,
                                        rc_ospf_nbr_inactivity_timer_ev, lp);
                        break;
                default:
                        tw_error(TW_LOC, "Unhandled event type (%d) in "
                                         "rc_event_handler!", msg->type);
        }
#endif
}
void ospf_router_debug_rate (tw_lp * lp, int * next)
Definition at line 8 of file ospf-router-debug.c.
{
        if(lp->id == 0 && lp->kp->s_nevent_processed > *next)
        {
                tw_wall_now(&g_tw_pe[0].end_time);
                tw_wall_sub(&g_tw_pe[0].run_time, &g_tw_pe[0].end_time,
                                &g_tw_pe[0].start_time);
                printf("Events processed: %ld \n",
                                lp->kp->s_nevent_processed);
                printf("Event rate: %11.2f (events/sec)\n",
                        (double) lp->kp->s_nevent_processed /
                        tw_wall_to_double(&g_tw_pe[0].run_time));
                *next += 1000000;
        }
}
void ospf_router_debug_routing (ospf_state * state, int d, tw_lp * lp)
Definition at line 30 of file ospf-router-debug.c.
References f, g_rn_nrouters, and x.
{
#if 0
        FILE    *f;
        char     file[1024];
        sprintf(file, "ospf/logs/r%ld-%d.log", lp->id, x++);
        f = fopen(file, "w");
        fprintf(f, "src\t\tdst\n");
        for(d = 0; d < g_rn_nrouters; d++)
        {
                if(state->ft[d] == 0xff)
                        fprintf(f, "%d\t\tno route\n", d);
                else if(lp->id == d)
                        fprintf(f, "%d\t\t self d\n", d);
                else
                        fprintf(f, "%d\t\t%d\n", d, state->ft[d]);
        }
        fclose(f);
#endif
}
void ospf_routing_init (ospf_state * state, tw_lp * lp)
Definition at line 404 of file ospf-routing.c.
References d, f, front, g_ospf_routing_file, g_ospf_rt_write, g_rn_nrouters, ospf_nbr_event_handler(), ospf_rt_timer(), p, rn_getmachine(), rn_route(), and s.
Referenced by ospf_startup().
{
        ospf_nbr        *nbr;
        int              i;
        // Init globals for Dijkstra's algorithm
        if(!front)
        {
                //int n = state->ar->g_ospf_nlsa;
                int n = g_rn_nrouters;
                front = calloc(n * sizeof(int), 1);
                p = calloc(n * sizeof(int), 1);
                f = calloc(n * sizeof(int), 1);
                s = calloc(n * sizeof(int), 1);
                d = calloc(n * sizeof(int), 1);
        }
        if(!state->m->nhop)
                state->m->nhop = tw_calloc(TW_LOC, "", sizeof(int), state->ar->g_ospf_nlsa);
        if(0 == g_ospf_rt_write)
        {
                rn_machine      *m = rn_getmachine(lp->id);
                int              i;
                for(i = 0; i < state->ar->g_ospf_nlsa; i++)
                        fscanf(g_ospf_routing_file, "%d", &m->ft[i]);
                //read(g_ospf_routing_file, rn_getmachine(lp->id)->ft,
                //      state->ar->g_ospf_nlsa * sizeof(int));
        } else
        {
                ospf_rt_timer(state, lp->id);
#if 0
                write(g_ospf_routing_file, rn_getmachine(lp->id)->ft,
                        (state->ar->g_ospf_nlsa) * sizeof(int));
#endif
        }
        return;
        /*
         * Take down adjacencies where there is no forwarding table entry
         */
        for(i = 0, nbr = state->nbr; i < state->n_interfaces; nbr = &state->nbr[++i])
        {
                if(rn_route(state->m, nbr->id) == -1)
                {
                        printf("%lld: taking down neighbor %d \n", lp->id, nbr->id);
                        ospf_nbr_event_handler(state, nbr, ospf_nbr_kill_nbr_ev, lp);
#if 0
                        // These are just OSPF AS X to OSPF AS Y nbrs
                        // we are taking down!
                        // setup just what I need!
                        nbr->state = ospf_nbr_full_st;
                        nbr->requests = (char *) calloc(state->ar->g_ospf_nlsa, 1);
                        if(!nbr->requests)
                                tw_error(TW_LOC, "Out of memory!");
#endif
                }
        }
}
void ospf_rt_build (ospf_state * state, int start_vertex)
Definition at line 4 of file ospf-routing.c.
References ospf_rt_timer(), and ospf_timer_start().
Referenced by ospf_aging_timer(), ospf_db_insert(), ospf_db_update(), ospf_experiment_weights(), and ospf_nbr_reset().
{
        if(!state->gstate->rt_interval)
        {
                ospf_rt_timer(state, start_vertex);
                return;
        }
        if(NULL == state->rt_timer)
        {
                state->rt_timer = ospf_timer_start(NULL,
                                                state->rt_timer,
                                                state->gstate->rt_interval,
                                                OSPF_RT_TIMER,
                                                tw_getlp(start_vertex));
#if VERIFY_ROUTING
                if(state->rt_timer)
                        printf("%d: RT Timer set for %lf \n",
                                start_vertex, state->rt_timer->recv_ts);
#endif
        }
}
void ospf_rt_print (ospf_state * state, tw_lp * lp, FILE *)
Definition at line 224 of file ospf-routing.c.
References d, g_rn_nas, getlsa(), rn_getarea(), rn_getmachine(), and rn_route().
Referenced by ospf_statistics_collection().
{
        rn_machine      *m;
        rn_area         *ar;
        ospf_lsa        *lsa;
        ospf_db_entry   *dbe;
        int     d;
        int     i;
        int     q;
        m = state->m;
        ar = rn_getarea(m);
        fprintf(log, "\nRouting table for %lld: \n\n"
                "\t%-20s %-20s %-20s\n", lp->id, "Host id",
                "next_hop_interface", "next_hop_node_id");
        for(i = 0; i < g_tw_nlp; i++)
        {
                if(i == lp->id)
                {
                        fprintf(log, "\t%-20d %-20s\n", i, "self");
                        continue;
                }
                if(rn_route(m, i) == -1)
                {
                        // May be that I am the originator of this LSA,
                        // which would have an FT of -1, so check LSA
                        // Check LSA for route
                        rn_area *dst = rn_getarea(rn_getmachine(i));
                        dbe = &state->db[i];
                        // if in same area, the only use FT
                        if(state->ar == dst)
{
                                fprintf(log, "\t%-20d %-20s\n", i, "no route");
                                continue;
                        } else if(state->ar->as == dst->as)
{
                                dbe = &state->db[state->ar->nmachines +
                                                 dst->id - dst->as->low];
                        } else
{
                                dbe = &state->db[state->ar->nmachines +
                                        state->ar->as->nareas + dst->as->id];
                        }
                        if(dbe->b.free)
{
                                fprintf(log, "\t%-20d %-20s\n", i, "no route");
                                continue;
                        }
                        lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                        if(!lsa)
{
                                fprintf(log, "\t%-20d %-20s\n", i, "no route (NO LSA)");
                                continue;
                        } else
                                d = rn_route(state->m, lsa->adv_r);
                        if(lsa->adv_r == lp->id)
{
                                if(lsa->links.size != 0)
{
                                        ospf_lsa_link * l =
                                                tw_memory_data(lsa->links.head);
                                        fprintf(log, "\t%-20d %-20s %-20d\n",
                                                i, "ORIGIN", l->dst);
                                } else
                                        fprintf(log, "\t%-20d %-20s \n",
                                                i, "ORIGIN");
                        } else if(d == -1)
                                fprintf(log, "\t%-20d %-20s\n", i, "no route");
                        else
                                fprintf(log, "\t%-20d %-20d %-25lld\n",
                                        i, d,
                                        state->m->link[d].addr);
                        //fprintf(log, "\t%-20d %-20s\n", i, "no route");
                } else
                        fprintf(log, "\t%-20d %-20d %-25lld\n",
                                        i, rn_route(m, i),
                                        state->m->link[rn_route(m, i)].addr);
        }
        q = ar->nmachines;
        fprintf(log, "\n\n\t%-20s %-20s %-20s\n", "Area id",
                "next_hop_interface", "next_hop_node_id");
        for(i = 0; q < ar->nmachines + ar->as->nareas; q++, i++)
        {
                if(i + state->ar->as->low == state->ar->id)
                {
                        fprintf(log, "\t%-20lld %-20s\n", i + ar->as->low, "self");
                        continue;
                }
                dbe = &state->db[q];
                if(dbe->b.free)
                {
                        d = rn_route(state->m, q);
                        if(-1 == d)
                                fprintf(log, "\t%-20lld %-20s\n",
                                        i + ar->as->low, "no route");
                        else
                                fprintf(log, "\t%-20lld %-20d %-15lld (no lsa)\n",
                                        i + ar->as->low, state->m->ft[q],
                                        state->m->link[state->m->ft[q]].addr);
                        continue;
                }
                // Check LSA for route
                lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                d = rn_route(state->m, lsa->adv_r);
                if(lsa->adv_r == lp->id)
                {
                        if(lsa->links.size)
{
                                ospf_lsa_link * l = tw_memory_data(lsa->links.head);
                                fprintf(log, "\t%-20lld %-20s %-20d\n",
                                        i + ar->as->low, "ORIGIN", l->dst);
                        } else
                                fprintf(log, "\t%-20lld %-20s\n",
                                        i + ar->as->low, "ORIGIN");
                } else if(d == -1)
                        fprintf(log, "\t%-20d %-20s\n", i, "no route");
                else
                        fprintf(log, "\t%-20lld %-20d %-25lld\n",
                                i + ar->as->low, state->m->ft[q],
                                state->m->link[state->m->ft[q]].addr);
        }
        fprintf(log, "\n\n\t%-20s %-20s %-20s\n", "AS id",
                "next_hop_interface", "next_hop_node_id");
        for(i = 0; q < ar->nmachines + ar->as->nareas + g_rn_nas; q++, i++)
        {
                if(i == state->ar->as->id)
                {
                        fprintf(log, "\t%-20d %-20s\n", i, "self");
                        continue;
                }
                // Check LSA for route
                dbe = &state->db[q];
                if(dbe->b.free)
                {
                        fprintf(log, "\t%-20d %-20s\n", i, "no route");
                        continue;
                }
                lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                d = rn_route(state->m, lsa->adv_r);
                if(lsa->adv_r == lp->id)
                {
                        if(lsa->links.size)
{
                                ospf_lsa_link * l = tw_memory_data(lsa->links.head);
                                fprintf(log, "\t%-20d %-20s %-20d\n",
                                                i, "ORIGIN", l->dst);
                        } else
                                fprintf(log, "\t%-20d %-20s\n", i, "ORIGIN");
                } else if(d == -1)
                        fprintf(log, "\t%-20d %-20s\n", i, "no route");
                else
                        fprintf(log, "\t%-20d %-20d %-25lld\n", i, state->m->ft[q],
                                state->m->link[state->m->ft[q]].addr);
        }
}
void ospf_rt_timer (ospf_state * state, int start_vertex)
Definition at line 29 of file ospf-routing.c.
References d, f, front, getlsa(), ospf_db_route(), p, parent, rn_getarea(), rn_getmachine(), and s.
Referenced by ospf_event_handler(), ospf_routing_init(), and ospf_rt_build().
{
        tw_memory       *b;
        rn_machine      *node;
        rn_machine      *dst;
        rn_area         *dst_ar;
        ospf_db_entry   *dbe;
        ospf_lsa        *lsa;
        ospf_lsa_link   *l;
        ospf_nbr        *nbr;
        int             i, j, q, v, w, low;
        int             nhop = 0;
        /*
         * d[] - distance to vertices. * front[] - stores the index to vertices
         * that are in the frontier. * p[] - position of vertices in front[]
         * array. * f[] - boolean frontier set array. * s[] - boolean solution
         * set array. * * timing - timing results structure for returning the
         * time taken. * dist - used in distance computations. * vertices, n -
         * Graph details: vertices array, size. * out_n - Current vertex's OUT
         * set size.
         */
        int      dist;
        int     *parent;
        w = 0;
        low = state->ar->low;
        parent = state->m->ft;
#if VERIFY_ROUTING
        printf("%d: Rebuilding routing table \n", start_vertex);
#endif
        if(state->ar->nmachines == 0)
                tw_error(TW_LOC, "No forwarding table for %d!", start_vertex);
        for (i = 0; i < state->ar->nmachines; i++)
        {
                parent[i] = -1;
                f[i] = 0;
                s[i] = 0;
        }
        // The start vertex is part of the solutions set.
        start_vertex -= low;
        s[start_vertex] = 1;
        d[start_vertex] = 0;
        // j is used as the size of the frontier set.
        j = 0;
        // Put out set of the starting vertex into the frontier and update the
        // distances to vertices in the out set.  k is the index for the out set.
        for(i = 0; i < state->n_interfaces; i++)
        {
                nbr = &state->nbr[i];
                if(nbr->state != ospf_nbr_full_st)
                        continue;
                if(nbr->id >= state->ar->low && nbr->id <= state->ar->high)
                {
                        w = nbr->id - low;
                } else if(nbr->ar->id >= state->ar->as->low &&
                        nbr->ar->id <= state->ar->as->high)
                {
                        w = state->ar->nmachines + nbr->ar->id - nbr->ar->as->low;
                } else
                        continue;
                dbe = &state->db[w];
                if(dbe->b.free)
                        continue;
                if(f[w])
                        continue;
                lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                b = lsa->links.head;
                if(!b)
                        continue;
                l = tw_memory_data(b);
                d[w] = l->metric;
                state->m->nhop[w] = 0;
                //printf("adding %d (w=%d), dist %d \n", nbr->id, w, l->metric);
                front[j] = w;
                p[w] = j;
                f[w] = 1;
                parent[w] = i;
                j++;
        }
        // At this point we are assuming that all vertices are reachable from
        // the starting vertex and N > 1 so that j > 0.
        while (j > 0)
        {
                // Find the vertex in frontier that has minimum distance.
                v = front[0];
                for (q = 1; q < j; q++)
                        if (d[front[q]] < d[v])
                                v = front[q];
                // Move this vertex from the frontier to the solution set.  It's old
                // position in the frontier array becomes occupied by the element
                // previously at the end of the frontier.
                j--;
                front[p[v]] = front[j];
                p[front[j]] = p[v];
                s[v] = 1;
                f[v] = 0;
                // Values in p[v] and front[j] no longer used, so are now meaningless
                // at this point.
                // Update distances to vertices, w, in the out set of v.
                dbe = &state->db[v];
                lsa = getlsa(state->m, dbe->lsa, dbe->b.entry);
                //node = rn_getmachine(v + low);
                node = rn_getmachine(lsa->adv_r);
                state->m->nhop[lsa->adv_r - state->ar->low] = nhop;
                //printf("considering node: %d \n", node->id);
                b = lsa->links.head;
                for (q = 0; q < lsa->links.size; q++, b = b->next)
                {
                        l = tw_memory_data(b);
                        dst = rn_getmachine(l->dst);
                        dst_ar = rn_getarea(dst);
                        // all w should be q
                        if(l->dst >= state->ar->low && l->dst <= state->ar->high)
                                w = l->dst - low;
                        else if(dst_ar->id >= state->ar->as->low &&
                                dst_ar->id <= state->ar->as->high)
                                w = state->ar->nmachines + dst_ar->id -
                                        dst_ar->as->low;
                        else
                                continue; //tw_error(TW_LOC, "Unknown case!");
                        // Only update if w is not already in the solution set.
                        if (s[w])
                                continue;
                        // If w is in the frontier the new distance to w
                        // is the minimum of its current distance and the
                        // distance to w via v.
                        dist = d[v] + l->metric;
                        if (f[w] == 1)
{
                                if (dist < d[w])
{
                                        //printf("up: dist to w %d: %d, nhop %d \n", w, dist, nhop);
                                        d[w] = dist;
                                        parent[w] = parent[v];
                                        state->m->nhop[w] = nhop+1;
                                }
                        } else
{
                                //printf("add: dist to w %d: %d, nhop %d \n", w, dist, nhop);
                                parent[w] = parent[v];
                                state->m->nhop[w] = nhop++;
                                d[w] = dist;
                                front[j] = w;
                                p[w] = j;
                                f[w] = 1;
                                j++;
                        }
                }
        }
        // Correct the AS external LSA entries in the routing table
        for(w = state->ar->nmachines; w < state->ar->g_ospf_nlsa; w++)
        {
                if(state->db[w].b.free == 0)
                {
                        //printf("Attempting to update route to LSA %d \n", w);
                        ospf_db_route(state, &state->db[w], tw_getlp(state->m->id));
                }
        }
        //ospf_rt_print(state, tw_getlp(start_vertex + low), stdout);
}
void ospf_startup (ospf_state * state, tw_lp * lp)
OSPF model LP init function.
This is the OSPF model LP initialization function. This function is responsible for initializing each OSPF LP. The main steps are:
Create and init the neighbor array
Create and init the LP LSA database
Create and init the LP forwarding table
Start the aging timer for the oldest LSA
The order of steps 2 and 3 are dependant upon if the model is started in converged state or not. The determination is based on the fact that sometimes we build the forwarding table from the LSA database, and sometimes we read it in from file.
Definition at line 237 of file ospf-router.c.
References g_ospf_rt_write, g_ospf_state, g_rn_converge_bgp, g_rn_converge_ospf, g_rn_logs_dir, g_route, g_route1, gr1, gr2, ospf_db_init(), ospf_db_read(), OSPF_MIN_LSA_SEQNUM, ospf_neighbor_init(), ospf_random_weights(), ospf_routing_init(), ospf_timer_start(), rn_getarea(), and rn_getmachine().
{
        unsigned int    rv;
        unsigned int    next_timer;
#if OSPF_LOG
        char             name[255];
        sprintf(name, "%s/ospf-router-%ld.log", g_rn_logs_dir, lp->id);
        //state->log = fopen(name, "w");
        state->log = stdout;
#endif
        state->from = -1;
        state->from1 = -1;
        state->gstate = g_ospf_state;
        state->m = rn_getmachine(lp->id);
        state->ar = rn_getarea(state->m);
        state->stats = tw_calloc(TW_LOC, "", sizeof(ospf_statistics), 1);
        if(lp->id == 0)
        {
                for(rv = 0; rv < 400; rv++)
                        g_route[rv] = g_route1[rv] = -1;
                gr1 = gr2 = 0;
                state->sn = .003;
        }
        //printf("Init OSPF router: %ld \n", lp->id);
        // Create the neighbor data structures
        ospf_neighbor_init(state, lp);
        // Create my router LSA links
        state->lsa_seqnum = OSPF_MIN_LSA_SEQNUM + 1;
        if(!g_rn_converge_ospf)
        {
                ospf_db_read(state, lp);
                ospf_routing_init(state, lp);
        } else if(!g_rn_converge_ospf)
        {
                ospf_routing_init(state, lp);
                ospf_db_read(state, lp);
        } else if(0 == g_ospf_rt_write)
        {
                // Setup the routing table for the first time
                ospf_routing_init(state, lp);
                // Setup the LSA database for the first time
                next_timer = ospf_db_init(state, lp);
        } else
        {
                // Setup the LSA database for the first time
                next_timer = ospf_db_init(state, lp);
                // Setup the routing table for the first time
                ospf_routing_init(state, lp);
        }
        state->lsa = tw_memory_data(state->ar->g_ospf_lsa[lp->id - state->ar->low]);
        if(!g_rn_converge_ospf && !g_rn_converge_bgp)
                ospf_random_weights(state, lp);
        /*
         * This timer should only go off when the oldest LSA in my DB
         * gets to be the REFRESH age, so that I can make sure to request an
         * update for it
         */
        state->aging_timer = NULL;
#if 0
        state->aging_timer =
                ospf_timer_start(NULL, state->aging_timer,
                                 next_timer, OSPF_AGING_TIMER, lp);
#endif
#if VERIFY_AGING
        printf("%ld: setting aging timer finally: %lf \n",
                lp->id, next_timer);
#endif
}
void ospf_statistics_collection (ospf_state * state, tw_lp * lp)
Definition at line 8 of file ospf-stats.c.
References c_time, g_ospf_lsa_file, g_ospf_stats, g_rn_converge_bgp, g_rn_converge_ospf, g_rn_logs_dir, g_route, g_route1, ospf_db_print(), ospf_db_print_raw(), ospf_lsa_print(), and ospf_rt_print().
{
#if LOG_ROUTER || OSPF_LOG
        //char           name[255];
#endif
        tw_memory       *b;
        ospf_lsa        *lsa;
        int              i;
        g_ospf_stats->s_e_hello_in += state->stats->s_e_hello_in;
        g_ospf_stats->s_e_hello_out += state->stats->s_e_hello_out;
        g_ospf_stats->dropped_packets += state->stats->dropped_packets;
        g_ospf_stats->s_drop_dd += state->stats->s_drop_dd;
        g_ospf_stats->s_sent_hellos += state->stats->s_sent_hellos;
        g_ospf_stats->s_sent_dds += state->stats->s_sent_dds;
        g_ospf_stats->s_sent_ls_requests += state->stats->s_sent_ls_requests;
        g_ospf_stats->s_sent_ls_updates += state->stats->s_sent_ls_updates;
        g_ospf_stats->s_sent_ls_acks += state->stats->s_sent_ls_acks;
        g_ospf_stats->s_sent_unknown += state->stats->s_sent_unknown;
        g_ospf_stats->s_sent_lost += state->stats->s_sent_lost;
        g_ospf_stats->s_cause_bgp += state->stats->s_cause_bgp;
        g_ospf_stats->s_cause_ospf += state->stats->s_cause_ospf;
        if(lp->id < 1000 && 0)
                printf("Finalizing OSPF lp %lld \n", lp->id);
        c_time = max(c_time, state->c_time);
#if VERIFY_OSPF_CONVERGENCE
        if(lp->id == 0)
        {
                printf("OSPFv2 Model Statistics: \n\n");
                printf("\tRoute 0: ");
                for(i = 0; i < 40000; i++)
                {
                        if(g_route[i] == -1)
                                break;
                        printf(" %d,", g_route[i]);
                }
                printf(" (i = %d) \n", i);
                printf("\tRoute 1: ");
                for(i = 0; i < 40000; i++)
                {
                        if(g_route1[i] == -1)
                                break;
                        printf(" %d", g_route1[i]);
                }
                printf(" (i = %d) \n", i);
                printf("\n\tTotal Network Convergence Time: %f \n", c_time);
        }
#endif
#if OSPF_LOG && 0
        if(state->log && state->log != stdout)
                fclose(state->log);
        sprintf(name, "%s/ospf-router-%ld.log", g_rn_logs_dir, lp->id);
        state->log = fopen(name, "w");
        if(!state->log)
                return;
        fprintf(state->log, "OSPFv2 Router %ld: Final Time: %f\n\n", lp->id, tw_now(lp));
        ospf_db_print(state, state->log, lp);
        ospf_rt_print(state, lp, state->log);
#endif
#if LOG_ROUTER
        fprintf(state->log, "Events Received:\n");
        fprintf(state->log, "\t%-50s %11ld\n", "HELLO msgs recvd",
                                                state->stats->s_e_hello_in);
        fprintf(state->log, "\t%-50s %11ld\n", "HELLO send timers",
                                                state->stats->s_e_hello_out);
        fprintf(state->log, "\t%-50s %11ld\n", "HELLO inactive timeouts",
                                                state->stats->s_e_hello_timeouts);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11ld\n", "DD msgs recvd", state->stats->s_e_dd_msgs);
        fprintf(state->log, "\t%-50s %11ld\n", "DD pkts dropped", state->stats->s_drop_dd);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11ld\n", "LS Requests recvd",
                                                state->stats->s_e_ls_requests);
        fprintf(state->log, "\t%-50s %11ld\n", "ACK timeouts",
                                                state->stats->s_e_ack_timeouts);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11ld\n", "Aging timer events",
                                                state->stats->s_e_aging_timeouts);
        fprintf(state->log, "\t%-50s %11ld\n", "Unknown events!", state->stats->s_e_unknown);
        fprintf(state->log, "\n");
        fprintf(state->log, "Events Sent:\n");
        fprintf(state->log, "\t%-50s %11ld\n", "HELLO msgs", state->stats->s_sent_hellos);
        fprintf(state->log, "\t%-50s %11ld\n", "DD packets", state->stats->s_sent_dds);
        fprintf(state->log, "\t%-50s %11ld\n", "LS Requests", state->stats->s_sent_ls_requests);
        fprintf(state->log, "\t%-50s %11ld\n", "Dropped Packets", state->stats->s_sent_lost);
        fprintf(state->log, "\t%-50s %11ld\n", "Unknown!", state->stats->s_sent_unknown);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11ld\n", "LS Updates sent ",
                state->stats->s_sent_ls_updates);
        fprintf(state->log, "\t%-50s %11ld\n", "LS ACKS recvd", state->stats->s_e_ls_acks);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11ld\n", "LS Updates recvd",
                state->stats->s_e_ls_updates);
        fprintf(state->log, "\t%-50s %11ld\n", "LS ACKs sent ",
                state->stats->s_sent_ls_acks);
        fprintf(state->log, "\n");
        fprintf(state->log, "%s %ld\n", "BGP Caused Updates",
                state->stats->s_cause_bgp);
        fprintf(state->log, "%s %ld\n", "OSPF Caused Updates",
                state->stats->s_cause_ospf);
        if(state->log && state->log != stdout)
                fclose(state->log);
#endif
        // Create the ospf-lsa.file
        if(!g_rn_converge_ospf && !g_rn_converge_bgp)
                return;
        // Print out the LSAs for the area
        if(state->ar->low == lp->id)
        {
                for(i = 0; i < state->ar->g_ospf_nlsa; i++)
                {
                        b = state->ar->g_ospf_lsa[i];
                        while(b && NULL != (lsa = tw_memory_data(b)))
{
                                ospf_lsa_print(g_ospf_lsa_file, lsa);
                                b = lsa->next;
                        }
                }
                fprintf(g_ospf_lsa_file, "-1\n");
        }
        ospf_db_print_raw(state, g_ospf_lsa_file, lp);
}
tw_event* ospf_timer_cancel (tw_event * tmr, tw_lp * lp)
Definition at line 4 of file ospf-timer.c.
References g_ospf_fd, and rn_timer_cancel().
Referenced by ospf_ack_timed_out(), ospf_flood_recv(), ospf_interface_reset(), ospf_nbr_exchange_done(), and ospf_nbr_reset().
{
        tw_memory       *b;
        if(tmr && NULL != tmr->memory)
        {
                b = tmr->memory;
                tmr->memory = NULL;
                tw_memory_free(lp, b, g_ospf_fd);
        }
        if(tmr && tw_now(lp) == tmr->recv_ts)
                tmr = NULL;
        else if(tmr)
        {
                rn_timer_cancel(lp, &tmr);
        }
        return NULL;
}
tw_event* ospf_timer_start (ospf_nbr * nbr, tw_event * tmr, tw_stime ts, int type, tw_lp * lp)
Definition at line 29 of file ospf-timer.c.
References g_ospf_fd, rn_timer_init(), and rn_timer_reset().
Referenced by dd_exchange(), neighbor_init(), ospf_ack_delayed(), ospf_aging_timer(), ospf_aging_timer_set(), ospf_dd_retransmit(), ospf_flood_recv(), ospf_hello_send(), ospf_interface_up(), ospf_ls_request(), ospf_nbr_hello_recv(), ospf_nbr_neg_done(), ospf_nbr_start(), ospf_nbr_two_way_recv(), ospf_rc_event_handler(), ospf_retrans_timed_out(), ospf_rt_build(), and ospf_startup().
{
        tw_memory       *b;
        ospf_message    *m;
        ts = tw_now(lp) + ts;
/*
        if(tmr && tmr->memory && tmr->memory->next)
                tw_error(TW_LOC, "More than one membuf on timer!");
*/
        /* THIS CONDITIONAL IS NECESSARY!! */
        /* Don't do anything if the timer is already set for this time! */
        if(tmr && tw_now(lp) >= tmr->recv_ts)
                tmr = NULL;
        else if(tmr && ts == tmr->recv_ts)
                return tmr;
        if(!tmr)
                tmr = rn_timer_init(lp, ts);
        else
                rn_timer_reset(lp, &tmr, ts);
        // Timer library will not allocate timers past end time!
        if(!tmr)
                return NULL;
/*
        if(nbr)
                printf("%ld OSPF: TIMER %d ev %d, type: %d, ts %lf \n",
                                        lp->id, (int) tmr, type, nbr->id, tmr->recv_ts);
*/
        if(NULL != tmr->memory)
                b = tmr->memory;
        else
        {
                b = tw_memory_alloc(lp, g_ospf_fd);
                tw_event_memory_set(tmr, b, g_ospf_fd);
        }
        m = tw_memory_data(b);
        m->type = type;
        m->data = nbr;
        return tmr;
}
void ospf_xml (ospf_state * state, const xmlNodePtr my_node, tw_lp * lp)
Definition at line 4 of file ospf-xml.c.
References rn_getarea(), rn_getas(), rn_getmachine(), and xml_getprop().
{
        xmlNodePtr              interface;
        ospf_nbr                *nbr;
        int                      addr;
        int                      i;
        state->m = rn_getmachine(lp->id);
        state->ar = rn_getarea(state->m);
        /*
         * Now we need to set up the LSAs/interfaces for the OSPF neighbors
         */
        state->n_interfaces = 0;
        for(interface = node->children; interface; interface = interface->next)
        {
                if(0 != strcmp((char *) interface->name, "interface"))
                        continue;
                addr = atoi(xml_getprop(interface, "addr"));
                if(state->ar->as == rn_getas(rn_getmachine(addr)))
                        state->n_interfaces++;
        }
        if(state->n_interfaces == 0)
        {
                printf("%lld: no neighbors! \n", lp->id);
                return;
        }
        state->nbr = (ospf_nbr *) calloc(sizeof(ospf_nbr), state->n_interfaces);
        if(!state->nbr)
                tw_error(TW_LOC, "Out of memory!");
        for(i = 0, interface = node->children; interface; interface = interface->next)
        {
                if(0 != strcmp((char *) interface->name, "interface"))
                        continue;
                nbr = &state->nbr[i++];
                addr = atoi(xml_getprop(interface, "addr"));
                if(state->ar->as != rn_getas(rn_getmachine(addr)))
                        continue;
                nbr->id = addr;
                nbr->m = rn_getmachine(addr);
                nbr->ar = rn_getarea(nbr->m);
        }
}
int shouldRecalculateTable (ospf_lsa * newLsa, ospf_lsa * oldLsa)
Variable Documentation
int* d
Definition at line 104 of file save/ip-routing.c.
Referenced by get_tod(), ospf_db_route(), ospf_ip_route(), ospf_routing_init(), ospf_rt_print(), ospf_rt_timer(), and rn_xml_link_topology().
int db_sz
Definition at line 5 of file ospf-global.c.
int* f
Definition at line 103 of file save/ip-routing.c.
Referenced by init_ic_stages_from_file(), init_profiles_from_file(), ospf_router_debug_routing(), ospf_routing_init(), and ospf_rt_timer().
int* front
Definition at line 28 of file ospf-global.c.
Referenced by ospf_routing_init(), and ospf_rt_timer().
int g_max_updates
Definition at line 24 of file ospf-global.c.
unsigned int g_memory
Definition at line 25 of file ospf-global.c.
tw_fd g_ospf_dd_fd
Definition at line 9 of file ospf-global.c.
Referenced by dd_exchange(), ospf_dd_copy(), ospf_dd_event_handler(), ospf_main(), ospf_nbr_neg_done(), and ospf_nbr_two_way_recv().
tw_fd g_ospf_fd
Definition at line 7 of file ospf-global.c.
Referenced by bgp_timer_cancel(), bgp_timer_start(), dd_exchange(), dd_process(), ls_update_process(), ospf_ack_process(), ospf_dd_copy(), ospf_event_handler(), ospf_event_send(), ospf_h_send(), ospf_hello_packet(), ospf_ls_request(), ospf_ls_request_recv(), ospf_ls_update_recv(), ospf_lsa_flush(), ospf_lsa_start_flood(), ospf_main(), ospf_random_weights(), ospf_timer_cancel(), ospf_timer_start(), and process_lsa_recv().
char* g_ospf_init_file
Definition at line 37 of file ospf-global.c.
Referenced by ospf_setup_options().
int g_ospf_link_weight
Definition at line 3 of file ospf-global.c.
Referenced by ospf_experiment_weights(), and ospf_setup_options().
tw_fd g_ospf_ll_fd
Definition at line 10 of file ospf-global.c.
Referenced by bgp_lsa_find(), bgp_lsa_link_allocate(), main_setup_areas(), ospf_db_read(), ospf_lsa_find(), ospf_lsa_link_allocate(), and ospf_main().
tw_memory** g_ospf_lsa
Referenced by DEF(), and getlsa().
tw_fd g_ospf_lsa_fd
Definition at line 8 of file ospf-global.c.
Referenced by ospf_db_read(), ospf_lsa_allocate(), and ospf_main().
FILE* g_ospf_lsa_file
Definition at line 39 of file ospf-global.c.
Referenced by ospf_main(), ospf_md_final(), and ospf_statistics_collection().
FILE* g_ospf_lsa_input
Definition at line 40 of file ospf-global.c.
Referenced by ospf_db_read(), and ospf_main().
FILE* g_ospf_routing_file
Definition at line 38 of file ospf-global.c.
Referenced by ospf_md_final(), ospf_routing_init(), and ospf_setup_options().
int g_ospf_rt_write
Definition at line 19 of file ospf-global.c.
Referenced by ospf_db_init(), ospf_routing_init(), ospf_setup_options(), and ospf_startup().
ospf_global_state* g_ospf_state
Definition at line 12 of file ospf-global.c.
Referenced by neighbor_init(), ospf_setup_options(), and ospf_startup().
ospf_statistics* g_ospf_stats
Definition at line 36 of file ospf-global.c.
Referenced by ospf_main(), ospf_md_final(), and ospf_statistics_collection().
int g_route[]
Definition at line 14 of file ospf-global.c.
Referenced by ospf_db_update(), ospf_startup(), and ospf_statistics_collection().
int g_route1[]
Definition at line 15 of file ospf-global.c.
Referenced by ospf_db_update(), ospf_startup(), and ospf_statistics_collection().
int g_routers
int gr1
Definition at line 16 of file ospf-global.c.
Referenced by ospf_db_update(), and ospf_startup().
int gr2
Definition at line 17 of file ospf-global.c.
Referenced by ospf_db_update(), and ospf_startup().
unsigned int OSPF_LSA_MAX_AGE
Definition at line 21 of file ospf-global.c.
Referenced by bgp_ospf_update(), can_be_removed(), ospf_aging_timer(), ospf_aging_timer_set(), ospf_db_init(), ospf_db_remove(), ospf_db_update(), ospf_lsa_age(), ospf_lsa_create(), ospf_lsa_flush(), ospf_lsa_isnewer(), ospf_lsa_refresh(), ospf_lsa_start_flood(), and process_lsa_recv().
unsigned int OSPF_LSA_REFRESH_AGE
Definition at line 22 of file ospf-global.c.
Referenced by ospf_aging_timer(), ospf_aging_timer_set(), and ospf_db_init().
int* p
Definition at line 27 of file ospf-global.c.
Referenced by init_default_profiles(), init_profiles_from_file(), ospf_routing_init(), ospf_rt_timer(), and percolate_up().
int* s
Definition at line 30 of file ospf-global.c.
Referenced by bgp_ospf_init(), bgp_ospf_update(), epi_agent_stage_tran(), epi_seir_compute(), epi_xml(), get_tod(), init_default_ic_stages(), init_ic_stages_from_file(), ospf_routing_init(), ospf_rt_timer(), rn_event_direct(), rn_event_new(), rn_event_send(), rn_final(), rn_getstream(), rn_timer_init(), rn_timer_simple(), and rn_xml_link_topology().