ROSS.Net: ospf-neighbor-list.c File Reference
ospf-neighbor-list.c File Reference
#include <ospf.h>
Functions
void ospf_list_free (char *list, unsigned int *size)
void ospf_list_unlink (char *list, int index, unsigned int *size)
int ospf_list_contains (char *list, int index)
void ospf_list_link (char *list, int index, unsigned int *size)
Function Documentation
int ospf_list_contains (char * list, int index)
Definition at line 22 of file ospf-neighbor-list.c.
Referenced by ls_update_process(), and process_lsa_recv().
{
        if(list[index] == 1)
                return TW_TRUE;
        return TW_FALSE;
}
void ospf_list_free (char * list, unsigned int * size)
Definition at line 4 of file ospf-neighbor-list.c.
{
        int     i;
        for(i = 0; i < *size; i++)
                list[i] = 0;
        *size = 0;
}
void ospf_list_link (char * list, int index, unsigned int * size)
Definition at line 31 of file ospf-neighbor-list.c.
{
        list[index] = 1;
        (*size)++;
}
void ospf_list_unlink (char * list, int index, unsigned int * size)
Definition at line 15 of file ospf-neighbor-list.c.
Referenced by ls_update_process().
{
        list[index] = 0;
        (*size)--;
}