ROSS.Net: ospf-interface.c File Reference
ospf-interface.c File Reference
#include <ospf.h>
Functions
void ospf_interface_reset (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_calc_dr (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_up (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_waittimer (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_backupseen (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_nbrchange (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_unloopind (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_down (ospf_nbr *nbr, tw_lp *lp)
void ospf_interface_event_handler (ospf_nbr *nbr, ospf_int_event event, tw_lp *lp)
Function Documentation
void ospf_interface_backupseen (ospf_nbr * nbr, tw_lp * lp)
Definition at line 263 of file ospf-interface.c.
References ospf_interface_calc_dr().
Referenced by ospf_interface_event_handler().
{
        ospf_interface_calc_dr(nbr, lp);
}
void ospf_interface_calc_dr (ospf_nbr * nbr, tw_lp * lp)
Definition at line 16 of file ospf-interface.c.
References ospf_nbr_event_handler().
Referenced by ospf_interface_backupseen(), ospf_interface_nbrchange(), and ospf_interface_waittimer().
{
        ospf_state      *r;
        ospf_nbr        *n;
        int              i;
        int              dr;
        int              bdr;
        int              dr_priority;
        int              bdr_priority;
        recalculate:
        r = nbr->router;
        bdr = dr = -1;
        bdr_priority = dr_priority = -1;
        for(i = 0; i < r->n_interfaces; i++)
        {
                n = &r->nbr[i];
                //routers with priority 0 ineligible to become DR
                if(n->priority == 0)
                        continue;
                // only consider rtrs which have established connections
                if(n->state < ospf_nbr_two_way_st)
                        continue;
                // only consider rtrs listing thenselves as designated
                // rtrs to become the new designated rtr
                if(n->designated_r)
                {
                        if(-1 == dr)
{
                                dr = n->id;
                                dr_priority = n->priority;
                        }
                        else
{
                                if(n->priority > dr_priority)
{
                                        dr = n->id;
                                        dr_priority = n->priority;
                                }
                                else if(n->priority == dr_priority &&
                                        n->id > dr)
{
                                        dr = n->id;
                                        dr_priority = n->priority;
                                }
                        }
                }
                // only consider rtrs listing themselves as backups
                // to become the new backup designated rtr
                if(n->b_designated_r)
                {
                        if(-1 == bdr)
{
                                bdr = n->id;
                                bdr_priority = n->priority;
                        }
                        else
{
                                if(n->priority > bdr_priority)
{
                                        bdr = n->id;
                                        bdr_priority = n->priority;
                                }
                                else if(n->priority == bdr_priority && n->id > bdr)
{
                                        bdr = n->id;
                                        bdr_priority = n->priority;
                                }
                        }
                }
        }
        /*
         * Also must consider ourselves in the computation
         */
        if(r->designated_r)
        {
                if(r->priority > dr_priority)
                {
                        dr = lp->id;
                        dr_priority = r->priority;
                }
                else if(r->priority == dr_priority && lp->id > dr)
                {
                        dr = lp->id;
                        dr_priority = r->priority;
                }
        }
        if(r->b_designated_r)
        {
                if(r->priority > bdr_priority)
                {
                        bdr = lp->id;
                        bdr_priority = r->priority;
                }
                else if(r->priority == bdr_priority && lp->id > bdr)
                {
                        bdr = lp->id;
                        bdr_priority = r->priority;
                }
        }
        if(-1 == dr)
        {
                dr = bdr;
                dr_priority = bdr_priority;
        }
        if(-1 == dr)
        {
                printf("%lld: No dr or rdr elected! \n", lp->id);
                r->bdr = -1;
                r->dr = -1;
                return;
        }
        printf("dr : %d \n", dr);
        printf("bdr: %d \n", bdr);
        // if I am currently elected new dr or bdr, recalc
        if((dr == lp->id && r->dr != lp->id) ||
           (bdr == lp->id && r->bdr != lp->id))
                goto recalculate;
        // if I am de-elected as the dr or bdr, recalc
        if((r->dr == lp->id && dr != lp->id) ||
           (r->bdr == lp->id && bdr != lp->id))
                goto recalculate;
        if(dr == lp->id)
        {
                r->istate = ospf_int_dr_other_st;
        }
        if(bdr == lp->id)
        {
                r->istate = ospf_int_backup_st;
        }
        if(r->dr != dr || r->bdr != bdr)
        {
                for(i = 0; i < r->n_interfaces; i++)
                {
                        n = &r->nbr[i];
                        if(n->state >= ospf_nbr_two_way_st)
                                ospf_nbr_event_handler(lp->cur_state, n, ospf_nbr_adj_ok_ev, lp);
                }
        }
        r->dr = dr;
        r->bdr = bdr;
        tw_error(TW_LOC, "New DR: %d, new BDR: %d", r->dr, r->bdr);
        if(r->dr == lp->id && r->bdr == lp->id)
                tw_error(TW_LOC, "%d: Set myself to be dr and bdr!", lp->id);
}
void ospf_interface_down (ospf_nbr * nbr, tw_lp * lp)
Definition at line 338 of file ospf-interface.c.
References ospf_interface_reset(), and ospf_nbr_event_handler().
Referenced by ospf_interface_event_handler().
{
        ospf_interface_reset(nbr, lp);
        ospf_nbr_event_handler(lp->cur_state, nbr, ospf_nbr_kill_nbr_ev, lp);
        nbr->istate = ospf_int_down_st;
        printf("%lld: Interface down: %d \n", lp->id, nbr->id);
}
void ospf_interface_event_handler (ospf_nbr * nbr, ospf_int_event event, tw_lp * lp)
Definition at line 348 of file ospf-interface.c.
References ospf_interface_backupseen(), ospf_interface_down(), ospf_interface_nbrchange(), ospf_interface_unloopind(), ospf_interface_up(), and ospf_interface_waittimer().
Referenced by ospf_hello_packet().
{
        switch(event)
        {
                case ospf_int_up_ev:
                        if(nbr->istate == ospf_int_down_st)
                                ospf_interface_up(nbr, lp);
                        break;
                case ospf_int_waittimer_ev:
                        if(nbr->istate == ospf_int_waiting_st)
                                ospf_interface_waittimer(nbr, lp);
                        break;
                case ospf_int_backupseen_ev:
                        if(nbr->istate == ospf_int_waiting_st)
                                ospf_interface_backupseen(nbr, lp);
                        break;
                case ospf_int_nbrchange_ev:
                        if(nbr->istate == ospf_int_dr_other_st ||
                           nbr->istate == ospf_int_backup_st ||
                           nbr->istate == ospf_int_dr_st)
                                ospf_interface_nbrchange(nbr, lp);
                        break;
                case ospf_int_loopind_ev:
                        ospf_interface_down(nbr, lp);
                        nbr->istate = ospf_int_loopback_st;
                        break;
                case ospf_int_unloopind_ev:
                        if(nbr->istate == ospf_int_loopback_st)
                                ospf_interface_unloopind(nbr, lp);
                        break;
                case ospf_int_down_ev:
                        ospf_interface_down(nbr, lp);
                        break;
                default:
                        tw_error(TW_LOC, "Unknown interface event: %d", event);
        }
}
void ospf_interface_nbrchange (ospf_nbr * nbr, tw_lp * lp)
Definition at line 283 of file ospf-interface.c.
References ospf_interface_calc_dr().
Referenced by ospf_interface_event_handler().
{
        ospf_interface_calc_dr(nbr, lp);
}
void ospf_interface_reset (ospf_nbr * nbr, tw_lp * lp)
Definition at line 7 of file ospf-interface.c.
References ospf_timer_cancel().
Referenced by ospf_interface_down().
{
        nbr->inactivity_timer = ospf_timer_cancel(nbr->inactivity_timer, lp);
}
void ospf_interface_unloopind (ospf_nbr * nbr, tw_lp * lp)
Definition at line 317 of file ospf-interface.c.
Referenced by ospf_interface_event_handler().
{
        nbr->istate = ospf_int_down_st;
}
void ospf_interface_up (ospf_nbr * nbr, tw_lp * lp)
Definition at line 214 of file ospf-interface.c.
References ospf_timer_start().
Referenced by ospf_interface_event_handler().
{
        nbr->inactivity_timer =
                ospf_timer_start(nbr, nbr->inactivity_timer,
                                 nbr->router_dead_interval,
                                OSPF_HELLO_TIMEOUT, lp);
        // assuming broadcast only right now, but future work is to simply
        // check the link type for this interface from the datastructure.
        nbr->istate = ospf_int_point_to_point_st;
        printf("%lld: Interface up: %d \n", lp->id, nbr->id);
}
void ospf_interface_waittimer (ospf_nbr * nbr, tw_lp * lp)
Definition at line 243 of file ospf-interface.c.
References ospf_interface_calc_dr().
Referenced by ospf_interface_event_handler().
{
        ospf_interface_calc_dr(nbr, lp);
}