ROSS.Net: ospf-ack.c File Reference
ospf-ack.c File Reference
#include <ospf.h>
Functions
void ospf_ack_delayed (ospf_nbr *nbr, tw_memory *buf, int size, tw_lp *lp)
void ospf_ack_timed_out (ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_ack_direct (ospf_nbr *nbr, tw_memory *buf, int size, tw_lp *lp)
void ospf_ack_process (ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
Function Documentation
void ospf_ack_delayed (ospf_nbr * nbr, tw_memory * buf, int size, tw_lp * lp)
Definition at line 4 of file ospf-ack.c.
References ospf_timer_start().
{
        if (NULL != nbr->delay_ack_timer)
        {
                // This means that this is the first delayed ack to be added to the
                // queue..
                nbr->delay_ack_timer = ospf_timer_start(nbr, nbr->delay_ack_timer,
                                                        1, OSPF_ACK_TIMEOUT, lp);
        }
        buf->next = nbr->delay;
        nbr->delay = buf;
        nbr->delay_ack_size += size;
}
void ospf_ack_direct (ospf_nbr * nbr, tw_memory * buf, int size, tw_lp * lp)
Definition at line 49 of file ospf-ack.c.
References OSPF_ACK_HEADER, ospf_event_new(), and ospf_event_send().
Referenced by ospf_lsa_flush(), and process_lsa_recv().
{
        tw_event       *e;
        ospf_db_entry  *dbe;
        dbe = tw_memory_data(buf);
        e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_LS_ACK, lp, size + OSPF_ACK_HEADER,
                                                buf, nbr->router->ar->id);
/*
        e = ospf_event_send(nbr->router, tw_getlp(nbr->id), OSPF_LS_ACK,
                                                lp, size + OSPF_ACK_HEADER,
                                                buf, nbr->router->area);
*/
#if VERIFY_OSPF_ACK
        printf("%ld: sending direct ACK for LSA %d to %d at %f, now %f\n",
                   lp->id, dbe->b.entry, nbr->id, e->recv_ts, tw_now(lp));
#endif
}
void ospf_ack_process (ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 75 of file ospf-ack.c.
References g_ospf_fd.
Referenced by ospf_event_handler().
{
        tw_memory      *buf;
        ospf_db_entry  *dbe;
        int             cnt;
        cnt = 0;
        for (buf = tw_event_memory_get(lp); buf; buf = tw_event_memory_get(lp))
        {
                dbe = tw_memory_data(buf);
                tw_memory_free(lp, buf, g_ospf_fd);
        }
#if VERIFY_OSPF_ACK
        if (nbr->state < ospf_nbr_exchange_st)
        {
                printf("%ld: nbr state is %d: LS ACK is ignored\n",
                                lp->id, nbr->state);
                return;
        }
#endif
}
void ospf_ack_timed_out (ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 25 of file ospf-ack.c.
References OSPF_ACK_HEADER, ospf_event_new(), ospf_event_send(), and ospf_timer_cancel().
Referenced by ospf_event_handler().
{
        tw_event        *e;
        e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_LS_ACK, lp,
                                        nbr->delay_ack_size,
                                        nbr->delay, nbr->router->ar->id);
/*
        ospf_event_send(nbr->router, tw_getlp(nbr->id), OSPF_LS_ACK, lp,
                                        nbr->delay_ack_size,
                                        nbr->delay, nbr->router->ar->id);
*/
        nbr->delay = NULL;
        nbr->delay_ack_size = OSPF_ACK_HEADER;
        nbr->delay_ack_timer = ospf_timer_cancel(nbr->delay_ack_timer, lp);
}