ROSS.Net: ospf-neighbor-state.c File Reference
ospf-neighbor-state.c File Reference
#include <ospf.h>
Functions
void ospf_nbr_reset (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_reset_rc (ospf_nbr *nbr, tw_lp *lp)
int ospf_nbr_establish_adjacency (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_exchange_done (ospf_state *state, ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_start (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_inactivity_timer (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_inactivity_timer_rc (ospf_nbr *nbr, tw_bf *bf, tw_lp *lp)
void ospf_nbr_kill_nbr (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_one_way_recv (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_ll_down (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_hello_recv (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_two_way_recv (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_neg_done (ospf_state *state, ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_adj_ok (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_seqnum_mismatch (ospf_nbr *nbr, tw_lp *lp)
void ospf_nbr_event_handler (ospf_state *state, ospf_nbr *nbr, ospf_nbr_event event, tw_lp *lp)
Function Documentation
void ospf_nbr_adj_ok (ospf_nbr * nbr, tw_lp * lp)
Definition at line 491 of file ospf-neighbor-state.c.
References ospf_nbr_establish_adjacency(), and ospf_nbr_two_way_recv().
Referenced by ospf_nbr_event_handler().
{
        if (nbr->state == ospf_nbr_two_way_st)
        {
                if (ospf_nbr_establish_adjacency(nbr, lp))
                {
                        nbr->state = ospf_nbr_init_st;
                        ospf_nbr_two_way_recv(nbr, lp);
                }
        } else if (nbr->state >= ospf_nbr_exstart_st)
        {
                if (ospf_nbr_establish_adjacency(nbr, lp))
                        return;
                nbr->state = ospf_nbr_two_way_st;
        }
}
int ospf_nbr_establish_adjacency (ospf_nbr * nbr, tw_lp * lp)
Definition at line 87 of file ospf-neighbor-state.c.
Referenced by ospf_nbr_adj_ok(), and ospf_nbr_two_way_recv().
{
        return 1;
}
void ospf_nbr_event_handler (ospf_state * state, ospf_nbr * nbr, ospf_nbr_event event, tw_lp * lp)
Definition at line 544 of file ospf-neighbor-state.c.
References ospf_nbr_adj_ok(), ospf_nbr_exchange_done(), ospf_nbr_hello_recv(), ospf_nbr_inactivity_timer(), ospf_nbr_kill_nbr(), ospf_nbr_ll_down(), ospf_nbr_neg_done(), ospf_nbr_one_way_recv(), ospf_nbr_seqnum_mismatch(), ospf_nbr_start(), and ospf_nbr_two_way_recv().
Referenced by dd_process(), ls_update_process(), ospf_dd_event_handler(), ospf_event_handler(), ospf_hello_packet(), ospf_interface_calc_dr(), ospf_interface_down(), ospf_rc_event_handler(), and ospf_routing_init().
{
        switch (event)
        {
        case ospf_nbr_hello_recv_ev:
                ospf_nbr_hello_recv(nbr, lp);
                break;
        case ospf_nbr_start_ev:
                ospf_nbr_start(nbr, lp);
                break;
        case ospf_nbr_one_way_ev:
                ospf_nbr_one_way_recv(nbr, lp);
                break;
        case ospf_nbr_two_way_recv_ev:
                ospf_nbr_two_way_recv(nbr, lp);
                break;
        case ospf_nbr_neg_done_ev:
                ospf_nbr_neg_done(state, nbr, lp);
                break;
        case ospf_nbr_exchange_done_ev:
                ospf_nbr_exchange_done(state, nbr, lp);
                break;
        case ospf_nbr_bad_ls_request_ev:
                if (nbr->state >= ospf_nbr_exchange_st)
                        ospf_nbr_seqnum_mismatch(nbr, lp);
                break;
        case ospf_nbr_load_done_ev:
                if (nbr->state == ospf_nbr_loading_st)
                        nbr->state = ospf_nbr_full_st;
                printf("%lld: new neighbor at full_st: %d \n", lp->id, nbr->id);
                break;
        case ospf_nbr_adj_ok_ev:
                ospf_nbr_adj_ok(nbr, lp);
                break;
        case ospf_nbr_seqnum_mismatch_ev:
                ospf_nbr_seqnum_mismatch(nbr, lp);
                break;
        case ospf_nbr_kill_nbr_ev:
                ospf_nbr_kill_nbr(nbr, lp);
                break;
        case ospf_nbr_inactivity_timer_ev:
                ospf_nbr_inactivity_timer(nbr, lp);
                break;
        case rc_ospf_nbr_inactivity_timer_ev:
                ospf_nbr_inactivity_timer(nbr, lp);
                break;
        case ospf_nbr_ll_down_ev:
                ospf_nbr_ll_down(nbr, lp);
                break;
        default:
                tw_error(TW_LOC, "Unknown nbr event: %d", event);
        }
}
void ospf_nbr_exchange_done (ospf_state * state, ospf_nbr * nbr, tw_lp * lp)
Definition at line 114 of file ospf-neighbor-state.c.
References ospf_ls_request(), ospf_lsa_create(), ospf_timer_cancel(), and rn_getarea().
Referenced by ospf_nbr_event_handler().
{
        if(nbr->nrequests == 0)
        {
                nbr->state = ospf_nbr_full_st;
                if(nbr->ar == nbr->router->ar)
                {
                        //state->stats->s_cause_ospf++;
                        ospf_lsa_create(state, nbr,
                                        lp->id - state->m->subnet->area->low, lp);
                } else
                {
                        //state->stats->s_cause_ospf++;
                        ospf_lsa_create(nbr->router, nbr,
                                rn_getarea(nbr->m)->id +
                                nbr->router->m->subnet->area->nmachines, lp);
                }
                printf("%lld: Exchange done: nbr %d full \n", lp->id, nbr->id);
                // Cancel the retrans timer now that I have recv'd the
                // response to my LS_REQUEST
                nbr->retrans_timer = ospf_timer_cancel(nbr->retrans_timer, lp);
        } else
        {
                nbr->state = ospf_nbr_loading_st;
                ospf_ls_request(state, nbr, lp);
                printf("%lld: Exchange done: nbr %d loading \n", lp->id, nbr->id);
        }
}
void ospf_nbr_hello_recv (ospf_nbr * nbr, tw_lp * lp)
Definition at line 289 of file ospf-neighbor-state.c.
References ospf_timer_start().
Referenced by ospf_nbr_event_handler().
{
        switch (nbr->state)
        {
        case ospf_nbr_attempt_st:
        case ospf_nbr_down_st:
                nbr->state = ospf_nbr_init_st;
                /*
                 * all other states
                 */
        default:
                nbr->inactivity_timer =
                        ospf_timer_start(nbr, nbr->inactivity_timer,
                                         nbr->router_dead_interval,
                                         OSPF_HELLO_TIMEOUT, lp);
        }
}
void ospf_nbr_inactivity_timer (ospf_nbr * nbr, tw_lp * lp)
Definition at line 178 of file ospf-neighbor-state.c.
References ospf_lsa_create(), ospf_nbr_reset(), and rn_getarea().
Referenced by ospf_nbr_event_handler().
{
#if VERIFY_LS
        printf("%ld OSPF: removing nbr %d from full st, HELLO timeout!\n",
                        lp->id, nbr->id);
#endif
        if (nbr->state == ospf_nbr_full_st)
        {
                nbr->state = ospf_nbr_down_st;
                // this will also rebuild routing table for me..
                if(nbr->ar == nbr->router->ar)
                {
                        ospf_lsa_create(nbr->router, nbr,
                                lp->id - nbr->router->m->subnet->area->low, lp);
                } else
                {
                        ospf_lsa_create(nbr->router, nbr,
                                rn_getarea(nbr->m)->id +
                                nbr->router->m->subnet->area->nmachines -
                                nbr->router->m->subnet->area->as->low, lp);
                }
                ospf_nbr_reset(nbr, lp);
        } else
                ospf_nbr_reset(nbr, lp);
}
void ospf_nbr_inactivity_timer_rc (ospf_nbr * nbr, tw_bf * bf, tw_lp * lp)
Definition at line 209 of file ospf-neighbor-state.c.
References ospf_nbr_reset_rc().
{
        ospf_nbr_reset_rc(nbr, lp);
        if(bf->c1 == 1)
        {
                //ospf_lsa_create_rc(nbr->router, nbr, lp->id - nbr->router->m->subnet->area->low, lp);
        }
}
void ospf_nbr_kill_nbr (ospf_nbr * nbr, tw_lp * lp)
Definition at line 232 of file ospf-neighbor-state.c.
References ospf_nbr_reset().
Referenced by ospf_nbr_event_handler().
{
        //printf("%ld: KILLING NBR %d !!! \n", lp->id, nbr->id);
        ospf_nbr_reset(nbr, lp);
}
void ospf_nbr_ll_down (ospf_nbr * nbr, tw_lp * lp)
Definition at line 271 of file ospf-neighbor-state.c.
References ospf_nbr_reset().
Referenced by ospf_nbr_event_handler().
{
        ospf_nbr_reset(nbr, lp);
}
void ospf_nbr_neg_done (ospf_state * state, ospf_nbr * nbr, tw_lp * lp)
Definition at line 407 of file ospf-neighbor-state.c.
References g_ospf_dd_fd, ospf_dd_copy(), OSPF_DD_HEADER, ospf_event_new(), ospf_event_send(), OSPF_RETRANS_INTERVAL, and ospf_timer_start().
Referenced by ospf_nbr_event_handler().
{
        tw_event        *e;
        tw_memory       *b;
        ospf_dd_pkt     *dd;
        if (nbr->state != ospf_nbr_exstart_st)
                tw_error(TW_LOC, "Invalid state for nbr_neg_done!");
        nbr->state = ospf_nbr_exchange_st;
        // master must wait for slave to reply with master's seqnum
        if(0 == nbr->master)
                return;
        // send dd pkt
        b = tw_memory_alloc(lp, g_ospf_dd_fd);
        dd = tw_memory_data(b);
        dd->b.init = 0;
        dd->b.more = 1;
        if(nbr->master)
        {
                //nbr->dd_seqnum++;
                dd->b.master = 0;
        } else
                dd->b.master = 1;
        dd->seqnum = nbr->dd_seqnum;
        dd->nlsas = 0;
        e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
        ospf_event_send(nbr->router, e, OSPF_DD_MSG, lp,
                        OSPF_DD_HEADER, b, nbr->router->ar->id);
        printf("%lld OSPF: send Exchange to %d %lf, seqnum %d, nbr %d master %d \n",
                lp->id, nbr->id, e->recv_ts, dd->seqnum, nbr->id, nbr->master);
        nbr->retrans_dd = ospf_dd_copy(b, lp);
        nbr->retrans_timer =
                        ospf_timer_start(nbr, nbr->retrans_timer,
                                                OSPF_RETRANS_INTERVAL,
                                                OSPF_RETRANS_TIMEOUT,
                                                lp);
}
void ospf_nbr_one_way_recv (ospf_nbr * nbr, tw_lp * lp)
Definition at line 252 of file ospf-neighbor-state.c.
Referenced by ospf_nbr_event_handler().
{
        if (nbr->state >= ospf_nbr_two_way_st)
                nbr->state = ospf_nbr_init_st;
}
void ospf_nbr_reset (ospf_nbr * nbr, tw_lp * lp)
Definition at line 11 of file ospf-neighbor-state.c.
References getlsa(), ospf_db_remove(), ospf_lsa_flush(), ospf_rt_build(), ospf_timer_cancel(), rn_getarea(), rn_getas(), and rn_getmachine().
Referenced by ospf_nbr_inactivity_timer(), ospf_nbr_kill_nbr(), and ospf_nbr_ll_down().
{
        rn_machine      *m;
        rn_area         *ar;
        ospf_lsa        *lsa;
        int              id;
        m = nbr->router->m;
        nbr->state = ospf_nbr_down_st;
        nbr->inactivity_timer = ospf_timer_cancel(nbr->inactivity_timer, lp);
        nbr->retrans_accum = 0;
        nbr->next_retransmit = -1;
        nbr->retrans_timer = NULL;
        nbr->flood = NULL;
        nbr->dd_seqnum = tw_rand_integer(lp->rng, 0, INT_MAX);
        ar = rn_getarea(rn_getmachine(lp->id));
        if(ar == rn_getarea(nbr->m))
                id = nbr->id - ar->low;
        else if(ar->as == rn_getas(nbr->m))
                id = ar->nmachines + nbr->ar->id - rn_getas(nbr->m)->low;
        else
                id = ar->nmachines + ar->as->nareas + rn_getas(nbr->m)->id;
        // Remove the neighbor LSA
        ospf_db_remove(nbr->router, id, lp);
        // Remove any other LSAs originated by this neighbor ..
        for(id = ar->nmachines; id < ar->g_ospf_nlsa; id++)
        {
                lsa = getlsa(nbr->router->m, nbr->router->db[id].lsa, id);
                if(m->link[m->ft[lsa->adv_r]].addr == nbr->id)
                {
                        ospf_lsa_flush(nbr->router, nbr, &nbr->router->db[id], lp);
                        ospf_db_remove(nbr->router, id, lp);
                }
        }
        ospf_rt_build(nbr->router, lp->id);
}
void ospf_nbr_reset_rc (ospf_nbr * nbr, tw_lp * lp)
Definition at line 56 of file ospf-neighbor-state.c.
Referenced by ospf_nbr_inactivity_timer_rc().
{
        tw_error(TW_LOC, "Unable to rollback nbr state yet!");
        //nbr->state = nbr->rc_state;
}
void ospf_nbr_seqnum_mismatch (ospf_nbr * nbr, tw_lp * lp)
Definition at line 532 of file ospf-neighbor-state.c.
References ospf_nbr_two_way_recv().
Referenced by ospf_nbr_event_handler().
{
        nbr->state = ospf_nbr_init_st;
        ospf_nbr_two_way_recv(nbr, lp);
        tw_error(TW_LOC, "Should not be getting mismatched seqnums on DD pkts!");
}
void ospf_nbr_start (ospf_nbr * nbr, tw_lp * lp)
Definition at line 152 of file ospf-neighbor-state.c.
References ospf_timer_start().
Referenced by ospf_nbr_event_handler().
{
        if (nbr->state == ospf_nbr_down_st)
        {
                printf("%lld: setting nbr %d to attempt!\n", lp->id, nbr->id);
                nbr->state = ospf_nbr_attempt_st;
        }
        nbr->inactivity_timer =
                ospf_timer_start(nbr, nbr->inactivity_timer, nbr->router_dead_interval,
                                                 OSPF_HELLO_TIMEOUT, lp);
}
void ospf_nbr_two_way_recv (ospf_nbr * nbr, tw_lp * lp)
Definition at line 334 of file ospf-neighbor-state.c.
References g_ospf_dd_fd, ospf_dd_copy(), OSPF_DD_HEADER, ospf_event_new(), ospf_event_send(), ospf_nbr_establish_adjacency(), OSPF_RETRANS_INTERVAL, and ospf_timer_start().
Referenced by ospf_nbr_adj_ok(), ospf_nbr_event_handler(), and ospf_nbr_seqnum_mismatch().
{
        tw_event        *e;
        tw_memory       *b;
        ospf_dd_pkt     *dd;
        if (nbr->state != ospf_nbr_init_st)
                return;
        if (ospf_nbr_establish_adjacency(nbr, lp))
        {
                // send dd pkt
                b = tw_memory_alloc(lp, g_ospf_dd_fd);
                dd = tw_memory_data(b);
                nbr->state = ospf_nbr_exstart_st;
                nbr->master = 0;
                dd->b.init = 1;
                dd->b.more = 1;
                dd->b.master = 1;
                dd->seqnum = ++nbr->dd_seqnum;
                dd->nlsas = 0;
                nbr->retrans_dd = ospf_dd_copy(b, lp);
                e = ospf_event_new(nbr->router, tw_getlp(nbr->id), 0.0, lp);
                ospf_event_send(nbr->router, e, OSPF_DD_MSG,
                                lp, OSPF_DD_HEADER, b, nbr->router->ar->id);
                printf("%lld OSPF: send ExStart to %d, %lf: I %d, M %d, Master %d \n",
                        lp->id, nbr->id, e->recv_ts, dd->b.init, dd->b.more, dd->b.master);
                nbr->retrans_timer =
                        ospf_timer_start(nbr, nbr->retrans_timer,
                                                OSPF_RETRANS_INTERVAL,
                                                OSPF_RETRANS_TIMEOUT,
                                                lp);
        } else
        {
                tw_error(TW_LOC, "Only simulating broadcast networks!");
        }
}