ROSS.Net: queue-heap.c File Reference
queue-heap.c File Reference
#include <epi.h>
Defines
#define KEY(e) (e->ts_next)
#define SWAP(heap, x, y, t)
Typedefs
typedef double KEY_TYPE
Functions
FWD (struct, CHeap)
DEF (struct, CHeap)
epi_agent * HeapPeekTop (CHeap *h)
void sift_down (CHeap *h, int i)
void percolate_up (CHeap *h, int i)
void pq_enqueue (void *pq, epi_agent *e)
void * pq_dequeue (void *pq)
void DumpBucket (void *pq, FILE *fp)
void pq_delete_any (void *pq, epi_agent **q)
void * pq_create (void)
tw_stime pq_minimum (void *pq)
void * pq_top (void *pq)
void * pq_next (void *h, int next)
unsigned int pq_get_size (void *pq)
Define Documentation
#define KEY (e) (e->ts_next)
Definition at line 60 of file queue-heap.c.
Referenced by DumpBucket(), percolate_up(), pq_delete_any(), pq_minimum(), and sift_down().
#define SWAP (heap, x, y, t)
Value:
{ \
    t = heap->elems[x]; \
    heap->elems[x] = heap->elems[y]; \
    heap->elems[y] = t; \
    heap->elems[x]->heap_index = x; \
    heap->elems[y]->heap_index = y; \
    }
Definition at line 71 of file queue-heap.c.
Referenced by percolate_up(), and sift_down().
Typedef Documentation
typedef double KEY_TYPE
Definition at line 59 of file queue-heap.c.
Function Documentation
DEF (struct , CHeap)
Definition at line 64 of file queue-heap.c.
{
  long nelems;
  int curr_max;
  epi_agent **elems; /* Array [0..curr_max] of epi_agent * */
};
void DumpBucket (void * pq, FILE * fp)
Definition at line 166 of file queue-heap.c.
References KEY.
{
  int i;
  CHeap *h = (CHeap *)(pq);
  fprintf( fp, "[ " );
  for( i = 0; i < h->nelems; i++ )
    {
      fprintf( fp, "%s", ( i && i % 10 == 0 ) ? "\n\t" : "" );
      fprintf( fp, "%s%lf", (i ? ", ":""), KEY(h->elems[i]) );
    }
  fprintf( fp, " ]\n" );
  fflush( fp );
}
FWD (struct , CHeap)
epi_agent* HeapPeekTop (CHeap * h) [inline]
Definition at line 80 of file queue-heap.c.
Referenced by pq_minimum(), and pq_top().
{
  return (h->nelems <= 0) ? 0 : h->elems[0];
}
void percolate_up (CHeap * h, int i)
Definition at line 105 of file queue-heap.c.
References KEY, p, and SWAP.
Referenced by pq_delete_any(), and pq_enqueue().
{
  int n = h->nelems, k = i, j, p;
  epi_agent * temp;
  if( n <= 1 ) return;
  /* Stops when parent is "less than or equal to" child */
  do
    {
      j = k;
      if( (p = (k+1)/2) )
        {
          --p;
          if( KEY(h->elems[k]) < KEY(h->elems[p]) ) k = p;
        }
      SWAP( h, j, k, temp );
    }while( j != k );
}
void* pq_create (void)
Definition at line 207 of file queue-heap.c.
{
  CHeap *h = (CHeap *)malloc(sizeof(CHeap));
  h->nelems = 0;
  h->curr_max = (10);
  h->elems = (epi_agent **)malloc(sizeof(epi_agent *)*h->curr_max);
  if( !h->elems ) { fprintf( stderr, "Failed to create heap\n" ); exit(1); }
/*  printf("Initialized Heap. Allocated %ld bytes\n", sizeof(epi_agent *)*h->curr_max); */
  fflush(stdout);
  return (void *)h;
}
void pq_delete_any (void * pq, epi_agent ** q)
Definition at line 181 of file queue-heap.c.
{
  CHeap *h = (CHeap *)(pq);
  epi_agent * victim = *q;
  int i = victim->heap_index;
  if( !(0 <= i && i < h->nelems) || (h->elems[i]->heap_index != i) )
    {
      fprintf( stderr, "Fatal: Bad node in FEL!\n" ); exit(2);
    }
  else
    {
      h->nelems--;
      if( h->nelems > 0 )
        {
          epi_agent * successor = h->elems[h->nelems];
          h->elems[i] = successor;
          successor->heap_index = i;
          if( KEY(successor) <= KEY(victim) ) percolate_up( h, i );
          else sift_down( h, i );
        }
    }
}
void* pq_dequeue (void * pq)
Definition at line 149 of file queue-heap.c.
{
  CHeap *h = (CHeap *)pq;
  if( h->nelems <= 0 )
    return 0;
  else
    {
      epi_agent * e = h->elems[0];
      h->elems[0] = h->elems[--h->nelems];
      h->elems[0]->heap_index = 0;
      sift_down( h, 0 );
      return e;
    }
}
void pq_enqueue (void * pq, epi_agent * e)
Definition at line 126 of file queue-heap.c.
{
  CHeap *h = (CHeap *)pq;
  if( h->nelems >= h->curr_max )
    {
      h->elems = (epi_agent **)
        realloc(h->elems, sizeof(epi_agent *)*(h->curr_max + 50));
      if( !h->elems ) {fprintf(stderr,"Can't expand heap!\n"); exit(1);}
      //else {fprintf(stderr,"Expanded heap to %d!\n", h->curr_max + 50);}
      h->curr_max += 50;
    }
  e->heap_index = h->nelems;
  h->elems[h->nelems++] = e;
  percolate_up( h, h->nelems-1 );
  e->next = NULL;
  e->prev = NULL;
}
unsigned int pq_get_size (void * pq)
Definition at line 245 of file queue-heap.c.
{
  return ( ((CHeap *)pq)->nelems );
}
tw_stime pq_minimum (void * pq)
Definition at line 222 of file queue-heap.c.
{
  epi_agent * e = HeapPeekTop( (CHeap*)(pq) );
  double retval = e ? KEY(e) : HUGE_VAL;
  return retval;
}
void* pq_next (void * h, int next)
Definition at line 240 of file queue-heap.c.
{
        return ((CHeap *) h)->elems[next];
}
void* pq_top (void * pq)
Definition at line 231 of file queue-heap.c.
{
  return HeapPeekTop( (CHeap*)(pq) );
}
void sift_down (CHeap * h, int i)
Definition at line 86 of file queue-heap.c.
References KEY, and SWAP.
Referenced by pq_delete_any(), and pq_dequeue().
{
  int n = h->nelems, k = i, j, c1, c2;
  epi_agent * temp;
  if( n <= 1 ) return;
  /* Stops when neither child is "strictly less than" parent */
  do{
    j = k;
    c1 = c2 = 2*k+1;
    c2++;
    if( c1 < n && KEY(h->elems[c1]) < KEY(h->elems[k]) ) k = c1;
    if( c2 < n && KEY(h->elems[c2]) < KEY(h->elems[k]) ) k = c2;
    SWAP( h, j, k, temp );
  }while( j != k );
}