ROSS.Net: rn-as.c File Reference
rn-as.c File Reference
#include <rossnet.h>
Functions
rn_as * rn_nextas (rn_as *as)
Functions relating to an Autonomous System.
Function Documentation
rn_as* rn_nextas (rn_as * as)
Functions relating to an Autonomous System.
This file provides functionality for the AS data type in rossnet.
Definition at line 7 of file rn-as.c.
References g_rn_as, and g_rn_nas.
Referenced by bgp_setup_ases(), rn_xml_topology(), and verify_topology().
{
        if(as == NULL)
                return g_rn_as;
        if(as->id == g_rn_nas - 1)
                return NULL;
        return &g_rn_as[as->id+1];
}