ROSS.Net: rn-extern.h File Reference
rn-extern.h File Reference
Functions
void * rn_hash_create (unsigned int)
void rn_hash_insert (void *h, rn_link *)
rn_link * rn_hash_remove (void *h, rn_link *)
rn_link * rn_hash_fetch (void *h, int id)
int rn_route (rn_machine *m, tw_lpid dst)
int rn_route_change (rn_machine *m, int loc, int new_val)
void rn_ft_route_add (tw_lp *lp, int id)
void rn_ft_route_del (tw_lp *lp, int id)
tw_event * rn_timer_simple (tw_lp *lp, tw_stime ts)
tw_event * rn_timer_init (tw_lp *lp, tw_stime ts)
tw_event * rn_timer_reset (tw_lp *lp, tw_event **e, tw_stime ts)
void rn_timer_cancel (tw_lp *lp, tw_event **e)
rn_as * rn_nextas (rn_as *as)
Functions relating to an Autonomous System.
char * xml_getprop (xmlNode *node, char *prop)
void rn_xml_init ()
void rn_xml_end ()
void rn_xml_topology ()
void rn_xml_link_topology ()
void rn_xml_model ()
xmlXPathObjectPtr xpath (char *expr, xmlXPathContextPtr ctxt)
rn_area * rn_nextarea (rn_area *as)
rn_area * rn_nextarea_onas (rn_area *ar, rn_as *as)
rn_subnet * rn_nextsn_onarea (rn_subnet *sn, rn_area *ar)
rn_machine * rn_nextmachine_onsn (rn_machine *m, rn_subnet *sn)
rn_as * rn_getas (rn_machine *m)
rn_area * rn_getarea (rn_machine *m)
rn_subnet * rn_getsubnet (rn_machine *m)
rn_machine * rn_getmachine (tw_lpid id)
void rn_setmachine (rn_machine *m)
void rn_machine_print (rn_machine *m)
rn_link_status rn_link_getstatus (rn_link *l, tw_stime ts)
void rn_link_random_weight_changes (tw_lp *lp)
void rn_link_random_changes (tw_lp *)
void rn_link_setwire (rn_link *l)
rn_machine * rn_link_getwire (rn_link *l)
rn_link * rn_getlink (rn_machine *m, tw_lpid id)
void rn_message_setsize (rn_message *e, unsigned long sz)
unsigned long rn_message_getsize (rn_message *e)
void * rn_message_data (rn_message *m)
void rn_message_setdirection (rn_message *m, rn_message_type direction)
int rn_message_getdirection (rn_message *m)
tw_event * rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp *src)
tw_event * rn_event_new (tw_lpid dst, tw_stime ts, tw_lp *src, rn_message_type dir, unsigned long int size)
void * rn_event_data (tw_event *e)
void rn_event_send (tw_event *e)
void rn_setup_streams (rn_lp_state *state, rn_lptype *types, tw_lp *lp)
void rn_setup_links (rn_lp_state *state, tw_lp *lp)
void rn_setup_options (int argc, char **argv)
void rn_setup ()
int rn_init (rn_lptype *types)
void rn_init_streams (rn_lp_state *state, tw_lp *lp)
void rn_init_lps (rn_lptype *types)
void rn_models_init (rn_lptype *, int, char **, char **)
void rn_models_final (rn_lptype *types)
void * rn_getstate (tw_lp *lp)
tw_lp * rn_getlp (rn_lp_state *state, int id)
tw_lp * rn_next_lp (rn_lp_state *state, tw_lp *last, int type)
rn_lptype * rn_lp_gettype (tw_lp *lp)
void rn_lp_settype (tw_lp *lp, char *name)
rn_layer * rn_layer_alloc (unsigned int nlayers)
rn_stream * rn_stream_alloc (unsigned int nstreams)
rn_stream * rn_getstream (tw_lp *lp)
rn_stream * rn_getstream_byport (rn_lp_state *state, tw_lpid port)
Variables
int g_rn_link_prob
int g_rn_converge_ospf
int g_rn_converge_bgp
int g_rn_src
int g_rn_dst
xmlDocPtr document_network
xmlDocPtr document_links
xmlDocPtr document_model
xmlXPathContextPtr ctxt
xmlXPathContextPtr ctxt_links
xmlXPathContextPtr ctxt_model
unsigned char g_rn_ttl
unsigned int g_rn_msg_sz
char g_rn_tools_dir []
char g_rn_rt_table []
char g_rn_xml_topology []
char g_rn_xml_link_topology []
char g_rn_xml_model []
char g_rn_logs_dir []
rn_statistics * g_rn_stats
rn_lptype * g_rn_lptypes
unsigned int g_rn_nas
rn_as * g_rn_as
unsigned int g_rn_nareas
rn_area * g_rn_areas
unsigned int g_rn_nsubnets
rn_subnet * g_rn_subnets
unsigned int g_rn_nlinks
unsigned int g_rn_nlink_status
unsigned int g_rn_nmachines
unsigned int g_rn_nrouters
rn_machine * g_rn_machines
unsigned int g_rn_nstreams
rn_stream * g_rn_streams
unsigned int g_rn_nextstream
unsigned int g_rn_nlayers
rn_layer * g_rn_layers
unsigned int g_rn_nextlayer
tw_barrier g_rn_barrier
tw_mutex g_rn_layer_lck
tw_mutex g_rn_stream_lck
Function Documentation
void* rn_event_data (tw_event * e)
Definition at line 167 of file rn-event.c.
References rn_message_data().
Referenced by ftp_event_handler(), ospf_ip_route(), and tcp_layer_util_event().
{
        return (void *) rn_message_data((rn_message *) tw_event_data(e));
}
tw_event* rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp * src)
Definition at line 8 of file rn-event.c.
References DIRECT, rn_getstream(), and s.
Referenced by epi_agent_remove(), epi_num_add(), epi_num_check_report(), and epi_num_remove().
{
        tw_event        *e;
        rn_lp_state     *state;
        rn_stream       *s;
        rn_message      *m;
        state = src->cur_state;
        s = rn_getstream(src);
        e = tw_event_new(dst, ts, src);
        m = tw_event_data(e);
        m->type = DIRECT;
        m->timer = state->cur_lp;
        m->size = s->cur_layer;
        m->port = s->port;
        m->src = src->id;
        m->dst = dst;
        return e;
}
tw_event* rn_event_new (tw_lpid dst, tw_stime ts, tw_lp * src, rn_message_type dir, unsigned long int size)
inter-lp: events which will be sent to a remote lp
inter-lp events are handled as usual
intra-lp: events which are sent to another layer on the same lp
intra-lp events are immediately scheduled and processed, because their destination is the local machine, and have a zero timestamp offset, which means the following:
the next layer is responsible for handling packet data, ie, from TCP to IP. The IP layer must re-create the TCP packect on the dest LP.
abort events: should not let them traverse layers.. first layer to get abort is then the only one to get rolled back
NOTE: We should probably base the timestamp off of the network characteristics, rather than make the model do it. When the model calls this function, and is the last layer, we should know the proper link to use, and can inform the model if this event will fail if sent, over the network.
Definition at line 58 of file rn-event.c.
References DOWNSTREAM, g_rn_ttl, rn_getmachine(), rn_getstream(), rn_link_down, rn_link_getstatus(), s, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), forward(), ftp_event_handler(), ftp_init(), ip_packet_drop(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_new(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().
{
        tw_event        *e;
        tw_stime         abs_ts = DBL_MAX;
        rn_lp_state     *state;
        rn_message      *r;
        rn_stream       *s;
        rn_machine      *m;
        //rn_link               *l;
        state = src->cur_state;
        s = rn_getstream(src);
        m = rn_getmachine(src->id);
        //l = rn_getlink(m, dst->id);
        // if model attempts to send upstream event, and is
        // top-most layer, abort processing
        if(dir == UPSTREAM && !s->cur_layer)
                return src->pe->abort_event;
        // Check for layer switching directions on us..
        if(state->cev)
        {
                r = tw_event_data(state->cev);
                if(r->type == UPSTREAM && dir == DOWNSTREAM)
                {
                        state->cev = NULL;
                } else if(r->type != dir && dir == UPSTREAM)
                {
                        state->cev = src->pe->cur_event;
                        abs_ts = state->cev->recv_ts + ts;
                }
        }
#if 0
        if(l && state->cev && rn_link_down == rn_link_getstatus(l, abs_ts))
        {
                e = src->pe->free_q->abort;
                e->src_lp = src;
                e->dest_lp = dst;
                e->recv_ts = tw_now(src) + ts;
                r = tw_event_data(src->pe->free_q->abort);
                r->type = dir;
                r->src = src->id;
                r->dst = dst->id;
                r->size = size;
                r->port = s->port;
                r->timer = NULL;
#if VERIFY_RN
                printf("%ld RN: new ABORT event %d, port %d \n",
                        src->id, (int) e, r->port);
#endif
                return e;
        }
#endif
        if(!state->cev)
        {
                e = tw_event_new(dst, ts, src);
                state->cev = e;
                r = tw_event_data(e);
                r->type = dir;
                r->src = src->id;
                r->dst = dst;
                r->size = size;
                r->port = s->port;
                r->timer = NULL;
                r->ttl = g_rn_ttl;
#if VERIFY_RN
                printf("%ld RN: Created new event %ld, port %d \n",
                        src->id, (long int) e, r->port);
#endif
        } else
        {
                e = state->cev;
                e->recv_ts += ts;
                r = tw_event_data(e);
                r->size = size;
                if(e->recv_ts > g_tw_ts_end)
                        src->pe->cev_abort = 1;
                //if((tw_lpid) e->dest_lp != dst)
                if(r->dst != dst)
                {
#if VERIFY_RN
                        printf("Redirecting event %ld: from %lld to %lld \n",
                                (long int) e, (tw_lpid) e->dest_lp, dst);
#endif
                        e->dest_lp = (tw_lp *) dst;
                }
        }
        return e;
}
void rn_event_send (tw_event * e)
Definition at line 173 of file rn-event.c.
References c_host, DIRECT, DOWNSTREAM, rn_getmachine(), rn_getstream(), rn_getstream_byport(), s, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), epi_agent_remove(), epi_num_add(), epi_num_check_report(), epi_num_remove(), ftp_event_handler(), ftp_init(), ip_downstream_forward(), ip_downstream_source(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_send(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().
{
        tw_memory       *b;
        tw_lp           *l = NULL;
        rn_lp_state     *state = NULL;
        rn_stream       *s = NULL;
        rn_message      *rn_msg;
        rn_machine      *m;
        rn_msg = tw_event_data(new_event);
        if(new_event->src_lp == NULL || new_event->src_lp->pe->cev_abort)
        {
                return;
        } else if(rn_msg->type == DOWNSTREAM)
        {
                state = (rn_lp_state *) new_event->src_lp->cur_state;
                s = rn_getstream(new_event->src_lp);
        } else if(rn_msg->type == UPSTREAM)
        {
                state = (rn_lp_state *) new_event->dest_lp->cur_state;
                s = rn_getstream_byport(state, rn_msg->port);
        } else if(rn_msg->type == DIRECT)
        {
                tw_event_send(new_event);
                return;
#if 0
                /*
                 * This is totally out-of-band .. similiar to a SIG_ALARM
                 * on the local machine
                 */
                state = (rn_lp_state *) new_event->src_lp->cur_state;
                s = rn_getstream(new_event->src_lp);
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg, l);
                return;
#endif
        } else
        {
                tw_error(TW_LOC, "Unknown event type sent!");
        }
        /*
         * If direction is UP, and more layers, send up to next layer.
         * If direction is down, and more layers, send down to next layer
         *
         * If direction is UP, and at top, nowhere else to go,
         *                      so done, consider it processed.
         *
         * If direction is down, and no more layers, tw_event_send it.
         */
        if(rn_msg->type == UPSTREAM && s->cur_layer > 0)
        {
                s->cur_layer--;
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                if(s->cur_layer == 0)
                        state->cev = NULL;
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: layer %d sending msg UP, src %d,  dst %d, %lf \n",
                        (int) l->id,
                        s->cur_layer + 1,
                        (int) new_event->src_lp->id,
                        (int) new_event->dest_lp->id,
                        new_event->recv_ts);
#endif
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg,
                        new_event->dest_lp);
                s->cur_layer++;
                state->cur_lp = &s->layers[s->cur_layer].lp;
                state->l_stats.s_nevents_processed++;
        } else if(rn_msg->type == DOWNSTREAM && s->cur_layer < s->nlayers - 1)
        {
                s->cur_layer++;
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                if(!l)
                        tw_error(TW_LOC, "NO LP!");
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: layer %d sending msg DOWN, dst %d, ts %f \n",
                        (int) l->id,
                        (int) s->cur_layer - 1,
                        (int) new_event->dest_lp->id,
                        new_event->recv_ts);
#endif
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg,
                        new_event->src_lp);
                // Restore the cur_layer when this lvl of recursion is complete
                s->cur_layer--;
                state->cev = NULL;
                state->cur_lp = &s->layers[s->cur_layer].lp;
                state->l_stats.s_nevents_processed++;
        } else if(rn_msg->type == DOWNSTREAM)
        {
                // Ok, so now we have reached the bottom of the stack and
                // can remove the event finally.
                if(new_event->src_lp->pe->cev_abort)
                {
                        while(NULL != (b = new_event->memory))
{
                                new_event->memory = b->next;
                                tw_memory_alloc_rc(new_event->src_lp, b, (tw_fd) b->prev);
                        }
                        return;
                }
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: Sending remote event (%d) from layer %d: %d -%f-> %d \n",
                                (int) new_event->src_lp->id,
                                (int) new_event,
                                s->cur_layer,
                                (int) new_event->src_lp->id,
                                new_event->recv_ts,
                                (int) new_event->dest_lp->id);
#endif
                /*
                 * This is where we would want to do things like fixing up
                 * the timestamp on the
                 * message, and the dest_lp pointer in the event.  We need to
                 * change the dest_lp appropriately in order to reflect
                 * the final destination considering the connection and/or nbr
                 */
                rn_msg->type = UPSTREAM;
                m = rn_getmachine(new_event->src_lp->id);
                if(m->type == c_host)
                        new_event->dest_lp = (tw_lp *) m->link[0].addr;
                tw_event_send(new_event);
                state->cev = NULL;
        } else if(rn_msg->type == UPSTREAM)
        {
                tw_error(TW_LOC, "%lld: sending message up, top-most layer!? \n",
                                new_event->src_lp->gid);
        } else
        {
                tw_error(TW_LOC, "no send?");
        }
}
void rn_ft_route_add (tw_lp * lp, int id)
This file contains all of the externable objects in rossnet.
void rn_ft_route_del (tw_lp * lp, int id)
rn_area* rn_getarea (rn_machine * m)
Definition at line 22 of file rn-machine.c.
Referenced by bgp_init(), bgp_keepalive(), bgp_ospf_init(), bgp_ospf_update(), bgp_route_add(), bgp_route_withdraw(), bgp_xml(), epi_xml(), getlsa(), lsa_create(), main_setup_areas(), ospf_db_init(), ospf_lsa_create(), ospf_nbr_exchange_done(), ospf_nbr_inactivity_timer(), ospf_nbr_reset(), ospf_rt_print(), ospf_rt_timer(), ospf_startup(), ospf_xml(), and rn_route().
{
        return m->subnet->area;
}
rn_as* rn_getas (rn_machine * m)
Definition at line 28 of file rn-machine.c.
Referenced by bgp_decision(), bgp_final(), bgp_init(), bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_open(), bgp_open_send(), bgp_rib_print(), bgp_route_add(), bgp_route_copy(), bgp_route_new(), bgp_update_all(), bgp_update_send(), bgp_xml(), deal_with_timed_out_routers(), ospf_event_handler(), ospf_nbr_reset(), ospf_xml(), rn_route(), update_add(), and update_withdraw().
{
        return m->subnet->area->as;
}
rn_link* rn_getlink (rn_machine * m, tw_lpid id)
Definition at line 17 of file rn-link.c.
References rn_hash_fetch().
Referenced by bgp_connect(), bgp_init(), bgp_lsa_find(), bgp_route_add(), bgp_route_copy(), getroute(), ip_route(), neighbor_init(), ospf_lsa_create(), ospf_lsa_find(), rc_getroute(), rn_event_handler(), rn_link_random_changes(), rn_xml_link_topology(), and update_add().
{
#if 0
        int     i;
        for(i = 0; i < m->nlinks; i++)
                if(m->link[i].addr == id)
                        return &m->link[i];
        return NULL;
#else
        return rn_hash_fetch(m->hash_link, id);
#endif
}
tw_lp* rn_getlp (rn_lp_state * state, int id)
Definition at line 18 of file rn-lp.c.
{
        //return &state->layers[id];
        return NULL;
}
rn_machine* rn_getmachine (tw_lpid id)
Definition at line 4 of file rn-machine.c.
References g_rn_machines.
Referenced by bgp_decision(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_open(), bgp_open_send(), bgp_ospf_init(), bgp_ospf_update(), bgp_rib_print(), bgp_route_add(), bgp_route_copy(), bgp_route_new(), bgp_update_all(), bgp_update_send(), bgp_xml(), deal_with_timed_out_routers(), epi_xml(), getroute(), ip_event_handler(), ip_init(), main_setup_areas(), neighbor_init(), ospf_ip_route(), ospf_lsa_create(), ospf_nbr_reset(), ospf_routing_init(), ospf_rt_print(), ospf_rt_timer(), ospf_startup(), ospf_xml(), rc_getroute(), rn_event_new(), rn_event_send(), rn_link_random_changes(), rn_link_random_weight_changes(), rn_link_setwire(), rn_route(), rn_setup_links(), rn_setup_streams(), rn_startup(), rn_xml_link_topology(), rn_xml_topology(), routing_init_ft_read(), routing_init_ft_write(), routing_write(), tcp_final(), tcp_init(), tcp_layer_init(), update_add(), update_withdraw(), and xml_link_topology().
{
        return &g_rn_machines[id];
}
void* rn_getstate (tw_lp * lp)
Definition at line 4 of file rn-lp.c.
{
#if 0
        rn_lp_state *me;
        me = (rn_lp_state *) lp->cur_state;
        return me->lp_list[me->cur_layer].cur_state;
#endif
        return NULL;
}
rn_stream* rn_getstream (tw_lp * lp)
Definition at line 23 of file rn-stream.c.
References s.
Referenced by rn_event_direct(), rn_event_new(), rn_event_send(), rn_timer_init(), and rn_timer_simple().
{
        rn_lp_state     *state;
        rn_stream       *s;
        state = (rn_lp_state *) lp->cur_state;
        s = &state->streams[state->cur_stream];
        if(!s)
                tw_error(TW_LOC, "Could not get stream from lp %d!", lp->id);
        return s;
}
rn_stream* rn_getstream_byport (rn_lp_state * state, tw_lpid port)
Definition at line 4 of file rn-stream.c.
Referenced by bgp_ospf_init(), bgp_ospf_update(), rn_event_handler(), rn_event_send(), and rn_rc_event_handler().
{
        unsigned int    i;
        for(i = 0; i < state->nstreams; i++)
        {
                if(state->streams[i].port == port)
                {
                        state->cur_stream = i;
                        return &state->streams[i];
                }
        }
        //tw_error(TW_LOC, "Unable to find stream port %d!", port);
        return state->streams;
}
rn_subnet* rn_getsubnet (rn_machine * m)
Definition at line 16 of file rn-machine.c.
Referenced by epi_xml().
{
        return m->subnet;
}
void* rn_hash_create (unsigned int)
Definition at line 31 of file hash-quadratic.c.
References rn_allocate_table(), rn_is_prime(), RN_MAX_FRACTION, and rn_next_prime().
Referenced by rn_xml_topology().
{
        rn_hash                 *h;
        unsigned int             size;
        h = (rn_hash *) tw_calloc(TW_LOC, "", sizeof(rn_hash), 1);
        if (!h)
                tw_error(TW_LOC, "Cannot rn_allocate rn_hash.");
        //h->storage = (rn_link **) tw_calloc(TW_LOC, "", sizeof(rn_link *), 1);
        size = sz;
        if(!rn_is_prime(sz) || sz == 1)
                size = rn_next_prime(sz);
        while(sz > floor(size * RN_MAX_FRACTION))
                size = rn_next_prime(size);
        h->nstored = 0;
        h->capacity = size;
        h->storage = rn_allocate_table(h->capacity);
        return (void *)h;
}
rn_link* rn_hash_fetch (void * h, int id)
Definition at line 122 of file hash-quadratic.c.
References rn_find_entry().
Referenced by rn_getlink().
{
        rn_hash         *hash_t = (rn_hash *) h;
        rn_link         *ret_event;
        int              key;
        key = rn_find_entry(hash_t->storage, id, hash_t->capacity);
        if(-1 == key)
                return NULL;
        ret_event = hash_t->storage[key];
#if 0
        if (!ret_event || ret_event->recv_ts != event->recv_ts || ret_event->seq_num != event->seq_num)
                tw_error(TW_LOC, "Could not find correct event in hash_table.");
#endif
        return ret_event;
}
void rn_hash_insert (void * h, rn_link *)
Definition at line 67 of file hash-quadratic.c.
References h_insert(), and RN_MAX_FRACTION.
Referenced by xml_link_topology().
{
        rn_hash        *hash_t;
        hash_t = (rn_hash *) h;
        h_insert(hash_t->storage, event, hash_t->capacity);
        hash_t->nstored++;
        if(hash_t->nstored > floor(hash_t->capacity * RN_MAX_FRACTION))
                tw_error(TW_LOC, "Inserted beyond RN_MAX_FRACTION!");
}
rn_link* rn_hash_remove (void * h, rn_link *)
Definition at line 144 of file hash-quadratic.c.
References rn_find_entry().
{
        rn_hash        *hash_t = (rn_hash *) h;
        rn_link       *ret_event;
        int             key;
        key = rn_find_entry(hash_t->storage, event->addr, hash_t->capacity);
        ret_event = hash_t->storage[key];
#if 0
        if (!ret_event || ret_event->recv_ts != event->recv_ts || ret_event->seq_num != event->seq_num)
                tw_error(TW_LOC, "Could not find correct event in hash_table.");
#endif
        hash_t->storage[key] = NULL;
        hash_t->nstored--;
        return ret_event;
}
int rn_init (rn_lptype * types)
Definition at line 55 of file rn-init.c.
References g_rn_barrier, g_rn_layer_lck, g_rn_layers, g_rn_nlayers, g_rn_nstreams, g_rn_stream_lck, and g_rn_streams.
Referenced by main().
{
        /*
         * Construct the STREAM array.
         */
        if(g_rn_nstreams)
        {
                g_rn_streams = (rn_stream *) tw_calloc(TW_LOC, "", sizeof(rn_stream) * g_rn_nstreams, 1);
                if(!g_rn_streams)
                        tw_error(TW_LOC, "Could not allocate stream memory!");
                //tw_printf(TW_LOC, "Created %d streams. \n", g_rn_nstreams);
        } else
                tw_error(TW_LOC, "No streams found to init!");
        /*
         * Construct the LAYER array
         */
        if(g_rn_nlayers)
        {
                g_rn_layers = (rn_layer *) tw_calloc(TW_LOC, "", sizeof(rn_layer) * g_rn_nlayers, 1);
                if(!g_rn_layers)
                        tw_error(TW_LOC, "Could not init layers!");
                //tw_printf(TW_LOC, "Created %d layers. \n", g_rn_nlayers);
        } else
                tw_error(TW_LOC, "No layers found to init!");
        /* setup locks and barriers */
        tw_barrier_create(&g_rn_barrier);
        tw_mutex_create(&g_rn_layer_lck);
        tw_mutex_create(&g_rn_stream_lck);
        return 1;
}
void rn_init_lps (rn_lptype * types)
Definition at line 95 of file rn-init.c.
References rn_setup_streams().
Referenced by main().
{
        tw_lp           *lp;
        tw_lp           *prev_lp;
        //tw_lptype     *t;
        int              i;
        lp = NULL;
        prev_lp = NULL;
        for(i = 0; i < g_tw_nlp; i++, prev_lp = NULL)
        {
                lp = tw_getlp(i);
#if 0
                t = tw_lp_gettype(lp);
                if (t && t->name)
                        memcpy(&lp->type, t, sizeof(*t));
                else
                        tw_error(TW_LOC, "No type defined for LP %i\n", lp->id);
#endif
                lp->state_qh = NULL;
                /*
                 * Allocate initial state vectors for this LP, and
                 * steal one of them for the initial state to be
                 * handed to the init function.
                 */
                if (lp->type.revent)
                        tw_state_alloc(lp, 1);
                else
                        tw_state_alloc(lp, g_tw_sv_growcnt + 1);
/*
                lp->cur_state = lp->state_qh;
                lp->state_qh = lp->state_qh->next;
*/
                /*
                 * Invoke LP XML init routine
                 */
                rn_setup_streams(lp->cur_state, types, lp);
        }
}
void rn_init_streams (rn_lp_state * state, tw_lp * lp)
This function calls the INIT routines of the star model layers
Definition at line 8 of file rn-init.c.
Referenced by rn_startup().
{
        tw_lp                   *layer_lp;
        rn_layer                *layer;
        rn_stream               *stream;
        int                      i;
        int                      j;
#if RN_VERIFY_SETUP
        printf("INIT star model for node: %lld, nstreams %d\n",
                lp->gid, state->nstreams);
#endif
        stream = state->streams;
        for(i = 0; i < state->nstreams; stream = &state->streams[++i])
        {
#if RN_VERIFY_SETUP
                printf("\tstream port: %d, nlayers %d \n",
                        stream->port, stream->nlayers);
#endif
                /*
                 * Setup the stream layers
                 */
                layer = &stream->layers[stream->nlayers - 1];
                for(j = stream->nlayers - 1; j >= 0; layer = &stream->layers[--j])
                {
                        layer_lp = &layer->lp;
                        state->cur_lp = layer_lp;
                        state->cur_stream = i;
                        stream->cur_layer = j;
                        /*
                         * Layer LP INIT function call
                         */
                        if(layer_lp->type.init)
                                (*(init_f)layer_lp->type.init) (layer_lp->cur_state, lp);
                        else
                                tw_error(TW_LOC, "No init routine: LP %d!", lp->id);
                }
        }
}
rn_layer* rn_layer_alloc (unsigned int nlayers)
This function allocates the layers to the rn_lps during the rn_startup phase, which is multi-threaded
Definition at line 8 of file rn-layer.c.
References g_rn_layer_lck, g_rn_layers, g_rn_nextlayer, and nlp.
Referenced by rn_setup_streams().
{
        rn_layer        *layer;
        tw_mutex_lock(&g_rn_layer_lck);
#if RN_VERIFY_LP
        if(nlayers > 1)
                printf("Allocating layers: %d to %d \n", g_rn_nextlayer, (g_rn_nextlayer + nlayers - 1));
        else if(nlp == 1)
                printf("Allocating layer: %d \n", g_rn_nextlayer);
        else
                tw_error(TW_LOC, "Trying to allocate %d layers!", nlayers);
#endif
        layer = &g_rn_layers[g_rn_nextlayer];
        g_rn_nextlayer += nlayers;
        tw_mutex_unlock(&g_rn_layer_lck);
        return layer;
}
rn_link_status rn_link_getstatus (rn_link * l, tw_stime ts)
Definition at line 33 of file rn-link.c.
References rn_link_down, and rn_link_up.
Referenced by rn_event_new().
{
        if(!l)
                tw_error(TW_LOC, "No link!");
#if DYNAMIC_LINKS
        if((l->status == rn_link_down && ts < l->next_status) ||
           (l->status == rn_link_up && ts >= l->next_status))
                return rn_link_down;
#endif
        return rn_link_up;
}
rn_machine* rn_link_getwire (rn_link * l)
Definition at line 11 of file rn-link.c.
{
        return l->wire;
}
void rn_link_random_changes (tw_lp *)
Definition at line 51 of file rn-link.c.
References g_rn_link_prob, rn_getlink(), and rn_getmachine().
{
#if DYNAMIC_LINKS
        rn_machine      *m;
        rn_link         *l;
        rn_link         *ol;
        int              percent;
        int              i;
        m = rn_getmachine(lp->id);
        for(i = 0; i < m->nlinks; i++)
        {
                l = &m->link[i];
                if(l->next_status != INT_MAX)
                        continue;
                percent = tw_rand_integer(lp->id, 0, 100);
                if(percent > g_rn_link_prob + 1)
                        return;
                ol = rn_getlink(l->wire, m->id);
                //l->next_status = ol->next_status = tw_rand_integer(lp->id, 25, g_tw_ts_end);
                //l->last_status = ol->last_status = 0;
                l->next_status = tw_rand_integer(lp->id, 25, g_tw_ts_end);
                l->last_status = 0;
        }
#endif
}
void rn_link_random_weight_changes (tw_lp * lp)
Definition at line 89 of file rn-link.c.
References LINK_STATUS_WEIGHT, and rn_getmachine().
{
        tw_stime         next_status;
        tw_event        *e;
        rn_message      *msg;
        rn_machine      *m;
        int              percent;
        int              i;
        m = rn_getmachine(lp->id);
        for(i = 0; i < m->nlinks; i++)
        {
                percent = tw_rand_integer(lp->rng, 0, 100);
                if(percent > 1 + 1)
                        return;
                next_status = tw_rand_integer(lp->rng, 1, g_tw_ts_end);
                e = tw_event_new(lp->gid, next_status, lp);
                msg = tw_event_data(e);
                msg->port = i;
                msg->src = lp->id;
                msg->dst = lp->id;
                msg->type = LINK_STATUS_WEIGHT;
                tw_event_send(e);
        }
}
void rn_link_setwire (rn_link * l)
Definition at line 4 of file rn-link.c.
References rn_getmachine().
Referenced by rn_machine_print().
{
        if(NULL == l->wire)
                l->wire = rn_getmachine(l->addr);
}
rn_lptype* rn_lp_gettype (tw_lp * lp)
Definition at line 37 of file rn-lp.c.
References g_rn_lptypes.
Referenced by rn_setup_layers().
{
        rn_lptype       *t;
        for(t = g_rn_lptypes; t && t->init; t++)
        {
                if(lp->type.init == t->init)
                        return t;
        }
        return NULL;
}
void rn_lp_settype (tw_lp * lp, char * name)
Definition at line 25 of file rn-lp.c.
References g_rn_lptypes.
{
        rn_lptype       *t;
        for(t = g_rn_lptypes; t; t++)
                if(0 == strcmp(t->sname, name))
                        break;
        memcpy(&lp->type, t, sizeof(tw_lptype));
}
void rn_machine_print (rn_machine * m)
Definition at line 34 of file rn-machine.c.
References rn_link_setwire().
{
        int     i;
        rn_link *l;
        printf("\tnLinks: %d \n", m->nlinks);
        for(i = 0; i < m->nlinks; i++)
        {
                l = &m->link[i];
                if(NULL == l->wire)
                        rn_link_setwire(l);
#if DYNAMIC_LINKS
                if(l->status == 0)
                        printf("\t\tLink status: down \n");
                else
                        printf("\t\tLink status: up\n");
#endif
                printf("\t\tLink to: %lld \n",
                        l->addr);
                printf("\t\tLink delay: %f \n",
                        l->delay);
                printf("\t\tLink bandwidth: %lf \n",
                        l->bandwidth);
                printf("\n");
        }
}
void* rn_message_data (rn_message * m)
Definition at line 16 of file rn-message.c.
Referenced by bgp_r_event_handler(), ftp_event_handler(), ftp_init(), ospf_ip_route(), ospf_rc_event_handler(), rn_event_data(), tcp_layer_event_handler(), tcp_layer_init(), tcp_layer_process_ack(), tcp_layer_process_ack_rc(), tcp_layer_process_data(), tcp_layer_process_data_rc(), tcp_layer_rc_event_handler(), tcp_layer_startup(), tcp_layer_timeout(), tcp_layer_update_rtt(), tcp_layer_util_event(), and tcp_process_ack_rc().
{
        tw_error(TW_LOC, "This function is deprecated, please use memory buffers!");
        //return (void *) &m->data;
        return NULL;
}
int rn_message_getdirection (rn_message * m)
Definition at line 32 of file rn-message.c.
{
        return m->type;
}
unsigned long rn_message_getsize (rn_message * e)
Definition at line 10 of file rn-message.c.
Referenced by ospf_ip_route().
{
        return m->size;
}
void rn_message_setdirection (rn_message * m, rn_message_type direction)
Definition at line 25 of file rn-message.c.
{
        tw_error(TW_LOC, "This is no longer needed!!!");
        m->type = direction;
}
void rn_message_setsize (rn_message * e, unsigned long sz)
Definition at line 4 of file rn-message.c.
Referenced by ospf_event_send(), and tcp_event_send().
{
        m->size = size;
}
void rn_models_final (rn_lptype * types)
Definition at line 29 of file rn-models.c.
Referenced by main().
{
        rn_lptype       *t;
        int              i;
        for(t = types, i = 0; t && t->init; t = &types[++i])
                if(*t->md_final)
                        (*t->md_final) ();
}
void rn_models_init (rn_lptype * , int , char ** , char **)
Definition at line 13 of file rn-models.c.
Referenced by main().
{
        rn_lptype       *t;
        int              i;
        for(t = types, i = 0; t && t->init; t = &types[++i])
                if(*t->md_init)
                        (*t->md_init) (argc, argv, env);
}
tw_lp* rn_next_lp (rn_lp_state * state, tw_lp * last, int type)
Definition at line 51 of file rn-lp.c.
References DOWNSTREAM.
{
#if 0
        if(type == DOWNSTREAM)
        {
                if(last == NULL)
                        return state->lp_list;
                if(last->id == state->nlp - 1)
                        return NULL;
                return &state->lp_list[last->id + 1];
        }
        if(last == NULL)
                return &state->lp_list[state->nlp - 1];
        if(last->id == 0)
                return NULL;
        return &state->lp_list[last->id - 1];
#endif
        return NULL;
}
rn_area* rn_nextarea (rn_area * as)
This file provides functionality for the AS data type in rossnet.
Definition at line 7 of file rn-area.c.
References g_rn_areas, and g_rn_nareas.
{
        if(as == NULL)
                return g_rn_areas;
        if(as->id == g_rn_nareas - 1)
                return NULL;
        return &g_rn_areas[as->id+1];
}
rn_area* rn_nextarea_onas (rn_area * ar, rn_as * as)
Definition at line 22 of file rn-area.c.
Referenced by rn_xml_topology(), and verify_topology().
{
        if(ar == NULL)
                return as->areas;
        else
                return ar->next;
}
rn_as* rn_nextas (rn_as * as)
Functions relating to an Autonomous System.
Author:
David Bauer This file provides functionality for the AS data type within rossnet. rn-as.c.
This file provides functionality for the AS data type in rossnet.
Definition at line 7 of file rn-as.c.
References g_rn_as, and g_rn_nas.
Referenced by bgp_setup_ases(), rn_xml_topology(), and verify_topology().
{
        if(as == NULL)
                return g_rn_as;
        if(as->id == g_rn_nas - 1)
                return NULL;
        return &g_rn_as[as->id+1];
}
rn_machine* rn_nextmachine_onsn (rn_machine * m, rn_subnet * sn)
Definition at line 13 of file rn-subnet.c.
Referenced by verify_topology().
{
        if(m == NULL)
                return sn->machines;
        else
                tw_error(TW_LOC, "Enable next pointer!");//return m->next;
        return NULL;
}
rn_subnet* rn_nextsn_onarea (rn_subnet * sn, rn_area * ar)
Definition at line 4 of file rn-subnet.c.
Referenced by verify_topology().
{
        if(sn == NULL)
                return ar->subnets;
        else
                return sn->next;
}
int rn_route (rn_machine * m, tw_lpid dst)
Definition at line 7 of file rn-routing.c.
References g_rn_nas, rn_getarea(), rn_getas(), and rn_getmachine().
Referenced by bgp_connect(), bgp_init(), bgp_lsa_find(), bgp_route_add(), bgp_route_copy(), bgp_route_withdraw(), dd_exchange(), ospf_db_route(), ospf_ip_route(), ospf_lsa_create(), ospf_routing_init(), ospf_rt_print(), and update_add().
{
        rn_area *ar = rn_getarea(m);
        rn_as   *as = ar->as;
        rn_area *d_ar = rn_getarea(rn_getmachine(dst));
        rn_as   *d_as = rn_getas(rn_getmachine(dst));
        if(dst >= ar->low && dst <= ar->high)
        {
                if(dst - ar->low >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[dst - ar->low];
        } else if(d_ar->id >= as->low && d_ar->id <= as->high)
        {
                if(ar->nmachines + d_ar->id - d_as->low  >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[ar->nmachines + d_ar->id - d_as->low];
        } else if(d_as->id >= 0 && d_as->id < g_rn_nas)
        {
                if(ar->nmachines + as->nareas + d_as->id  >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[ar->nmachines + as->nareas + d_as->id];
        } else
        {
                printf("%lld: Attempting to route to network? %d >= %lld \n",
                        m->id, ar->nmachines + as->nareas + g_rn_nas, dst);
                printf("%lld: nMachines %d, Area %d, AS nAreas %d, AS %d \n",
                        m->id, ar->nmachines, ar->id, as->nareas, as->id);
                return -1;
        }
}
int rn_route_change (rn_machine * m, int loc, int new_val)
Definition at line 48 of file rn-routing.c.
Referenced by bgp_route_add(), bgp_route_withdraw(), and ospf_db_route().
{
        char old_val = m->ft[loc];
        m->ft[loc] = new_val;
        return (int) old_val;
}
void rn_setmachine (rn_machine * m)
Definition at line 10 of file rn-machine.c.
References g_rn_machines.
{
        g_rn_machines[m->id] = *m;
}
void rn_setup ()
Definition at line 205 of file rn-setup.c.
References g_rn_rt_table, g_rn_tools_dir, g_rn_xml_link_topology, and g_rn_xml_topology.
Referenced by main().
{
        if(0 != strcmp(g_rn_tools_dir, ""))
        {
                char * dir = g_rn_tools_dir;
                sprintf(g_rn_xml_topology, "tools/%s/%s.xml", dir, dir);
                sprintf(g_rn_rt_table, "tools/%s/%s.rt", dir, dir);
                sprintf(g_rn_xml_link_topology, "tools/%s/links.xml", dir);
                //sprintf(g_rn_xml_model, "tools/%s/model.xml", dir);
                printf("Opening config file: %s \n", g_rn_xml_topology);
                printf("Opening link file: %s \n", g_rn_xml_link_topology);
                printf("Opening routing table file: %s \n", g_rn_rt_table);
        }
}
void rn_setup_links (rn_lp_state * state, tw_lp * lp)
Definition at line 164 of file rn-setup.c.
References g_rn_nlink_status, LINK_STATUS_DOWN, LINK_STATUS_UP, rn_getmachine(), and rn_link_up.
Referenced by rn_startup().
{
#if DYNAMIC_LINKS
        tw_event        *e;
        rn_message      *msg;
        rn_machine      *m;
        int              i;
        m = rn_getmachine(lp->id);
        for(i = 0; i < m->nlinks; i++)
        {
                if(m->link[i].next_status == 0 || m->link[i].next_status == INT_MAX)
                        continue;
#if 1
                printf("%lld: Setting link status event for time %lf, now %lf \n",
                                lp->gid, m->link[i].next_status, tw_now(lp));
#endif
                g_rn_nlink_status++;
                e = tw_event_new(lp, m->link[i].next_status, lp);
                msg = tw_event_data(e);
                msg->port = i;
                msg->src = lp->id;
                msg->dst = lp->id;
                if(m->link[i].status == rn_link_up)
                        msg->type = LINK_STATUS_DOWN;
                else
                        msg->type = LINK_STATUS_UP;
                tw_event_send(e);
        }
#endif
}
void rn_setup_options (int argc, char ** argv)
void rn_setup_streams (rn_lp_state * state, rn_lptype * types, tw_lp * lp)
This function sets up the star model for the different layers
Definition at line 81 of file rn-setup.c.
References rn_getmachine(), rn_layer_alloc(), rn_setup_layers(), rn_stream_alloc(), and xml_getprop().
Referenced by rn_init_lps().
{
        xmlNodePtr              node;
        xmlNodePtr              x_temp;
        xmlNodePtr              x_stream;
        xmlNodePtr              x_layer;
        int                     cur_stream;
        rn_layer                *layer;
        rn_stream               *stream;
        rn_machine              *m;
        m = rn_getmachine(lp->id);
#if RN_VERIFY_SETUP
        printf("SETUP star model for node: %lld \n", lp->gid);
#endif
        for(x_stream = m->xml->children; x_stream; x_stream = x_stream->next)
        {
                if(0 != strcmp((char *) x_stream->name, "stream"))
                        continue;
                state->nstreams++;
        }
        state->streams = rn_stream_alloc(state->nstreams);
        if(!state->streams)
                tw_error(TW_LOC, "Did not get any streams for machine %d!", lp->id);
        node = m->xml;
        stream = state->streams;
        cur_stream = 0;
        for(x_stream = node->children; x_stream; x_stream = x_stream->next)
        {
                if(0 != strcmp((char *) x_stream->name, "stream"))
                        continue;
                stream->port = atoi(xml_getprop(x_stream, "port"));
#if RN_VERIFY_SETUP
                printf("\tport: %d \n", stream->port);
#endif
                /*
                 * Setup the stream layers
                 */
                for(x_temp = x_stream->children; x_temp; x_temp = x_temp->next)
                {
                        if(0 != strcmp((char *) x_temp->name, "layer"))
                                continue;
                        stream->nlayers++;
                }
                stream->layers = rn_layer_alloc(stream->nlayers);
                layer = stream->layers;
                x_layer = x_stream->children;
#if RN_VERIFY_SETUP
                printf("\tlayers: %d\n", stream->nlayers);
#endif
                while(0 != strcmp((char *) x_layer->name, "layer"))
                        x_layer = x_layer->next;
                rn_setup_layers(state, cur_stream, layer, types, x_layer, lp);
                stream = stream + 1;
                cur_stream++;
        }
        m->xml = NULL;
}
rn_stream* rn_stream_alloc (unsigned int nstreams)
This function allocates the streams to the rn_lps during the rn_startup phase, which is multi-threaded
Definition at line 42 of file rn-stream.c.
References g_rn_nextstream, g_rn_stream_lck, and g_rn_streams.
Referenced by rn_setup_streams().
{
        rn_stream       *stream;
        tw_mutex_lock(&g_rn_stream_lck);
        if(nstreams == 0)
                tw_error(TW_LOC, "No streams for this node!");
#if RN_VERIFY_LP
        if(nstreams > 1)
                printf("Allocating streams: %d to %d \n",
                                g_rn_nextstream, (g_rn_nextstream + nstreams - 1));
        else if(nstreams == 1)
                printf("Allocating stream: %d \n", g_rn_nextstream);
        else
                tw_error(TW_LOC, "Trying to allocate %d streams!", nstreams);
#endif
        stream = &g_rn_streams[g_rn_nextstream];
        g_rn_nextstream += nstreams;
        tw_mutex_unlock(&g_rn_stream_lck);
        return stream;
}
void rn_timer_cancel (tw_lp * lp, tw_event ** e)
Definition at line 80 of file rn-timer.c.
Referenced by bgp_timer_cancel(), epi_timer_cancel(), num_timer_cancel(), ospf_timer_cancel(), stop_transfer(), tcp_rc_timer_reset(), and tcp_timer_cancel().
{
        tw_timer_cancel(lp, e);
        e = NULL;
}
tw_event* rn_timer_init (tw_lp * lp, tw_stime ts)
Definition at line 30 of file rn-timer.c.
References rn_getstream(), s, and TIMER.
Referenced by bgp_timer_start(), epi_init(), epi_location_timer(), epi_timer_start(), num_file_complete(), num_start(), num_timer_start(), ospf_timer_start(), start_transfer(), tcp_host_timeout(), tcp_layer_init(), tcp_layer_startup(), tcp_layer_timeout(), and tcp_timer_reset().
{
        tw_event        *e;
        rn_lp_state     *state;
        rn_message      *msg;
        rn_stream       *s;
        e = tw_timer_init(lp, ts);
        if(!e)
                return NULL;
        msg = tw_event_data(e);
        state = lp->cur_state;
        s = rn_getstream(lp);
        msg->type = TIMER;
        msg->timer = state->cur_lp;
        msg->src = lp->id;
        msg->dst = lp->id;
        msg->size = s->cur_layer;
        msg->port = s->port;
        msg->ttl = 0;
        return e;
}
tw_event* rn_timer_reset (tw_lp * lp, tw_event ** e, tw_stime ts)
Definition at line 58 of file rn-timer.c.
References TIMER.
Referenced by bgp_timer_start(), epi_location_timer(), epi_timer_start(), num_timer_start(), ospf_timer_start(), tcp_host_process_ack(), tcp_host_update_rtt(), tcp_layer_process_ack(), tcp_layer_update_rtt(), and tcp_timer_reset().
{
        rn_message      *msg;
        rn_lp_state     *state;
        tw_timer_reset(lp, e, ts);
        if(!*e)
                return *e;
        state = (rn_lp_state *) lp->cur_state;
        msg = (rn_message *) tw_event_data(*e);
        msg->type = TIMER;
        msg->timer = state->cur_lp;
        msg->src = lp->id;
        msg->dst = lp->id;
        return *e;
}
tw_event* rn_timer_simple (tw_lp * lp, tw_stime ts)
Definition at line 4 of file rn-timer.c.
References rn_getstream(), s, and TIMER.
Referenced by bgp_timer_start(), and ospf_random_weights().
{
        tw_event        *tmr;
        rn_lp_state     *state;
        rn_message      *r;
        rn_stream       *s;
        state = lp->cur_state;
        tmr = tw_event_new(lp->gid, ts, lp);
        r = tw_event_data(tmr);
        s = rn_getstream(lp);
        r->type = TIMER;
        r->dst = lp->id;
        r->src = lp->id;
        r->timer = state->cur_lp;
        r->size = s->cur_layer;
        r->port = s->port;
        tw_event_send(tmr);
        return tmr;
}
void rn_xml_end ()
Definition at line 135 of file xml-libxml.c.
References ctxt, document_links, document_model, and document_network.
Referenced by main().
{
        if(ctxt)
                xmlXPathFreeContext(ctxt);
        if(document_network)
                xmlFreeDoc(document_network);
        if(document_links)
                xmlFreeDoc(document_links);
        if(document_model)
                xmlFreeDoc(document_model);
        xmlCleanupParser();
}
void rn_xml_init ()
Definition at line 77 of file xml-libxml.c.
References ctxt, ctxt_links, ctxt_model, document_links, document_model, document_network, g_rn_xml_link_topology, g_rn_xml_model, g_rn_xml_topology, rn_xml_link_topology(), rn_xml_model(), and rn_xml_topology().
Referenced by main().
{
#if RN_XML_DEBUG
        printf("Reading in XML topology file: %s\n\n", g_rn_xml_topology);
#endif
        xmlXPathInit();
        document_network = xmlReadFile(g_rn_xml_topology, NULL , 0);
        if(!document_network)
                tw_error(TW_LOC, "Parsing of network topology file %s failed!",
                        g_rn_xml_topology);
        ctxt = xmlXPathNewContext(document_network);
        if(!ctxt)
                tw_error(TW_LOC, "Could not create network topology XML context!");
        /* read in the XML network topology */
        rn_xml_topology();
        if(g_rn_xml_link_topology != NULL)
        {
                document_links = xmlReadFile(g_rn_xml_link_topology, NULL ,0);
                if(!document_links)
                        tw_error(TW_LOC, "Parsing of link topology file %s failed!",
                                g_rn_xml_link_topology);
                ctxt_links = xmlXPathNewContext(document_links);
                if(!ctxt_links)
                        tw_error(TW_LOC, "Unable to create model XML context!");
                /* read in the XML link topology */
                rn_xml_link_topology();
                xmlXPathFreeContext(ctxt_links);
        }
        if(NULL != g_rn_xml_model && 0 != strcmp(g_rn_xml_model, ""))
        {
                document_model = xmlReadFile(g_rn_xml_model, NULL, 0);
                if(!document_model)
                        tw_error(TW_LOC, "Parsing of model file %s failed!",
                                g_rn_xml_model);
                ctxt_model = xmlXPathNewContext(document_model);
                if(!ctxt_model)
                        tw_error(TW_LOC, "Unable to create model XML context!");
                rn_xml_model();
                xmlXPathFreeContext(ctxt_model);
        }
}
void rn_xml_link_topology ()
Definition at line 153 of file xml-libxml.c.
References ctxt_links, d, rn_getlink(), rn_getmachine(), s, xml_getprop(), and xpath().
Referenced by rn_xml_init().
{
        xmlXPathObjectPtr       obj;
        xmlNodePtr              node;
        int                     src;
        int                     dst;
        rn_machine              *d;
        rn_machine              *s;
        rn_link                 *s_l;
        rn_link                 *d_l;
        /* Statuses */
        obj = xpath("//status", ctxt_links);
        if(0 == obj->nodesetval->nodeNr)
                return;
        for(node = *obj->nodesetval->nodeTab; node != NULL; node = node->next)
        {
                if(0 != strcmp((char *) node->name, "status"))
                        continue;
                src = atoi(xml_getprop(node, "src"));
                dst = atoi(xml_getprop(node, "addr"));
                s = rn_getmachine(src);
                d = rn_getmachine(dst);
                /*
                 * Should check link type and change the status approp
                 */
                s_l = rn_getlink(s, d->id);
                d_l = rn_getlink(d, s->id);
                if(!s_l || !d_l)
                {
                        printf("Bad link specified in links.xml -- ignoring! \n");
                        continue;
                }
#if DYNAMIC_LINKS
                s_l->next_status = d_l->next_status = atoi(xml_getprop(node, "change"));
                s_l->last_status = d_l->last_status = 0;
#endif
        }
        xmlXPathFreeObject(obj);
}
void rn_xml_model ()
Definition at line 355 of file xml-libxml.c.
Referenced by rn_xml_init().
{
        tw_error(TW_LOC, "Seperate file for model not implemented yet!!");
}
void rn_xml_topology ()
Definition at line 364 of file xml-libxml.c.
References c_co_router, c_ct_router, c_ha_router, c_host, c_og_router, c_router, ctxt, g_rn_areas, g_rn_as, g_rn_machines, g_rn_nareas, g_rn_nas, g_rn_nlayers, g_rn_nlinks, g_rn_nmachines, g_rn_nrouters, g_rn_nstreams, g_rn_nsubnets, g_rn_subnets, rn_getmachine(), rn_hash_create(), rn_nextarea_onas(), rn_nextas(), xml_getprop(), xml_link_topology(), and xpath().
Referenced by rn_xml_init().
{
        xmlXPathObjectPtr       obj;
        xmlNodePtr              node;
        unsigned int            i;
        //unsigned int          j;
        unsigned int            id;
        unsigned int            size;
        rn_as                   *as;
        rn_area                 *ar;
        rn_subnet               *sn;
        rn_machine              *m;
        size = 0;
        /* Streams and Layers */
        obj = xpath("//stream", ctxt);
        g_rn_nstreams = xmlXPathNodeSetGetLength(obj->nodesetval);
        xmlXPathFreeObject(obj);
        obj = xpath("//layer", ctxt);
        g_rn_nlayers = xmlXPathNodeSetGetLength(obj->nodesetval);
        xmlXPathFreeObject(obj);
        /* ASes */
        obj = xpath("/rossnet/as", ctxt);
        g_rn_nas = xmlXPathNodeSetGetLength(obj->nodesetval);
        if(g_rn_nas > 0)
        {
                g_rn_as = (rn_as *) tw_calloc(TW_LOC, "", sizeof(rn_as), g_rn_nas);
                size += sizeof(rn_as) * g_rn_nas;
        }
        node = obj->nodesetval->nodeTab[0];
        for(i = 0; i < obj->nodesetval->nodeNr; )
        {
                g_rn_as[i].low = -1;
                g_rn_as[i].id = atoi(xml_getprop(node, "id"));
                //g_rn_as[i].frequency = atoi(xml_getprop(node, "frequency"));
#if WASTE_MEM
                if(0 == strcmp(xml_getprop(node, "name"), "name"))
                        g_rn_as[i].name = (char *) xmlStrdup((xmlChar *) xml_getprop(node, "name"));
#endif
                node = obj->nodesetval->nodeTab[++i];
        }
        xmlXPathFreeObject(obj);
        /* Areas */
        obj = xpath("/rossnet/as/area", ctxt);
        g_rn_nareas = xmlXPathNodeSetGetLength(obj->nodesetval);
        if(g_rn_nareas > 0)
        {
                g_rn_areas = (rn_area *) tw_calloc(TW_LOC, "", sizeof(rn_area), g_rn_nareas);
                size += sizeof(rn_area) * g_rn_nareas;
        }
        node = obj->nodesetval->nodeTab[0];
        for(i = 0; i < obj->nodesetval->nodeNr; )
        {
                //g_rn_areas[i].root = INT_MAX;
                //g_rn_areas[i].root_lvl = 0xff;
                g_rn_areas[i].low = INT_MAX;
                g_rn_areas[i].id = atoi(xml_getprop(node, "id"));
                g_rn_areas[i].as = &g_rn_as[atoi(xml_getprop(node->parent, "id"))];
                if(g_rn_areas[i].as->areas == NULL)
                        g_rn_areas[i].as->areas = &g_rn_areas[i];
                if(i > 0 && g_rn_areas[i-1].as->id == g_rn_areas[i].as->id)
                        g_rn_areas[i-1].next = &g_rn_areas[i];
                g_rn_areas[i].as->nareas++;
                node = obj->nodesetval->nodeTab[++i];
        }
        xmlXPathFreeObject(obj);
        /* Subnets */
        obj = xpath("/rossnet/as/area/subnet", ctxt);
        g_rn_nsubnets = xmlXPathNodeSetGetLength(obj->nodesetval);
        if(g_rn_nsubnets > 0)
        {
                g_rn_subnets = (rn_subnet *) tw_calloc(TW_LOC, "", sizeof(rn_subnet), g_rn_nsubnets);
                size += sizeof(rn_subnet) * g_rn_nsubnets;
        }
        node = *obj->nodesetval->nodeTab;
        for(i = 0; i < obj->nodesetval->nodeNr; )
        {
                g_rn_subnets[i].low = INT_MAX;
                g_rn_subnets[i].id = atoi(xml_getprop(node, "id"));
                g_rn_subnets[i].area = &g_rn_areas[atoi(xml_getprop(node->parent, "id"))];
                if(g_rn_subnets[i].area->subnets == NULL)
                        g_rn_subnets[i].area->subnets = &g_rn_subnets[i];
                if(i > 0 && g_rn_subnets[i-1].area->id == g_rn_subnets[i].area->id)
                        g_rn_subnets[i-1].next = &g_rn_subnets[i];
                g_rn_subnets[i].area->nsubnets++;
                node = obj->nodesetval->nodeTab[++i];
        }
        xmlXPathFreeObject(obj);
        /* Machines */
        obj = xpath("//node", ctxt);
        g_rn_nmachines = xmlXPathNodeSetGetLength(obj->nodesetval);
        if(g_rn_nmachines)
        {
                g_rn_machines = (rn_machine *) tw_calloc(TW_LOC, "", sizeof(rn_machine), g_rn_nmachines);
                size += sizeof(rn_machine) * g_rn_nmachines;
        } else
                tw_error(TW_LOC, "No machines found in XML!");
        g_tw_nlp = obj->nodesetval->nodeNr;
        node = *obj->nodesetval->nodeTab;
        for(i = 0; i < obj->nodesetval->nodeNr; )
        {
                id = atoi(xml_getprop(node, "id"));
                m = rn_getmachine(id);
                m->xml = node;
                m->conn = -1;
                m->id = id;
                m->nlinks = atoi(xml_getprop(node, "links"));
                //m->level = atoi(xml_getprop(node, "lvl"));
                m->subnet = &g_rn_subnets[atoi(xml_getprop(node->parent, "id"))];
                if(0 != strcmp("", xml_getprop(node, "uid")))
                        m->uid = atoi(xml_getprop(node, "uid"));
                else
                        m->uid = -1;
                if(strcmp("c_router", xml_getprop(node, "type")) == 0)
                {
                        m->type = c_router;
                        g_rn_nrouters++;
                } else if(strcmp("c_ct_router", xml_getprop(node, "type")) == 0)
                {
                        m->type = c_ct_router;
                        g_rn_nrouters++;
                } else if(strcmp("c_og_router", xml_getprop(node, "type")) == 0)
                {
                        m->type = c_og_router;
                        g_rn_nrouters++;
                } else if(strcmp("c_co_router", xml_getprop(node, "type")) == 0)
                {
                        m->type = c_co_router;
                        g_rn_nrouters++;
                } else if(strcmp("c_ha_router", xml_getprop(node, "type")) == 0)
                {
                        m->type = c_ha_router;
                        g_rn_nrouters++;
                } else if(strcmp("c_host", xml_getprop(node, "type")) == 0)
                        m->type = c_host;
                else
                        tw_error(TW_LOC, "Unknown node type: %s", xml_getprop(node, "type"));
                if(m->subnet->machines == NULL)
                        m->subnet->machines = &g_rn_machines[i];
#if 0
                if(id > 0 &&
                   g_rn_machines[id-1].subnet->id == g_rn_machines[id].subnet->id)
                        g_rn_machines[id-1].next = &g_rn_machines[id];
#endif
                m->subnet->nmachines++;
                m->subnet->area->nmachines++;
                m->link = (rn_link *) tw_calloc(TW_LOC, "", sizeof(rn_link) * m->nlinks, 1);
                m->hash_link = rn_hash_create(m->nlinks);
                size += sizeof(rn_link) * m->nlinks;
                //printf("Init\'ing Machines id: %d \n", m->id);
                node = obj->nodesetval->nodeTab[++i];
        }
        xmlXPathFreeObject(obj);
        xml_link_topology();
        /*
         * Set up the global connection library
         */
        obj = xpath("//connect", ctxt);
        if(obj->nodesetval->nodeNr)
        {
                node = *obj->nodesetval->nodeTab;
                for(i = 0; i < obj->nodesetval->nodeNr; )
                {
                        m = rn_getmachine(atoll(xml_getprop(node, "src")));
                        m->conn = atoll(xml_getprop(node, "dst"));
                        // back link the connection
                        rn_getmachine(m->conn)->conn = m->id;
                        node = obj->nodesetval->nodeTab[++i];
                }
        }
        xmlXPathFreeObject(obj);
        for(i = 0; i < g_rn_nmachines; i++)
        {
                m = rn_getmachine(i);
                sn = m->subnet;
                ar = sn->area;
                as = ar->as;
                if(i < sn->low)
                {
                        sn->low = i;
                        if(i < ar->low)
{
                                ar->low = i;
                                if(0 && i < as->low)
                                        as->low = i;
                        }
                }
                if(i > sn->high)
                {
                        sn->high = i;
                        if(i > ar->high)
{
                                ar->high = i;
                                if(0 && i > as->high)
                                        as->high = i;
                        }
                }
                if(m->type == c_host)
                        continue;
                ar->g_ospf_nlsa = ar->nmachines + ar->as->nareas + g_rn_nas;
                if(ar->nmachines == 0)
                        tw_error(TW_LOC, "No machines in Area %d!\n", ar->id);
#if 0
                m->ft = (int *) tw_calloc(TW_LOC, "", sizeof(int ) * ar->g_ospf_nlsa, 1);
                size += sizeof(int) * ar->g_ospf_nlsa;
                for(j = 0; j < ar->g_ospf_nlsa; j++)
                        m->ft[j] = -1;
#endif
/*
                printf("mach %d: alloc FT of size: %d \n",
                        i, ar->nmachines + as->nareas + g_rn_nas);
*/
        }
        ar = NULL;
        as = NULL;
        while(NULL != (as = rn_nextas(as)))
        {
                while(NULL != (ar = rn_nextarea_onas(ar, as)))
                {
                        if(as->low == -1)
                                as->low = ar->id;
                        as->high = ar->id;
                }
                //printf("AS %d: low %ld, high %ld \n", as->id, as->low, as->high);
        }
#if RN_XML_DEBUG || 1
                printf("\n");
                printf("%-32s %11d \n", "ASes: ", g_rn_nas);
                printf("%-32s %11d \n", "Areas: ", g_rn_nareas);
                printf("%-32s %11d \n", "Subnets: ", g_rn_nsubnets);
                printf("%-32s %11d \n", "Machines: ", g_rn_nmachines);
                printf("%-32s %11d \n", "Links: ", g_rn_nlinks);
                printf("%-32s %11d bytes\n", "Total topology size: ", size);
#endif
        //verify_topology();
}
char* xml_getprop (xmlNode * node, char * prop)
Definition at line 207 of file xml-libxml.c.
Referenced by bgp_xml(), epi_xml(), main_setup_areas(), num_xml(), ospf_xml(), rn_setup_layers(), rn_setup_streams(), rn_xml_link_topology(), rn_xml_topology(), tcp_layer_xml(), and xml_link_topology().
{
        xmlAttrPtr next = node->properties;
        while(next)
        {
                if(0 == strcmp(prop, (char *) next->name))
                        return (char *) next->children->content;
                next = next->next;
        }
        return "";
}
xmlXPathObjectPtr xpath (char * expr, xmlXPathContextPtr ctxt)
Definition at line 68 of file xml-libxml.c.
Referenced by bgp_setup_ases(), ospf_main(), rn_xml_link_topology(), rn_xml_topology(), tcp_layer_xml(), and xml_link_topology().
{
        return xmlXPathEvalExpression(BAD_CAST expr, ctxt);
}
Variable Documentation
xmlXPathContextPtr ctxt
Definition at line 91 of file rn-global.c.
Referenced by bgp_setup_ases(), ospf_main(), rn_xml_end(), rn_xml_init(), rn_xml_topology(), tcp_layer_xml(), and xml_link_topology().
xmlXPathContextPtr ctxt_links
Definition at line 92 of file rn-global.c.
Referenced by rn_xml_init(), and rn_xml_link_topology().
xmlXPathContextPtr ctxt_model
Definition at line 93 of file rn-global.c.
Referenced by rn_xml_init().
xmlDocPtr document_links
Definition at line 88 of file rn-global.c.
Referenced by rn_xml_end(), and rn_xml_init().
xmlDocPtr document_model
Definition at line 89 of file rn-global.c.
Referenced by rn_xml_end(), and rn_xml_init().
xmlDocPtr document_network
Definition at line 87 of file rn-global.c.
Referenced by rn_xml_end(), rn_xml_init(), and tcp_layer_xml().
rn_area* g_rn_areas
Definition at line 47 of file rn-global.c.
Referenced by bgp_init(), main_setup_areas(), rn_nextarea(), and rn_xml_topology().
rn_as* g_rn_as
Definition at line 44 of file rn-global.c.
Referenced by rn_nextas(), rn_xml_topology(), update_add(), and update_withdraw().
tw_barrier g_rn_barrier
g_rn_barrier -- barrier used during lp initialization, gives RN a chance to init sequential, in multi-threaded enviroment of ROSS g_rn_lp_lck -- lock used in rn_lps, during tw_init_lps, to init local lps
Definition at line 100 of file rn-global.c.
Referenced by rn_init().
int g_rn_converge_bgp
Definition at line 5 of file rn-global.c.
Referenced by init_rib(), ospf_startup(), and ospf_statistics_collection().
int g_rn_converge_ospf
Definition at line 4 of file rn-global.c.
Referenced by bgp_event_handler(), bgp_final(), bgp_init(), flood_summary(), init_rib(), ospf_main(), ospf_startup(), and ospf_statistics_collection().
int g_rn_dst
Definition at line 8 of file rn-global.c.
tw_mutex g_rn_layer_lck
Definition at line 101 of file rn-global.c.
Referenced by rn_init(), and rn_layer_alloc().
rn_layer* g_rn_layers
Definition at line 65 of file rn-global.c.
Referenced by rn_init(), and rn_layer_alloc().
int g_rn_link_prob
Definition at line 3 of file rn-global.c.
Referenced by rn_link_random_changes().
char g_rn_logs_dir[]
Definition at line 85 of file rn-global.c.
Referenced by bgp_final(), bgp_init(), epi_main(), epi_setup_options(), ip_md_init(), num_setup_options(), ospf_main(), ospf_setup_options(), ospf_startup(), ospf_statistics_collection(), routing_write(), and tcp_final().
rn_lptype* g_rn_lptypes
g_rn_lptypes -- list of module lp types
Definition at line 71 of file rn-global.c.
Referenced by main(), rn_lp_gettype(), and rn_lp_settype().
rn_machine* g_rn_machines
Definition at line 58 of file rn-global.c.
Referenced by ospf_md_final(), rn_event_handler(), rn_getmachine(), rn_setmachine(), rn_xml_topology(), routing_write(), and xml_link_topology().
unsigned int g_rn_msg_sz
Definition at line 16 of file rn-global.c.
Referenced by main().
unsigned int g_rn_nareas
Definition at line 46 of file rn-global.c.
Referenced by main_setup_areas(), rn_nextarea(), and rn_xml_topology().
unsigned int g_rn_nas
These are the data type lists that make up a topology.
g_rn_nas -- number of ASes in the topology g_rn_as -- list of ASes in the top
g_rn_nareas -- number of areas in the topology g_rn_areas -- list of Areas in the topology
g_rn_nsubnets -- number of subnets in the topology g_rn_subnets -- list of Subnets in the topology
g_rn_nmachines -- number of machines in the topology g_rn_machines -- list of machines in the topology
g_rn_nstreams -- number of streams in the topology g_rn_streams -- global array of streams
g_rn_nlayers -- number of layers in the topology g_rn_layers -- layer lps in the topology
g_rn_nextlp -- the next layer LP to allocate
Definition at line 43 of file rn-global.c.
Referenced by bgp_final(), bgp_init(), bgp_keepalive(), bgp_md_final(), bgp_mrai_timer(), bgp_open(), bgp_rib_print(), bgp_setup_ases(), bgp_setup_options(), deal_with_timed_out_routers(), init_rib(), ospf_db_init(), ospf_rt_print(), rn_nextas(), rn_route(), and rn_xml_topology().
unsigned int g_rn_nextlayer
Definition at line 66 of file rn-global.c.
Referenced by rn_layer_alloc().
unsigned int g_rn_nextstream
Definition at line 62 of file rn-global.c.
Referenced by rn_stream_alloc().
unsigned int g_rn_nlayers
Definition at line 64 of file rn-global.c.
Referenced by rn_init(), and rn_xml_topology().
unsigned int g_rn_nlink_status
Definition at line 55 of file rn-global.c.
Referenced by rn_setup_links(), and rn_startup().
unsigned int g_rn_nlinks
Definition at line 54 of file rn-global.c.
Referenced by rn_xml_topology(), and xml_link_topology().
unsigned int g_rn_nmachines
Definition at line 57 of file rn-global.c.
Referenced by ospf_md_final(), rn_xml_topology(), routing_init_ft_write(), routing_read(), routing_write(), and xml_link_topology().
unsigned int g_rn_nrouters
Definition at line 52 of file rn-global.c.
Referenced by ospf_ip_route(), ospf_router_debug_routing(), ospf_routing_init(), and rn_xml_topology().
unsigned int g_rn_nstreams
Definition at line 60 of file rn-global.c.
Referenced by rn_init(), and rn_xml_topology().
unsigned int g_rn_nsubnets
Definition at line 49 of file rn-global.c.
Referenced by rn_xml_topology().
char g_rn_rt_table[]
Definition at line 83 of file rn-global.c.
Referenced by ospf_setup_options(), and rn_setup().
int g_rn_src
Definition at line 7 of file rn-global.c.
rn_statistics* g_rn_stats
Definition at line 18 of file rn-global.c.
Referenced by main(), rn_final(), and rn_print_statistics().
tw_mutex g_rn_stream_lck
Definition at line 102 of file rn-global.c.
Referenced by rn_init(), and rn_stream_alloc().
rn_stream* g_rn_streams
Definition at line 61 of file rn-global.c.
Referenced by rn_init(), and rn_stream_alloc().
rn_subnet* g_rn_subnets
Definition at line 50 of file rn-global.c.
Referenced by rn_xml_topology().
char g_rn_tools_dir[]
Definition at line 84 of file rn-global.c.
Referenced by bgp_main(), epi_setup_options(), num_setup_options(), ospf_main(), rn_setup(), routing_read(), and routing_write().
unsigned char g_rn_ttl
rossnet global data items
g_rn_stats -- rossnet statistics struct
Definition at line 15 of file rn-global.c.
Referenced by ip_rc_upstream(), ip_upstream(), rn_event_new(), and routing_init_ft_write().
char g_rn_xml_link_topology[]
Definition at line 81 of file rn-global.c.
Referenced by rn_setup(), and rn_xml_init().
char g_rn_xml_model[]
Definition at line 82 of file rn-global.c.
Referenced by rn_xml_init().
char g_rn_xml_topology[]
These are the files that hold the topology and the model configurations.
g_rn_xml_topology -- the node topology descriptor g_rn_link_topology -- the link topology descriptor g_rn_xml_model -- the model descriptor
Definition at line 80 of file rn-global.c.
Referenced by rn_setup(), and rn_xml_init().