ROSS.Net: rn-event.c File Reference
rn-event.c File Reference
#include <rossnet.h>
Functions
tw_event * rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp *src)
tw_event * rn_event_new (tw_lpid dst, tw_stime ts, tw_lp *src, rn_message_type dir, unsigned long int size)
void * rn_event_data (tw_event *e)
void rn_event_send (tw_event *new_event)
Function Documentation
void* rn_event_data (tw_event * e)
Definition at line 167 of file rn-event.c.
References rn_message_data().
Referenced by ftp_event_handler(), ospf_ip_route(), and tcp_layer_util_event().
{
        return (void *) rn_message_data((rn_message *) tw_event_data(e));
}
tw_event* rn_event_direct (tw_lpid dst, tw_stime ts, tw_lp * src)
Definition at line 8 of file rn-event.c.
References DIRECT, rn_getstream(), and s.
Referenced by epi_agent_remove(), epi_num_add(), epi_num_check_report(), and epi_num_remove().
{
        tw_event        *e;
        rn_lp_state     *state;
        rn_stream       *s;
        rn_message      *m;
        state = src->cur_state;
        s = rn_getstream(src);
        e = tw_event_new(dst, ts, src);
        m = tw_event_data(e);
        m->type = DIRECT;
        m->timer = state->cur_lp;
        m->size = s->cur_layer;
        m->port = s->port;
        m->src = src->id;
        m->dst = dst;
        return e;
}
tw_event* rn_event_new (tw_lpid dst, tw_stime ts, tw_lp * src, rn_message_type dir, unsigned long int size)
inter-lp: events which will be sent to a remote lp
inter-lp events are handled as usual
intra-lp: events which are sent to another layer on the same lp
intra-lp events are immediately scheduled and processed, because their destination is the local machine, and have a zero timestamp offset, which means the following:
the next layer is responsible for handling packet data, ie, from TCP to IP. The IP layer must re-create the TCP packect on the dest LP.
abort events: should not let them traverse layers.. first layer to get abort is then the only one to get rolled back
NOTE: We should probably base the timestamp off of the network characteristics, rather than make the model do it. When the model calls this function, and is the last layer, we should know the proper link to use, and can inform the model if this event will fail if sent, over the network.
Definition at line 58 of file rn-event.c.
References DOWNSTREAM, g_rn_ttl, rn_getmachine(), rn_getstream(), rn_link_down, rn_link_getstatus(), s, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), forward(), ftp_event_handler(), ftp_init(), ip_packet_drop(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_new(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().
{
        tw_event        *e;
        tw_stime         abs_ts = DBL_MAX;
        rn_lp_state     *state;
        rn_message      *r;
        rn_stream       *s;
        rn_machine      *m;
        //rn_link               *l;
        state = src->cur_state;
        s = rn_getstream(src);
        m = rn_getmachine(src->id);
        //l = rn_getlink(m, dst->id);
        // if model attempts to send upstream event, and is
        // top-most layer, abort processing
        if(dir == UPSTREAM && !s->cur_layer)
                return src->pe->abort_event;
        // Check for layer switching directions on us..
        if(state->cev)
        {
                r = tw_event_data(state->cev);
                if(r->type == UPSTREAM && dir == DOWNSTREAM)
                {
                        state->cev = NULL;
                } else if(r->type != dir && dir == UPSTREAM)
                {
                        state->cev = src->pe->cur_event;
                        abs_ts = state->cev->recv_ts + ts;
                }
        }
#if 0
        if(l && state->cev && rn_link_down == rn_link_getstatus(l, abs_ts))
        {
                e = src->pe->free_q->abort;
                e->src_lp = src;
                e->dest_lp = dst;
                e->recv_ts = tw_now(src) + ts;
                r = tw_event_data(src->pe->free_q->abort);
                r->type = dir;
                r->src = src->id;
                r->dst = dst->id;
                r->size = size;
                r->port = s->port;
                r->timer = NULL;
#if VERIFY_RN
                printf("%ld RN: new ABORT event %d, port %d \n",
                        src->id, (int) e, r->port);
#endif
                return e;
        }
#endif
        if(!state->cev)
        {
                e = tw_event_new(dst, ts, src);
                state->cev = e;
                r = tw_event_data(e);
                r->type = dir;
                r->src = src->id;
                r->dst = dst;
                r->size = size;
                r->port = s->port;
                r->timer = NULL;
                r->ttl = g_rn_ttl;
#if VERIFY_RN
                printf("%ld RN: Created new event %ld, port %d \n",
                        src->id, (long int) e, r->port);
#endif
        } else
        {
                e = state->cev;
                e->recv_ts += ts;
                r = tw_event_data(e);
                r->size = size;
                if(e->recv_ts > g_tw_ts_end)
                        src->pe->cev_abort = 1;
                //if((tw_lpid) e->dest_lp != dst)
                if(r->dst != dst)
                {
#if VERIFY_RN
                        printf("Redirecting event %ld: from %lld to %lld \n",
                                (long int) e, (tw_lpid) e->dest_lp, dst);
#endif
                        e->dest_lp = (tw_lp *) dst;
                }
        }
        return e;
}
void rn_event_send (tw_event * new_event)
Definition at line 173 of file rn-event.c.
References c_host, DIRECT, DOWNSTREAM, rn_getmachine(), rn_getstream(), rn_getstream_byport(), s, and UPSTREAM.
Referenced by bgp_connect(), bgp_keepalive_send(), bgp_keepalive_timer(), bgp_notify_send(), bgp_open_send(), bgp_update_send(), epi_agent_remove(), epi_num_add(), epi_num_check_report(), epi_num_remove(), ftp_event_handler(), ftp_init(), ip_downstream_forward(), ip_downstream_source(), ip_upstream(), num_file_start(), num_file_stop(), ospf_event_send(), tcp_event_send(), tcp_layer_util_event(), tcp_process_ack(), and tcp_timeout().
{
        tw_memory       *b;
        tw_lp           *l = NULL;
        rn_lp_state     *state = NULL;
        rn_stream       *s = NULL;
        rn_message      *rn_msg;
        rn_machine      *m;
        rn_msg = tw_event_data(new_event);
        if(new_event->src_lp == NULL || new_event->src_lp->pe->cev_abort)
        {
                return;
        } else if(rn_msg->type == DOWNSTREAM)
        {
                state = (rn_lp_state *) new_event->src_lp->cur_state;
                s = rn_getstream(new_event->src_lp);
        } else if(rn_msg->type == UPSTREAM)
        {
                state = (rn_lp_state *) new_event->dest_lp->cur_state;
                s = rn_getstream_byport(state, rn_msg->port);
        } else if(rn_msg->type == DIRECT)
        {
                tw_event_send(new_event);
                return;
#if 0
                /*
                 * This is totally out-of-band .. similiar to a SIG_ALARM
                 * on the local machine
                 */
                state = (rn_lp_state *) new_event->src_lp->cur_state;
                s = rn_getstream(new_event->src_lp);
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg, l);
                return;
#endif
        } else
        {
                tw_error(TW_LOC, "Unknown event type sent!");
        }
        /*
         * If direction is UP, and more layers, send up to next layer.
         * If direction is down, and more layers, send down to next layer
         *
         * If direction is UP, and at top, nowhere else to go,
         *                      so done, consider it processed.
         *
         * If direction is down, and no more layers, tw_event_send it.
         */
        if(rn_msg->type == UPSTREAM && s->cur_layer > 0)
        {
                s->cur_layer--;
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                if(s->cur_layer == 0)
                        state->cev = NULL;
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: layer %d sending msg UP, src %d,  dst %d, %lf \n",
                        (int) l->id,
                        s->cur_layer + 1,
                        (int) new_event->src_lp->id,
                        (int) new_event->dest_lp->id,
                        new_event->recv_ts);
#endif
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg,
                        new_event->dest_lp);
                s->cur_layer++;
                state->cur_lp = &s->layers[s->cur_layer].lp;
                state->l_stats.s_nevents_processed++;
        } else if(rn_msg->type == DOWNSTREAM && s->cur_layer < s->nlayers - 1)
        {
                s->cur_layer++;
                l = state->cur_lp = &s->layers[s->cur_layer].lp;
                if(!l)
                        tw_error(TW_LOC, "NO LP!");
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: layer %d sending msg DOWN, dst %d, ts %f \n",
                        (int) l->id,
                        (int) s->cur_layer - 1,
                        (int) new_event->dest_lp->id,
                        new_event->recv_ts);
#endif
                (*l->type.event)
                        (l->cur_state,
                        &new_event->cv,
                        (void *) rn_msg,
                        new_event->src_lp);
                // Restore the cur_layer when this lvl of recursion is complete
                s->cur_layer--;
                state->cev = NULL;
                state->cur_lp = &s->layers[s->cur_layer].lp;
                state->l_stats.s_nevents_processed++;
        } else if(rn_msg->type == DOWNSTREAM)
        {
                // Ok, so now we have reached the bottom of the stack and
                // can remove the event finally.
                if(new_event->src_lp->pe->cev_abort)
                {
                        while(NULL != (b = new_event->memory))
{
                                new_event->memory = b->next;
                                tw_memory_alloc_rc(new_event->src_lp, b, (tw_fd) b->prev);
                        }
                        return;
                }
#if VERIFY_RN
        if(rn_msg->src == 338 && rn_msg->dst == 8026)
                printf("%d RN: Sending remote event (%d) from layer %d: %d -%f-> %d \n",
                                (int) new_event->src_lp->id,
                                (int) new_event,
                                s->cur_layer,
                                (int) new_event->src_lp->id,
                                new_event->recv_ts,
                                (int) new_event->dest_lp->id);
#endif
                /*
                 * This is where we would want to do things like fixing up
                 * the timestamp on the
                 * message, and the dest_lp pointer in the event.  We need to
                 * change the dest_lp appropriately in order to reflect
                 * the final destination considering the connection and/or nbr
                 */
                rn_msg->type = UPSTREAM;
                m = rn_getmachine(new_event->src_lp->id);
                if(m->type == c_host)
                        new_event->dest_lp = (tw_lp *) m->link[0].addr;
                tw_event_send(new_event);
                state->cev = NULL;
        } else if(rn_msg->type == UPSTREAM)
        {
                tw_error(TW_LOC, "%lld: sending message up, top-most layer!? \n",
                                new_event->src_lp->gid);
        } else
        {
                tw_error(TW_LOC, "no send?");
        }
}