ROSS.Net: rn-link.c File Reference
rn-link.c File Reference
#include <rossnet.h>
Functions
void rn_link_setwire (rn_link *l)
rn_machine * rn_link_getwire (rn_link *l)
rn_link * rn_getlink (rn_machine *m, tw_lpid id)
rn_link_status rn_link_getstatus (rn_link *l, tw_stime ts)
void rn_link_random_changes (tw_lp *lp)
void rn_link_random_weight_changes (tw_lp *lp)
Function Documentation
rn_link* rn_getlink (rn_machine * m, tw_lpid id)
Definition at line 17 of file rn-link.c.
References rn_hash_fetch().
Referenced by bgp_connect(), bgp_init(), bgp_lsa_find(), bgp_route_add(), bgp_route_copy(), getroute(), ip_route(), neighbor_init(), ospf_lsa_create(), ospf_lsa_find(), rc_getroute(), rn_event_handler(), rn_link_random_changes(), rn_xml_link_topology(), and update_add().
{
#if 0
        int     i;
        for(i = 0; i < m->nlinks; i++)
                if(m->link[i].addr == id)
                        return &m->link[i];
        return NULL;
#else
        return rn_hash_fetch(m->hash_link, id);
#endif
}
rn_link_status rn_link_getstatus (rn_link * l, tw_stime ts)
Definition at line 33 of file rn-link.c.
References rn_link_down, and rn_link_up.
Referenced by rn_event_new().
{
        if(!l)
                tw_error(TW_LOC, "No link!");
#if DYNAMIC_LINKS
        if((l->status == rn_link_down && ts < l->next_status) ||
           (l->status == rn_link_up && ts >= l->next_status))
                return rn_link_down;
#endif
        return rn_link_up;
}
rn_machine* rn_link_getwire (rn_link * l)
Definition at line 11 of file rn-link.c.
{
        return l->wire;
}
void rn_link_random_changes (tw_lp * lp)
Definition at line 51 of file rn-link.c.
References g_rn_link_prob, rn_getlink(), and rn_getmachine().
{
#if DYNAMIC_LINKS
        rn_machine      *m;
        rn_link         *l;
        rn_link         *ol;
        int              percent;
        int              i;
        m = rn_getmachine(lp->id);
        for(i = 0; i < m->nlinks; i++)
        {
                l = &m->link[i];
                if(l->next_status != INT_MAX)
                        continue;
                percent = tw_rand_integer(lp->id, 0, 100);
                if(percent > g_rn_link_prob + 1)
                        return;
                ol = rn_getlink(l->wire, m->id);
                //l->next_status = ol->next_status = tw_rand_integer(lp->id, 25, g_tw_ts_end);
                //l->last_status = ol->last_status = 0;
                l->next_status = tw_rand_integer(lp->id, 25, g_tw_ts_end);
                l->last_status = 0;
        }
#endif
}
void rn_link_random_weight_changes (tw_lp * lp)
Definition at line 89 of file rn-link.c.
References LINK_STATUS_WEIGHT, and rn_getmachine().
{
        tw_stime         next_status;
        tw_event        *e;
        rn_message      *msg;
        rn_machine      *m;
        int              percent;
        int              i;
        m = rn_getmachine(lp->id);
        for(i = 0; i < m->nlinks; i++)
        {
                percent = tw_rand_integer(lp->rng, 0, 100);
                if(percent > 1 + 1)
                        return;
                next_status = tw_rand_integer(lp->rng, 1, g_tw_ts_end);
                e = tw_event_new(lp->gid, next_status, lp);
                msg = tw_event_data(e);
                msg->port = i;
                msg->src = lp->id;
                msg->dst = lp->id;
                msg->type = LINK_STATUS_WEIGHT;
                tw_event_send(e);
        }
}
void rn_link_setwire (rn_link * l)
Definition at line 4 of file rn-link.c.
References rn_getmachine().
Referenced by rn_machine_print().
{
        if(NULL == l->wire)
                l->wire = rn_getmachine(l->addr);
}