ROSS.Net: rn-message.c File Reference
rn-message.c File Reference
#include <rossnet.h>
Functions
void rn_message_setsize (rn_message *m, unsigned long size)
unsigned long rn_message_getsize (rn_message *m)
void * rn_message_data (rn_message *m)
void rn_message_setdirection (rn_message *m, rn_message_type direction)
int rn_message_getdirection (rn_message *m)
Function Documentation
void* rn_message_data (rn_message * m)
Definition at line 16 of file rn-message.c.
Referenced by bgp_r_event_handler(), ftp_event_handler(), ftp_init(), ospf_ip_route(), ospf_rc_event_handler(), rn_event_data(), tcp_layer_event_handler(), tcp_layer_init(), tcp_layer_process_ack(), tcp_layer_process_ack_rc(), tcp_layer_process_data(), tcp_layer_process_data_rc(), tcp_layer_rc_event_handler(), tcp_layer_startup(), tcp_layer_timeout(), tcp_layer_update_rtt(), tcp_layer_util_event(), and tcp_process_ack_rc().
{
        tw_error(TW_LOC, "This function is deprecated, please use memory buffers!");
        //return (void *) &m->data;
        return NULL;
}
int rn_message_getdirection (rn_message * m)
Definition at line 32 of file rn-message.c.
{
        return m->type;
}
unsigned long rn_message_getsize (rn_message * m)
Definition at line 10 of file rn-message.c.
Referenced by ospf_ip_route().
{
        return m->size;
}
void rn_message_setdirection (rn_message * m, rn_message_type direction)
Definition at line 25 of file rn-message.c.
{
        tw_error(TW_LOC, "This is no longer needed!!!");
        m->type = direction;
}
void rn_message_setsize (rn_message * m, unsigned long size)
Definition at line 4 of file rn-message.c.
Referenced by ospf_event_send(), and tcp_event_send().
{
        m->size = size;
}