ROSS.Net: rn-machine.c File Reference
rn-machine.c File Reference
#include <rossnet.h>
Functions
rn_machine * rn_getmachine (tw_lpid id)
void rn_setmachine (rn_machine *m)
rn_subnet * rn_getsubnet (rn_machine *m)
rn_area * rn_getarea (rn_machine *m)
rn_as * rn_getas (rn_machine *m)
void rn_machine_print (rn_machine *m)
Function Documentation
rn_area* rn_getarea (rn_machine * m)
Definition at line 22 of file rn-machine.c.
Referenced by bgp_init(), bgp_keepalive(), bgp_ospf_init(), bgp_ospf_update(), bgp_route_add(), bgp_route_withdraw(), bgp_xml(), epi_xml(), getlsa(), lsa_create(), main_setup_areas(), ospf_db_init(), ospf_lsa_create(), ospf_nbr_exchange_done(), ospf_nbr_inactivity_timer(), ospf_nbr_reset(), ospf_rt_print(), ospf_rt_timer(), ospf_startup(), ospf_xml(), and rn_route().
{
        return m->subnet->area;
}
rn_as* rn_getas (rn_machine * m)
Definition at line 28 of file rn-machine.c.
Referenced by bgp_decision(), bgp_final(), bgp_init(), bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_open(), bgp_open_send(), bgp_rib_print(), bgp_route_add(), bgp_route_copy(), bgp_route_new(), bgp_update_all(), bgp_update_send(), bgp_xml(), deal_with_timed_out_routers(), ospf_event_handler(), ospf_nbr_reset(), ospf_xml(), rn_route(), update_add(), and update_withdraw().
{
        return m->subnet->area->as;
}
rn_machine* rn_getmachine (tw_lpid id)
Definition at line 4 of file rn-machine.c.
References g_rn_machines.
Referenced by bgp_decision(), bgp_final(), bgp_init(), bgp_keepalive(), bgp_lsa_find(), bgp_lsa_link_allocate(), bgp_open(), bgp_open_send(), bgp_ospf_init(), bgp_ospf_update(), bgp_rib_print(), bgp_route_add(), bgp_route_copy(), bgp_route_new(), bgp_update_all(), bgp_update_send(), bgp_xml(), deal_with_timed_out_routers(), epi_xml(), getroute(), ip_event_handler(), ip_init(), main_setup_areas(), neighbor_init(), ospf_ip_route(), ospf_lsa_create(), ospf_nbr_reset(), ospf_routing_init(), ospf_rt_print(), ospf_rt_timer(), ospf_startup(), ospf_xml(), rc_getroute(), rn_event_new(), rn_event_send(), rn_link_random_changes(), rn_link_random_weight_changes(), rn_link_setwire(), rn_route(), rn_setup_links(), rn_setup_streams(), rn_startup(), rn_xml_link_topology(), rn_xml_topology(), routing_init_ft_read(), routing_init_ft_write(), routing_write(), tcp_final(), tcp_init(), tcp_layer_init(), update_add(), update_withdraw(), and xml_link_topology().
{
        return &g_rn_machines[id];
}
rn_subnet* rn_getsubnet (rn_machine * m)
Definition at line 16 of file rn-machine.c.
Referenced by epi_xml().
{
        return m->subnet;
}
void rn_machine_print (rn_machine * m)
Definition at line 34 of file rn-machine.c.
References rn_link_setwire().
{
        int     i;
        rn_link *l;
        printf("\tnLinks: %d \n", m->nlinks);
        for(i = 0; i < m->nlinks; i++)
        {
                l = &m->link[i];
                if(NULL == l->wire)
                        rn_link_setwire(l);
#if DYNAMIC_LINKS
                if(l->status == 0)
                        printf("\t\tLink status: down \n");
                else
                        printf("\t\tLink status: up\n");
#endif
                printf("\t\tLink to: %lld \n",
                        l->addr);
                printf("\t\tLink delay: %f \n",
                        l->delay);
                printf("\t\tLink bandwidth: %lf \n",
                        l->bandwidth);
                printf("\n");
        }
}
void rn_setmachine (rn_machine * m)
Definition at line 10 of file rn-machine.c.
References g_rn_machines.
{
        g_rn_machines[m->id] = *m;
}