ROSS.Net: rn-routing.c File Reference
rn-routing.c File Reference
#include <rossnet.h>
Functions
int rn_route (rn_machine *m, tw_lpid dst)
int rn_route_change (rn_machine *m, int loc, int new_val)
Function Documentation
int rn_route (rn_machine * m, tw_lpid dst)
Definition at line 7 of file rn-routing.c.
References g_rn_nas, rn_getarea(), rn_getas(), and rn_getmachine().
Referenced by bgp_connect(), bgp_init(), bgp_lsa_find(), bgp_route_add(), bgp_route_copy(), bgp_route_withdraw(), dd_exchange(), ospf_db_route(), ospf_ip_route(), ospf_lsa_create(), ospf_routing_init(), ospf_rt_print(), and update_add().
{
        rn_area *ar = rn_getarea(m);
        rn_as   *as = ar->as;
        rn_area *d_ar = rn_getarea(rn_getmachine(dst));
        rn_as   *d_as = rn_getas(rn_getmachine(dst));
        if(dst >= ar->low && dst <= ar->high)
        {
                if(dst - ar->low >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[dst - ar->low];
        } else if(d_ar->id >= as->low && d_ar->id <= as->high)
        {
                if(ar->nmachines + d_ar->id - d_as->low  >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[ar->nmachines + d_ar->id - d_as->low];
        } else if(d_as->id >= 0 && d_as->id < g_rn_nas)
        {
                if(ar->nmachines + as->nareas + d_as->id  >= ar->g_ospf_nlsa)
                        tw_error(TW_LOC, "Out of range!");
                return (int) m->ft[ar->nmachines + as->nareas + d_as->id];
        } else
        {
                printf("%lld: Attempting to route to network? %d >= %lld \n",
                        m->id, ar->nmachines + as->nareas + g_rn_nas, dst);
                printf("%lld: nMachines %d, Area %d, AS nAreas %d, AS %d \n",
                        m->id, ar->nmachines, ar->id, as->nareas, as->id);
                return -1;
        }
}
int rn_route_change (rn_machine * m, int loc, int new_val)
Definition at line 48 of file rn-routing.c.
Referenced by bgp_route_add(), bgp_route_withdraw(), and ospf_db_route().
{
        char old_val = m->ft[loc];
        m->ft[loc] = new_val;
        return (int) old_val;
}