ROSS.Net: rn-stream.c File Reference
rn-stream.c File Reference
#include <rossnet.h>
Functions
rn_stream * rn_getstream_byport (rn_lp_state *state, tw_lpid port)
rn_stream * rn_getstream (tw_lp *lp)
rn_stream * rn_stream_alloc (unsigned int nstreams)
Function Documentation
rn_stream* rn_getstream (tw_lp * lp)
Definition at line 23 of file rn-stream.c.
References s.
Referenced by rn_event_direct(), rn_event_new(), rn_event_send(), rn_timer_init(), and rn_timer_simple().
{
        rn_lp_state     *state;
        rn_stream       *s;
        state = (rn_lp_state *) lp->cur_state;
        s = &state->streams[state->cur_stream];
        if(!s)
                tw_error(TW_LOC, "Could not get stream from lp %d!", lp->id);
        return s;
}
rn_stream* rn_getstream_byport (rn_lp_state * state, tw_lpid port)
Definition at line 4 of file rn-stream.c.
Referenced by bgp_ospf_init(), bgp_ospf_update(), rn_event_handler(), rn_event_send(), and rn_rc_event_handler().
{
        unsigned int    i;
        for(i = 0; i < state->nstreams; i++)
        {
                if(state->streams[i].port == port)
                {
                        state->cur_stream = i;
                        return &state->streams[i];
                }
        }
        //tw_error(TW_LOC, "Unable to find stream port %d!", port);
        return state->streams;
}
rn_stream* rn_stream_alloc (unsigned int nstreams)
This function allocates the streams to the rn_lps during the rn_startup phase, which is multi-threaded
Definition at line 42 of file rn-stream.c.
References g_rn_nextstream, g_rn_stream_lck, and g_rn_streams.
Referenced by rn_setup_streams().
{
        rn_stream       *stream;
        tw_mutex_lock(&g_rn_stream_lck);
        if(nstreams == 0)
                tw_error(TW_LOC, "No streams for this node!");
#if RN_VERIFY_LP
        if(nstreams > 1)
                printf("Allocating streams: %d to %d \n",
                                g_rn_nextstream, (g_rn_nextstream + nstreams - 1));
        else if(nstreams == 1)
                printf("Allocating stream: %d \n", g_rn_nextstream);
        else
                tw_error(TW_LOC, "Trying to allocate %d streams!", nstreams);
#endif
        stream = &g_rn_streams[g_rn_nextstream];
        g_rn_nextstream += nstreams;
        tw_mutex_unlock(&g_rn_stream_lck);
        return stream;
}