ROSS.Net: rn-timer.c File Reference
rn-timer.c File Reference
#include <rossnet.h>
Functions
tw_event * rn_timer_simple (tw_lp *lp, tw_stime ts)
tw_event * rn_timer_init (tw_lp *lp, tw_stime ts)
tw_event * rn_timer_reset (tw_lp *lp, tw_event **e, tw_stime ts)
void rn_timer_cancel (tw_lp *lp, tw_event **e)
Function Documentation
void rn_timer_cancel (tw_lp * lp, tw_event ** e)
Definition at line 80 of file rn-timer.c.
Referenced by bgp_timer_cancel(), epi_timer_cancel(), num_timer_cancel(), ospf_timer_cancel(), stop_transfer(), tcp_rc_timer_reset(), and tcp_timer_cancel().
{
        tw_timer_cancel(lp, e);
        e = NULL;
}
tw_event* rn_timer_init (tw_lp * lp, tw_stime ts)
Definition at line 30 of file rn-timer.c.
References rn_getstream(), s, and TIMER.
Referenced by bgp_timer_start(), epi_init(), epi_location_timer(), epi_timer_start(), num_file_complete(), num_start(), num_timer_start(), ospf_timer_start(), start_transfer(), tcp_host_timeout(), tcp_layer_init(), tcp_layer_startup(), tcp_layer_timeout(), and tcp_timer_reset().
{
        tw_event        *e;
        rn_lp_state     *state;
        rn_message      *msg;
        rn_stream       *s;
        e = tw_timer_init(lp, ts);
        if(!e)
                return NULL;
        msg = tw_event_data(e);
        state = lp->cur_state;
        s = rn_getstream(lp);
        msg->type = TIMER;
        msg->timer = state->cur_lp;
        msg->src = lp->id;
        msg->dst = lp->id;
        msg->size = s->cur_layer;
        msg->port = s->port;
        msg->ttl = 0;
        return e;
}
tw_event* rn_timer_reset (tw_lp * lp, tw_event ** e, tw_stime ts)
Definition at line 58 of file rn-timer.c.
References TIMER.
Referenced by bgp_timer_start(), epi_location_timer(), epi_timer_start(), num_timer_start(), ospf_timer_start(), tcp_host_process_ack(), tcp_host_update_rtt(), tcp_layer_process_ack(), tcp_layer_update_rtt(), and tcp_timer_reset().
{
        rn_message      *msg;
        rn_lp_state     *state;
        tw_timer_reset(lp, e, ts);
        if(!*e)
                return *e;
        state = (rn_lp_state *) lp->cur_state;
        msg = (rn_message *) tw_event_data(*e);
        msg->type = TIMER;
        msg->timer = state->cur_lp;
        msg->src = lp->id;
        msg->dst = lp->id;
        return *e;
}
tw_event* rn_timer_simple (tw_lp * lp, tw_stime ts)
Definition at line 4 of file rn-timer.c.
References rn_getstream(), s, and TIMER.
Referenced by bgp_timer_start(), and ospf_random_weights().
{
        tw_event        *tmr;
        rn_lp_state     *state;
        rn_message      *r;
        rn_stream       *s;
        state = lp->cur_state;
        tmr = tw_event_new(lp->gid, ts, lp);
        r = tw_event_data(tmr);
        s = rn_getstream(lp);
        r->type = TIMER;
        r->dst = lp->id;
        r->src = lp->id;
        r->timer = state->cur_lp;
        r->size = s->cur_layer;
        r->port = s->port;
        tw_event_send(tmr);
        return tmr;
}