ROSS.Net: rn.c File Reference
rn.c File Reference
#include <rossnet.h>
#include <rn_config.h>
Functions
tw_peid rn_map (tw_lpid gid)
void rn_startup (rn_lp_state *state, tw_lp *lp)
void rn_event_handler (rn_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rn_rc_event_handler (rn_lp_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void rn_final (rn_lp_state *state, tw_lp *lp)
void rn_print_statistics ()
int main (int argc, char **argv, char **env)
Variables
rn_lptype layer_types []
unsigned int g_rn_memory = 0
tw_lptype rnlps []
const tw_optdef rn_opts []
Function Documentation
int main (int argc, char ** argv, char ** env)
Definition at line 522 of file rn.c.
References g_rn_lptypes, g_rn_msg_sz, g_rn_stats, layer_types, rn_init(), rn_init_lps(), rn_models_final(), rn_models_init(), rn_print_statistics(), rn_setup(), rn_xml_end(), and rn_xml_init().
{
        int              i;
        g_rn_stats = tw_calloc(TW_LOC, "RN Statistics", sizeof(*g_rn_stats), 1);
        g_rn_lptypes = layer_types;
        /* add command line args */
        tw_opt_add(rn_opts);
        /* Initialize ROSS */
        tw_init(&argc, &argv);
        rn_setup();
        /* init the XML package */
        rn_xml_init();
        /* RN configurables */
        g_rn_msg_sz = sizeof(rn_message);
#ifdef HAVE_EPI_H
        g_tw_memory_nqueues += 1;
#endif
#ifdef HAVE_TCP_H
        g_tw_memory_nqueues += 1;
#endif
#ifdef HAVE_OSPF_H
        g_tw_memory_nqueues += 5;
#endif
#ifdef HAVE_IP_H
        g_tw_memory_nqueues += 1;
#endif
#ifdef HAVE_BGP_H
        g_tw_memory_nqueues += 3;
#endif
        /* Initialize RN */
        if(0 == (rn_init(layer_types)))
                tw_error(TW_LOC, "ROSS.Net could not be initialized. \n");
        /* ROSS configurables */
        g_tw_nlp /= tw_nnodes();
        g_tw_events_per_pe = g_tw_nlp * 40;
        tw_define_lps(g_tw_nlp, g_rn_msg_sz, 0);
        /* initialize the models */
        rn_models_init(layer_types, argc, argv, env);
        for(i = 0; i < g_tw_nlp; i++)
                tw_lp_settype(i, &rnlps[0]);
        rn_init_lps(layer_types);
        rn_xml_end();
        tw_run();
        rn_models_final(layer_types);
        rn_print_statistics();
        return 0;
}
void rn_event_handler (rn_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 235 of file rn.c.
References DIRECT, g_rn_machines, LINK_STATUS, LINK_STATUS_DOWN, LINK_STATUS_UP, LINK_STATUS_WEIGHT, rn_getlink(), rn_getstream_byport(), rn_link_down, rn_link_up, TIMER, and UPSTREAM.
{
#if DYNAMIC_LINKS
        tw_event        *e;
#endif
        tw_lp           *l;
#if DYNAMIC_LINKS
        rn_message      *m;
#endif
        rn_stream       *cur_stream;
        state->l_stats.s_nevents_processed++;
        /*
         * Timers need to be sent directly to the layer which set them
         */
        if (msg->type == TIMER)
        {
                state->cev = NULL;
                state->cur_lp = msg->timer;
                cur_stream = rn_getstream_byport(state, msg->port);
                cur_stream->cur_layer = msg->size;
#if VERIFY_RN
                printf("\n%ld RN: TIMER src %ld, port %ld, ts %lf \n\n",
                                lp->id, msg->src, msg->port, tw_now(lp));
#endif
                (*msg->timer->type.event) (msg->timer->cur_state, bf, msg, lp);
                return;
        } else if(msg->type == DIRECT)
        {
                // handled in the same way as TIMER events
                state->cev = NULL;
                state->cur_lp = msg->timer;
                cur_stream = rn_getstream_byport(state, msg->port);
                cur_stream->cur_layer = msg->size;
                state->cev = NULL;
                state->cur_lp = &cur_stream->layers[0].lp;
                cur_stream = rn_getstream_byport(state, msg->port);
                cur_stream->cur_layer = 0;
#if VERIFY_RN
                printf("\n%ld RN: DIRECT src %ld, port %ld, ts %lf \n\n",
                                lp->id, msg->src, msg->port, tw_now(lp));
#endif
                //(*msg->timer->type.event) (msg->timer->cur_state, bf, msg, lp);
                (*state->cur_lp->type.event) (state->cur_lp->cur_state, bf, msg, lp);
                return;
        } else if(msg->type == LINK_STATUS ||
                  msg->type == LINK_STATUS_DOWN ||
                  msg->type == LINK_STATUS_UP ||
                  msg->type == LINK_STATUS_WEIGHT)
        {
                rn_link *l;
#if VERIFY_RN
                printf("%ld: link to %ld status change at %lf: %d -> %d \n",
                        lp->id,
                        g_rn_machines[lp->id].link[msg->port].wire->id,
                        tw_now(lp),
                        g_rn_machines[lp->id].link[msg->port].status,
                        msg->type);
#endif
                l = &g_rn_machines[lp->id].link[msg->port];
                if(msg->type == LINK_STATUS_WEIGHT)
                {
                        tw_error(TW_LOC, "Link cost disabled!");
                        //l->cost = tw_rand_integer(lp->id, 1, 100);
                }
#if DYNAMIC_LINKS
                else if(msg->type == LINK_STATUS_DOWN)
                {
                        l->status = rn_link_down;
                } else if(msg->type == LINK_STATUS_UP)
                {
                        l->status = rn_link_up;
                } else
                {
                        if(l->status == rn_link_up)
                                l->status = rn_link_down;
                        else
                                l->status = rn_link_up;
                }
                l->last_status = tw_now(lp);
                l->next_status = INT_MAX;
                /*
                 * If mode != once, then need to send the next
                 * status change event here!
                 */
                // If we took the link down, then bring it back up again
                // a short time later
                if(0 && msg->type == LINK_STATUS_DOWN)
                {
                        rn_link *ol = rn_getlink(l->wire, lp->id);
                        if(ol->next_status > tw_now(lp))
                                l->next_status = ol->next_status;
                        else
                                l->next_status = tw_rand_integer(lp->id, floor(tw_now(lp)),
                                                         floor(tw_now(lp)) + 100);
                        e = tw_event_new(lp, l->next_status - tw_now(lp), lp);
                        m = tw_event_data(e);
                        m->timer = NULL;
                        m->port = msg->port;
                        m->src = lp->id;
                        m->dst = lp->id;
                        m->type = LINK_STATUS_UP;
                        tw_event_send(e);
                        printf("%ld: bringing link to %d up at time %lf (ns: %lf), now %lf\n",
                                lp->id, l->addr, e->recv_ts, l->next_status, tw_now(lp));
                }
#endif
                return;
        }
        if(msg->type != UPSTREAM)
                tw_error(TW_LOC, "Did not get upstream event!");
        /*
         * This is where we traverse the star model:
         *
         * We need to start by finding the LP(s) which are on the port,
         * and the send up the list based on the port number.. I suppose
         * multiple layers could be using the same port at the same level,
         * so we need to handle that also.
         */
        cur_stream = rn_getstream_byport(state, msg->port);
        state->cev = lp->pe->cur_event;
        l = &cur_stream->layers[cur_stream->nlayers-1].lp;
        cur_stream->cur_layer = cur_stream->nlayers - 1;
        state->cur_lp = l;
        if(cur_stream->cur_layer == 0)
                state->cev = NULL;
#if VERIFY_RN
        printf("\n%ld RN: UPSTREAM src %ld, ts %lf \n",
                        lp->id, msg->src, tw_now(lp));
#endif
        (*l->type.event) (l->cur_state, bf, msg, lp);
}
void rn_final (rn_lp_state * state, tw_lp * lp)
Definition at line 439 of file rn.c.
References g_rn_stats, and s.
{
        tw_lp           *l;
        rn_stream       *s;
        unsigned int i;
        unsigned int j;
        if(0 == lp->id % 100000)
                printf("Finalizing RN lp %d \n", (int) lp->id);
        for (i = 0; i < state->nstreams; i++)
        {
                s = &state->streams[i];
                for(j = 0; j < s->nlayers; j++)
                {
                        l = &s->layers[j].lp;
                        (*l->type.final) (l->cur_state, lp);
                }
        }
        g_rn_stats->s_nevents_processed += state->l_stats.s_nevents_processed;
        g_rn_stats->s_nevents_rollback += state->l_stats.s_nevents_rollback;
}
tw_peid rn_map (tw_lpid gid)
Definition at line 163 of file rn.c.
{
        return (tw_peid) gid / g_tw_nlp;
}
void rn_print_statistics ()
Definition at line 481 of file rn.c.
References g_rn_stats.
Referenced by main().
{
        tw_lpid  events;
        printf("\nROSS.Net Library Statistics: \n\n");
        printf("\t%-50s %11d\n", "Event Size", (int) g_tw_msg_sz);
        printf("\t%-50s %11d\n", "Total Events Processed",
                   g_rn_stats->s_nevents_processed);
        printf("\t%-50s %11d\n", "Events Rolled Back",
                   g_rn_stats->s_nevents_rollback);
        printf("\n");
        events = g_rn_stats->s_nevents_processed - g_rn_stats->s_nevents_rollback;
        printf("\t%-50s %11lld *\n", "Network Events Processed", events);
        printf("\t%-50s %11.2f (events/sec)\n", "Event Rate",
                (double) (events / g_tw_pe[0]->statistics.max_run_time));
}
void rn_rc_event_handler (rn_lp_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 401 of file rn.c.
References rn_getstream_byport(), TIMER, and UPSTREAM.
{
        tw_lp          *l;
        rn_stream       *cur_stream;
        state->l_stats.s_nevents_processed--;
        if (msg->type == TIMER)
        {
                state->cur_lp = msg->timer;
                (*msg->timer->type.revent) (msg->timer->cur_state, bf, msg, lp);
                return;
        }
        cur_stream = rn_getstream_byport(state, msg->port);
        if (msg->type == UPSTREAM)
        {
                l = &cur_stream->layers[0].lp;
                state->cur_lp = l;
                (*l->type.revent) (l->cur_state, bf, msg, lp);
        } else
        {
                l = &cur_stream->layers[cur_stream->nlayers - 1].lp;
                state->cur_lp = l;
                (*l->type.revent) (l->cur_state, bf, msg, lp);
        }
}
void rn_startup (rn_lp_state * state, tw_lp * lp)
Definition at line 169 of file rn.c.
References g_rn_nlink_status, rn_getmachine(), rn_init_streams(), and rn_setup_links().
{
        rn_machine     *m;
#if RN_TIMING
        tw_wtime        start;
        tw_wtime        end;
        tw_wtime        run;
        tw_wtime        xml_start;
        tw_wtime        xml_end;
        tw_wtime        xml_run;
        tw_wtime        init_start;
        tw_wtime        init_end;
        tw_wtime        init_run;
        int             memory;
        tw_wall_now(&start);
        memory = sizeof(rn_lp_state);
#endif
        if(0 == lp->id % 100000)
                printf("Initializing RN lp %d \n", (int) lp->id);
        /* Our machine gives us all the configurables from the XML topology */
        m = rn_getmachine(lp->id);
        //rn_link_random_changes(lp);
        rn_setup_links(state, lp);
        rn_init_streams(state, lp);
        if(lp->id == g_tw_nlp - 1)
                printf("Link status changes: %d \n", g_rn_nlink_status);
#if RN_TIMING
        //memory += sizeof(tw_lp) * m->nlayers;
        tw_wall_now(&end);
        tw_wall_sub(&run, &end, &start);
        tw_wall_sub(&xml_run, &xml_end, &xml_start);
        tw_wall_sub(&init_run, &init_end, &init_start);
        g_rn_memory += memory;
        if (lp->id % 50 == 0)
        {
                printf
                        ("rn lp %d: Done with startup, xml %f secs, init %f secs, overall %f secs\n",
                         lp->id, tw_wall_to_double(&xml_run), tw_wall_to_double(&init_run),
                         tw_wall_to_double(&run));
                printf
                        ("rn lp %d: memory used for this lp %d, overall to now %d \n\n",
                         lp->id, memory, g_rn_memory);
        }
#endif
        if(g_tw_nlp == lp->id)
                printf("Initializing rn lps complete! \n");
        return;
}
Variable Documentation
unsigned int g_rn_memory = 0
Definition at line 160 of file rn.c.
rn_lptype layer_types[]
Definition at line 38 of file rn.c.
Referenced by main().
const tw_optdef rn_opts[]
Initial value:
{
        TWOPT_GROUP("ROSS.Net Model"),
        TWOPT_UINT("link-prob", g_rn_link_prob, "link failure rate"),
        TWOPT_UINT("bgp", g_rn_converge_bgp, "pre-converge BGP model"),
        TWOPT_UINT("ospf", g_rn_converge_ospf, "pre-converge OSPFv2 model"),
        TWOPT_CHAR("log-dir", g_rn_logs_dir, "user specified log directory"),
        TWOPT_CHAR("topology", g_rn_xml_topology, "user specified XML config file"),
        TWOPT_CHAR("route-table", g_rn_rt_table, "user specified routing table"),
        TWOPT_CHAR("model", g_rn_xml_model, "user specified model"),
        TWOPT_CHAR("link-topology", g_rn_xml_link_topology, "user specified link topology"),
        TWOPT_CHAR("scenario", g_rn_tools_dir, "tools scenario"),
}
Definition at line 500 of file rn.c.
tw_lptype rnlps[]
Initial value:
 {
        {
         (init_f) rn_startup,
         (event_f) rn_event_handler,
         (revent_f) rn_rc_event_handler,
         (final_f) rn_final,
         (map_f) rn_map,
         sizeof(rn_lp_state),
        },
        {0}
        ,
}
Definition at line 467 of file rn.c.