ROSS.Net: num-helper.c File Reference
num-helper.c File Reference
#include <num.h>
Functions
char * get_tod (tw_stime ts)
Variables
static char tod [1024]
Function Documentation
char* get_tod (tw_stime ts)
Definition at line 6 of file save/num-helper.c.
References d, s, tod, and TWENTY_FOUR_HOURS.
Referenced by num_file_complete(), num_file_start(), and num_file_stop().
{
        int time = (int) ts % TWENTY_FOUR_HOURS;
        int d = (int) ts / TWENTY_FOUR_HOURS;;
        int h = time / 3600;
        int m = (time % 3600) / 60;
        double s = ts - (d * 86400) - (h * 3600) - (m * 60);
        sprintf(tod, "D%d %02d:%02d:%02.4lf", d, h, m, s);
        return tod;
}
Variable Documentation
char tod[1024] [static]
Definition at line 3 of file save/num-helper.c.