ROSS.Net: epi-main.c File Reference
epi-main.c File Reference
#include <epi.h>
Functions
void epi_main (int argc, char **argv, char **env)
void epi_md_final ()
Function Documentation
void epi_main (int argc, char ** argv, char ** env)
Definition at line 8 of file save/epi-main.c.
References epi_init_scenario(), epi_setup_options(), g_epi_log_f, g_epi_stats, and g_rn_logs_dir.
{
        char    log[1024];
        g_epi_stats = tw_vector_create(1, sizeof(epi_statistics));
        sprintf(log, "%s/epi.log", g_rn_logs_dir);
        g_epi_log_f = fopen(log, "w");
        if(!g_epi_log_f)
                tw_error(TW_LOC, "Unable to open: %s \n", log);
        // parse command line args
        epi_setup_options(argc, argv);
        // read input files, create global data structures, etc
        epi_init_scenario();
}
void epi_md_final ()
Definition at line 28 of file save/epi-main.c.
References epi_stats_print(), g_epi_log_f, g_epi_nagents, and g_epi_nsick.
{
        if (g_epi_log_f)
                fclose(g_epi_log_f);
        printf("\nPandemic Flu Initial State Variables: \n");
        printf("\n");
        printf("\t%-50s %11d\n", "Total Agents", g_epi_nagents);
        printf("\t%-50s %11d\n", "Total Sick", g_epi_nsick);
        printf("\n");
        epi_stats_print();
}