ROSS.Net: epi.c File Reference
epi.c File Reference
#include <epi.h>
Defines
#define EPI_MAP_LINEAR 1
#define TWENTY_FOUR_HOURS 86400
Functions
void epi_init (epi_state *state, tw_lp *lp)
void epi_event_handler (epi_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void epi_rc_event_handler (epi_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
void epi_final (epi_state *state, tw_lp *lp)
Define Documentation
#define EPI_MAP_LINEAR 1
Definition at line 3 of file save/epi.c.
#define TWENTY_FOUR_HOURS 86400
Definition at line 10 of file save/epi.c.
Function Documentation
void epi_event_handler (epi_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 63 of file save/epi.c.
References epi_agent_add(), epi_agent_remove(), epi_agent_stage_tran(), epi_location_timer(), epi_num_add(), epi_num_remove(), epi_report_census_tract(), epi_seir_compute(), EPSILON, g_epi_complete, g_epi_day, g_epi_next_report_day, g_epi_nreport_days, g_epi_report_days, and TWENTY_FOUR_HOURS.
{
        epi_agent       *a;
        int              today;
        // TO DO: need to check for last day to get last day of statistics
        today = (int) (tw_now(lp) / TWENTY_FOUR_HOURS);
        if( today > g_epi_day)
        {
                // report yesterday's statistics
                epi_report_census_tract();
                g_epi_day++;
        }
        tw_stime delta_time = tw_now(lp) - state->last_event;
        if(NULL == (a = (epi_agent *) tw_event_memory_get(lp)))
                tw_error(TW_LOC, "No agent on event!");
        *(int *) bf = 0;
        switch(a->e_type)
        {
                case EPI_ADD:
                        // compute SEIR for existing, then add agent to LP
                        // skip seir if no time has passed
                        if ( (state->ncontagious > 0) && (EPSILON < delta_time) )
                                epi_seir_compute(state, bf, a, lp);
                        epi_agent_add(state, bf, a, lp);
                        epi_num_add(state, bf, a, lp);
                        break;
                case EPI_REMOVE:
                        // compute SEIR for all, then remove agent from LP
                        // skip seir if no time has passed
                        if((state->ncontagious > 0) && (EPSILON < delta_time))
                                epi_seir_compute(state, bf, a, lp);
                        if (epi_agent_remove(state, bf, a, lp))
                                epi_num_remove(state, bf, a, lp);
                        break;
                case EPI_STAGE_TRANSITION:
                        // compute seir for all, then change stage for agent
                        // skip seir if no time has passed
                        if( (state->ncontagious > 0) && (EPSILON < delta_time) )
                                epi_seir_compute(state, bf, a, lp);
                        epi_agent_stage_tran(state, bf, a, lp);
                        break;
                default:
                        tw_error(TW_LOC, "Unhandled event message!");
        }
        state->last_event = tw_now(lp);
}
void epi_final (epi_state * state, tw_lp * lp)
Definition at line 142 of file save/epi.c.
References epi_report_census_tract(), g_epi_day, and g_epi_stats.
{
        if(g_epi_day)
        {
                epi_report_census_tract();
                g_epi_day = 0;
        }
        g_epi_stats->s_move_ev += state->stats->s_move_ev;
        g_epi_stats->s_nchecked += state->stats->s_nchecked;
        g_epi_stats->s_ndraws += state->stats->s_ndraws;
        g_epi_stats->s_ninfected += state->stats->s_ninfected;
        g_epi_stats->s_ndead += state->stats->s_ndead;
}
void epi_init (epi_state * state, tw_lp * lp)
Definition at line 19 of file save/epi.c.
References epi_location_timer(), pq_top(), and rn_timer_init().
{
        epi_agent       *a = pq_top(state->pq);
        // agents mapped to LP?
        if(!a)
        {
                // NOTE: If not home assumed to be work
                // No check for school, etc.
                state->grid_type = EPI_GRID_OFFICE_1;
                return;
        }
        state->grid_type = EPI_GRID_HOME;
        // agents will not have a remove time of zero.
        // set timer for minimum of ts_remove and ts_stage_tran with
        // appropriate event type.  EPI_STAGE_TRANSITION has priority.
        if (a->ts_stage_tran <= a->ts_remove)
        {
                state->tmr_remove = rn_timer_init(lp, a->ts_stage_tran);
                a->e_type = EPI_STAGE_TRANSITION;
        } else
        {
                state->tmr_remove = rn_timer_init(lp, a->dur[0]);
                a->e_type = EPI_REMOVE;
        }
        if(state->tmr_remove)
                state->tmr_remove->memory = (tw_memory *) a;
//      else
//              tw_error("tmr_remove at lp %ld for agent %u is NULL\n", lp->id, a->id);
        //printf("%ld: TMR for %u at %lf\n", lp->id, a->id, state->tmr_remove->recv_ts);
}
void epi_rc_event_handler (epi_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 131 of file save/epi.c.
{
}