ROSS.Net: num-file.c File Reference
num-file.c File Reference
#include <num.h>
Defines
#define NUM_VERIFY 1
#define ONE 0
#define DEBUG_LP 504065
Functions
void num_file_start (num_state *state, tw_bf *bf, unsigned int size, tw_lp *lp)
void num_file_stop (num_state *state, tw_bf *bf, tw_lp *lp)
void num_file_complete (num_state *state, tw_bf *bf, rn_message *msg, tw_lp *lp)
Define Documentation
#define DEBUG_LP 504065
Definition at line 5 of file save/num-file.c.
#define NUM_VERIFY 1
Definition at line 3 of file save/num-file.c.
#define ONE 0
Definition at line 4 of file save/num-file.c.
Function Documentation
void num_file_complete (num_state * state, tw_bf * bf, rn_message * msg, tw_lp * lp)
Definition at line 55 of file save/num-file.c.
References DEBUG_LP, g_num_profiles, get_tod(), MAX_FILE_SIZE, MIN_FILE_SIZE, num_file_start(), QUIT_TIME, rn_timer_init(), TWENTY_FOUR_HOURS, and TWO_MINUTES.
Referenced by num_event_handler().
{
        tw_stime         elapsed;
        tw_stime         ts, tn;
        num_profile     *np;
        int              actual;
        int              timeofday;
#if NUM_VERIFY
        if(lp->id == DEBUG_LP)
                printf("%ld T%d %s: FILE_COMPLETE\n", lp->id, state->type,
                         get_tod(tw_now(lp)));
#endif
        tn = tw_now(lp);
        timeofday = (int) tn % TWENTY_FOUR_HOURS;
        elapsed = tn - state->start;
        if(msg->size == 40)
        {
                tw_error(TW_LOC, "Received TCP ACK!");
        } else if (msg->size > 40)
        {
                state->stats->s_total_time += elapsed;
                state->stats->s_total_kb += state->file_size;
                state->stats->s_nfiles++;
        } else
        {
                // try again?
                state->stats->s_nfailures = 3;;
                return;
        }
        actual = state->file_size / elapsed;
        np = &g_num_profiles[state->type];
#if NUM_VERIFY
        if(lp->id == DEBUG_LP)
        {
                printf("%ld T%d %s: actual: %d, desired: %u, size: %.2lfB, elapsed: %lf\n",
                        lp->id, state->type, get_tod(tw_now(lp)), actual,
                        np->bitrate, (double) state->file_size / 8.0, elapsed);
        }
#endif
#if ONE
        if(lp->id != DEBUG_LP)
                return;
#endif
        // If after quitting time, then do not ask for another file
        if(timeofday >= QUIT_TIME)
                return;
        // Both rate and desired are in bits / second
        if(actual >= np->bitrate)
        {
                // Stay with file_size if achieved the desired bitrate
                ts = tn + ((state->file_size / np->bitrate) - elapsed);
                if ( ts <= tn )
                        ts = tn + 1.0;
                if((int) ts % TWENTY_FOUR_HOURS >= QUIT_TIME)
                        return;
                rn_timer_init(lp, ts);
        } else if (actual >= np->bitrate / 10.0)
        {
                // Ask for another file right away
                state->file_size *= 2;
                if(state->file_size > MAX_FILE_SIZE)
                        state->file_size = MAX_FILE_SIZE;
                num_file_start(state, bf, state->file_size, lp);
        } else
        {
                // rate is less than acceptable, walk away from network
                // this would be stage 2
                state->stats->s_nfailures = 2;
        }
}
void num_file_start (num_state * state, tw_bf * bf, unsigned int size, tw_lp * lp)
Definition at line 8 of file save/num-file.c.
References DEBUG_LP, DOWNSTREAM, get_tod(), rn_event_new(), and rn_event_send().
Referenced by num_event_handler(), num_file_complete(), and num_start().
{
#if NUM_VERIFY
        if(lp->id == DEBUG_LP)
                printf("%ld T%d %s: FILE_START size: %.2lfB\n",
                        lp->id, state->type, get_tod(tw_now(lp)), (double) size / 8.0);
#endif
        // send event down to TCP
        state->file_size = size;
        state->stats->s_nstart++;
        state->start = tw_now(lp);
        rn_event_send(rn_event_new(lp, 0.0, lp, DOWNSTREAM, size/8));
}
void num_file_stop (num_state * state, tw_bf * bf, tw_lp * lp)
Definition at line 24 of file save/num-file.c.
References DEBUG_LP, DOWNSTREAM, g_num_mod, g_num_nreport_days, get_tod(), rn_event_new(), and rn_event_send().
Referenced by num_event_handler().
{
#if NUM_VERIFY
if(lp->id == DEBUG_LP)
        printf("%ld T%d %s: FILE_STOP\n", lp->id, state->type, get_tod(tw_now(lp)));
#endif
        state->stats->s_nstop++;
        if(g_num_mod < 1)
                return;
        // send event down to TCP
        rn_event_send(rn_event_new(lp, 0.0, lp, DOWNSTREAM, 0));
}