ROSS.Net: num-timer.c File Reference
num-timer.c File Reference
#include <num.h>
Functions
void num_timer_cancel (tw_event *timer, tw_lp *lp)
tw_event * num_timer_start (tw_event *timer, tw_stime ts, tw_lp *lp)
Function Documentation
void num_timer_cancel (tw_event * timer, tw_lp * lp)
Definition at line 9 of file save/num-timer.c.
References rn_timer_cancel().
{
        if(timer->memory)
                tw_error(TW_LOC, "Membuf on timer!");
        rn_timer_cancel(lp, &timer);
}
tw_event* num_timer_start (tw_event * timer, tw_stime ts, tw_lp * lp)
Definition at line 18 of file save/num-timer.c.
References rn_timer_init(), and rn_timer_reset().
{
        ts += tw_now(lp);
        if(timer && timer->memory)
                tw_error(TW_LOC, "Membuf on timer!");
        if(timer && timer->state.b.abort)
                tw_error(TW_LOC, "Timer ABORT event!");
        if(!timer || timer == lp->cur_event)
                timer = rn_timer_init(lp, ts);
        else
                rn_timer_reset(lp, &timer, ts);
//DEBUG
        //if (timer == 0x1aec81d0)
        //      tw_error(TW_LOC, "Event 0x1aec81d0");
        return timer;
}