ROSS.Net: num-report.c File Reference
num-report.c File Reference
#include <num.h>
Functions
void num_print ()
void num_report_levels (int today)
Function Documentation
void num_print ()
Definition at line 33 of file save/num-report.c.
References g_num_day, g_num_level, g_num_log_f, g_num_max_users, g_num_mod, g_num_net_pop, g_num_nprofiles, g_num_profile_cnts, and NUM_LEVELS.
Referenced by num_final(), and num_report_levels().
{
        int             i,j;
        long int        total;
        long int        total_users = 0;
        int             delta_day;
        delta_day = (g_num_mod > 0)?g_num_mod:1;
        for (i = 0; i < g_num_nprofiles; i++)
        {
                total = 0;
                for (j=0; j < NUM_LEVELS; j++)
                        total += g_num_level[i][j];
                total_users += total;
                if(g_num_mod > g_num_day)
                        fprintf(g_num_log_f, "%d %d", g_num_day, i);
                else
                        fprintf(g_num_log_f, "%d %d", g_num_day-g_num_mod, i);
                for(j = 0; j < NUM_LEVELS; j++)
                {
                        if(total && g_num_mod > 0)
{
                                fprintf(g_num_log_f, " %4.4lf",
                                        100.0 *
                                                ((float) g_num_level[i][j] /
                                                (float) total));
                        } else if(g_num_mod == 0)
{
                                fprintf(g_num_log_f, " %4.4lf",
                                        100.0 *
                                                ((float) g_num_level[i][j] /
                                                (float) g_num_profile_cnts[j]));
                        } else
                                fprintf(g_num_log_f, " 0.0000");
                }
                if(g_num_mod > 0)
                        fprintf(g_num_log_f," %ld", total);
                else
                        fprintf(g_num_log_f," %d", g_num_profile_cnts[i]);
                for(j = 0; j < NUM_LEVELS; j++)
                        fprintf(g_num_log_f, " %d", g_num_level[i][j]);
                fprintf(g_num_log_f, " %d\n", g_num_net_pop[i]);
        }
        if(total_users > g_num_max_users)
                g_num_max_users = total_users;
        for (i = 0; i < g_num_nprofiles; i++)
        {
                for(j = 0; j < NUM_LEVELS; j++)
                        g_num_level[i][j] = 0;
                g_num_net_pop[i] = 0;
        }
}
void num_report_levels (int today)
Definition at line 106 of file save/num-report.c.
References g_num_day, g_num_log_f, g_num_mod, g_num_next_report_day, g_num_nreport_days, g_num_report_days, and num_print().
Referenced by num_final(), num_start(), and num_update().
{
        // same day, different agent
        if(today <= g_num_day)
                return;
        g_num_day = today;
        // log file off
        if(!g_num_log_f)
                return;
        // do not print until after first mod period has passed
        if(today < g_num_mod)
                return;
        // only print every g_num_mod days
        if((g_num_day+1) % g_num_mod == 0)
                num_print();
}