ROSS.Net: tcp-layer-util.c File Reference
tcp-layer-util.c File Reference
#include <tcp-layer.h>
Functions
void tcp_layer_util_event (tw_lp *lp, int type, int source, int dest, int seq_num, int ack, int size)
Function Documentation
void tcp_layer_util_event (tw_lp * lp, int type, int source, int dest, int seq_num, int ack, int size)
Definition at line 8 of file tcp-layer-util.c.
References DOWNSTREAM, rn_event_data(), rn_event_new(), rn_event_send(), and rn_message_data().
Referenced by tcp_layer_process_ack(), tcp_layer_process_data(), tcp_layer_startup(), and tcp_layer_timeout().
{
  rn_message  * r;
  tcp_layer_message * TWMsg;
  tw_event *CurEvent;
  // should put in the tcp_util_nexthop
  CurEvent = rn_event_new(tw_getlp(dest), 0.0, lp, DOWNSTREAM, size);
  r = rn_event_data(CurEvent);
  TWMsg = rn_message_data(r);
  //printf("%d: TCP sending event to lp %d ts = %f %f\n", CurEvent->src_lp->id,
  //       CurEvent->dest_lp->id, CurEvent->recv_ts, ts);
  TWMsg->MethodName = type;
  TWMsg->source = source;
  TWMsg->dest = dest;
  TWMsg->seq_num = seq_num;
  TWMsg->ack = ack;
  rn_event_send(CurEvent);
}