ROSS.Net: tcp-extern.h File Reference
tcp-extern.h File Reference
Functions
tw_event * tcp_timer_reset (tw_event *timer, tw_bf *bf, tcp_message *old, tw_stime ts, int sn, tw_lp *lp)
tw_event * tcp_rc_timer_reset (tw_event *, tw_bf *bf, tcp_message *old, tw_lp *lp)
void tcp_timer_cancel (tw_event *timer, tw_bf *bf, tcp_message *old, tw_lp *lp)
tw_event * tcp_rc_timer_cancel (tcp_message *old, tw_lp *lp)
void tcp_xml (tcp_state *, const xmlNodePtr node, tw_lp *)
void tcp_md_init (int argc, char **argv, char **env)
void tcp_md_final ()
void tcp_init (tcp_state *, tw_lp *)
void tcp_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_final (tcp_state *, tw_lp *)
void tcp_rc_event_handler (tcp_state *, tw_bf *, rn_message *, tw_lp *)
void tcp_process (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_cwnd (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_update_rtt (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_ack (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_process_data (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_rc_timeout (tcp_state *, tw_bf *, tcp_message *, tw_lp *)
void tcp_event_send (tcp_state *, tw_lpid, tw_stime, tw_lpid, int, int, int, tw_lp *)
Variables
tcp_state * g_state
tw_fd g_tcp_fd
tcp_statistics * g_tcp_stats
int g_tcp_mss
int g_tcp_rwd
FILE * g_tcp_f
Function Documentation
void tcp_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 118 of file tcp.c.
References DOWNSTREAM, g_tcp_fd, start_transfer(), stop_transfer(), tcp_process_ack(), tcp_process_data(), tcp_timeout(), and TIMER.
{
        tw_memory       *b;
        tcp_message     *in = NULL;
        *(int *) bf = 0;
        // if no membuf, then must be application layer
        if(NULL != (b = tw_event_memory_get(lp)))
                in = tw_memory_data(b);
        if(m->type == DOWNSTREAM)
        {
                if(m->size)
                        start_transfer(state, bf, m, lp);
                else
                        stop_transfer(state, bf, m, lp);
        } else if(m->type == TIMER)
        {
#ifdef TCP_DEBUG
                printf("%lld: RTO for %lld at %lf (%ld)\n",
                        lp->id, in->src, tw_now(lp), (long int) lp->pe->cur_event);
#endif
                tcp_timeout(state, bf, in, lp);
        } else if(state->connection != -1)
        {
#ifdef TCP_DEBUG
                printf("%lld: ACK from %lld at %lf \n", lp->id, in->src, tw_now(lp));
#endif
                tcp_process_ack(state, bf, in, lp);
        } else
        {
#ifdef TCP_DEBUG
                printf("%lld: DATA from %lld at %lf \n", lp->id, in->src, tw_now(lp));
#endif
                tcp_process_data(state, bf, in, lp);
        }
        if(b)
                tw_memory_free(lp, b, g_tcp_fd);
}
void tcp_event_send (tcp_state * , tw_lpid , tw_stime , tw_lpid , int , int , int , tw_lp *)
Definition at line 4 of file tcp-util.c.
References DOWNSTREAM, g_tcp_f, g_tcp_fd, rn_event_new(), rn_event_send(), and rn_message_setsize().
Referenced by start_transfer(), tcp_host_process_ack(), tcp_host_process_data(), tcp_host_timeout(), tcp_process_ack(), tcp_process_data(), and tcp_timeout().
{
        tw_event        *e;
        tw_memory       *b;
        //tw_stime       xfer;
        tcp_message     *m;
#if TCP_DEBUG
if(state->connection != -1)
{
        printf("\t\t%lld: SEND DATA at %lf (%d) to %lld \n",
                lp->id, tw_now(lp) + ts, seq_num, dst);
        if(lp->id == 504065)
        {
        fprintf(g_tcp_f, "0 %lf %d\n", tw_now(lp) + ts, seq_num % 60000);
        fprintf(g_tcp_f, "2 %lf %lf\n", tw_now(lp) + ts, state->cwnd * state->mss);
        fprintf(g_tcp_f, "3 %lf %d\n", tw_now(lp) + ts, state->recv_wnd* state->mss);
        fprintf(g_tcp_f, "4 %lf %lf\n", tw_now(lp) + ts, state->ssthresh * state->mss);
        }
} else
{
        printf("\t\t%lld: SEND ACK at %lf (%d) to %lld \n",
                lp->id, tw_now(lp) + ts, ack, dst);
        if(lp->id == 119654)
        {
        fprintf(g_tcp_f, "1 %lf %d\n", tw_now(lp) + ts, ack % 60000);
        }
}
#endif
        e = rn_event_new(dst, ts, lp, DOWNSTREAM, 0);
        b = tw_memory_alloc(lp, g_tcp_fd);
        m = tw_memory_data(b);
        m->src = src;
        //m->dst = dst;
        m->ack = ack;
        m->seq_num = seq_num;
        tw_event_memory_set(e, b, g_tcp_fd);
        rn_message_setsize(tw_event_data(e), 8.0 * size);
        rn_event_send(e);
}
void tcp_final (tcp_state * , tw_lp *)
Definition at line 208 of file tcp.c.
References g_rn_logs_dir, g_tcp_stats, and rn_getmachine().
{
#ifdef TCP_LOG
        char    log[255];
        if(state->log && state->log != stdout)
                fclose(state->log);
        if(state->connection > -1)
                sprintf(log, "%s/tcp-host-%ld.log", g_rn_logs_dir, lp->id);
        else
                sprintf(log, "%s/tcp-server-%ld.log", g_rn_logs_dir, lp->id);
        state->log = fopen(log, "w");
        if(!state->log)
                return;
        if(state->connection > -1)
        {
                fprintf(state->log, "TCP Svr %ld: Conn Duration: %lf-%lf \n\n",
                        lp->id, state->stats->start_time, state->stats->final_time);
                g_tcp_stats->throughput +=
                        (((state->len * 8.0)/
                                (tw_now(lp) - state->stats->start_time)) / 1024);
                fprintf(state->log, "\t%-50s %11d\n", "Server", rn_getmachine(lp)->link[0].addr);
                fprintf(state->log, "\t%-50s %11d Bytes\n", "Length", state->len);
                fprintf(state->log, "\t%-50s %11.4lf Kbps\n", "Throughput",
                           (((state->len * 8) /
                                 (tw_now(lp) - state->stats->start_time)) / 1024));
                fprintf(state->log, "\t%-50s %11d\n", "Timeouts", state->stats->tout);
                fprintf(state->log, "\t%-50s %11.4lf\n", "Cwnd", state->cwnd);
                fprintf(state->log, "\n");
        } else
        {
                fprintf(state->log, "TCP Clt %ld: Conn Duration: %lf-%lf \n\n",
                        lp->id, state->stats->start_time, state->stats->final_time);
        }
        fprintf(state->log, "\t%-50s %11d\n", "Sent Pkts", state->stats->sent);
        fprintf(state->log, "\t%-50s %11d\n", "Recv Pkts", state->stats->recv);
        fprintf(state->log, "\t%-50s %11d\n", "Drop Pkts", state->stats->dropped_packets);
        fprintf(state->log, "\t%-50s %11d\n", "Bad Pkts", state->stats->bad_msgs);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11d\n", "ACK Sent", state->stats->ack_sent);
        fprintf(state->log, "\t%-50s %11d\n", "ACK Recv", state->stats->ack_recv);
        fprintf(state->log, "\t%-50s %11d\n", "ACK Invalid", state->stats->ack_invalid);
#endif
        g_tcp_stats->sent += state->stats->sent;
        g_tcp_stats->recv += state->stats->recv;
        g_tcp_stats->tout += state->stats->tout;
        g_tcp_stats->ack_sent += state->stats->ack_sent;
        g_tcp_stats->ack_recv += state->stats->ack_recv;
        g_tcp_stats->ack_invalid += state->stats->ack_invalid;
        g_tcp_stats->bad_msgs += state->stats->bad_msgs;
        g_tcp_stats->dropped_packets += state->stats->dropped_packets;
        if(0 && lp->id % 100000 == 0)
                printf("Finalizing TCP LP %lld \n", lp->gid);
}
void tcp_init (tcp_state * , tw_lp *)
Definition at line 80 of file tcp.c.
References g_state, g_tcp_mss, g_tcp_rwd, rn_getmachine(), start_transfer(), and TCP_SND_WND.
{
        state->cwnd = 1;
        state->ssthresh = TCP_SND_WND;
        state->rto = 3.0;
        //state->host = rn_getmachine(lp->id);
        if(rn_getmachine(lp->id)->conn > lp->id)
                state->connection = rn_getmachine(lp->id)->conn;
        else
                state->connection = -1;
        state->stats = tw_calloc(TW_LOC, "", sizeof(tcp_statistics), 1);
        state->mss = g_tcp_mss;
        state->recv_wnd = g_tcp_rwd;
        // faking out that this is not in transfer
        state->len = 1;
        state->unack = 0;
        g_state = state;
#ifdef TCP_LOG
        state->log = stdout;
#endif
        //if(-1 != state->connection)
        if(lp->id == 0)
        {
                rn_message m;
                m.size = 40960;
                start_transfer(state, NULL, &m, lp);
        }
}
void tcp_md_final ()
Definition at line 27 of file tcp-model.c.
References g_tcp_f, and g_tcp_stats.
{
        fclose(g_tcp_f);
        printf("\nTCP Model Statistics: \n\n");
        printf("\t%-50s %11d\n", "Sent Packets", g_tcp_stats->sent);
        printf("\t%-50s %11d\n", "Recv Packets", g_tcp_stats->recv);
        printf("\t%-50s %11d\n", "Sent ACKs", g_tcp_stats->ack_sent);
        printf("\t%-50s %11d\n", "Recv ACKs", g_tcp_stats->ack_recv);
        printf("\t%-50s %11d\n", "Invalid ACKs", g_tcp_stats->ack_invalid);
        printf("\t%-50s %11d\n", "TimeOut Packets", g_tcp_stats->tout);
        printf("\t%-50s %11d\n", "Drop Packets", g_tcp_stats->dropped_packets);
        //printf("\t%-50s %11.4lf\n", "Throughput", g_tcp_stats->throughput);
}
void tcp_md_init (int argc, char ** argv, char ** env)
Definition at line 4 of file tcp-model.c.
References g_tcp_f, g_tcp_fd, and g_tcp_stats.
{
        int      i;
        g_tcp_stats = tw_calloc(TW_LOC, "", sizeof(*g_tcp_stats), 1);
        g_tcp_f = fopen("tcp.data", "w");
        if(!g_tcp_f)
                tw_error(TW_LOC, "Unable to open TCP validation file!");
        for(i = 0; i < g_tw_nkp; i++)
                g_tcp_fd = tw_kp_memory_init(tw_getkp(i), 1000000 / g_tw_nkp,
                                        sizeof(tcp_message), 1);
        if(tw_ismaster())
        {
                printf("\nInitializing Model: TCP Tahoe\n");
                printf("\t%-50s %11d (%ld)\n",
                        "TCP Membufs", 1000000, g_tcp_fd);
        }
}
void tcp_process (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
void tcp_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-process.c.
References rn_event_new(), rn_event_send(), tcp_event_send(), TCP_MTU, tcp_timer_reset(), tcp_update_cwnd(), tcp_update_rtt(), and UPSTREAM.
Referenced by tcp_event_handler().
{
        int              ack;
        if(state->unack == 0 && in->ack > 0)
                return;
        if ((bf->c2 = (state->unack <= in->ack)))
        {
#if TCP_DEBUG
//if(lp->id == 9377)
                printf("\t%lld: ACK: unack %d ack %d sn %d (%lf)\n",
                        lp->id, state->unack, in->ack , in->seq_num, tw_now(lp));
#endif
                state->stats->ack_recv++;
                // printf(" should work %d %d %d\n",in->ack , in->seq_num, lp->id);
                if ((bf->c9 = (in->ack >= state->seq_num)))
                {       // CHANGE
                        //in->RC.seq_num = state->seq_num;
                        // printf("new seq %d \n",state->seq_num);
                        state->seq_num = in->ack + state->mss;
                }
                //in->RC.dup_count = state->dup_count;
                state->dup_count = 0;
                ack = state->unack;
                state->unack = in->ack + state->mss;
                tcp_update_cwnd(state, bf, in, lp);
                tcp_update_rtt(state, bf, in, lp);
                /*
                 * Prints the time it took to transfer, the rate and congestion
                 * window size
                 */
                if(state->len && state->unack >= state->len)
                {
#if 0
                        double   rate = ((state->len) /
                                         (tw_now(lp) - state->stats->start_time)) /
                                          1024;
                        fprintf(stdout, "\t%-50s %11.4lf KB\n", "Xfer",
                                        state->len / 1024.0);
                        fprintf(stdout, "\t%-50s %11.4lf secs\n", "Time",
                                        tw_now(lp) - state->stats->start_time);
                        fprintf(stdout, "\t%-50s %11.4lf Kbps\n", "Rate", rate);
                        fprintf(stdout, "\t%-50s %11.4lf \n", "Cwnd", state->cwnd);
                        fprintf(stdout, "\t%-50s %11d %11d \n", "ACK", state->unack, state->len);
                        fprintf(stdout, "\t%-50s %11.4lf \n", "Now", tw_now(lp));
#endif
                        //state->len = 0;
#if TCP_DEBUG
        printf("\t%lld: file complete (unack %d, len %d)\n", lp->id, state->unack, state->len);
#endif
                        // send event up to app with throughput rate
                        rn_event_send(rn_event_new(lp->gid, 0.0, lp, UPSTREAM, state->len));
                }
                in->seq_num = 0;
                //in->RC.lastsent = state->lastsent;
                while (state->seq_num < state->len &&
                           (state->seq_num + state->mss) <=
                           (state->unack + (min(state->cwnd, state->recv_wnd) * state->mss)))
                {
                        in->seq_num++;
                        tcp_event_send(state, lp->id, 0.0, state->connection, TCP_MTU,
                                        state->seq_num, 0, lp);
                        state->stats->sent++;
                        state->seq_num += state->mss;
                        printf(" %d + %d <= %d + min(%lf, %d) * %d\n",
                                state->seq_num, state->mss, state->unack, state->cwnd, state->recv_wnd, state->mss);
                }
                in->ack = ack;
        } else
        {
                state->stats->ack_invalid++;
#if TCP_DEBUG
//if(lp->id == 9377)
                printf("\t%lld: Invalid ACK: unack %d ack %d at %lf\n", lp->id, state->unack, in->ack, tw_now(lp));
#endif
                if ((bf->c3 = ((state->unack) == in->ack)))
                {
                        state->dup_count += 1;
                        if ((bf->c4 = (state->dup_count == 4)))
{
                                //in->dst = state->ssthresh;
                                state->ssthresh =
                                        (min(((int)state->cwnd + 1), state->recv_wnd) / 2) *
                                        state->mss;
                                // CHANGED
                                //in->RC.cwnd = state->cwnd;
                                state->cwnd = 1;
                                //in->RC.lastsent = state->lastsent;
                                tcp_event_send(state, lp->id, 0.0, state->connection, TCP_MTU,
                                                state->unack, 0, lp);
                                in->ack = state->seq_num;
                                state->seq_num = state->unack + state->mss;
                                // CHANGE Maybe.
                                state->rto_seq++;
                                state->timer = tcp_timer_reset(state->timer, bf, in,
                                                tw_now(lp) + state->rto, state->unack, lp);
                                // state-save variables into event
                                //in->RC.seq_num = state->rtt_seq;
                                state->rtt_seq = state->unack;
                                //in->RC.rtt_time = state->rtt_time;
                                state->rtt_time = 0;
                        }
                }
        }
}
void tcp_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 140 of file tcp-process.c.
References g_tcp_rwd, TCP_DEBUG, tcp_event_send(), TCP_HEADER_SIZE, and TCP_SND_WND.
Referenced by tcp_event_handler().
{
#if TCP_DEBUG
//if(lp->id == 42380)
        printf("\t%lld: DATA: in sn %d, st sn %d \n", lp->id, in->seq_num, state->seq_num);
#endif
        state->stats->recv++;
        state->stats->ack_sent++;
        // server sending new file..
        if(in->seq_num == 0)
        {
                int     i;
                state->seq_num = 0;
                state->recv_wnd = g_tcp_rwd;
                for(i = 0; i < g_tcp_rwd; i++)
                        state->out_of_order[i] = 0;
#if TCP_DEBUG
                printf("\t%lld: Client starting new file receive!\n", lp->id);
#endif
        }
        if ((bf->c2 = (in->seq_num == state->seq_num)))
        {
                //in->RC.dup_count = 0;
                state->seq_num += state->mss;
                while(state->out_of_order[(state->seq_num / (int)state->mss) %
                                state->recv_wnd])
                {
                        //in->RC.dup_count++;
                        state->out_of_order[(state->seq_num / (int)state->mss) %
                                                                state->recv_wnd] = 0;
                        state->seq_num += state->mss;
                }
        } else if ((bf->c3 = (in->seq_num > state->seq_num)))
        {
                if ((bf->c4 = (in->seq_num >
                                (state->seq_num + state->recv_wnd * state->mss
                                        /* TCP_SND_WND */  - state->mss))))
                {
                        // look up need rc code CHANGE
                        tw_printf(TW_LOC,"recv_wnd buffer overflow %d %d\n",
                                         in->seq_num,
                                 state->seq_num + TCP_SND_WND - state->mss);
                        //tw_error(TW_LOC, "recv_wnd buffer overflow %d %d\n",
                        //               in->seq_num,
                        //       state->seq_num + TCP_SND_WND - state->mss);
                } else
                {
#if TCP_DEBUG
//if(lp->id == 42380)
                        printf("\tin sn %d, sn %d, window %d, loc %d\n",
                                in->seq_num, state->seq_num,
                                (state->seq_num + TCP_SND_WND - state->mss),
                                (in->seq_num / state->mss) % state->recv_wnd);
#endif
                        state->out_of_order[(in->seq_num / state->mss) %
                                                state->recv_wnd] = 1;
                }
        }
        //in->RC.lastsent = state->lastsent;
        tcp_event_send(state, lp->id, 0.0, in->src, TCP_HEADER_SIZE,
                        0, state->seq_num - state->mss, lp);
}
void tcp_rc_event_handler (tcp_state * , tw_bf * , rn_message * , tw_lp *)
Definition at line 165 of file tcp.c.
References g_tcp_fd, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), and TIMER.
{
#if 0
        tw_memory       *b;
        tcp_message     *in;
        if(NULL == (b = tw_memory_free_rc(lp, g_tcp_fd)))
                tw_error(TW_LOC, "No membuf on event!");
        in = tw_memory_data(b);
        if(m->type == TIMER)
        {
#ifdef TCP_DEBUG
                printf("%ld: RC RTO for %d at %lf (%ld)\n",
                        lp->id, in->src, tw_now(lp), (long int) lp->cur_event);
#endif
                tcp_rc_timeout(state, bf, in, lp);
        } else if(state->connection == -1)
        {
#ifdef TCP_DEBUG
                printf("%ld: RC ACK from %d at %lf \n",
                        lp->id, in->src, tw_now(lp));
#endif
                tcp_rc_process_ack(state, bf, in, lp);
        } else
        {
#ifdef TCP_DEBUG
                printf("%ld: RC DATA from %d at %lf \n",
                        lp->id, in->src, tw_now(lp));
#endif
                tcp_rc_process_data(state, bf, in, lp);
        }
        if(b)
                tw_event_memory_set(lp->cur_event, b, g_tcp_fd);
#endif
}
void tcp_rc_process_ack (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-process.c.
References tcp_rc_timer_cancel(), and tcp_rc_timer_reset().
Referenced by tcp_rc_event_handler().
{
        int             i;
        int             ack;
        if (bf->c2)
        {
                state->stats->ack_recv--;
                for (i = 0; i < in->seq_num; i++)
                {
                        // tw_rand_reverse_unif(lp->id);
                        state->seq_num -= state->mss;
                        state->stats->sent--;
                }
                state->lastsent = in->RC.lastsent;
                // reverse tcp_update_rtt
                if (bf->c5 || bf->c7)
                {
                        state->rtt_seq = in->RC.rtt_seq;
                        // in->RC.rtt_seq = state->rtt_seq;
                        // state->rtt_seq = in->ack; // wrong CHANGE
                        state->rtt_time = in->RC.rtt_time;
                        if (bf->c6 && bf->c5)
                                state->rto = in->dst;
                        state->rto_seq--;
                        state->timer = tcp_rc_timer_reset(state->timer, bf, in, lp);
                }
                // Reverse tcp_update_cwnd
                if (bf->c3 || bf->c4)
                        state->cwnd = in->RC.cwnd;
                if(bf->c15)
                        state->timer = tcp_rc_timer_cancel(in, lp);
                ack = state->unack;
                state->unack = in->ack;
                in->ack = ack - state->mss;
                state->dup_count = in->RC.dup_count;
                if (bf->c9)
                        state->seq_num = in->RC.seq_num;
        } else
        {
#if TCP_DEBUG
                printf("\t%ld: INVALID ACK: %d \n", lp->id, in->ack);
#endif
                state->stats->ack_invalid--;
                if (bf->c3)
                {
                        state->dup_count -= 1;
                        if (bf->c4)
{
                                state->rtt_time = in->RC.rtt_time;
                                state->rtt_seq = in->RC.seq_num;        // state->unack; //big CHANGE
                                // state->tout--;
                                // state->sent--;
                                state->rto_seq--;
                                state->seq_num = in->ack;
                                in->ack = state->unack - state->mss;
                                state->lastsent = in->RC.lastsent;
                                state->cwnd = in->RC.cwnd;
                                state->ssthresh = in->dst;
                                state->timer = tcp_rc_timer_reset(state->timer, bf, in, lp);
                        }
                }
        }
}
void tcp_rc_process_data (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 94 of file tcp-rc-process.c.
Referenced by tcp_rc_event_handler().
{
        // printf("%f \n", in->RC.lastsent);
        state->stats->ack_sent--;
        state->stats->recv--;
        state->lastsent = in->RC.lastsent;
        if (bf->c2)
        {
                // tw_rand_reverse_unif(lp->id);
                state->seq_num -= state->mss;
                while (in->RC.dup_count)
                {
                        state->out_of_order[(state->seq_num / (int)state->mss) %
                                                                state->recv_wnd] = 1;
                        state->seq_num -= state->mss;
                        in->RC.dup_count--;
                }
        } else
        {
                if (bf->c3)
                {
                        if (bf->c4)
{
                                // need to think about this one WILL NOT WORK
                                // UNTIL YOU FIX!!!!!
                                tw_error(TW_LOC, "broken here");
                        } else
                                state->out_of_order[(in->seq_num / state->mss) %
                                                        state->recv_wnd] = 0;
                }
        }
}
void tcp_rc_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-rc-timeout.c.
References tcp_rc_timer_reset().
Referenced by tcp_rc_event_handler().
{
        int             ssthresh = in->dst;
        int             seq_num = in->ack;
        if(bf->c1 == 0)
                return;
        state->rtt_time = in->RC.rtt_time;
        state->rtt_seq = in->RC.rtt_seq;
        state->rto_seq--;
        state->rto = in->RC.dup_count;
        state->stats->tout--;
        state->seq_num = seq_num;
        state->lastsent = in->RC.lastsent;
        state->cwnd = in->RC.cwnd;
        state->ssthresh = ssthresh;
        state->timer = tcp_rc_timer_reset(state->timer, bf, in, lp);
}
tw_event* tcp_rc_timer_cancel (tcp_message * old, tw_lp * lp)
Definition at line 134 of file tcp-timer.c.
References g_tcp_fd.
Referenced by tcp_rc_process_ack().
{
        tw_event * timer = NULL;
        //if(!old->RC.timer_ts)
                tw_error(TW_LOC, "No prev timer ts!");
        if(!timer)
                tw_error(TW_LOC, "Why cannot I create this timer now?");
        //timer = rn_timer_init(lp, old->RC.timer_ts);
        timer->memory = tw_memory_free_rc(lp, g_tcp_fd);
        // more debug
        if(timer->memory)
        {
                tcp_message *m = tw_memory_data(timer->memory);
                if(m->src != old->src)
                        tw_error(TW_LOC, "bad membuf!");
        } else
                tw_error(TW_LOC, "Could not unfree membuf!");
        return timer;
}
tw_event* tcp_rc_timer_reset (tw_event * , tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 60 of file tcp-timer.c.
References g_tcp_fd, and rn_timer_cancel().
Referenced by tcp_rc_process_ack(), and tcp_rc_timeout().
{
        if(bf->c14)
        {
                // If I init'd a timer, cancel it.
                if(timer)
                {
                        tw_memory_alloc_rc(lp, timer->memory, g_tcp_fd);
                        timer->memory = NULL;
#if TCP_DEBUG
                        printf("\t%lld: cancel timer at %lf (%ld)\n",
                                lp->id, timer->recv_ts, (long int) timer);
#endif
                        rn_timer_cancel(lp, &timer);
                }
                // restore pointer to previous timer
                //timer = old->RC.timer;
                //old->RC.timer = NULL;
        } else
        {
                //rn_timer_reset(lp, &timer, old->RC.timer_ts);
        }
        if(bf->c13 == 0)
                return timer;
        if(timer)
        {
                tcp_message     *m;
#if TCP_DEBUG
                printf("\t%lld: new RTO at %lf (%ld)\n",
                        lp->id, tw_now(lp), (long int) timer);
#endif
                if(NULL == timer->memory)
                        timer->memory = tw_memory_alloc(lp, g_tcp_fd);
                m = tw_memory_data(timer->memory);
                //m->seq_num = old->RC.timer_seq;
                m->src = old->src;
        }
        if(timer && !timer->memory)
                tw_error(TW_LOC, "no membuf here!");
        return timer;
}
void tcp_timeout (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 4 of file tcp-timeout.c.
References rn_event_new(), rn_event_send(), tcp_event_send(), TCP_MTU, tcp_timer_reset(), and UPSTREAM.
Referenced by tcp_event_handler().
{
        if(in->seq_num < state->unack || state->unack >= state->len)
                return;
        bf->c1 = 1;
#if TCP_DEBUG
//if(lp->id == 9377)
        printf("\n\t%lld: timeout %lf\n", lp->id, tw_now(lp));
#endif
        //in->dst = state->ssthresh;
        state->ssthresh = (min(((int)state->cwnd + 1), state->recv_wnd) / 2) * state->mss;
        //in->RC.cwnd = state->cwnd;
        state->cwnd = 1;
        //in->RC.lastsent = state->lastsent;
        tcp_event_send(state, lp->id, 0.0, state->connection, TCP_MTU, state->unack, 0, lp);
        in->ack = state->seq_num;
        //state->seq_num = state->unack + state->mss;
        state->stats->tout++;
        state->stats->sent++;
        //in->RC.dup_count = state->rto;
        state->rto = state->rto * 2;
        state->rto_seq++;
        if(state->rto < 60.0)
        {
#if TCP_DEBUG
//if(lp->id == 9377)
        printf("\t%lld: timeout reset to %lf (was %lf) (unack %d)\n\n", lp->id, tw_now(lp) + state->rto, state->timer->recv_ts, state->unack);
#endif
                state->timer = tcp_timer_reset(state->timer, bf, in,
                                        tw_now(lp) + state->rto, state->unack, lp);
        } else
        {
#if TCP_DEBUG
//if(lp->id == 9377)
        printf("\t%lld: timeout cancelled (was %lf) (unack %d)\n\n", lp->id, state->timer->recv_ts, state->unack);
                state->timer = NULL;
#endif
                rn_event_send(rn_event_new(lp->gid, 0.0, lp, UPSTREAM, 0));
        }
        // state-save into event
        //in->RC.rtt_seq = state->rtt_seq;
        state->rtt_seq = state->unack;
        //in->RC.rtt_time = state->rtt_time;
        state->rtt_time = 0;
}
void tcp_timer_cancel (tw_event * timer, tw_bf * bf, tcp_message * old, tw_lp * lp)
Definition at line 113 of file tcp-timer.c.
References g_tcp_fd, and rn_timer_cancel().
Referenced by tcp_update_rtt().
{
        //old->RC.timer_ts = timer->recv_ts;
//      if(timer->recv_ts <= tw_now(lp) || timer->state.uint == 0)
        if(!timer || timer == lp->pe->cur_event)
                return;
        if(!timer->memory)
                tw_error(TW_LOC, "No membuf on timer!");
        tw_memory_free(lp, timer->memory, g_tcp_fd);
        timer->memory = NULL;
        rn_timer_cancel(lp, &timer);
#if TCP_DEBUG && 0
        printf("\t%ld: cancel RTO for %lf\n", lp->id, old->RC.timer_ts);
#endif
}
tw_event* tcp_timer_reset (tw_event * timer, tw_bf * bf, tcp_message * old, tw_stime ts, int sn, tw_lp * lp)
Definition at line 7 of file tcp-timer.c.
References g_tcp_fd, rn_timer_init(), and rn_timer_reset().
Referenced by tcp_process_ack(), tcp_timeout(), and tcp_update_rtt().
{
        tcp_message     *m;
        if(timer && timer->recv_ts == ts)
        {
                tw_printf(TW_LOC, "%ld: attempt to reset timer to cur ts!", lp->id);
                m = tw_memory_data(timer->memory);
                m->src = old->src;
                m->seq_num = sn;
                return timer;
        }
        // if this IS the timer firing, then do create new timer!
        if((bf->c14 = (!timer || timer == lp->pe->cur_event)))
        {
                //old->RC.timer = timer;
                timer = NULL;
                timer = rn_timer_init(lp, ts);
        } else
        {
                //old->RC.timer_ts = timer->recv_ts;
                rn_timer_reset(lp, &timer, ts);
        }
        if((bf->c13 = (timer != NULL)))
        {
                if(!timer->memory)
                        timer->memory = tw_memory_alloc(lp, g_tcp_fd);
#if TCP_DEBUG
                printf("\t%lld: reset RTO to %lf (%ld)\n", lp->id, ts, (long int)timer);
#endif
                m = tw_memory_data(timer->memory);
                // do I need this?
                //old->RC.timer_seq = m->seq_num;
                m->src = old->src;
                m->seq_num = sn;
        }
        if(timer && !timer->memory)
                tw_error(TW_LOC, "no membuf here!");
        return timer;
}
void tcp_update_cwnd (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 7 of file tcp-update.c.
References TCP_SND_WND.
Referenced by tcp_host_process_ack(), and tcp_process_ack().
{
        if((bf->c3 = ((state->cwnd * state->mss) < state->ssthresh
                  && state->cwnd * state->mss < TCP_SND_WND)))
        {
                //in->RC.cwnd = state->cwnd;
                state->cwnd += 1;
        } else if((bf->c4 = (state->cwnd * state->mss < TCP_SND_WND)))
        {
                //in->RC.cwnd = state->cwnd;
                state->cwnd += 1 / state->cwnd;
        }
}
void tcp_update_rtt (tcp_state * , tw_bf * , tcp_message * , tw_lp *)
Definition at line 25 of file tcp-update.c.
References tcp_timer_cancel(), and tcp_timer_reset().
Referenced by tcp_host_process_ack(), and tcp_process_ack().
{
        tw_stime ts;
        if ((bf->c5 = (in->ack == state->rtt_seq && state->unack < state->len)))
        {
                if ((bf->c6 = (state->rtt_time != 0)))
                {
                        //in->dst = state->rto;
                        state->rto = .875 * state->rto +
                                (10 * (tw_now(lp) - state->rtt_time)) * .125;
                        state->rto = min(1.0, state->rto);
                }
                //in->RC.rtt_seq = state->rtt_seq;
                //in->RC.rtt_time = state->rtt_time;
                state->rtt_time = tw_now(lp);
                state->rtt_seq = state->seq_num;
                state->rto_seq++;
        } else if((bf->c7 = (in->ack > state->rtt_seq && state->unack < state->len)))
        {
                //in->RC.rtt_seq = state->rtt_seq;
                //in->RC.rtt_time = state->rtt_time;
                state->rtt_time = tw_now(lp);
                state->rtt_seq = state->seq_num;
                state->rto_seq++;
        } else if(state->unack >= state->len)
        {
                if(!state->timer)
                        return;
                bf->c15 = 1;
                //state->stats->final_time = tw_now(lp);
                tcp_timer_cancel(state->timer, bf, in, lp);
                state->timer = NULL;
                return;
        }
        if(state->timer && state->timer->recv_ts > tw_now(lp))
                ts = state->timer->recv_ts;
        else
                ts = -1.0;
        state->timer = tcp_timer_reset(state->timer, bf, in,
                                        tw_now(lp) + state->rto, state->unack, lp);
#ifdef TCP_DEBUG
//if(lp->id == 9377)
        printf("\t%lld: update RTT tmr to %lf (was %lf) (unack %d)\n", lp->id, tw_now(lp) + state->rto, ts, state->unack);
#endif
}
void tcp_xml (tcp_state * , const xmlNodePtr node, tw_lp *)
Definition at line 4 of file tcp-xml.c.
References g_tcp_mss, and g_tcp_rwd.
{
        xmlNodePtr       e;
        for(e = node->children; e; e = e->next)
        {
                if(0 == strcmp((char *) e->name, "mss"))
                        state->mss = atoi((char *)e->children->content);
                if(0 == strcmp((char *) e->name, "recv_wnd"))
                        state->recv_wnd = atoi((char *)e->children->content);
        }
        if(!state->mss)
                state->mss = g_tcp_mss;
        if(!state->recv_wnd)
                state->recv_wnd = g_tcp_rwd;
}
Variable Documentation
tcp_state* g_state
Definition at line 3 of file tcp-global.c.
Referenced by tcp_init().
FILE* g_tcp_f
Definition at line 12 of file tcp-global.c.
Referenced by tcp_event_send(), tcp_md_final(), and tcp_md_init().
tw_fd g_tcp_fd
Definition at line 9 of file tcp-global.c.
Referenced by start_transfer(), stop_transfer(), tcp_event_handler(), tcp_event_send(), tcp_host_process_ack(), tcp_host_timeout(), tcp_host_update_rtt(), tcp_md_init(), tcp_rc_event_handler(), tcp_rc_timer_cancel(), tcp_rc_timer_reset(), tcp_timer_cancel(), and tcp_timer_reset().
int g_tcp_mss
Definition at line 5 of file tcp-global.c.
Referenced by tcp_init(), and tcp_xml().
int g_tcp_rwd
Definition at line 7 of file tcp-global.c.
Referenced by tcp_init(), tcp_process_data(), and tcp_xml().
tcp_statistics* g_tcp_stats
Definition at line 10 of file tcp-global.c.
Referenced by tcp_final(), tcp_md_final(), and tcp_md_init().