ROSS.Net: tcp-layer-extern.h File Reference
tcp-layer-extern.h File Reference
Functions
void tcp_layer_xml (tw_lp *lp, xmlNodePtr node)
void tcp_layer_init (tcp_layer_state *SV, xmlNodePtr node, tw_lp *lp)
void tcp_layer_event_handler (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_final (tcp_layer_state *SV, tw_lp *lp)
void tcp_layer_rc_event_handler (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_process_ack (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_process_data (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_update_cwnd (tcp_layer_state *SV, tw_bf *CV, tcp_layer_message *M, tw_lp *lp)
void tcp_layer_update_rtt (tcp_layer_state *SV, tw_bf *CV, tcp_layer_message *M, tw_lp *lp)
void tcp_layer_timeout (tcp_layer_state *SV, tw_bf *CV, tcp_layer_message *M, tw_lp *lp)
void tcp_layer_process_ack_rc (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_process_data_rc (tcp_layer_state *SV, tw_bf *CV, rn_message *M, tw_lp *lp)
void tcp_layer_timeout_rc (tcp_layer_state *SV, tw_bf *CV, tcp_layer_message *M, tw_lp *lp)
void tcp_layer_util_event (tw_lp *lp, int type, int source, int dest, int seq_num, int ack, int size)
Variables
tcp_layer_statistics g_tcp_layer_stats
int g_tcp_layer_iss
int g_tcp_layer_mss
int g_tcp_layer_recv_wnd
Function Documentation
void tcp_layer_event_handler (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 73 of file tcp-layer.c.
References FORWARD, rn_message_data(), RTO, STARTUP, tcp_layer_process_ack(), tcp_layer_process_data(), tcp_layer_startup(), and tcp_layer_timeout().
{
  tcp_layer_message    *msg;
  msg = rn_message_data(M);
  CV = &(msg->CV);
  *(int *)CV = (int)0;
  switch (msg->MethodName)
    {
    case FORWARD:
      switch (SV->connection)
        {
        case -1:
          tcp_layer_process_data(SV, CV, M, lp);
          break;
        default:
          tcp_layer_process_ack(SV, CV, M, lp);
          break;
        }
      break;
    case RTO:
      tcp_layer_timeout(SV, CV, msg, lp);
      break;
    case STARTUP:
      tcp_layer_startup(SV, CV, M, lp);
      break;
    default:
      tw_error(TW_LOC,
               "APP_ERROR(%ld): Invalid MethodName(%d):Time (%f)\n",
               lp->id, msg->MethodName, tw_now(lp));
    }
}
void tcp_layer_final (tcp_layer_state * SV, tw_lp * lp)
Definition at line 148 of file tcp-layer.c.
References g_tcp_layer_stats.
{
  printf("%ld: TCP bad messages received = %d \n", lp->id, SV->bad_msgs);
  g_tcp_layer_stats.sent_packets += SV->sent_packets;
  g_tcp_layer_stats.received_packets += SV->received_packets;
  g_tcp_layer_stats.timedout_packets += SV->timedout_packets;
  if (SV->connection > -1){
    g_tcp_layer_stats.throughput += ((SV->unack / (tw_now(lp) - SV->start_time)) / 1000);
    printf("\nThroughput %f Kbps, Sent Packets %d, Timeouts %d, Cwnd %f\n",
           (((SV->unack *(double) 8)/ (tw_now(lp) - SV->start_time)) / 1000) ,
           SV->sent_packets, SV->timedout_packets, SV->cwnd);
  }
}
void tcp_layer_init (tcp_layer_state * SV, xmlNodePtr node, tw_lp * lp)
Definition at line 11 of file tcp-layer.c.
References rn_getmachine(), rn_message_data(), rn_timer_init(), STARTUP, and TCP_LAYER_SND_WND.
{
  SV->bad_msgs = 0;
  SV->cwnd = 1;
  SV->ssthresh = TCP_LAYER_SND_WND;
  SV->rto = 3;
  SV->host = rn_getmachine(lp->id);
  SV->connection = SV->host->conn;
  if(SV->connection > -1)
    {
      SV->timer = rn_timer_init(lp, 1);
      if(SV->timer)
        {
          rn_message *msg;
          tcp_layer_message *M;
          msg = tw_event_data(SV->timer);
          M = rn_message_data(msg);
          M->MethodName = STARTUP;
          printf("%d %d \n",STARTUP, M->MethodName);
        }
    }
}
void tcp_layer_process_ack (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 8 of file tcp-layer-process.c.
References FORWARD, g_tcp_layer_mss, g_tcp_layer_recv_wnd, rn_message_data(), rn_timer_reset(), TCP_LAYER_TRANSFER_SIZE, tcp_layer_update_cwnd(), tcp_layer_update_rtt(), and tcp_layer_util_event().
Referenced by tcp_layer_event_handler().
{
  int             ack;
  tw_stime        ts;
  tcp_layer_message    *M;
  ts = 0.0;
  M = rn_message_data(msg);
  if ((CV->c2 = (SV->unack <= M->ack)))
    {
        if ((CV->c9 = (M->ack >= SV->seq_num)))
        {                                               // CHANGE
          M->RC.seq_num = SV->seq_num;
          SV->seq_num = M->ack + g_tcp_layer_mss;
        }
      M->RC.dup_count = SV->dup_count;
      SV->dup_count = 0;
      ack = SV->unack;
      SV->unack = M->ack + g_tcp_layer_mss;
      tcp_layer_update_cwnd(SV, CV, M, lp);
      /*
       * Prints the time it took to transfer, the rate and congestion
       * window size
       */
      if (SV->unack >= SV->len)
        {
          printf("\n\t\tTransfer Time = %f at %f kbps \n\t\tCWND = %f lp = %ld\n\n",
             (tw_now(lp) - SV->start_time) ,
             ((SV->len) / (tw_now(lp) - SV->start_time))/ 1000,
             SV->cwnd, lp->id);
        }
      tcp_layer_update_rtt(SV, CV, M, lp);
      M->seq_num = 0;
      while (SV->seq_num < SV->len &&
             (SV->seq_num + g_tcp_layer_mss) <=
             (SV->unack + min(SV->cwnd, g_tcp_layer_recv_wnd) * g_tcp_layer_mss))
        {
          M->seq_num++;
          tcp_layer_util_event(lp, FORWARD, lp->id, M->source, SV->seq_num, 0,
                               TCP_LAYER_TRANSFER_SIZE);
          SV->sent_packets++;
          SV->seq_num += g_tcp_layer_mss;
          //if(SV->seq_num < 0 )
          // tw_error(TW_LOC,"OverFlow\n");
        }
      M->ack = ack;
    } else
      {
        // printf("Invalid Ack %d\n", M->ack);
        if ((CV->c3 = ((SV->unack - g_tcp_layer_mss) == M->ack)))
          {
            SV->dup_count += 1;
            if ((CV->c4 = (SV->dup_count == 4)))
              {
                M->dest = SV->ssthresh;
                SV->ssthresh =
                  (min(((int)SV->cwnd + 1), g_tcp_layer_recv_wnd) / 2) * g_tcp_layer_mss;
                                // CHANGED
                M->RC.cwnd = SV->cwnd;
                SV->cwnd = 1;
                tcp_layer_util_event(lp, FORWARD, lp->id,
                               M->source, SV->unack, 0, TCP_LAYER_TRANSFER_SIZE);
                M->ack = SV->seq_num;
                SV->seq_num = SV->unack + g_tcp_layer_mss;
                                // CHANGE MAYBE.
                SV->rto_seq++;
                //tcp_layer_util_event(lp, RTO, M->source, lp->id, SV->unack,
                //             SV->rto_seq, SV->rto);
                if((CV->c13 = (SV->timer != NULL))) {
                  rn_message *rn_m;
                  tcp_layer_message *m1;
                  rn_m = tw_event_data(SV->timer);
                  m1 = rn_message_data(rn_m);
                  M->RC.timer_ts = SV->timer->recv_ts;
                  M->RC.timer_seq = m1->seq_num;
                  rn_timer_reset(lp, &(SV->timer), tw_now(lp) + SV->rto);
                  if(SV->timer)
                    m1->seq_num = SV->unack;
                }
                M->RC.seq_num = SV->rtt_seq;
                SV->rtt_seq = SV->unack;
                M->RC.rtt_time = SV->rtt_time;
                SV->rtt_time = 0;
              }
          }
      }
}
void tcp_layer_process_ack_rc (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 13 of file tcp-layer-process-rc.c.
References g_tcp_layer_mss, rn_message_data(), and RTO.
Referenced by tcp_layer_rc_event_handler().
{
  int i;
  int ack;
  tcp_layer_message    *M;
  // printf("%f roll ack %d %d lp %d\n",tw_now(lp), SV->unack, M->ack, lp->id);
  M = rn_message_data(msg);
  if(CV->c2)
    {
      for(i=0; i<M->seq_num; i++)
        {
          //  tw_rand_reverse_unif(lp->id);
          SV->seq_num -= g_tcp_layer_mss;
          SV->sent_packets--;
        }
      // reverse tcp_update_rtt
      if(CV->c5 || CV->c7)
        {
          SV->rtt_seq = M->RC.rtt_seq;
          // M->RC.rtt_seq = SV->rtt_seq;
          //SV->rtt_seq = M->ack;  // wrong CHANGE
          SV->rtt_time = M->RC.rtt_time;
          if(CV->c6 && CV->c5)
            SV->rto = M->dest;
          SV->rto_seq--;
          if(CV->c13){
            tcp_layer_message *M1;
            rn_message *msg1;
            if(SV->timer)
              tw_timer_reset(lp, &(SV->timer), M->RC.timer_ts);
            else
              SV->timer = tw_timer_init(lp, M->RC.timer_ts);
            msg1 = tw_event_data(SV->timer);
            M1 = rn_message_data(msg1);
            M1->seq_num = M->RC.timer_seq;
            M1->source = M->source;
            M1->MethodName = RTO;
          }
        }
    // Reverse tcp_update_cwnd
    if(CV->c3 || CV->c4)
      SV->cwnd = M->RC.cwnd;
    ack = SV->unack;
    SV->unack = M->ack;
    M->ack = ack - g_tcp_layer_mss;
    SV->dup_count = M->RC.dup_count;
    if(CV->c9)
      SV->seq_num = M->RC.seq_num;
  }
  else
    {
      if(CV->c3)
        {
          SV->dup_count -= 1;
          if(CV->c4)
            {
              SV->rtt_time = M->RC.rtt_time;
              SV->rtt_seq  = M->RC.seq_num;//SV->unack; //big CHANGE
              //SV->timedout_packets--;
              //SV->sent_packets--;
              SV->rto_seq--;
              SV->seq_num = M->ack;
              M->ack = SV->unack - g_tcp_layer_mss;
              SV->cwnd = M->RC.cwnd;
              SV->ssthresh = M->dest;
              if(CV->c13){
                //rn_message *msg1;
                tcp_layer_message *M1;
                if(SV->timer)
                  tw_timer_reset(lp, &(SV->timer), M->RC.timer_ts);
                else
                  SV->timer = tw_timer_init(lp, M->RC.timer_ts);
                M1 = tw_event_data(SV->timer);
                M1->seq_num = M->RC.timer_seq;
                M1->source = M->source;
                M1->MethodName = RTO;
              }
            }
        }
    }
}
void tcp_layer_process_data (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 119 of file tcp-layer-process.c.
References FORWARD, g_tcp_layer_mss, g_tcp_layer_recv_wnd, rn_message_data(), TCP_LAYER_HEADER_SIZE, TCP_LAYER_SND_WND, and tcp_layer_util_event().
Referenced by tcp_layer_event_handler().
{
  //int             id_offset;
  tcp_layer_message    *M;
  tw_stime        ts;
  ts = 0.0;
  M = rn_message_data(rn_msg);
  //id_offset = lp->id;
  if ((CV->c2 = (M->seq_num == SV->seq_num)))
    {
      SV->received_packets++;
      M->RC.dup_count = 0;
      SV->seq_num += g_tcp_layer_mss;
      while (SV->out_of_order[(SV->seq_num / (int)g_tcp_layer_mss) % g_tcp_layer_recv_wnd])
        {
          M->RC.dup_count++;
          SV->out_of_order[(SV->seq_num / (int)g_tcp_layer_mss) % g_tcp_layer_recv_wnd] = 0;
          SV->seq_num += g_tcp_layer_mss;
        }
      tcp_layer_util_event(lp, FORWARD, lp->id, M->source,
                           0, SV->seq_num - g_tcp_layer_mss, TCP_LAYER_HEADER_SIZE);
      // printf("SV->seq %d and rn_msg %ld\n",SV->seq_num, rn_msg->size);
        }
  else
    {
      if ((CV->c3 = (M->seq_num > SV->seq_num)))
        {
          if ((CV->c4 = (M->seq_num > (SV->seq_num + g_tcp_layer_recv_wnd * g_tcp_layer_mss
                                       /*
                                        * TCP_LAYER_SND_WND
                                        */  - g_tcp_layer_mss))))
            {
                                // look up need rc code  CHANGE
              tw_error(TW_LOC, "revc_wnd buffer overflow %d %d\n",
                       M->seq_num, SV->seq_num + TCP_LAYER_SND_WND - g_tcp_layer_mss);
            }
          else
            {
              /*
                printf("M %d window %d, loc %d\n",
                M->seq_num,
                (SV->seq_num + TCP_LAYER_SND_WND - g_tcp_layer_mss),
                  (M->seq_num / g_tcp_layer_mss) % g_tcp_layer_recv_wnd);
              */
              SV->out_of_order[(M->seq_num / g_tcp_layer_mss) % g_tcp_layer_recv_wnd] = 1;
            }
        }
      tcp_layer_util_event(lp, FORWARD, lp->id, M->source,
                           0, SV->seq_num - g_tcp_layer_mss, TCP_LAYER_HEADER_SIZE);
    }
}
void tcp_layer_process_data_rc (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 120 of file tcp-layer-process-rc.c.
References g_tcp_layer_mss, g_tcp_layer_recv_wnd, and rn_message_data().
Referenced by tcp_layer_rc_event_handler().
{
  tcp_layer_message    *M;
  M = rn_message_data(msg);
  if(CV->c2)
    {
      // tw_rand_reverse_unif(lp->id);
      SV->received_packets--;
      SV->seq_num -= g_tcp_layer_mss;
      while(M->RC.dup_count){
        SV->out_of_order[(SV->seq_num / (int) g_tcp_layer_mss) % g_tcp_layer_recv_wnd ] = 1;
        SV->seq_num -= g_tcp_layer_mss;
        M->RC.dup_count--;
      }
    }
  else
    {
      if(CV->c3){
        if(CV->c4) {} // need to think about this one  WILL NOT WORK UNTILL YOU FIX!!!!!
        else
          SV->out_of_order[(M->seq_num / (int) g_tcp_layer_mss) % g_tcp_layer_recv_wnd] = 0;
      }
    }
}
void tcp_layer_rc_event_handler (tcp_layer_state * SV, tw_bf * CV, rn_message * M, tw_lp * lp)
Definition at line 115 of file tcp-layer.c.
References FORWARD, rn_message_data(), RTO, tcp_layer_process_ack_rc(), tcp_layer_process_data_rc(), and tcp_layer_timeout_rc().
{
  tcp_layer_message    *msg;
  msg = rn_message_data(M);
  CV = &(msg->CV);
   switch (msg->MethodName)
     {
     case FORWARD:
       switch (SV->connection)
         {
         case -1:
          tcp_layer_process_data_rc(SV, CV, M, lp);
          break;
         default:
           tcp_layer_process_ack_rc(SV, CV, M, lp);
           break;
         }
       break;
    case RTO:
      tcp_layer_timeout_rc(SV, CV, msg, lp);
      break;
     default:
       tw_error(TW_LOC,
                "APP_ERROR(%d): Invalid MethodName(%d):Time (%f)\n",
                lp->id, msg->MethodName, tw_now(lp));
     }
}
void tcp_layer_timeout (tcp_layer_state * SV, tw_bf * CV, tcp_layer_message * M, tw_lp * lp)
Definition at line 271 of file tcp-layer-process.c.
References FORWARD, g_tcp_layer_mss, g_tcp_layer_recv_wnd, rn_message_data(), rn_timer_init(), RTO, TCP_LAYER_HEADER_SIZE, and tcp_layer_util_event().
Referenced by tcp_layer_event_handler().
{
  // printf("bw %d de %f last %f \n", SV->host->link->bandwidth,
  // SV->host->link->delay,  SV->lastsent);
  if ((CV->c1 = (M->seq_num >= SV->unack && SV->unack < SV->len)))
    {
      //printf("should timeout %f %d %f\n", tw_now(lp), lp->id, SV->lastsent );
      M->dest = SV->ssthresh;
      SV->ssthresh = (min(((int)SV->cwnd + 1), g_tcp_layer_recv_wnd) / 2) * g_tcp_layer_mss;
      // CHANGED
      M->RC.cwnd = SV->cwnd;
      SV->cwnd = 1;
      //printf("bw %d de %f last %f \n", SV->host->link->bandwidth,
      //     SV->host->link->delay,  SV->lastsent);
      tcp_layer_util_event(lp, FORWARD, lp->id, M->source, SV->unack, 0,
                     TCP_LAYER_HEADER_SIZE);
      M->ack = SV->seq_num;
      SV->seq_num = SV->unack + g_tcp_layer_mss;
      SV->timedout_packets++;
      M->RC.dup_count = SV->rto;
      SV->rto = SV->rto * 2;    // PUT IN MAX TIME CHANGE
      // M->RC.event = SV->event;
      SV->rto_seq++;
      //tcp_layer_util_event(lp, RTO, M->source, lp->id, SV->unack, SV->rto_seq,
      //             SV->rto);
      M->RC.timer = SV->timer;
      SV->timer = rn_timer_init(lp, tw_now(lp) + SV->rto);
      if((CV->c13 = (SV->timer != NULL))){
        rn_message *rn_m = tw_event_data(SV->timer);
        tcp_layer_message *M1 = rn_message_data(rn_m);
        M1->source = M->source;
        M1->seq_num= SV->unack;
        M1->MethodName = RTO;
      }
      M->RC.rtt_seq = SV->rtt_seq;
      SV->rtt_seq = SV->unack;
      M->RC.rtt_time = SV->rtt_time;
      SV->rtt_time = 0;
    }
}
void tcp_layer_timeout_rc (tcp_layer_state * SV, tw_bf * CV, tcp_layer_message * M, tw_lp * lp)
Definition at line 152 of file tcp-layer-process-rc.c.
Referenced by tcp_layer_rc_event_handler().
{
  int ssthresh = M->dest;
  int seq_num = M->ack;
  if(CV->c1)
    {
      SV->rtt_time = M->RC.rtt_time;
      SV->rtt_seq = M->RC.rtt_seq;//M->seq_num; CHANGE
      SV->rto_seq--;
      SV->timedout_packets--;
      //SV->sent_packets--;
      SV->rto = M->RC.dup_count;//SV->rto/2; //possible an error.
      SV->seq_num = seq_num;
      SV->cwnd = M->RC.cwnd;
      SV->ssthresh = ssthresh;
      tw_timer_cancel(lp, &(SV->timer));
      SV->timer = M->RC.timer;
    }
}
void tcp_layer_update_cwnd (tcp_layer_state * SV, tw_bf * CV, tcp_layer_message * M, tw_lp * lp)
Definition at line 188 of file tcp-layer-process.c.
References g_tcp_layer_mss, and TCP_LAYER_SND_WND.
Referenced by tcp_layer_process_ack().
{
  if (
      (CV->c3 =
       ((SV->cwnd * g_tcp_layer_mss) < SV->ssthresh && SV->cwnd * g_tcp_layer_mss < TCP_LAYER_SND_WND)))
    {
      M->RC.cwnd = SV->cwnd;
      SV->cwnd += 1;
    } else if ((CV->c4 = (SV->cwnd * g_tcp_layer_mss < TCP_LAYER_SND_WND)))
      {
        M->RC.cwnd = SV->cwnd;
        SV->cwnd += 1 / SV->cwnd;
      }
}
void tcp_layer_update_rtt (tcp_layer_state * SV, tw_bf * CV, tcp_layer_message * M, tw_lp * lp)
Definition at line 210 of file tcp-layer-process.c.
References rn_message_data(), and rn_timer_reset().
Referenced by tcp_layer_process_ack().
{
  if ((CV->c5 = (M->ack == SV->rtt_seq && SV->unack < SV->len)))
    {
      if ((CV->c6 = (SV->rtt_time != 0)))
        {
          M->dest = SV->rto;
          SV->rto =
            .875 * SV->rto + (10 * (tw_now(lp) - SV->rtt_time)) * .125;
        }
      M->RC.rtt_seq = SV->rtt_seq;
      M->RC.rtt_time = SV->rtt_time;
      SV->rtt_time = tw_now(lp);
      SV->rtt_seq = SV->seq_num;
      SV->rto_seq++;
      if((CV->c13 = (SV->timer != NULL))) {
        rn_message *rn_m = tw_event_data(SV->timer);
        tcp_layer_message *m1 = rn_message_data(rn_m);
        M->RC.timer_ts = SV->timer->recv_ts;
        M->RC.timer_seq = m1->seq_num;
        rn_timer_reset(lp, &(SV->timer), tw_now(lp) + SV->rto);
        if(SV->timer)
          m1->seq_num = SV->unack;
      }
    } else if ((CV->c7 = (M->ack > SV->rtt_seq && SV->unack < SV->len)))
      {
        M->RC.rtt_seq = SV->rtt_seq;
        M->RC.rtt_time = SV->rtt_time;
        SV->rtt_time = tw_now(lp);
        SV->rtt_seq = SV->seq_num;
        SV->rto_seq++;
        if((CV->c13 = (SV->timer != NULL))) {
          rn_message *rn_m = tw_event_data(SV->timer);
          tcp_layer_message *m1 = rn_message_data(rn_m);
          M->RC.timer_ts = SV->timer->recv_ts;
          M->RC.timer_seq = m1->seq_num;
          rn_timer_reset(lp, &(SV->timer), tw_now(lp) + SV->rto);
          if(SV->timer)
            m1->seq_num = SV->unack;
        }
      }
}
void tcp_layer_util_event (tw_lp * lp, int type, int source, int dest, int seq_num, int ack, int size)
Definition at line 8 of file tcp-layer-util.c.
References DOWNSTREAM, rn_event_data(), rn_event_new(), rn_event_send(), and rn_message_data().
Referenced by tcp_layer_process_ack(), tcp_layer_process_data(), tcp_layer_startup(), and tcp_layer_timeout().
{
  rn_message  * r;
  tcp_layer_message * TWMsg;
  tw_event *CurEvent;
  // should put in the tcp_util_nexthop
  CurEvent = rn_event_new(tw_getlp(dest), 0.0, lp, DOWNSTREAM, size);
  r = rn_event_data(CurEvent);
  TWMsg = rn_message_data(r);
  //printf("%d: TCP sending event to lp %d ts = %f %f\n", CurEvent->src_lp->id,
  //       CurEvent->dest_lp->id, CurEvent->recv_ts, ts);
  TWMsg->MethodName = type;
  TWMsg->source = source;
  TWMsg->dest = dest;
  TWMsg->seq_num = seq_num;
  TWMsg->ack = ack;
  rn_event_send(CurEvent);
}
void tcp_layer_xml (tw_lp * lp, xmlNodePtr node)
Definition at line 4 of file tcp-layer-xml.c.
References ctxt, document_network, g_tcp_layer_mss, g_tcp_layer_recv_wnd, TCP_LAYER_LP_TYPE, xml_getprop(), and xpath().
{
        xmlXPathContextPtr      ctxt;
        xmlXPathObjectPtr       obj;
        xmlNodePtr              layer;
        static int              init = 0;
        xmlNodePtr              node;
        for(layer = n; layer; layer = layer->next)
        {
                if(0 != strcmp((char *) layer->name, "layer"))
                        continue;
                if(strcmp(xml_getprop(layer, "name"), "tcp") == 0)
                {
                        tw_lp_settype(lp, TCP_LAYER_LP_TYPE);
                        //printf("Setting LP %d to TCP! \n", lp->id);
                        break;
                }
        }
        ctxt = xmlXPathNewContext(document_network);
        ctxt->node = xmlDocGetRootElement(document_network);
        if(!init){
          init = 1;
          obj = xpath("//mss", ctxt);
          if(obj && obj->nodesetval->nodeNr)
            {
            node = *obj->nodesetval->nodeTab;
            g_tcp_layer_mss = atoi((char *) node->children->content);
            }
          xmlXPathFreeObject(obj);
          obj = xpath("//recv_wnd", ctxt);
          if(obj && obj->nodesetval->nodeNr)
          {
            node = *obj->nodesetval->nodeTab;
            g_tcp_layer_recv_wnd = atoi((char *) node->children->content);
          }
          xmlXPathFreeObject(obj);
        }
        //tw_mutex_unlock(&g_tw_debug_lck);
}
Variable Documentation
int g_tcp_layer_iss
Definition at line 3 of file tcp-layer-global.c.
int g_tcp_layer_mss
Definition at line 5 of file tcp-layer-global.c.
Referenced by tcp_layer_process_ack(), tcp_layer_process_ack_rc(), tcp_layer_process_data(), tcp_layer_process_data_rc(), tcp_layer_startup(), tcp_layer_timeout(), tcp_layer_update_cwnd(), and tcp_layer_xml().
int g_tcp_layer_recv_wnd
Definition at line 4 of file tcp-layer-global.c.
Referenced by tcp_layer_process_ack(), tcp_layer_process_data(), tcp_layer_process_data_rc(), tcp_layer_timeout(), and tcp_layer_xml().
tcp_layer_statistics g_tcp_layer_stats
Definition at line 7 of file tcp-layer-global.c.
Referenced by tcp_layer_final().