ROSS.Net: tcp.c File Reference
tcp.c File Reference
#include <tcp.h>
Functions
void stop_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void start_transfer (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_init (tcp_state *state, tw_lp *lp)
void tcp_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_rc_event_handler (tcp_state *state, tw_bf *bf, rn_message *m, tw_lp *lp)
void tcp_final (tcp_state *state, tw_lp *lp)
Function Documentation
void start_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 25 of file tcp.c.
References g_tcp_fd, rn_timer_init(), tcp_event_send(), TCP_MTU, and TCP_SND_WND.
Referenced by tcp_event_handler(), and tcp_init().
{
#ifdef TCP_DEGUG
        printf("%ld: START XFER: %d of %d bytes at %lf\n",
                lp->id, state->unack, m->size, tw_now(lp));
#endif
        if (state->timer)
                tw_error(TW_LOC, "tcp start with timer set.");
        // file size
        state->len = m->size;
        state->unack = 0;
        // from init
        state->cwnd = 1;
        state->ssthresh = TCP_SND_WND;
        state->rto = 3.0;
#ifdef TCP_DEBUG
        printf("%lld: START XFER: %d bytes at %lf\n", lp->id, state->len, tw_now(lp));
#endif
        state->stats->sent++;
        state->seq_num = state->mss;
        state->rtt_seq = 0;
        state->rtt_time = tw_now(lp);
        m->dst = state->connection;
        tcp_event_send(state, lp->id, 0.0, state->connection, TCP_MTU, 0, 0, lp);
        state->timer = rn_timer_init(lp, tw_now(lp) + state->rto);
        if(state->timer)
        {
                tw_memory       *b;
                tcp_message     *msg;
                b = tw_memory_alloc(lp, g_tcp_fd);
                msg = tw_memory_data(b);
                msg->src = m->src;
                msg->seq_num = 0;
                tw_event_memory_set(state->timer, b, g_tcp_fd);
#ifdef TCP_DEBUG
                printf("%lld: RTO timer at %lf \n", lp->id, state->timer->recv_ts);
#endif
        }
}
void stop_transfer (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 4 of file tcp.c.
References g_tcp_fd, and rn_timer_cancel().
Referenced by tcp_event_handler().
{
#ifdef TCP_DEBUG
        printf("%lld: STOP XFER: %d of %d bytes at %lf\n",
                lp->id, state->unack, state->len, tw_now(lp));
#endif
        //state->unack = 0;
        state->len = 0;
        if(state->timer)
        {
                tw_memory_free(lp, state->timer->memory, g_tcp_fd);
                state->timer->memory = NULL;
                rn_timer_cancel(lp, &state->timer);
                state->timer = NULL;
        }
}
void tcp_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 118 of file tcp.c.
References DOWNSTREAM, g_tcp_fd, start_transfer(), stop_transfer(), tcp_process_ack(), tcp_process_data(), tcp_timeout(), and TIMER.
{
        tw_memory       *b;
        tcp_message     *in = NULL;
        *(int *) bf = 0;
        // if no membuf, then must be application layer
        if(NULL != (b = tw_event_memory_get(lp)))
                in = tw_memory_data(b);
        if(m->type == DOWNSTREAM)
        {
                if(m->size)
                        start_transfer(state, bf, m, lp);
                else
                        stop_transfer(state, bf, m, lp);
        } else if(m->type == TIMER)
        {
#ifdef TCP_DEBUG
                printf("%lld: RTO for %lld at %lf (%ld)\n",
                        lp->id, in->src, tw_now(lp), (long int) lp->pe->cur_event);
#endif
                tcp_timeout(state, bf, in, lp);
        } else if(state->connection != -1)
        {
#ifdef TCP_DEBUG
                printf("%lld: ACK from %lld at %lf \n", lp->id, in->src, tw_now(lp));
#endif
                tcp_process_ack(state, bf, in, lp);
        } else
        {
#ifdef TCP_DEBUG
                printf("%lld: DATA from %lld at %lf \n", lp->id, in->src, tw_now(lp));
#endif
                tcp_process_data(state, bf, in, lp);
        }
        if(b)
                tw_memory_free(lp, b, g_tcp_fd);
}
void tcp_final (tcp_state * state, tw_lp * lp)
Definition at line 208 of file tcp.c.
References g_rn_logs_dir, g_tcp_stats, and rn_getmachine().
{
#ifdef TCP_LOG
        char    log[255];
        if(state->log && state->log != stdout)
                fclose(state->log);
        if(state->connection > -1)
                sprintf(log, "%s/tcp-host-%ld.log", g_rn_logs_dir, lp->id);
        else
                sprintf(log, "%s/tcp-server-%ld.log", g_rn_logs_dir, lp->id);
        state->log = fopen(log, "w");
        if(!state->log)
                return;
        if(state->connection > -1)
        {
                fprintf(state->log, "TCP Svr %ld: Conn Duration: %lf-%lf \n\n",
                        lp->id, state->stats->start_time, state->stats->final_time);
                g_tcp_stats->throughput +=
                        (((state->len * 8.0)/
                                (tw_now(lp) - state->stats->start_time)) / 1024);
                fprintf(state->log, "\t%-50s %11d\n", "Server", rn_getmachine(lp)->link[0].addr);
                fprintf(state->log, "\t%-50s %11d Bytes\n", "Length", state->len);
                fprintf(state->log, "\t%-50s %11.4lf Kbps\n", "Throughput",
                           (((state->len * 8) /
                                 (tw_now(lp) - state->stats->start_time)) / 1024));
                fprintf(state->log, "\t%-50s %11d\n", "Timeouts", state->stats->tout);
                fprintf(state->log, "\t%-50s %11.4lf\n", "Cwnd", state->cwnd);
                fprintf(state->log, "\n");
        } else
        {
                fprintf(state->log, "TCP Clt %ld: Conn Duration: %lf-%lf \n\n",
                        lp->id, state->stats->start_time, state->stats->final_time);
        }
        fprintf(state->log, "\t%-50s %11d\n", "Sent Pkts", state->stats->sent);
        fprintf(state->log, "\t%-50s %11d\n", "Recv Pkts", state->stats->recv);
        fprintf(state->log, "\t%-50s %11d\n", "Drop Pkts", state->stats->dropped_packets);
        fprintf(state->log, "\t%-50s %11d\n", "Bad Pkts", state->stats->bad_msgs);
        fprintf(state->log, "\n");
        fprintf(state->log, "\t%-50s %11d\n", "ACK Sent", state->stats->ack_sent);
        fprintf(state->log, "\t%-50s %11d\n", "ACK Recv", state->stats->ack_recv);
        fprintf(state->log, "\t%-50s %11d\n", "ACK Invalid", state->stats->ack_invalid);
#endif
        g_tcp_stats->sent += state->stats->sent;
        g_tcp_stats->recv += state->stats->recv;
        g_tcp_stats->tout += state->stats->tout;
        g_tcp_stats->ack_sent += state->stats->ack_sent;
        g_tcp_stats->ack_recv += state->stats->ack_recv;
        g_tcp_stats->ack_invalid += state->stats->ack_invalid;
        g_tcp_stats->bad_msgs += state->stats->bad_msgs;
        g_tcp_stats->dropped_packets += state->stats->dropped_packets;
        if(0 && lp->id % 100000 == 0)
                printf("Finalizing TCP LP %lld \n", lp->gid);
}
void tcp_init (tcp_state * state, tw_lp * lp)
Definition at line 80 of file tcp.c.
References g_state, g_tcp_mss, g_tcp_rwd, rn_getmachine(), start_transfer(), and TCP_SND_WND.
{
        state->cwnd = 1;
        state->ssthresh = TCP_SND_WND;
        state->rto = 3.0;
        //state->host = rn_getmachine(lp->id);
        if(rn_getmachine(lp->id)->conn > lp->id)
                state->connection = rn_getmachine(lp->id)->conn;
        else
                state->connection = -1;
        state->stats = tw_calloc(TW_LOC, "", sizeof(tcp_statistics), 1);
        state->mss = g_tcp_mss;
        state->recv_wnd = g_tcp_rwd;
        // faking out that this is not in transfer
        state->len = 1;
        state->unack = 0;
        g_state = state;
#ifdef TCP_LOG
        state->log = stdout;
#endif
        //if(-1 != state->connection)
        if(lp->id == 0)
        {
                rn_message m;
                m.size = 40960;
                start_transfer(state, NULL, &m, lp);
        }
}
void tcp_rc_event_handler (tcp_state * state, tw_bf * bf, rn_message * m, tw_lp * lp)
Definition at line 165 of file tcp.c.
References g_tcp_fd, tcp_rc_process_ack(), tcp_rc_process_data(), tcp_rc_timeout(), and TIMER.
{
#if 0
        tw_memory       *b;
        tcp_message     *in;
        if(NULL == (b = tw_memory_free_rc(lp, g_tcp_fd)))
                tw_error(TW_LOC, "No membuf on event!");
        in = tw_memory_data(b);
        if(m->type == TIMER)
        {
#ifdef TCP_DEBUG
                printf("%ld: RC RTO for %d at %lf (%ld)\n",
                        lp->id, in->src, tw_now(lp), (long int) lp->cur_event);
#endif
                tcp_rc_timeout(state, bf, in, lp);
        } else if(state->connection == -1)
        {
#ifdef TCP_DEBUG
                printf("%ld: RC ACK from %d at %lf \n",
                        lp->id, in->src, tw_now(lp));
#endif
                tcp_rc_process_ack(state, bf, in, lp);
        } else
        {
#ifdef TCP_DEBUG
                printf("%ld: RC DATA from %d at %lf \n",
                        lp->id, in->src, tw_now(lp));
#endif
                tcp_rc_process_data(state, bf, in, lp);
        }
        if(b)
                tw_event_memory_set(lp->cur_event, b, g_tcp_fd);
#endif
}